// Batch P0-B — `attacks` for P0 questions B01..B06 (JavaScript), D01..D06 (HTTP/web),
// E01..E06 (FastAPI). Two hostile follow-ups each, distinct from the existing followups.
export default {
B01: {
attacks: [
{ q: `Vì sao <code>const obj = {a:1}; const copy = {...obj}</code> rồi sửa <code>copy.a</code> lại không ảnh hưởng <code>obj</code>, nhưng sửa một object lồng bên trong thì có?`, a: `Vì toán tử trải chỉ sao chép một tầng. Nó tạo object mới và gán từng thuộc tính cấp một sang, nên với kiểu nguyên thuỷ thì đó là bản sao thật. Nhưng nếu một thuộc tính là object hoặc mảng, giá trị được sao chép là tham chiếu, nên cả hai object cùng trỏ tới một object lồng. Sửa thuộc tính bên trong object lồng đó hiện ra ở cả hai. Đây là nguồn lỗi rất phổ biến trong cập nhật trạng thái: bạn tưởng đã tạo bản sao nên an toàn, nhưng thực ra vẫn đang sửa dữ liệu dùng chung ở tầng sâu hơn.` },
{ q: `Trong cập nhật trạng thái, vì sao phải tạo object mới thay vì sửa object cũ?`, a: `Vì nhiều thư viện và cơ chế so sánh dựa trên danh tính tham chiếu để quyết định có cần cập nhật hay không. Nếu bạn sửa tại chỗ, tham chiếu không đổi, nên phép so sánh kết luận là không có gì mới và giao diện không được vẽ lại. Ngoài ra việc sửa tại chỗ làm mất khả năng so sánh lịch sử trạng thái, khiến các tính năng như hoàn tác hoặc ghi lại thay đổi trở nên khó. Cái giá phải trả là bộ nhớ cho các object mới, nhưng với cấu trúc được chia sẻ giữa các phiên bản thì chi phí đó thường nhỏ hơn nhiều so với lợi ích về tính đúng đắn.` },
],
},
B02: {
attacks: [
{ q: `Vì sao <code>let</code> ném lỗi khi truy cập trước khai báo, còn <code>var</code> thì trả về <code>undefined</code>?`, a: `Vì <code>var</code> được đưa lên đầu phạm vi hàm và khởi tạo bằng <code>undefined</code> ngay khi vào phạm vi, nên đọc trước khai báo cho giá trị rỗng chứ không lỗi. <code>let</code> và <code>const</code> cũng được đưa lên đầu khối, nhưng nằm trong một vùng mà truy cập bị cấm cho tới khi câu lệnh khai báo thực sự chạy — đó là vùng chết tạm thời. Hành vi này là cải tiến có chủ đích: nó biến một lỗi âm thầm thành một lỗi rõ ràng. Với <code>var</code>, việc đọc ra <code>undefined</code> thường bị bỏ qua và gây lỗi ở tận chỗ khác, khó truy hơn nhiều.` },
{ q: `Vì sao <code>const</code> không làm object bất biến?`, a: `Vì <code>const</code> ràng buộc việc gán lại tên, không ràng buộc nội dung của object. Sau khi khai báo, bạn không thể làm tên đó trỏ tới object khác, nhưng vẫn thêm, sửa, xoá thuộc tính bình thường. Đây là điểm hay bị hiểu nhầm và dẫn tới việc tưởng rằng dữ liệu được bảo vệ trong khi nó vẫn bị sửa từ nơi khác. Muốn bất biến thật thì phải đóng băng object, nhưng cần lưu ý là đóng băng chỉ có tác dụng ở tầng nông theo mặc định, và trong chế độ nghiêm ngặt thì việc ghi vào object đã đóng băng sẽ ném lỗi thay vì im lặng.` },
],
},
B03: {
attacks: [
{ q: `Vì sao <code>NaN === NaN</code> cho <code>false</code>, và bạn kiểm tra nó thế nào?`, a: `Vì theo đặc tả số học dấu phẩy động, <code>NaN</code> biểu diễn một kết quả không xác định, nên nó không bằng chính nó. Đây là hành vi của chuẩn số, không phải lỗi của JavaScript. Cách kiểm tra đúng là dùng hàm kiểm tra riêng, hoặc dùng phép so sánh theo cùng thuật toán nhưng coi hai giá trị không xác định là bằng nhau. Điểm liên quan là trong tập hợp và bản đồ, khoá <code>NaN</code> vẫn hoạt động và tra cứu được, vì thuật toán so sánh ở đó coi các giá trị không xác định là bằng nhau — nên hành vi khác với phép so sánh ba dấu bằng.` },
{ q: `Khi nào <code>==</code> thực sự hữu ích, và vì sao hầu hết đội cấm nó?`, a: `Trường hợp hữu ích phổ biến nhất là so sánh với <code>null</code>: <code>x == null</code> đúng cho cả <code>null</code> và <code>undefined</code>, nên nó diễn đạt gọn ý "không có giá trị" mà phải viết hai phép so sánh nếu dùng ba dấu bằng. Ngoài trường hợp đó, các quy tắc ép kiểu còn lại rất khó nhớ và tạo ra kết quả bất ngờ — so sánh chuỗi với số, mảng với số, object với nguyên thuỷ. Vì chi phí ghi nhớ và chi phí đọc lại code lớn hơn lợi ích, hầu hết đội cấm nó và chỉ cho phép dạng so sánh với <code>null</code> nếu quy ước nêu rõ.` },
],
},
B04: {
attacks: [
{ q: `Vì sao arrow function không có <code>this</code> riêng, và điều đó gây lỗi gì trong thực tế?`, a: `Arrow function không tạo ngữ cảnh thực thi riêng, nên <code>this</code> bên trong nó là <code>this</code> của phạm vi bao quanh tại thời điểm định nghĩa. Điều đó hữu ích khi bạn muốn giữ ngữ cảnh trong callback, nhưng gây lỗi khi bạn cần ngữ cảnh động: gán arrow function làm phương thức của object thì <code>this</code> không trỏ tới object đó, và dùng nó làm constructor thì không được phép. Lỗi thực tế hay gặp là viết phương thức xử lý sự kiện bằng arrow function rồi truy cập <code>this</code> để lấy phần tử, nhưng nhận được ngữ cảnh của module hoặc của lớp ngoài.` },
{ q: `Bạn gọi một hàm callback và <code>this</code> bên trong bị mất. Ba cách sửa?`, a: `Một là truyền một hàm đã ràng buộc ngữ cảnh, tạo bằng phương thức ràng buộc của hàm — rõ ràng và phổ biến nhất. Hai là dùng arrow function ở chỗ truyền callback, vì nó kế thừa ngữ cảnh từ nơi định nghĩa. Ba là khai báo phương thức của lớp bằng arrow function ngay tại chỗ, để mỗi instance có một hàm đã gắn ngữ cảnh — tiện nhưng tốn thêm bộ nhớ cho mỗi instance. Điều nên tránh là lưu ngữ cảnh vào một biến tạm rồi dùng nó, vì cách đó làm code khó đọc và dễ sai khi có nhiều tầng lồng nhau.` },
],
},
B05: {
attacks: [
{ q: `Vì sao gọi phương thức qua biến tách rời lại mất ngữ cảnh?`, a: `Vì ngữ cảnh được quyết định tại thời điểm gọi, dựa trên cách hàm được gọi chứ không dựa trên nơi nó được định nghĩa. Khi bạn viết <code>obj.method()</code>, ngữ cảnh là <code>obj</code>. Khi bạn gán <code>const f = obj.method</code> rồi gọi <code>f()</code>, không còn object nào đứng trước dấu chấm, nên ngữ cảnh là <code>undefined</code> ở chế độ nghiêm ngặt hoặc đối tượng toàn cục ở chế độ thường. Đây chính là lý do callback hay bị mất ngữ cảnh, và cũng là lý do việc ràng buộc ngữ cảnh tồn tại.` },
{ q: `Kế thừa theo prototype và kế thừa theo lớp khác nhau ở đâu?`, a: `Kế thừa theo lớp là cú pháp được xây trên cùng cơ chế prototype, nên về bản chất không có hai hệ thống chạy song song. Khác biệt thực tế nằm ở chỗ tra cứu thuộc tính vẫn đi theo chuỗi prototype, nên bạn có thể thêm thuộc tính vào nguyên mẫu của một hàm tạo và mọi instance thấy ngay — điều không làm được với lớp theo nghĩa chặt. Ngoài ra lớp có những ràng buộc mà hàm tạo không có: không gọi được nếu thiếu từ khoá khởi tạo, và phải gọi hàm khởi tạo của lớp cha trước khi dùng ngữ cảnh. Hiểu điều này quan trọng vì nó giải thích những hành vi trông có vẻ lạ khi trộn hai cách viết.` },
],
},
B06: {
attacks: [
{ q: `Vì sao <code>setTimeout(fn, 0)</code> không chạy trước một promise đã resolve?`, a: `Vì promise và timer nằm ở hai hàng đợi khác nhau với mức ưu tiên khác nhau. Sau khi đoạn mã đồng bộ hiện tại kết thúc, hệ thống xử lý hết toàn bộ hàng đợi vi tác vụ — nơi callback của promise nằm — rồi mới lấy một tác vụ vĩ mô từ hàng đợi còn lại, nơi timer nằm. Độ trễ bằng không chỉ có nghĩa là "sớm nhất có thể sau khi hàng đợi vi tác vụ rỗng", chứ không có nghĩa là chạy ngay. Đây là lý do thứ tự thực thi trong các ví dụ về vòng lặp sự kiện thường gây bất ngờ nếu chỉ đọc code theo thứ tự viết.` },
{ q: `Nếu một vi tác vụ liên tục đẩy thêm vi tác vụ vào hàng đợi thì chuyện gì xảy ra?`, a: `Hàng đợi vi tác vụ không bao giờ rỗng, nên hệ thống không bao giờ chuyển sang tác vụ vĩ mô tiếp theo. Hệ quả là giao diện đứng hoàn toàn: không vẽ lại, không xử lý sự kiện người dùng, và timer không chạy. Đây là một dạng treo khó chẩn đoán vì tiến trình vẫn dùng CPU và không có lỗi nào được ném ra. Cách phòng là không tạo chuỗi vi tác vụ vô hạn, và nếu cần xử lý khối lượng lớn thì chia thành các phần nhỏ rồi nhường quyền cho tác vụ vĩ mô giữa các phần.` },
],
},
D01: {
attacks: [
{ q: `Một trang chậm. Bạn phân biệt độ trễ do mạng với độ trễ do server bằng cách nào?`, a: `Bằng cách tách thời gian theo từng chặng. Trong công cụ của trình duyệt, bạn xem được thời gian phân giải tên miền, thời gian thiết lập kết nối, thời gian chờ phản hồi đầu tiên, và thời gian tải nội dung. Nếu phần chờ phản hồi đầu tiên lớn thì nút thắt nằm ở server hoặc ở phụ thuộc của nó. Nếu thời gian thiết lập kết nối lớn thì vấn đề nằm ở mạng hoặc ở khoảng cách địa lý. Và nếu tổng thời gian lớn nhưng từng chặng đều nhỏ thì vấn đề nằm ở số lượng request hoặc ở việc tải tài nguyên tuần tự thay vì song song.` },
{ q: `Vì sao lần truy cập đầu tiên chậm hơn nhiều so với các lần sau?`, a: `Vì lần đầu phải trả toàn bộ chi phí thiết lập: phân giải tên miền, bắt tay TCP, thương lượng khoá bảo mật, rồi mới tới request thật. Những lần sau tái dùng kết nối đã thiết lập và tên miền đã được nhớ, nên bỏ được phần lớn chi phí đó. Ngoài ra cache ở nhiều tầng — trình duyệt, proxy trung gian, mạng phân phối nội dung — chỉ có tác dụng từ lần thứ hai. Đây là lý do phải phân biệt rõ hai loại số liệu này khi báo cáo hiệu năng, vì dùng số của lần đầu để nói về trải nghiệm chung là sai, còn dùng số của lần sau để che đi vấn đề của người dùng mới cũng sai.` },
],
},
D02: {
attacks: [
{ q: `Vì sao một số phương thức được gọi là an toàn còn một số chỉ là idempotent?`, a: `An toàn nghĩa là gọi không làm thay đổi trạng thái phía server, nên có thể gọi bao nhiêu lần cũng không sao — đọc dữ liệu là ví dụ điển hình. Idempotent nghĩa là gọi nhiều lần cho cùng kết quả như gọi một lần, nhưng trạng thái có thể đã thay đổi ở lần đầu. Xoá một tài nguyên là idempotent nhưng không an toàn: lần đầu xoá thành công, lần sau trả về không tìm thấy, và trạng thái cuối cùng vẫn là đã xoá. Phân biệt này quan trọng khi thiết kế retry: chỉ những phương thức idempotent mới an toàn để thử lại tự động.` },
{ q: `Nếu client gửi lại một yêu cầu tạo tài nguyên sau khi hết thời gian chờ, server nên trả về mã nào?`, a: `Nếu server đã tạo tài nguyên ở lần đầu, lần gửi lại lý tưởng nhất là trả về cùng kết quả với lần đầu — nghĩa là server phải nhận ra đây là cùng một thao tác, thường qua một khoá idempotency do client gửi kèm. Khi đó mã trả về là mã của lần tạo ban đầu, kèm thông tin cho biết kết quả đã có sẵn. Nếu server không có cơ chế nhận ra, nó sẽ tạo bản ghi thứ hai và trả về mã thành công — đó là lỗi dữ liệu trùng chứ không phải hành vi đúng. Điểm cần nói rõ là vấn đề không nằm ở mã trả về mà ở chỗ server có phân biệt được hai lần gửi hay không.` },
],
},
D03: {
attacks: [
{ q: `Vì sao gửi dữ liệu bằng định dạng sai lại khiến server hiểu nhầm thay vì báo lỗi?`, a: `Vì phần lớn framework chọn cách phân tích thân yêu cầu dựa trên tiêu đề khai báo định dạng, và nhiều framework có cơ chế đoán khi tiêu đề thiếu hoặc không khớp. Nếu bạn gửi dữ liệu dạng biểu mẫu nhưng khai báo là JSON, server có thể phân tích ra một object rỗng thay vì từ chối, và logic nghiệp vụ chạy với dữ liệu trống — sinh ra lỗi ở tận đâu đó hoặc ghi dữ liệu sai. Cách phòng là khai báo đúng định dạng, và ở phía server thì kiểm tra chặt: nếu tiêu đề không khớp với thân thì trả về lỗi rõ ràng thay vì cố đoán.` },
{ q: `Khi nào dùng tham số đường dẫn, khi nào dùng tham số truy vấn, khi nào dùng thân yêu cầu?`, a: `Tham số đường dẫn dùng để định danh tài nguyên, vì nó là một phần của địa chỉ và nên xuất hiện trong mọi bản ghi log hay bộ nhớ đệm. Tham số truy vấn dùng cho việc lọc, sắp xếp, phân trang — tức là những thứ thay đổi cách nhìn cùng một tài nguyên mà không đổi tài nguyên. Thân yêu cầu dùng khi dữ liệu lớn hoặc có cấu trúc, và về nguyên tắc không nên dùng cho yêu cầu đọc vì thân của yêu cầu đọc không có ngữ nghĩa rõ ràng và nhiều tầng trung gian bỏ qua nó. Điều cần tránh là đặt định danh tài nguyên trong thân, vì khi đó không thể dùng địa chỉ để chỉ tới tài nguyên.` },
],
},
D04: {
attacks: [
{ q: `Vì sao phân trang bằng số trang lại gây ra kết quả trùng hoặc thiếu khi dữ liệu đang thay đổi?`, a: `Vì số trang là một vị trí trong một danh sách được sắp xếp lại mỗi lần truy vấn. Nếu một bản ghi mới được chèn vào đầu danh sách giữa hai lần lật trang, mọi vị trí dịch một bậc, nên bản ghi cuối của trang trước xuất hiện lại ở đầu trang sau — hoặc ngược lại, một bản ghi bị bỏ qua nếu có bản ghi bị xoá. Cách tránh là phân trang theo con trỏ dựa trên giá trị của bản ghi cuối cùng, vì khi đó mỗi lần lấy là một truy vấn độc lập dựa trên dữ liệu chứ không dựa trên vị trí. Đánh đổi là không nhảy tới trang bất kỳ được.` },
{ q: `Làm sao thiết kế API lọc và sắp xếp để không mở ra lỗ hổng?`, a: `Bằng cách dùng danh sách cho phép, không phải danh sách loại trừ. Chỉ chấp nhận sắp xếp theo những trường bạn đã định nghĩa, và với mỗi trường thì ánh xạ sang biểu thức truy vấn do bạn viết — không nối tên trường từ tham số vào câu truy vấn. Với lọc, dùng tham số hoá và giới hạn kiểu giá trị. Điều cần tránh là cho phép sắp xếp theo tên cột tuỳ ý, vì điều đó vừa có thể dẫn tới tiêm nhiễm, vừa cho phép dò cấu trúc bảng qua thông báo lỗi, vừa tạo ra những truy vấn cực chậm trên cột không có chỉ mục.` },
],
},
D05: {
attacks: [
{ q: `Vì sao không được dùng nguồn đại diện cùng với thông tin xác thực?`, a: `Vì nếu cho phép, bất kỳ trang nào cũng có thể gửi yêu cầu kèm cookie của người dùng và đọc phản hồi, nên cơ chế bảo vệ mất hết ý nghĩa. Trình duyệt chặn cấu hình này vì lý do đó. Cách làm đúng là phản hồi nguồn cụ thể của người gọi, và nếu có nhiều nguồn thì kiểm tra nguồn đến rồi trả về đúng giá trị đó, kèm tiêu đề cho biết phản hồi phụ thuộc vào nguồn để các tầng đệm không dùng chung bản đã đệm giữa các nguồn khác nhau.` },
{ q: `Vì sao lỗi CORS hiện ở trình duyệt nhưng log server lại cho thấy request thành công?`, a: `Vì CORS là cơ chế do trình duyệt thực thi, không phải do server. Server vẫn nhận và xử lý request bình thường, rồi trả về phản hồi; trình duyệt mới là bên quyết định có cho mã phía client đọc phản hồi đó hay không, dựa trên các tiêu đề cho phép. Vì vậy trong log của server, request trông hoàn toàn thành công. Hệ quả thực tế là bạn không thể chẩn đoán lỗi CORS bằng log server; phải xem thông báo ở phía trình duyệt, và cần nhớ rằng với yêu cầu không đơn giản thì yêu cầu kiểm tra trước có thể đã thất bại nên request thật chưa từng được gửi.` },
],
},
D06: {
attacks: [
{ q: `Vì sao không nên lưu token trong bộ nhớ cục bộ của trình duyệt?`, a: `Vì mọi đoạn mã chạy trên trang đều đọc được, nên một lỗ hổng chèn mã là đủ để lấy token và dùng nó từ nơi khác cho tới khi hết hạn. Lưu trong cookie có thuộc tính chặn đọc từ mã thì an toàn hơn trước kiểu tấn công đó, nhưng lại mở ra nguy cơ khác là yêu cầu giả mạo từ trang khác, và nguy cơ đó được xử lý bằng thuộc tính hạn chế gửi cookie kèm yêu cầu liên trang. Không có lựa chọn nào miễn nhiễm hoàn toàn; điều quan trọng khi trả lời là nêu rõ mối đe doạ nào được giảm và mối đe doạ nào xuất hiện thay thế.` },
{ q: `Nếu người dùng bị khoá tài khoản, làm sao chặn ngay lập tức?`, a: `Với token tự chứa thì không chặn được ngay, vì server không tra cứu trạng thái khi xác minh. Ba cách xử lý: giữ thời hạn token rất ngắn để cửa sổ thu hồi hẹp, duy trì một danh sách thu hồi và kiểm tra nó ở mỗi yêu cầu, hoặc dùng phiên phía server với định danh phiên trong cookie và xoá phiên khi cần. Cách thứ ba đơn giản nhất nếu bạn không cần chia sẻ danh tính giữa nhiều hệ thống độc lập. Điểm cần nói rõ là mọi cách thu hồi đều đánh đổi mất tính phi trạng thái — tức là bạn trả lại đúng chi phí mà token tự chứa được chọn để tránh.` },
],
},
E01: {
attacks: [
{ q: `Vì sao middleware bọc ngoài dependency, và điều đó ảnh hưởng gì tới xử lý lỗi?`, a: `Vì middleware chạy quanh toàn bộ quá trình xử lý yêu cầu, còn dependency được giải quyết bên trong, sau khi yêu cầu đã đi qua các lớp ngoài. Hệ quả là nếu dependency ném lỗi, middleware vẫn thấy lỗi đó ở nhánh ra của nó, nên middleware là chỗ đúng để ghi log, thêm mã tương quan, hoặc chuyển lỗi thành phản hồi thống nhất. Nhưng nếu lỗi được xử lý bên trong và chuyển thành phản hồi thành công, middleware không biết là đã có lỗi. Vì vậy muốn đo tỉ lệ lỗi thật thì phải đặt phép đo ở chỗ thấy được cả hai, hoặc đánh dấu lỗi vào ngữ cảnh yêu cầu.` },
{ q: `Nếu một dependency được dùng ở ba nơi trong cùng một yêu cầu thì nó chạy mấy lần?`, a: `Một lần, vì framework ghi nhớ kết quả theo từng yêu cầu. Đây là hành vi có chủ đích và rất quan trọng: nó bảo đảm mọi tầng trong cùng một yêu cầu chia sẻ đúng một phiên cơ sở dữ liệu, nên transaction hoạt động như mong đợi. Nếu bạn vô tình phá vỡ điều đó — bằng cách gọi hàm tạo phiên trực tiếp thay vì qua dependency, hoặc bằng cách khai báo hai dependency khác nhau cùng tạo phiên — thì mỗi tầng có một phiên riêng, transaction không còn bao trùm, và bạn nhận được trạng thái dở dang mà không có lỗi nào báo.` },
],
},
E02: {
attacks: [
{ q: `Vì sao model dùng để kiểm tra đầu vào không nên dùng luôn để trả về?`, a: `Vì hai việc có yêu cầu trái ngược nhau. Kiểm tra đầu vào cần chấp nhận dữ liệu từ ngoài và có thể linh hoạt, còn dữ liệu trả về phải chặt và không được để lộ trường nội bộ. Nếu dùng chung một model, bạn dễ vô tình trả về những trường mà client không nên thấy, và mỗi lần thêm trường phục vụ việc kiểm tra là một lần có nguy cơ rò rỉ. Ngoài ra trường chỉ ghi và trường chỉ đọc có ngữ nghĩa khác nhau, nên gộp chúng làm mờ hợp đồng. Cách đúng là tách model đầu vào và model đầu ra, dù chúng có nhiều trường giống nhau.` },
{ q: `Sự khác biệt giữa chế độ chặt và chế độ linh hoạt gây hậu quả gì trong production?`, a: `Ở chế độ linh hoạt, giá trị được ép kiểu khi có thể, nên một chuỗi số có thể trở thành số và yêu cầu vẫn thành công. Điều này tiện cho việc tích hợp nhưng có thể che đi lỗi ở phía client, và với một số kiểu thì việc ép kiểu làm mất thông tin — ví dụ giá trị đúng hay sai nhận từ chuỗi. Ở chế độ chặt, kiểu phải khớp chính xác nên lỗi lộ ra ngay. Điểm cần nắm là bạn chọn được chế độ cho từng trường, và cách làm thực dụng là để mặc định linh hoạt cho những trường người dùng nhập, nhưng dùng chặt cho những trường ảnh hưởng tới nghiệp vụ hoặc bảo mật.` },
],
},
E03: {
attacks: [
{ q: `Bạn có một thư viện cũ chỉ hỗ trợ gọi đồng bộ. Đặt nó ở đâu?`, a: `Đặt trong một hàm đồng bộ và để framework tự đẩy nó sang luồng riêng, hoặc tự đẩy sang một luồng công việc một cách tường minh. Điều tuyệt đối không làm là gọi nó trực tiếp bên trong hàm bất đồng bộ, vì khi đó nó giữ vòng lặp sự kiện và chặn mọi yêu cầu khác của tiến trình. Cần lưu ý thêm hai điều: số luồng trong nhóm công việc có giới hạn, nên nếu bạn đẩy quá nhiều việc đồng bộ sang đó thì chúng sẽ xếp hàng; và nếu việc đó là tính toán nặng chứ không phải chờ đợi thì nên đẩy sang tiến trình riêng thay vì luồng.` },
{ q: `Nếu bạn lỡ chặn vòng lặp sự kiện, làm sao phát hiện trên production?`, a: `Bằng ba tín hiệu. Thứ nhất, độ trễ của mọi endpoint cùng tăng trong khi thời gian truy vấn cơ sở dữ liệu không đổi — đó là dấu hiệu nút thắt nằm trong tiến trình chứ không ở phụ thuộc. Thứ hai, số yêu cầu mỗi giây giảm mạnh trong khi mức dùng CPU thấp, vì tiến trình đang chờ chứ không tính toán. Thứ ba, bật chế độ gỡ lỗi của máy chủ để nhận cảnh báo về những đoạn xử lý chạy quá lâu, kèm vị trí trong mã nguồn. Cách phòng là đo độ trễ của vòng lặp sự kiện như một chỉ số riêng và đặt cảnh báo trên nó.` },
],
},
E04: {
attacks: [
{ q: `Khi nào việc tách tầng service và repository trở thành chi phí thuần tuý?`, a: `Khi mỗi tầng chỉ chuyển tiếp lời gọi cho tầng dưới mà không thêm quyết định nào. Nếu hàm service chỉ nhận tham số, gọi repository, rồi trả về đúng kết quả đó, thì nó không mang lại gì ngoài một tệp nữa phải mở khi đọc code. Chi phí đó chỉ đáng trả khi tầng đó thực sự làm việc: phối hợp nhiều nguồn dữ liệu, quyết định ranh giới giao dịch, áp quy tắc nghiệp vụ, hoặc chuyển đổi giữa mô hình lưu trữ và mô hình nghiệp vụ. Dấu hiệu nhận biết là đếm số dòng logic thật trong hàm — nếu gần bằng không thì nên gộp lại.` },
{ q: `Ranh giới giao dịch nên nằm ở tầng nào?`, a: `Ở tầng điều phối yêu cầu, tức là tầng service, chứ không ở tầng truy cập dữ liệu. Lý do là chỉ tầng service mới biết một thao tác nghiệp vụ gồm những bước ghi nào và khi nào thì toàn bộ được coi là hoàn tất. Nếu để repository tự xác nhận sau mỗi lần ghi, bạn mất khả năng gộp nhiều bước thành một đơn vị nguyên tử, và mọi lỗi ở bước sau để lại trạng thái dở dang. Quy tắc thực dụng là một yêu cầu, một giao dịch, mở ở tầng service và đóng ở đó — và không gọi ra dịch vụ bên ngoài trong lúc giao dịch đang mở.` },
],
},
E05: {
attacks: [
{ q: `Vì sao kiểm tra quyền phải nằm trong dependency chứ không trong thân hàm xử lý?`, a: `Vì dependency là chỗ duy nhất mà mọi đường vào đều phải đi qua, nên nó biến việc kiểm tra thành mặc định thay vì việc phải nhớ. Nếu kiểm tra nằm trong thân hàm, mỗi endpoint mới là một cơ hội để quên, và một endpoint quên sẽ trả về dữ liệu cho người không có quyền mà không có dấu hiệu gì. Ngoài ra dependency cho phép tái sử dụng cùng một quy tắc trên nhiều endpoint, và cho phép kiểm thử quy tắc đó độc lập với logic nghiệp vụ. Điều cần tránh là rải kiểm tra rải rác ở nhiều tầng, vì khi đó không ai biết quy tắc thật nằm ở đâu.` },
{ q: `Token hợp lệ nhưng người dùng không còn quyền. Hệ thống của bạn xử lý thế nào?`, a: `Đây là trường hợp phải phân biệt rõ hai mã trả về. Nếu token không hợp lệ hoặc đã hết hạn thì trả về mã lỗi xác thực, kèm chỉ dẫn để client làm mới. Nếu token hợp lệ nhưng không đủ quyền cho hành động đó thì trả về mã lỗi phân quyền, và client không nên thử làm mới token vì làm mới không giải quyết gì. Điểm quan trọng trong thực tế là quyền phải được đọc từ nguồn sự thật tại thời điểm kiểm tra, chứ không chỉ tin vào nội dung của token — vì token có thể được phát hành trước khi quyền bị thu hồi, và đó chính là cửa sổ mà kẻ tấn công khai thác.` },
],
},
E06: {
attacks: [
{ q: `Vì sao lỗi N+1 thường không lộ ra ở môi trường phát triển?`, a: `Vì số dòng dữ liệu nhỏ. Với mười bản ghi, mười một truy vấn chạy trong vài mili giây và không ai để ý; với mười nghìn bản ghi, số truy vấn tăng theo cấp số nhân và độ trễ vượt xa ngưỡng chấp nhận. Ngoài ra ở môi trường phát triển, cơ sở dữ liệu thường nằm cùng máy nên độ trễ mỗi truy vấn gần bằng không, trong khi ở production mỗi truy vấn có chi phí mạng thật. Vì vậy cách phát hiện đáng tin là đếm số truy vấn trong test và đặt ngưỡng, chứ không dựa vào cảm giác về tốc độ khi phát triển.` },
{ q: `Nạp trước quan hệ có nhược điểm gì?`, a: `Nó có thể làm truy vấn nặng hơn khi bạn không thực sự cần dữ liệu liên quan, vì bạn luôn trả giá cho việc lấy thêm dù chỉ dùng ở một nhánh hiếm. Với quan hệ nhiều-nhiều, việc nạp trước có thể tạo ra tích Descartes làm số dòng tăng vọt, và khi đó phải tách thành hai truy vấn thay vì một phép nối. Ngoài ra nạp trước làm mất tính lười của truy vấn, nên những chỗ dựa vào việc chỉ chạm dữ liệu khi cần sẽ bị ảnh hưởng. Cách cân bằng là nạp trước theo từng endpoint dựa trên dữ liệu endpoint đó thật sự trả về, chứ không đặt một quy tắc chung cho toàn bộ mô hình.` },
],
},
};
