// Batch P0-A — `attacks` (hostile interviewer follow-ups) for the highest-value P0
// questions: Python A01..A07, Vue C01..C09, AWS G02..G10. Two attacks each, chosen to
// be the question a strong interviewer asks immediately after the textbook answer —
// and deliberately NOT a restatement of the existing 3-tier `followups` chain.
export default {
A01: {
attacks: [
{ q: `Bạn nói <code>is</code> so sánh danh tính. Vậy vì sao <code>a = 256; b = 256; a is b</code> cho <code>True</code> còn <code>1000</code> thì cho <code>False</code>?`, a: `Vì CPython cache sẵn các số nguyên nhỏ trong một khoảng, thường là từ -5 tới 256, nên hai tên cùng trỏ vào một object đã có. Với 1000 thì mỗi lần viết literal là một object mới, nên danh tính khác nhau. Điểm cần nói rõ trong phỏng vấn là đây là chi tiết triển khai của CPython, không phải bảo đảm của ngôn ngữ — một bản Python khác hoặc một phiên bản khác hoàn toàn có thể làm khác, và không có gì trong đặc tả buộc phải cache. Vì vậy đừng bao giờ dựa vào <code>is</code> cho số hay chuỗi; chỉ dùng nó cho <code>None</code>, <code>True</code>, <code>False</code> và cho việc so sánh với một sentinel do chính bạn tạo.` },
{ q: `Nếu tôi định nghĩa <code>__eq__</code> cho lớp của mình mà quên <code>__hash__</code>, chuyện gì xảy ra?`, a: `Python đặt <code>__hash__</code> thành <code>None</code> cho lớp đó, nên các instance trở thành không băm được và không đặt được vào set hay dict. Đây là hành vi có chủ đích: nếu hai object bằng nhau theo <code>__eq__</code> nhưng lại có hash khác nhau thì bất biến của bảng băm bị phá vỡ, và việc tra cứu sẽ sai một cách âm thầm. Vì vậy Python chọn cách chặn hẳn thay vì để bạn tự gây lỗi. Muốn dùng được trong set thì phải định nghĩa <code>__hash__</code> nhất quán với <code>__eq__</code>, và chỉ băm những trường bất biến.` },
],
},
A02: {
attacks: [
{ q: `Vậy nếu tôi cần sao chép sâu một object có tham chiếu vòng thì <code>deepcopy</code> xử lý thế nào?`, a: `<code>deepcopy</code> giữ một bảng ánh xạ từ object gốc sang bản sao trong suốt quá trình, nên khi gặp lại một object đã sao chép, nó trả về bản sao đã có thay vì đệ quy vô hạn. Nhờ vậy cấu trúc vòng được tái tạo đúng hình dạng chứ không bị treo hay bị cắt. Chi phí là bộ nhớ cho bảng ánh xạ đó, và tốc độ chậm hơn nhiều so với sao chép nông. Điều cần lưu ý thêm là một số object không sao chép sâu được — kết nối mạng, handle tệp, lock — và với chúng bạn phải tự định nghĩa cách xử lý.` },
{ q: `Trong một API, khi nào việc truyền object vào hàm rồi hàm sửa nó lại trở thành lỗi production?`, a: `Khi object đó được chia sẻ ngoài ý muốn. Ví dụ điển hình là tham số mặc định mutable, biến cấp module, hoặc một object được cache rồi truyền vào nhiều request. Hàm sửa nó, và thay đổi đó rò sang request khác — không có lỗi nào được ném, chỉ có dữ liệu của người dùng này xuất hiện trong phản hồi của người dùng kia. Đây là loại lỗi khó tái hiện nhất vì nó phụ thuộc thứ tự request. Cách phòng là để hàm nhận dữ liệu và trả về dữ liệu mới thay vì sửa tại chỗ, và với những cấu trúc được chia sẻ thì sao chép ở ranh giới.` },
],
},
A03: {
attacks: [
{ q: `Bạn nói tuple băm được khi mọi phần tử băm được. Vậy tuple chứa list thì sao, và vì sao thiết kế lại như vậy?`, a: `Nó không băm được và Python ném <code>TypeError: unhashable type</code>. Lý do là bất biến của bảng băm: một khoá phải giữ nguyên hash trong suốt thời gian nó nằm trong bảng. Tuple là bất biến nên hash của nó ổn định, nhưng chỉ khi các phần tử cũng vậy — nếu một phần tử là list và bị sửa, hash của tuple sẽ đổi trong khi tuple vẫn nằm trong dict, và mọi tra cứu sau đó sai. Vì vậy Python kiểm tra tính băm được của từng phần tử và từ chối ngay thay vì để bảng băm hỏng âm thầm.` },
{ q: `Vậy có phải chỉ object bất biến mới băm được?`, a: `Không, và đây là hiểu nhầm phổ biến. Một instance của lớp bạn tự viết mặc định vẫn băm được, với hash dựa trên danh tính của object — nghĩa là nó mutable nhưng vẫn dùng làm khoá được. Cái không được phép là định nghĩa <code>__eq__</code> theo giá trị mà không định nghĩa <code>__hash__</code> tương ứng, vì khi đó hai object bằng nhau có thể có hash khác nhau. Vậy quy tắc đúng không phải "bất biến thì băm được", mà là "hash phải ổn định và nhất quán với bằng nhau". Bất biến chỉ là cách dễ nhất để bảo đảm điều đó.` },
],
},
A04: {
attacks: [
{ q: `Nếu hàm của tôi có mười tham số tùy chọn, tôi có phải viết mười lần kiểm tra None không?`, a: `Không, và nếu bạn thấy mình đang làm vậy thì đó là dấu hiệu thiết kế sai. Cách gọn hơn là gom các tham số tùy chọn vào một object cấu hình bất biến, hoặc dùng một dataclass với <code>field(default_factory=...)</code> để mỗi instance có giá trị mới. Nếu hàm thực sự cần mười tham số tùy chọn thì vấn đề nằm ở việc hàm đang làm quá nhiều việc, và nên tách ra. Điểm cần giữ là nguyên tắc: giá trị mặc định mutable không bao giờ được đặt trực tiếp trong chữ ký hàm, bất kể có bao nhiêu tham số.` },
{ q: `Làm sao bạn chứng minh cơ chế này trong phỏng vấn mà không chỉ nói lý thuyết?`, a: `Bằng cách chỉ vào chính thuộc tính của hàm. <code>add_tag.__defaults__</code> cho <code>([],)</code>, và nếu bạn gọi hàm một lần rồi in lại, bạn thấy chính tuple đó đã đổi thành <code>(['a'],)</code> — nghĩa là object mặc định bị sửa tại chỗ chứ không được tạo lại. Đối chiếu thêm với <code>add_tag.__code__.co_consts</code> cho thấy list không nằm trong bảng hằng số, nên nó không phải hằng số của code object mà là giá trị gắn vào chính đối tượng hàm. Cách chứng minh này mạnh hơn nhiều so với việc mô tả lại định nghĩa.` },
],
},
A05: {
attacks: [
{ q: `Vậy comprehension có phạm vi riêng, nhưng vì sao lambda trong comprehension vẫn bắt cùng một giá trị?`, a: `Vì phạm vi riêng và số ô nhớ là hai chuyện khác nhau. Comprehension tạo một phạm vi mới nên biến đếm không rò ra ngoài, nhưng bên trong phạm vi đó vẫn chỉ có một ô cho biến đếm, dùng lại qua mọi vòng lặp — đúng như vòng lặp for thường. Mỗi lambda đóng lại trên chính ô đó, nên tất cả cùng đọc giá trị cuối. Nếu muốn mỗi lambda giữ giá trị riêng thì phải buộc tạo ô mới cho từng vòng, ví dụ bằng cách đặt giá trị đó làm tham số mặc định của lambda, hoặc dùng hàm nhà máy trả về một closure mới mỗi lần gọi.` },
{ q: `Có cách viết nào vừa gọn vừa đúng cho trường hợp tạo nhiều handler trong vòng lặp?`, a: `Ba cách, tuỳ ngữ cảnh. Một là dùng tham số mặc định để chụp giá trị tại thời điểm tạo: <code>lambda i=i: i</code> — ngắn nhưng dễ bị người đọc bỏ qua. Hai là hàm nhà máy: một hàm nhận giá trị và trả về một closure mới, cách này rõ nghĩa nhất và dễ kiểm thử. Ba là dùng <code>functools.partial</code> khi handler chỉ cần nhận thêm tham số. Điều nên tránh là dựa vào việc biến vòng lặp "trông như" đã được chụp — nó chưa bao giờ như vậy, và đây là lỗi xuất hiện trong cả JavaScript với <code>var</code> lẫn Python.` },
],
},
A06: {
attacks: [
{ q: `Nếu tôi đọc một biến toàn cục trong hàm thì Python tìm ở đâu, và vì sao gán lại nó trong hàm lại lỗi?`, a: `Python tìm theo thứ tự từ phạm vi cục bộ, tới phạm vi bao quanh, tới phạm vi module, rồi tới built-in. Việc gán trong hàm làm tên đó trở thành biến cục bộ của cả hàm — quyết định này được đưa ra lúc biên dịch, dựa trên sự tồn tại của phép gán ở bất kỳ đâu trong thân hàm. Vì vậy nếu bạn đọc tên đó ở dòng đầu rồi gán ở dòng cuối, dòng đầu sẽ ném <code>UnboundLocalError</code>, vì lúc đó tên đã được xác định là cục bộ nhưng chưa có giá trị. Muốn gán vào biến toàn cục phải khai báo <code>global</code>, và muốn gán vào biến của hàm bao quanh phải khai báo <code>nonlocal</code>.` },
{ q: `Vì sao việc sửa một list toàn cục trong hàm lại không cần <code>global</code>?`, a: `Vì bạn không gán lại tên, bạn gọi một phương thức trên object mà tên đó trỏ tới. Quy tắc <code>global</code> chỉ áp dụng cho phép gán tên, tức là làm cho tên trỏ tới một object khác. <code>items.append(x)</code> đọc tên <code>items</code> từ phạm vi ngoài rồi sửa chính object đó, nên không có phép gán tên nào và không cần khai báo. Đây là lý do trạng thái toàn cục mutable nguy hiểm: nó bị sửa từ khắp nơi mà không có dấu hiệu nào ở chữ ký hàm cho thấy hàm đó có tác dụng phụ.` },
],
},
A07: {
attacks: [
{ q: `Decorator của bạn có giữ được metadata của hàm gốc không? Vì sao điều đó quan trọng?`, a: `Mặc định là không: hàm bọc thay thế hàm gốc nên <code>__name__</code>, <code>__doc__</code> và chữ ký đều bị mất, và công cụ introspection như tài liệu tự sinh hay framework dựa trên chữ ký sẽ hoạt động sai. Cách sửa là dùng <code>functools.wraps</code> trên hàm bọc, nó sao chép metadata và cả <code>__wrapped__</code>. Điều này quan trọng trong thực tế vì FastAPI và nhiều framework đọc chữ ký hàm để suy ra tham số; nếu chữ ký bị mất thì dependency injection hoặc tài liệu API hỏng theo cách rất khó lần ra.` },
{ q: `Decorator có tham số khác gì decorator không tham số về mặt cấu trúc?`, a: `Nó thêm một tầng hàm. Decorator không tham số nhận hàm và trả về hàm. Decorator có tham số nhận tham số và trả về một decorator — tức là ba tầng lồng nhau: tầng ngoài nhận cấu hình, tầng giữa nhận hàm, tầng trong là hàm bọc thực thi. Chỗ dễ sai là quên một tầng, dẫn tới việc hàm bị gọi ngay lúc định nghĩa thay vì lúc được gọi. Và nếu decorator được áp dụng cho phương thức thì cần chú ý tới việc <code>self</code> được truyền qua như tham số đầu tiên của hàm bọc.` },
],
},
C01: {
attacks: [
{ q: `Trong <code>script setup</code>, vì sao không cần trả về gì mà template vẫn dùng được biến?`, a: `Vì trình biên dịch của Vue xử lý khối đó theo cách riêng: nó đưa mọi khai báo cấp cao nhất vào phạm vi mà hàm render nhìn thấy, nên template truy cập trực tiếp được. Điều này khác với <code>setup()</code> thường, nơi bạn phải trả về một object chứa những gì template cần. Hệ quả thực tế là trong <code>script setup</code> bạn không thể dùng cú pháp đó ở chỗ cần giá trị trả về, và mọi import cũng tự động có sẵn cho template. Đây là lý do <code>script setup</code> ngắn hơn hẳn, nhưng cũng là lý do cần hiểu nó là cú pháp được biên dịch chứ không phải một hàm thông thường.` },
{ q: `Options API và Composition API có thể trộn trong cùng một dự án không, và khi nào nên?`, a: `Có, và chúng thậm chí trộn được trong cùng một component. Trong thực tế, trộn ở cấp dự án là hợp lý khi bạn đang chuyển dần một codebase lớn: viết component mới bằng Composition API, giữ component cũ nguyên trạng, và chỉ chuyển khi có lý do cụ thể. Trộn trong cùng một component thì nên tránh vì hai hệ thống có cách khai báo vòng đời và trạng thái khác nhau, nên rất dễ gây nhầm lẫn về thứ tự chạy và phạm vi. Điều quan trọng khi trả lời phỏng vấn là nêu được tiêu chí chuyển: logic phức tạp cần tái sử dụng thì Composition API thắng, còn component nhỏ, ít logic thì Options API vẫn đọc rõ ràng hơn.` },
],
},
C02: {
attacks: [
{ q: `Nếu tôi viết <code>const count = ref(0)</code> rồi <code>count = count + 1</code> thì chuyện gì xảy ra?`, a: `Với <code>const</code> bạn nhận <code>TypeError: Assignment to constant variable</code> ngay lập tức. Với <code>let</code> thì phép cộng chạy trên chính object ref, nên kết quả là một chuỗi hoặc <code>NaN</code> tuỳ toán tử — và biến <code>count</code> giờ trỏ tới giá trị rác đó thay vì một ref, nên template mất tính phản ứng. Đây là lỗi rất dễ xảy ra vì trong template bạn viết <code>{{ count }}</code> không có <code>.value</code> — trình biên dịch tự mở gói — nhưng trong script thì bắt buộc phải có. Cách nhớ là: template tự mở gói, script thì không.` },
{ q: `Khi nào bạn chọn <code>reactive</code> thay vì <code>ref</code>, và cái giá phải trả là gì?`, a: `Chọn <code>reactive</code> khi bạn có một object trạng thái gồm nhiều trường liên quan và muốn truy cập trực tiếp không qua <code>.value</code>. Cái giá là ba hạn chế thật: destructure làm mất tính phản ứng vì bạn sao chép giá trị nguyên thuỷ ra khỏi proxy; gán lại toàn bộ object làm hỏng liên kết phản ứng vì bạn thay proxy bằng object thường; và nó không dùng được cho kiểu nguyên thuỷ. Vì vậy nhiều đội chọn <code>ref</code> cho mọi thứ để có một quy tắc duy nhất, chấp nhận viết <code>.value</code> nhiều hơn. Điều cần tránh là trộn hai cách tuỳ hứng, vì người đọc phải nhớ trường nào thuộc loại nào.` },
],
},
C03: {
attacks: [
{ q: `Vì sao <code>const { count } = state</code> làm mất tính phản ứng, và <code>toRefs</code> sửa được gì?`, a: `Destructure đọc giá trị ra khỏi proxy và gán vào một biến mới, nên biến đó là một con số hoặc chuỗi bình thường, không còn liên kết với proxy. Vue chỉ theo dõi được qua proxy, nên mọi thay đổi sau đó không còn được ghi nhận. <code>toRefs</code> trả về một object trong đó mỗi trường là một ref trỏ tới đúng thuộc tính của object gốc, nên destructure ra vẫn giữ liên kết — bạn phải đọc qua <code>.value</code>, nhưng tính phản ứng còn nguyên. Với store của Pinia thì dùng <code>storeToRefs</code>, vì store có thêm các thuộc tính không phải state mà bạn không muốn biến thành ref.` },
{ q: `Vue dùng Proxy để làm gì, và có trường hợp nào Proxy không theo dõi được?`, a: `Proxy bọc object và chặn các phép đọc ghi, cho phép Vue ghi lại ai đọc thuộc tính nào và thông báo cho những effect phụ thuộc khi thuộc tính đó đổi. Nó không theo dõi được những thứ nằm ngoài tầm chặn: một object không được bọc, một giá trị nguyên thuỷ bị sao chép ra khỏi proxy, hoặc một cấu trúc không đi qua proxy như bản đồ hay tập hợp chưa được xử lý. Nó cũng không theo dõi được thay đổi bên trong một thư viện bên thứ ba nếu thư viện đó giữ tham chiếu tới object gốc. Đây là lý do phải dùng <code>ref</code> cho giá trị nguyên thuỷ và phải cẩn thận khi tích hợp thư viện ngoài.` },
],
},
C04: {
attacks: [
{ q: `Nếu tôi đặt một lời gọi API trong <code>computed</code> thì sao?`, a: `Nó chạy, nhưng sai về mặt thiết kế và gây hậu quả thật. <code>computed</code> được đánh giá lại mỗi khi phụ thuộc đổi và cũng có thể được đánh giá trong lúc render, nên bạn sẽ gọi API với tần suất không kiểm soát được, có thể nhiều lần cho một thay đổi. Nó cũng khiến kết quả phụ thuộc vào thời điểm, nên component không còn thuần tuý và khó kiểm thử. Ngoài ra bạn không có chỗ để dọn dẹp tác dụng phụ cũ. Quy tắc là <code>computed</code> chỉ để tính giá trị từ state, còn mọi việc có tác dụng phụ — gọi mạng, ghi log, điều hướng — thuộc về <code>watch</code>, nơi có cơ chế dọn dẹp.` },
{ q: `<code>watch</code> và <code>watchEffect</code> khác nhau ở điểm nào quan trọng nhất?`, a: `Ở cách xác định phụ thuộc. <code>watchEffect</code> chạy hàm ngay lập tức và tự thu thập mọi thứ được đọc trong lần chạy đó, nên bạn viết ít hơn nhưng khó kiểm soát chính xác cái gì kích hoạt nó. <code>watch</code> nhận nguồn theo cách tường minh, nên bạn biết chính xác khi nào nó chạy, và có thêm các tuỳ chọn như chạy ngay lần đầu, theo dõi sâu, hay chọn thời điểm chạy. Điểm quan trọng nhất trong thực tế là <code>watch</code> cho bạn giá trị cũ và giá trị mới, còn <code>watchEffect</code> thì không. Khi logic phụ thuộc vào việc so sánh trước sau thì phải dùng <code>watch</code>.` },
],
},
C05: {
attacks: [
{ q: `Vì sao tính phản ứng của Vue không tự giải quyết được race condition giữa hai request?`, a: `Vì tính phản ứng chỉ giải quyết việc đồng bộ giữa state và giao diện, không giải quyết thứ tự hoàn thành của các tác vụ bất đồng bộ. Khi một response cũ về sau, việc gán nó vào state là một phép ghi hợp lệ — Vue ghi nhận và cập nhật giao diện đúng như thiết kế. Hệ thống phản ứng không có cách nào biết rằng phép ghi đó là lỗi thời, vì nó không biết gì về nghiệp vụ. Vì vậy việc chống ghi đè phải nằm ở tầng logic: huỷ request cũ, hoặc gắn định danh đơn điệu cho mỗi lần gọi và bỏ qua response không còn là mới nhất.` },
{ q: `<code>onCleanup</code> trong <code>watch</code> chạy khi nào, và nó khác <code>onUnmounted</code> ở đâu?`, a: `<code>onCleanup</code> chạy ngay trước mỗi lần callback được gọi lại, tức là mỗi khi phụ thuộc đổi, và cũng chạy khi component bị gỡ. <code>onUnmounted</code> chỉ chạy một lần khi component bị gỡ. Vì vậy chỗ đúng để huỷ request cũ là <code>onCleanup</code>, không phải <code>onUnmounted</code>: nếu bạn chỉ huỷ khi component bị gỡ thì những request bị bỏ dở giữa các lần đổi từ khoá vẫn tiếp tục chạy và vẫn có thể ghi đè. Đây chính là chi tiết mà nhiều bản cài đặt làm thiếu, và triệu chứng là kết quả cũ xuất hiện trở lại sau khi người dùng đã gõ từ khoá mới.` },
],
},
C06: {
attacks: [
{ q: `Vì sao component con không nên sửa trực tiếp prop?`, a: `Vì prop thuộc sở hữu của component cha, và luồng dữ liệu được thiết kế một chiều để việc suy luận về trạng thái là khả thi. Nếu con sửa được prop, thì khi giao diện sai bạn không biết ai đã đổi giá trị đó, và hai component có thể ghi đè lẫn nhau. Vue cảnh báo trong môi trường phát triển khi bạn gán vào prop, nhưng với object hoặc mảng thì nó không phát hiện được việc bạn sửa thuộc tính bên trong — và đó là lỗi phổ biến hơn. Cách đúng là con phát sự kiện để cha quyết định, hoặc dùng một trạng thái cục bộ được khởi tạo từ prop khi thực sự cần bản sao.` },
{ q: `Khi nào bạn dùng <code>v-model</code> trên component thay vì tự phát sự kiện?`, a: `Dùng <code>v-model</code> khi component đóng vai trò một ô nhập có giá trị hai chiều rõ ràng — input tuỳ chỉnh, bộ chọn, ô tìm kiếm. Nó là cú pháp rút gọn cho một prop giá trị cộng một sự kiện cập nhật, nên nó không thêm khả năng mới mà chỉ làm ý định rõ hơn. Ngược lại, nên phát sự kiện có tên nghiệp vụ khi component không phải là ô nhập — ví dụ <code>submitted</code>, <code>cancelled</code> — vì những sự kiện đó truyền đạt ý định chứ không chỉ truyền giá trị. Điều cần tránh là dùng <code>v-model</code> cho mọi thứ, vì nó làm mờ việc component đang thực sự làm gì.` },
],
},
C07: {
attacks: [
{ q: `Vì sao <code>v-for</code> cần khoá ổn định, và dùng chỉ số làm khoá gây lỗi gì?`, a: `Khoá cho Vue biết phần tử nào trong danh sách mới tương ứng với phần tử nào trong danh sách cũ, để nó tái sử dụng đúng thực thể component thay vì dựng lại theo vị trí. Nếu bạn dùng chỉ số làm khoá và chèn một phần tử vào đầu danh sách, mọi chỉ số dịch một bậc, nên Vue tưởng rằng nội dung của từng vị trí đã thay đổi và cập nhật lại toàn bộ. Triệu chứng thật là trạng thái cục bộ của component con bị gắn nhầm — ví dụ nội dung đang gõ trong ô nhập của dòng thứ ba nhảy sang dòng thứ tư. Khoá phải là định danh của dữ liệu, không phải vị trí của nó.` },
{ q: `<code>v-if</code> và <code>v-show</code> khác nhau ở đâu về chi phí?`, a: `<code>v-if</code> không dựng phần tử khi điều kiện sai, nên tiết kiệm chi phí render và bộ nhớ nhưng mỗi lần đổi điều kiện phải dựng hoặc huỷ thật. <code>v-show</code> luôn dựng phần tử và chỉ đổi thuộc tính hiển thị, nên lần đổi đầu rẻ nhưng phần tử vẫn nằm trong cây DOM và vẫn tốn bộ nhớ. Vì vậy chọn theo tần suất đổi: nội dung ít khi hiện thì dùng <code>v-if</code>, nội dung đổi qua lại liên tục như tab thì <code>v-show</code>. Một điểm cần lưu ý là <code>v-show</code> không hoạt động trên <code>template</code> vì nó cần một phần tử thật để gắn thuộc tính.` },
],
},
C08: {
attacks: [
{ q: `Vì sao thay đổi state rồi đọc DOM ngay lập tức lại nhận giá trị cũ?`, a: `Vì Vue gom các thay đổi trong cùng một lượt và cập nhật DOM bất đồng bộ, ở cuối chu kỳ cập nhật. Khi bạn gán state, Vue chỉ đánh dấu là cần cập nhật; DOM chưa đổi cho tới khi hàng đợi được xử lý. Vì vậy phép đọc ngay sau đó thấy DOM cũ. Cách đúng là chờ <code>nextTick</code>, hoặc dùng <code>watch</code> với thời điểm chạy sau khi DOM đã cập nhật. Cơ chế gom này là điều kiện để hiệu năng chấp nhận được — nếu mỗi phép gán đều cập nhật DOM ngay thì một vòng lặp sửa nhiều trường sẽ gây rất nhiều lần render.` },
{ q: `Template ref nên dùng khi nào, và có cách nào tránh nó không?`, a: `Template ref cần thiết khi bạn phải tương tác với API của DOM mà Vue không bọc: đặt focus, đo kích thước, cuộn tới một vị trí, hoặc khởi tạo một thư viện bên ngoài cần phần tử thật. Cách tránh là đẩy hành vi đó vào chính component con, để component con tự quản lý phần tử của nó và chỉ phát ra sự kiện hay nhận prop — như vậy component cha không phải biết gì về DOM. Nếu bạn thấy template ref xuất hiện ở nhiều component cha để điều khiển con, đó thường là dấu hiệu ranh giới component chưa đúng.` },
],
},
C09: {
attacks: [
{ q: `Khi nào nên dùng composable, khi nào nên dùng Pinia?`, a: `Composable phù hợp khi bạn muốn tái sử dụng logic có trạng thái cục bộ — mỗi lần gọi tạo một bản trạng thái riêng, ví dụ logic tìm kiếm có debounce, hoặc xử lý biểu mẫu. Pinia phù hợp khi trạng thái phải được chia sẻ giữa nhiều component ở những nhánh cây khác nhau, hoặc phải tồn tại qua việc điều hướng. Tiêu chí phân biệt là phạm vi sống của trạng thái: nếu nó thuộc về một màn hình thì composable, nếu nó thuộc về ứng dụng thì store. Điều nên tránh là biến store thành nơi chứa mọi thứ, vì khi đó mọi component đều phụ thuộc vào nó và việc kiểm thử trở nên khó.` },
{ q: `Vì sao <code>provide</code> và <code>inject</code> không nên dùng thay cho props?`, a: `Vì nó làm mất tính tường minh của phụ thuộc. Với props, đọc chữ ký component là biết nó cần gì; với <code>inject</code>, component có thể phụ thuộc vào thứ không xuất hiện ở đâu trong giao diện của nó, và nếu nhà cung cấp không tồn tại thì lỗi chỉ xuất hiện lúc chạy. Nó cũng khiến việc tái sử dụng component ra ngoài ngữ cảnh ban đầu trở nên khó vì thiếu nhà cung cấp. <code>provide</code>/<code>inject</code> đúng khi cần tránh truyền xuyên qua nhiều tầng trung gian không liên quan, hoặc khi thư viện cung cấp một ngữ cảnh dùng chung — và nên đi kèm một khoá có kiểu rõ ràng cùng giá trị mặc định hợp lý.` },
],
},
G02: {
attacks: [
{ q: `Nếu execution role có quyền <code>s3:*</code> thì có vấn đề gì, khi mọi thứ vẫn chạy?`, a: `Nó chạy, nhưng bạn đã biến một lỗ hổng nhỏ thành một lỗ hổng lớn. Nếu hàm bị chiếm qua một lỗ hổng trong thư viện, kẻ tấn công nhận được toàn quyền trên mọi bucket mà tài khoản truy cập được — đọc, ghi, và xoá dữ liệu của mọi khách hàng. Quyền tối thiểu giới hạn thiệt hại trong trường hợp đó: hàm chỉ đọc được đúng bucket và tiền tố nó cần, nên phạm vi ảnh hưởng bị chặn. Ngoài ra quyền rộng còn che mất lỗi thiết kế, vì hàm gọi được những thứ mà đáng lẽ nó không nên biết tới. Cách làm đúng là bắt đầu từ không có quyền và thêm dần theo nhu cầu thật.` },
{ q: `Một hàm báo AccessDenied. Bạn kiểm tra theo thứ tự nào?`, a: `Bốn bước, từ khả năng cao nhất. Một là xác định danh tính thật sự đang gọi: với hàm Lambda tự gọi dịch vụ thì đó là execution role, không phải người gọi hàm. Hai là đọc thông báo lỗi đầy đủ, vì nó thường nêu chính xác action bị từ chối và ai từ chối — thiếu một action phụ như liệt kê bucket là nguyên nhân phổ biến. Ba là kiểm tra cả hai lớp quyền: policy gắn vào danh tính và policy gắn vào tài nguyên, vì một trong hai có thể đang chặn. Bốn là kiểm tra các rào cản ngang: ranh giới quyền, chính sách tổ chức, và điều kiện trong policy như yêu cầu mã hoá hoặc yêu cầu định danh cụ thể.` },
],
},
G03: {
attacks: [
{ q: `Handler của bạn ném lỗi ở dòng đầu tiên. Với invocation bất đồng bộ, khách hàng có biết không?`, a: `Không. Với invocation bất đồng bộ, bên gọi chỉ nhận được xác nhận rằng event đã vào hàng đợi, chứ không nhận kết quả xử lý. Lỗi xảy ra sau đó chỉ đi vào log, vào metric lỗi, và — nếu bạn cấu hình — vào một điểm đến xử lý lỗi. Đây là hệ quả quan trọng: một hàm bất đồng bộ lỗi 100% vẫn trông như thành công từ phía người gọi. Vì vậy với luồng bất đồng bộ, cảnh báo trên metric lỗi và trên độ sâu hàng đợi của điểm đến là thứ duy nhất cho bạn biết có chuyện, và nếu không có nó thì sự cố chỉ lộ ra khi người dùng cuối phàn nàn.` },
{ q: `Vì sao đặt client ở cấp module lại có thể gây lỗi khó tìm?`, a: `Vì kết nối được tạo ở pha khởi tạo và có thể đã bị phía đối tác đóng trong lúc môi trường nằm chờ. Khi môi trường được tái dùng cho lần gọi sau, client đó vẫn tồn tại nhưng kết nối bên dưới đã chết, nên lần gọi đầu tiên thất bại trong khi lần gọi thứ hai thành công — triệu chứng là lỗi thoáng qua, không tái hiện được, xuất hiện ngẫu nhiên theo thời gian sống của môi trường. Cách xử lý là bắt lỗi kết nối và dựng lại client, chứ không phải dựng client mới ở mọi lần gọi, vì như vậy bạn mất hết lợi ích của việc tái dùng.` },
],
},
G04: {
attacks: [
{ q: `Vì sao phải tách quyền gọi hàm khỏi quyền của hàm?`, a: `Vì chúng trả lời hai câu hỏi khác nhau và có hai chủ thể khác nhau. Quyền gọi hàm nằm trong policy gắn vào tài nguyên hàm và trả lời "ai được phép kích hoạt hàm này" — thường là một dịch vụ, một tài khoản khác, hoặc API Gateway. Quyền của hàm nằm trong execution role và trả lời "hàm này được phép làm gì với các dịch vụ khác". Trộn hai thứ này là lỗi thiết kế phổ biến: cấp cho người gọi quyền của hàm, hoặc ngược lại. Hệ quả là hoặc người gọi có nhiều quyền hơn cần, hoặc hàm không gọi được dịch vụ dù người gọi có quyền.` },
{ q: `Một tài khoản khác trong cùng tổ chức muốn gọi hàm của bạn. Bạn cấu hình gì?`, a: `Hai việc ở hai phía. Phía bạn, thêm một policy gắn vào tài nguyên hàm cho phép principal của tài khoản kia thực hiện hành động gọi hàm, và giới hạn vào đúng hàm đó chứ không phải tất cả. Phía họ, thêm một policy trên danh tính cho phép gọi hàm đó. Cả hai đều cần, vì một bên cho phép tài nguyên và một bên cho phép danh tính. Nếu phía họ cần gọi từ một hàm của họ, thì nên dùng một role với điều kiện nguồn cụ thể thay vì cấp quyền cho cả tài khoản — cách này thu hẹp phạm vi và tránh việc mọi thứ trong tài khoản kia đều gọi được.` },
],
},
G05: {
attacks: [
{ q: `API Gateway trả 502. Bạn phân biệt nguyên nhân thế nào?`, a: `502 nghĩa là gateway nhận được phản hồi không hợp lệ từ phía sau, nên nguyên nhân nằm ở định dạng phản hồi chứ không ở logic nghiệp vụ. Với hàm proxy, nguyên nhân phổ biến nhất là thân phản hồi không đúng cấu trúc mà gateway mong đợi — thiếu trường mã trạng thái, hoặc thân không phải chuỗi. Nguyên nhân thứ hai là hàm ném lỗi chưa được bắt, khiến gateway nhận một phản hồi không đúng định dạng. Nguyên nhân thứ ba là vượt thời gian chờ tích hợp, nhưng trường hợp đó thường cho 504. Cách phân biệt nhanh là đọc log của hàm trước, vì 502 hầu như luôn có tương ứng một lần chạy hàm thất bại hoặc trả về sai định dạng.` },
{ q: `Vì sao CORS ở API Gateway lại hay gây lỗi khó hiểu?`, a: `Vì CORS là cơ chế của trình duyệt, và khi nó chặn thì lỗi hiện ở phía client chứ không ở phía server — log của API có thể cho thấy request đã thành công. Với yêu cầu không đơn giản, trình duyệt gửi một yêu cầu kiểm tra trước, và nếu yêu cầu đó không được trả lời đúng thì request thật không bao giờ được gửi. Điểm dễ sai là cấu hình CORS phải áp dụng cho cả yêu cầu kiểm tra lẫn phản hồi thật, và với thông tin xác thực thì không được dùng nguồn đại diện. Một điểm nữa là CORS không phải cơ chế xác thực — nó chỉ quyết định trình duyệt có cho phép đọc phản hồi hay không, còn máy khách khác hoàn toàn có thể gọi API trực tiếp.` },
],
},
G06: {
attacks: [
{ q: `Presigned URL có bảo vệ được việc người dùng tải lên nội dung độc hại không?`, a: `Không. Presigned URL chỉ là một chữ ký cho phép thực hiện đúng một hành động trên đúng một khoá trong một khoảng thời gian. Nó không kiểm tra nội dung, không giới hạn kích thước thật, và không ngăn được việc tải lên một tệp có định dạng khác với khai báo. Vì vậy mọi kiểm tra nội dung phải nằm sau đó: xác minh kích thước và loại nội dung thật bằng cách đọc phần đầu tệp, quét virus, và chỉ công bố tệp sau khi kiểm tra xong. Điểm quan trọng là không được phục vụ tệp trực tiếp từ bucket nhận tải lên; hãy để nó ở trạng thái chờ và chuyển sang bucket công bố sau khi qua kiểm tra.` },
{ q: `Làm sao giới hạn kích thước tệp khi dùng presigned URL?`, a: `Bằng điều kiện trong chính chữ ký. Với phương thức tải lên bằng POST, bạn khai báo một dải kích thước cho phép và đưa nó vào chính sách được ký, nên máy chủ lưu trữ sẽ từ chối nếu vượt. Với phương thức PUT, bạn có thể ràng buộc bằng cách ký kèm điều kiện về độ dài nội dung, nhưng điều này phụ thuộc vào việc client gửi đúng header — nên không đủ chắc. Cách an toàn nhất là dùng POST với chính sách có điều kiện, hoặc coi giới hạn ở phía client chỉ là lớp trải nghiệm và luôn kiểm tra lại kích thước thật ở bước xử lý sau khi tệp đã lên.` },
],
},
G07: {
attacks: [
{ q: `Vì sao không nên đặt cơ sở dữ liệu quan hệ trong subnet công khai?`, a: `Vì subnet công khai chỉ có nghĩa là có đường ra và vào từ Internet, và điều đó biến cơ sở dữ liệu thành mục tiêu trực tiếp có thể bị dò tìm và tấn công từ bên ngoài. Nó cũng mở rộng bề mặt tấn công sang cả những lỗ hổng chưa biết trong phần mềm cơ sở dữ liệu. Cách đúng là đặt trong subnet riêng, chỉ cho phép kết nối từ nhóm bảo mật của tầng ứng dụng, và nếu cần truy cập từ máy cá nhân để gỡ lỗi thì đi qua một máy chủ nhảy hoặc một đường hầm, chứ không mở cổng ra Internet.` },
{ q: `Sao lưu tự động có đủ để bảo vệ dữ liệu không?`, a: `Không, vì sao lưu và khả năng phục hồi là hai chuyện khác nhau. Sao lưu tự động giúp bạn khôi phục về một thời điểm trong quá khứ, nhưng bạn chỉ biết mình thực sự phục hồi được khi đã thử. Điều cần làm thêm là kiểm tra định kỳ rằng bản sao lưu khôi phục được và dữ liệu sau khôi phục là đúng, vì một quy trình sao lưu chưa từng được thử thì chưa được coi là có. Cũng cần xác định rõ mục tiêu về lượng dữ liệu có thể mất và thời gian phục hồi, rồi kiểm tra cấu hình hiện tại có đáp ứng được hai mục tiêu đó không — chứ không chỉ tin rằng sao lưu đang bật là đủ.` },
],
},
G08: {
attacks: [
{ q: `Vì sao Scan lại nguy hiểm trong production?`, a: `Vì chi phí của nó tỉ lệ với toàn bộ dữ liệu trong bảng, không với số kết quả trả về. Một phép quét tìm mười dòng trong bảng một trăm triệu dòng vẫn phải đọc hết một trăm triệu dòng, nên nó tốn thời gian và tiêu hết dung lượng đọc được cấp. Hệ quả nghiêm trọng hơn là nó ảnh hưởng tới các truy vấn khác: khi một phép quét lớn chiếm hết dung lượng, những truy vấn đúng thiết kế cũng bị chậm hoặc bị từ chối. Vì vậy phép quét chỉ nên dùng cho công việc chạy nền, có giới hạn tốc độ, hoặc cho bảng nhỏ; trong đường phục vụ người dùng thì nó là dấu hiệu khoá chính hoặc chỉ mục chưa được thiết kế theo truy vấn.` },
{ q: `Bạn thiết kế khoá thế nào cho một truy vấn cần lọc theo hai trường?`, a: `Bằng cách chọn một khoá phân vùng theo trường có tính phân tán cao và được hỏi trong phần lớn truy vấn, rồi đặt trường còn lại vào khoá sắp xếp. Khoá sắp xếp cho phép lọc theo khoảng và sắp xếp kết quả ngay trong một phân vùng, nên bạn lấy được nhiều mẫu truy vấn từ cùng một bảng. Nếu cả hai trường đều cần được hỏi độc lập với tư cách điều kiện chính, thì thường phải ghi dữ liệu hai lần theo hai khoá khác nhau, hoặc thêm một chỉ mục phụ — và cả hai đều là chi phí thật cần nêu ra. Điều cần tránh là chọn khoá theo cách dữ liệu được tạo ra, vì cách tạo không liên quan gì tới cách truy vấn.` },
],
},
G09: {
attacks: [
{ q: `Vì sao điều kiện ghi lại an toàn hơn đọc rồi ghi trong DynamoDB?`, a: `Vì điều kiện được đánh giá nguyên tử bên trong dịch vụ, trên chính phiên bản của item tại thời điểm ghi. Khi hai request cùng ghi một item, dịch vụ xử lý tuần tự và một trong hai nhận lỗi điều kiện — không có cửa sổ nào để cả hai cùng thấy trạng thái cũ. Ngược lại, đọc rồi ghi là hai lời gọi riêng biệt, nên giữa chúng luôn có khoảng thời gian để request khác thay đổi dữ liệu, và cả hai đều quyết định dựa trên thông tin đã lỗi thời. Đây là cùng một nguyên tắc như ràng buộc duy nhất trong cơ sở dữ liệu quan hệ: chỉ tầng lưu trữ mới nguyên tử trước hai request đồng thời.` },
{ q: `Nếu điều kiện ghi thất bại, ứng dụng nên làm gì?`, a: `Phân biệt hai loại thất bại. Nếu thất bại vì một thao tác đã tồn tại — ví dụ cùng một khoá idempotency — thì đó là thành công về mặt nghiệp vụ, và nên trả về kết quả của lần trước thay vì báo lỗi. Nếu thất bại vì xung đột phiên bản trong một thao tác cập nhật, thì đó là tín hiệu có người khác vừa sửa, và cách xử lý phụ thuộc vào nghiệp vụ: đọc lại rồi thử lại với số phiên bản mới, hoặc báo cho người dùng rằng dữ liệu đã thay đổi. Điều không nên làm là thử lại mù quáng trong vòng lặp, vì với tranh chấp cao nó tạo ra vòng lặp thất bại liên tục và làm tình hình nặng hơn.` },
],
},
G10: {
attacks: [
{ q: `Vì sao tăng visibility timeout lên rất dài lại là ý tồi?`, a: `Vì nó đánh đổi khả năng chịu lỗi lấy sự yên tâm. Visibility timeout là khoảng thời gian message bị ẩn khỏi các consumer khác; nếu worker xử lý xong sớm thì không sao, nhưng nếu worker chết, message chỉ được giao lại sau khi hết khoảng đó. Đặt nó dài nghĩa là mỗi lần worker chết, message bị treo lâu trước khi có người xử lý lại, nên tuổi của message tăng và hàng đợi tụt lại. Cách đúng là đặt timeout theo thời gian xử lý thực tế cộng biên, và với công việc dài thì gia hạn timeout trong lúc đang xử lý thay vì đặt một con số khổng lồ từ đầu.` },
{ q: `Làm sao phát hiện hệ thống đang tụt lại trước khi người dùng nhận ra?`, a: `Bằng hai chỉ số cùng nhau. Chỉ số thứ nhất là tuổi của message cũ nhất đang chờ — nếu nó tăng đều, tốc độ xử lý đang thấp hơn tốc độ đến, và đó là dấu hiệu sớm nhất. Chỉ số thứ hai là độ sâu hàng đợi; nó tăng theo nhịp và có thể dao động, nên đọc một mình dễ gây nhiễu, nhưng đọc cùng tuổi message thì rất rõ. Cần đặt cảnh báo trên tuổi message chứ không chỉ trên độ sâu, vì độ sâu có thể ổn định trong khi tuổi tăng — nghĩa là có một message kẹt đang chặn tiến độ.` },
],
},
};
