var QUESTIONS = QUESTIONS || [];
QUESTIONS.push(
{
id: 'G01',
group: 'G',
topic: 'Region và Availability Zone, mô hình trách nhiệm chung',
prio: 'P0',
level: 'L1',
type: 'concept',
q: 'Hãy phân biệt Region với Availability Zone và cho biết phía khách hàng chịu trách nhiệm gì trong mô hình trách nhiệm chung?',
oral: 'Region là một khu vực địa lý độc lập gồm nhiều Availability Zone, còn mỗi Availability Zone là một trung tâm dữ liệu hoặc cụm trung tâm dữ liệu có nguồn điện và mạng riêng. Bạn chọn Region gần người dùng để giảm độ trễ và đáp ứng yêu cầu lưu trữ dữ liệu trong lãnh thổ nhất định, rồi triển khai dự phòng qua nhiều Zone để một sự cố cháy nổ hay mất điện không đánh sập toàn bộ hệ thống. Trong mô hình trách nhiệm chung, nhà cung cấp chịu trách nhiệm bảo mật cho hạ tầng đám mây như phần cứng và ảo hóa, còn bạn chịu trách nhiệm bảo mật trong đám mây như dữ liệu, phân quyền và cấu hình. Hiểu rõ ranh giới này giúp bạn không phó mặc mọi việc cho nhà cung cấp mà chủ động cấu hình sao lưu, mã hóa và kiểm soát truy cập.',
deep: '<p><strong>Đó là gì:</strong> <code>Region</code> là một vùng địa lý độc lập, ví dụ Singapore hay Tokyo, gồm từ ba Availability Zone trở lên. <code>Availability Zone</code> là một hay nhiều trung tâm dữ liệu vật lý tách biệt về nguồn điện, làm mát và mạng, nhưng được nối với nhau bằng đường truyền riêng tốc độ cao và độ trễ thấp.</p><p><strong>Cơ chế hoạt động:</strong> khi bạn tạo tài nguyên, bạn chọn Region cố định cho tài nguyên đó, còn dữ liệu sao chép giữa các Zone trong cùng Region gần như đồng bộ và rất nhanh. Triển khai đa Zone giúp hệ thống sống sót khi một Zone gặp sự cố, vì lưu lượng được chuyển sang Zone còn lại mà không cần đổi Region.</p><p><strong>Vì sao cần mô hình trách nhiệm chung:</strong> nhà cung cấp bảo đảm an toàn cho hạ tầng vật lý, phần cứng và lớp ảo hóa, còn bạn chịu trách nhiệm cho những gì bạn đặt lên đám mây gồm dữ liệu, mã nguồn, chính sách truy cập và cấu hình mạng. Ranh giới này buộc mọi đội đều phải làm phần việc của mình thay vì mặc định đám mây đã an toàn sẵn.</p><ul><li><strong>Tình huống cụ thể:</strong> một web chạy ở Region Singapore với máy chủ đặt ở hai Zone khác nhau, một Zone mất điện thì Zone còn lại vẫn phục vụ người dùng.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng đa Zone cho mọi hệ thống production cần độ sẵn sàng cao; không cần đa Region ngay từ đầu vì chi phí vận hành và độ phức tạp đồng bộ dữ liệu tăng mạnh.</li><li><strong>Lỗi phổ biến:</strong> nghĩ thuê máy chủ đám mây là nhà cung cấp lo luôn vá lỗi hệ điều hành và rò rỉ dữ liệu do cấu hình sai.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu yêu cầu pháp lý bắt dữ liệu ở lại một quốc gia, bạn phải gom tài nguyên về Region phù hợp và kiểm tra cả bản sao lưu lẫn log; nếu người dùng phân bố toàn cầu, bạn giữ Region chính cộng thêm phân phối nội dung ở biên thay vì nhân bản toàn bộ hệ thống sang nhiều Region.</p>',
code: null,
expected: null,
followups: [
{q: 'Vì sao triển khai ở hai Zone trong cùng Region rẻ và đơn giản hơn hai Region?', a: 'Hai Zone trong cùng Region được nối bằng mạng riêng tốc độ cao nên sao chép dữ liệu nhanh và ít tốn kém, còn liên Region phải đi đường truyền xa với độ trễ cao và phát sinh chi phí truyền tải. Vận hành đa Region còn buộc bạn giải quyết xung đột ghi, thứ tự sự kiện và chuyển đổi dự phòng giữa hai cụm độc lập. Vì vậy bạn luôn bắt đầu bằng đa Zone, chỉ lên đa Region khi yêu cầu chịu thảm họa cấp vùng địa lý.'},
{q: 'Khách hàng chịu trách nhiệm cụ thể những gì trong mô hình trách nhiệm chung?', a: 'Khách hàng chịu trách nhiệm cho dữ liệu của mình gồm phân loại, mã hóa và sao lưu, cho danh tính và phân quyền gồm ai được truy cập tài nguyên nào, và cho cấu hình mạng cùng bản vá của hệ điều hành khách. Nhà cung cấp chỉ lo phần cứng, trung tâm dữ liệu và lớp ảo hóa bên dưới. Nếu bạn mở quyền truy cập công khai nhầm hay lộ khóa truy cập, đó là lỗi phía bạn chứ không phải lỗi hạ tầng.'},
{q: 'Khi nào bạn chấp nhận chạy single Zone dù biết rủi ro?', a: 'Bạn chấp nhận single Zone cho môi trường dev, bài kiểm thử ngắn hạn hoặc tác vụ batch có thể chạy lại, nơi gián đoạn vài giờ không gây thiệt hại. Điều kiện là dữ liệu quan trọng vẫn được sao lưu sang nơi khác và cả đội hiểu rõ rủi ro. Với production có người dùng thật, bạn luôn dùng đa Zone vì chi phí chênh lệch nhỏ hơn nhiều so với thiệt hại khi sập hệ thống.'}
],
pitfalls: ['Nhầm Region với Zone nên triển khai dự phòng hai máy trong cùng một Zone mà tưởng đã an toàn', 'Nghĩ thuê hạ tầng đám mây là nhà cung cấp lo luôn cấu hình quyền và rò rỉ dữ liệu'],
selfcheck: ['Tôi vẫn chưa giải thích được lưu lượng chuyển giữa các Zone khi một Zone sập theo cơ chế định tuyến nào', 'Tôi có thể giải thích bằng ví dụ web chạy hai Zone ở Singapore và một Zone mất điện thì Zone còn lại gánh tải', 'Tôi có thể chọn Region và thiết kế dự phòng đa Zone cho một web production nhỏ có yêu cầu lưu dữ liệu trong khu vực'],
refs: ['aws-vpc', 'aws-cfn']
},
{
id: 'G02',
group: 'G',
topic: 'IAM user, role, policy và execution role',
prio: 'P0',
level: 'L2',
type: 'concept',
q: 'Hãy phân biệt IAM user, IAM role và policy, rồi giải thích execution role của Lambda hoạt động thế nào theo nguyên tắc least privilege?',
oral: 'IAM user là danh tính gắn với một người hoặc một ứng dụng cố định, đi kèm khóa truy cập lâu dài nên bạn chỉ dùng cho trường hợp thật cần. IAM role cũng là danh tính nhưng không ai đăng nhập trực tiếp, mà ai đó hoặc dịch vụ nào đó đảm nhận tạm thời để nhận quyền trong thời gian ngắn. Policy là tài liệu quyền hạn mô tả được làm gì trên tài nguyên nào, và bạn gắn policy vào user hoặc role để cấp quyền. Lambda không chạy bằng quyền của người gọi mà chạy bằng execution role, tức là một role bạn chỉ định cho hàm, mọi thao tác đọc ghi của hàm đều dùng quyền của role đó. Theo nguyên tắc least privilege, bạn chỉ cho role đúng các quyền tối thiểu trên đúng tài nguyên cần thiết, ví dụ chỉ được đọc một bảng dữ liệu duy nhất thay vì mọi bảng trong tài khoản.',
deep: '<p><strong>Đó là gì:</strong> <code>IAM user</code> là danh tính lâu dài gắn với người hoặc ứng dụng, xác thực bằng mật khẩu hoặc khóa truy cập. <code>IAM role</code> là danh tính không có khóa cố định, bên khác đảm nhận tạm thời qua cơ chế tin cậy để nhận quyền ngắn hạn. <code>Policy</code> là tài liệu quyền hạn liệt kê hành động được phép trên tài nguyên nào, và bạn gắn policy vào user, role hoặc nhóm để cấp quyền.</p><p><strong>Cơ chế hoạt động:</strong> khi Lambda chạy, dịch vụ Lambda đảm nhận <code>execution role</code> mà bạn đã gắn cho hàm, lấy chứng chỉ tạm thời và thực thi mã với đúng quyền của role đó. Mỗi lần gọi hàm đều dùng cùng một role, độc lập với người gọi hàm là ai, nên quyền của người gọi và quyền của hàm là hai lớp hoàn toàn tách biệt.</p><p><strong>Vì sao cần least privilege:</strong> quyền càng rộng thì một lỗi nhỏ trong mã hoặc một khóa lộ ra ngoài càng gây thiệt hại lớn, từ xóa nhầm dữ liệu đến bị kẻ xấu lợi dụng tài nguyên. Thu hẹp quyền theo đúng nhu cầu giúp giảm bán kính nổ của mọi sự cố bảo mật.</p><ul><li><strong>Tình huống cụ thể:</strong> hàm xử lý ảnh chỉ được đọc một bucket đầu vào và ghi một bucket đầu ra, không được liệt kê các bucket khác, không được xóa bất kỳ thứ gì.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng role cho mọi dịch vụ và ứng dụng chạy trên đám mây; chỉ tạo IAM user cho người thật cần truy cập bảng điều khiển và cho vài công cụ cũ không hỗ trợ role.</li><li><strong>Lỗi phổ biến:</strong> gắn quyền quản trị đầy đủ cho execution role cho nhanh, rồi quên thu hẹp lại khi lên production.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu một hàm cần thêm quyền mới, bạn mở rộng policy từng bước và ghi chú lý do thay vì cấp quyền rộng cho tiện; nếu nhiều hàm chia sẻ một role, bạn tách role riêng khi quyền của chúng bắt đầu khác nhau để một hàm không thừa hưởng quyền của hàm khác.</p>',
code: '{\n  "Version": "2012-10-17",\n  "Statement": [\n    {\n      "Effect": "Allow",\n      "Action": ["s3:GetObject"],\n      "Resource": "arn:aws:s3:::input-bucket/*"\n    },\n    {\n      "Effect": "Allow",\n      "Action": ["s3:PutObject"],\n      "Resource": "arn:aws:s3:::output-bucket/*"\n    },\n    {\n      "Effect": "Allow",\n      "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],\n      "Resource": "arn:aws:logs:*:*:*"\n    }\n  ]\n}',
expected: null,
followups: [
{q: 'Vì sao service nên dùng role thay vì nhúng khóa truy cập của user vào mã nguồn?', a: 'Khóa của user tồn tại lâu dài nên một khi lộ ra ngoài kẻ xấu dùng được mãi cho tới khi bạn phát hiện và xoay vòng. Role cấp chứng chỉ tạm thời tự hết hạn sau thời gian ngắn và được dịch vụ tự xoay vòng, nên không có gì để lộ trong mã nguồn hay kho chứa mã. Role còn cho phép thu hồi quyền tập trung bằng cách sửa policy một chỗ thay vì đi tìm mọi nơi đang nhúng khóa. Vì vậy quy tắc chuẩn là không bao giờ nhúng khóa dài hạn vào mã hay file cấu hình.'},
{q: 'Policy đánh giá quyền thế nào khi có cả cho phép và từ chối tường minh?', a: 'Mặc định mọi hành động đều bị từ chối, policy cho phép mới mở ra từng quyền cụ thể. Nếu có bất kỳ câu từ chối tường minh nào khớp với yêu cầu, yêu cầu bị từ chối bất kể có bao nhiêu câu cho phép khác. Nhờ vậy bạn dùng câu từ chối để chặn các trường hợp nguy hiểm như xóa bucket hay đổi chính sách, ngay cả khi ai đó vô tình cấp quyền rộng ở chỗ khác. Khi gỡ lỗi quyền, bạn kiểm tra câu từ chối trước rồi mới xem đã có câu cho phép phù hợp chưa.'},
{q: 'Bạn thu hẹp một execution role đang có quyền rộng ra sao mà không làm sập production?', a: 'Bạn bật ghi log truy cập để quan sát hàm thực sự gọi những hành động nào trong vài ngày, rồi viết policy mới chỉ bao gồm đúng các hành động và tài nguyên đã quan sát. Bạn triển khai policy mới ở môi trường kiểm thử trước, chạy lại toàn bộ luồng chính gồm cả nhánh lỗi để chắc không thiếu quyền. Cuối cùng bạn áp lên production vào giờ thấp điểm và giữ sẵn bản policy cũ để quay lại nhanh nếu có cảnh báo thiếu quyền.'}
],
pitfalls: ['Gắn quyền quản trị đầy đủ cho execution role cho nhanh rồi quên thu hẹp khi lên production', 'Nhầm quyền của người gọi hàm với quyền của hàm, tưởng người gọi có quyền là hàm tự có quyền'],
selfcheck: ['Tôi vẫn chưa giải thích được cơ chế đảm nhận role cấp chứng chỉ tạm thời và xoay vòng thế nào', 'Tôi có thể giải thích bằng ví dụ hàm xử lý ảnh chỉ đọc một bucket và ghi một bucket theo policy mẫu', 'Tôi có thể viết policy least privilege cho một hàm Lambda mới và rà soát quyền dư thừa của hàm cũ'],
refs: ['aws-iam', 'aws-lambda-permissions']
},
{
id: 'G03',
group: 'G',
topic: 'Lambda handler, event, context, cold start và giới hạn',
prio: 'P0',
level: 'L2',
type: 'concept',
q: 'Hãy giải thích Lambda handler nhận event và context thế nào, cùng với cold start, concurrency, timeout và retry ảnh hưởng ra sao đến thiết kế hàm?',
oral: 'Handler là hàm Python bạn chỉ định làm điểm vào, nó nhận hai tham số là event chứa dữ liệu kích hoạt và context chứa thông tin môi trường chạy. Event thay đổi theo nguồn gọi, ví dụ sự kiện từ cổng API chứa phương thức và tham số đường dẫn, còn sự kiện từ hàng đợi chứa danh sách bản ghi. Context cho biết tên hàm, phiên bản, giới hạn bộ nhớ và thời gian còn lại trước timeout để bạn chủ động dừng sớm. Cold start là độ trễ khởi tạo môi trường chạy mới khi chưa có sẵn, nên hàm cần phản hồi nhanh phải giữ gói triển khai gọn và khởi tạo nặng ngoài handler. Bạn đặt timeout vừa đủ để hàm lỗi treo không chạy mãi, và thiết kế concurrency cùng retry sao cho hàm chịu được gọi trùng mà không sinh dữ liệu trùng.',
deep: '<p><strong>Đó là gì:</strong> <code>handler</code> là hàm Python bạn đăng ký làm điểm vào, có dạng nhận <code>event</code> và <code>context</code>. <code>Event</code> là dữ liệu dạng từ điển mô tả lần kích hoạt này, cấu trúc của nó do nguồn gọi quyết định. <code>Context</code> là đối tượng mô tả môi trường chạy gồm tên hàm, phiên bản, giới hạn bộ nhớ và số mili giây còn lại.</p><p><strong>Cơ chế hoạt động:</strong> khi có yêu cầu, Lambda chọn một môi trường chạy, truyền event vào handler và thực thi tới khi hàm trả về hoặc hết timeout. Môi trường chạy được giữ ấm một thời gian để tái sử dụng cho lần gọi sau, lần gọi trúng môi trường ấm chạy ngay còn lần gọi phải tạo mới thì chịu thêm <code>cold start</code>. <code>Concurrency</code> là số môi trường chạy song song, hết suất thì yêu cầu mới bị tiết chế hoặc xếp hàng tùy nguồn gọi.</p><p><strong>Vì sao cần quan tâm các giới hạn:</strong> timeout mặc định ngắn nên tác vụ dài phải chia nhỏ hoặc chuyển sang dịch vụ chạy lâu; retry tự động của nguồn gọi bất đồng bộ nghĩa là hàm của bạn có thể chạy lại cùng một event nhiều lần. Thiết kế bỏ qua các giới hạn này dẫn tới mất dữ liệu hoặc sinh dữ liệu trùng mà rất khó gỡ.</p><ul><li><strong>Tình huống cụ thể:</strong> hàm đọc thời gian còn lại từ context để dừng vòng lặp xử lý trước khi timeout, ghi lại vị trí đã xong để lần retry tiếp tục thay vì làm lại từ đầu.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng Lambda cho tác vụ ngắn, theo sự kiện và lưu lượng thất thường; không dùng cho tiến trình nền chạy hàng giờ hay kết nối bám dính cần giữ trạng thái trong bộ nhớ.</li><li><strong>Lỗi phổ biến:</strong> đặt timeout quá dài để che lỗi treo, khởi tạo nặng trong handler khiến mọi lần gọi đều chậm.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu lưu lượng tăng đột biến, bạn đặt giới hạn concurrency cho hàm quan trọng để nó không chiếm hết suất của cả tài khoản; nếu hàm bắt đầu chậm vì gói triển khai phình to, bạn tách phụ thuộc nặng ra khỏi gói hoặc chuyển phần khởi tạo tốn kém ra ngoài handler để môi trường ấm tái sử dụng.</p>',
code: 'import json\n\n_heavy_client = None\n\ndef _get_client():\n    global _heavy_client\n    if _heavy_client is None:\n        _heavy_client = build_client()\n    return _heavy_client\n\ndef handler(event, context):\n    ms_left = context.get_remaining_time_in_millis()\n    if ms_left < 5000:\n        return {"statusCode": 503, "body": json.dumps({"retry": True})}\n    client = _get_client()\n    order_id = event.get("order_id")\n    result = client.process(order_id)\n    return {"statusCode": 200, "body": json.dumps(result)}',
expected: null,
followups: [
{q: 'Vì sao khởi tạo nặng nên đặt ngoài handler thay vì trong handler?', a: 'Mã ngoài handler chỉ chạy một lần khi môi trường chạy khởi tạo, còn mã trong handler chạy lại ở mọi lần gọi. Đặt kết nối cơ sở dữ liệu hay tải mô hình ra ngoài giúp các lần gọi ấm tái sử dụng và chạy nhanh hơn nhiều. Bạn kết hợp với biến toàn cục có kiểm tra rỗng để lần đầu dùng mới khởi tạo mà các lần sau dùng lại. Lưu ý là môi trường chạy có thể bị thu hồi bất cứ lúc nào nên bạn không được coi trạng thái trong bộ nhớ là bền.'},
{q: 'Timeout đặt quá dài gây hại gì ngoài việc chờ lâu?', a: 'Timeout dài khiến hàm lỗi treo chiếm suất concurrency tới khi hết giờ, vừa tốn chi phí vừa có thể làm cạn suất khiến các yêu cầu khác bị tiết chế. Với nguồn gọi bất đồng bộ, timeout dài còn làm chậm vòng retry vì lần thử lại chỉ bắt đầu sau khi lần trước thất bại hẳn. Bạn nên đặt timeout theo thời gian xử lý thực tế cộng một biên nhỏ, và dùng thời gian còn lại trong context để dừng sớm có kiểm soát.'},
{q: 'Concurrency của một hàm ảnh hưởng tới các hàm khác trong cùng tài khoản ra sao?', a: 'Mặc định mọi hàm trong một Region chia sẻ chung một hạn mức concurrency của tài khoản, nên một hàm bị gọi ồ ạt có thể chiếm hết suất và bóp nghẹt các hàm khác. Bạn đặt concurrency dự trữ cho hàm quan trọng để luôn giữ một phần suất riêng, và đặt giới hạn tối đa cho hàm dễ bùng nổ để nó không lan sang phần còn lại. Khi thiết kế hệ thống nhiều hàm, bạn phân bổ suất như phân bổ ngân sách chứ không để mặc định.'}
],
pitfalls: ['Khởi tạo kết nối và tải dữ liệu nặng trong handler khiến mọi lần gọi đều chậm', 'Đặt timeout rất dài để che lỗi treo, gây tốn chi phí và cạn concurrency khi sự cố'],
selfcheck: ['Tôi vẫn chưa giải thích được vòng đời môi trường chạy từ khởi tạo tới thu hồi và khi nào cold start xảy ra', 'Tôi có thể giải thích bằng ví dụ hàm chuyển khởi tạo ra ngoài handler và đọc thời gian còn lại từ context', 'Tôi có thể chọn timeout và concurrency hợp lý cho một hàm xử lý đơn hàng mới dựa trên thời gian xử lý đo được'],
refs: ['aws-lambda-best', 'aws-lambda-permissions']
},
{
id: 'G04',
group: 'G',
topic: 'Phân biệt quyền gọi Lambda và quyền của Lambda',
prio: 'P0',
level: 'L2',
type: 'concept',
q: 'Hãy phân biệt quyền được phép gọi một hàm Lambda với quyền mà hàm Lambda có để truy cập tài nguyên, và cho biết thiếu mỗi loại thì lỗi hiện ra thế nào?',
oral: 'Đây là hai lớp quyền ngược chiều nhau và bạn phải cấu hình cả hai. Quyền gọi hàm trả lời câu hỏi ai được phép kích hoạt hàm, ví dụ cổng API hay một hàm khác có được gọi tới hàm này không, và nó được quản lý bằng chính sách tài nguyên gắn trên hàm. Quyền của hàm trả lời câu hỏi hàm được phép làm gì sau khi đã chạy, ví dụ đọc bảng dữ liệu hay ghi file, và nó do execution role quyết định. Thiếu quyền gọi thì yêu cầu bị từ chối ngay từ ngoài với lỗi cấm truy cập, hàm chưa hề chạy và không sinh log. Thiếu quyền của hàm thì hàm vẫn chạy nhưng sập giữa chừng khi chạm vào tài nguyên, lỗi ghi rõ hành động nào trên tài nguyên nào bị từ chối và bạn thấy được trong log.',
deep: '<p><strong>Đó là gì:</strong> <code>quyền gọi hàm</code> là chính sách tài nguyên gắn trên chính hàm Lambda, liệt kê bên nào được kích hoạt hàm. <code>Quyền của hàm</code> là <code>execution role</code> mà hàm đảm nhận khi chạy, liệt kê tài nguyên mà mã bên trong được chạm tới. Hai lớp này độc lập hoàn toàn và bổ sung cho nhau.</p><p><strong>Cơ chế hoạt động:</strong> khi có yêu cầu gọi, Lambda kiểm tra chính sách tài nguyên trước, nếu bên gọi không có tên trong danh sách cho phép thì từ chối ngay mà không khởi tạo môi trường chạy. Nếu qua được cửa này, hàm bắt đầu chạy với chứng chỉ tạm thời của execution role, và mỗi thao tác gọi dịch vụ khác đều được kiểm tra tiếp với role đó.</p><p><strong>Vì sao cần tách hai lớp:</strong> tách lớp giúp bạn mở cửa gọi cho đúng đối tượng mà không vô tình cho họ quyền bên trong hàm, và ngược lại cho hàm quyền mạnh mà không mở cửa gọi cho cả thế giới. Đây chính là cách áp dụng least privilege cho kiến trúc hướng sự kiện.</p><ul><li><strong>Tình huống cụ thể:</strong> cổng API được phép gọi hàm thanh toán nhưng người dùng trực tiếp thì không; hàm thanh toán được ghi bảng đơn hàng nhưng không được xóa bảng.</li><li><strong>Khi nào dùng và khi nào không:</strong> luôn cấu hình tường minh cả hai lớp cho mọi hàm production; không dùng chính sách mở cho mọi bên gọi rồi dựa vào mã để kiểm tra thủ công.</li><li><strong>Lỗi phổ biến:</strong> cấp execution role mạnh rồi ngạc nhiên khi cổng API vẫn báo cấm vì quên cho phép gọi; ngược lại mở quyền gọi rồi tưởng hàm tự có quyền đọc dữ liệu.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu thêm nguồn gọi mới như bộ định giờ hay sự kiện lưu trữ, bạn bổ sung từng quyền gọi cụ thể cho nguồn đó thay vì mở rộng cho mọi nguồn; nếu hàm cần truy cập tài nguyên mới, bạn mở rộng execution role theo từng tài nguyên và kiểm thử lại toàn bộ luồng.</p>',
code: '{\n  "Version": "2012-10-17",\n  "Statement": [\n    {\n      "Effect": "Allow",\n      "Principal": {"Service": "apigateway.amazonaws.com"},\n      "Action": "lambda:InvokeFunction",\n      "Resource": "arn:aws:lambda:*:*:function:pay-handler",\n      "Condition": {"ArnLike": {"AWS:SourceArn": "arn:aws:execute-api:*:*:*/*/*/*"}}\n    }\n  ]\n}',
expected: null,
followups: [
{q: 'Làm sao bạn chẩn đoán nhanh một lỗi cấm là do thiếu quyền gọi hay thiếu quyền của hàm?', a: 'Bạn nhìn vào nơi lỗi xuất hiện và log đi kèm. Thiếu quyền gọi thì bên gọi nhận lỗi cấm truy cập ngay, hàm chưa chạy nên không có log thực thi nào được sinh ra. Thiếu quyền của hàm thì hàm đã chạy nên bạn thấy log thực thi dừng đúng ở thao tác gọi dịch vụ, kèm thông điệp nêu rõ hành động và tài nguyên bị từ chối. Phân biệt được hai dấu hiệu này giúp bạn sửa đúng chỗ thay vì mở quyền bừa cả hai lớp.'},
{q: 'Vì sao không nên mở quyền gọi cho mọi nguồn rồi kiểm tra trong mã?', a: 'Kiểm tra trong mã chỉ chạy sau khi hàm đã khởi tạo và tốn chi phí, còn chính sách tài nguyên chặn ngay từ ngoài miễn phí và an toàn hơn. Mã kiểm tra còn dễ bị bỏ sót nhánh, ghi log lộ thông tin nhạy cảm hoặc bị vượt qua khi có lỗi logic. Chính sách tài nguyên do nền tảng thực thi nên đồng nhất và có thể rà soát tập trung. Bạn dùng mã để kiểm tra nghiệp vụ, còn việc ai được gọi hàm thì để chính sách lo.'},
{q: 'Khi cho một hàm khác gọi hàm này, bạn cấu hình hai lớp quyền thế nào?', a: 'Bạn cho phép hàm nguồn gọi tới bằng cách thêm quyền gọi với điều kiện giới hạn đúng tên hàm nguồn, đồng thời gắn cho hàm nguồn một policy cho phép hành động gọi trên đúng hàm đích. Hàm đích vẫn giữ execution role riêng cho công việc của nó, không chia sẻ role với hàm nguồn. Cách này giữ mỗi hàm đúng quyền tối thiểu của mình và đường gọi nào cũng được ghi nhận tường minh.'}
],
pitfalls: ['Cấp execution role mạnh rồi tưởng quyền gọi tự có, khiến cổng API báo cấm dù hàm đủ quyền bên trong', 'Mở quyền gọi cho mọi nguồn cho nhanh rồi quên thu hẹp khi lên production'],
selfcheck: ['Tôi vẫn chưa giải thích được thứ tự kiểm tra quyền gọi trước rồi mới tới kiểm tra execution role khi hàm chạm tài nguyên', 'Tôi có thể giải thích bằng ví dụ cổng API được gọi hàm thanh toán nhưng hàm vẫn cần role riêng để ghi bảng đơn hàng', 'Tôi có thể chẩn đoán một lỗi cấm thực tế là thiếu quyền gọi hay thiếu quyền của hàm và sửa đúng lớp'],
refs: ['aws-lambda-permissions', 'aws-iam']
},
{
id: 'G05',
group: 'G',
topic: 'API Gateway: route, CORS, xác thực và throttling',
prio: 'P0',
level: 'L2',
type: 'concept',
q: 'Hãy giải thích API Gateway định tuyến request, xử lý CORS, xác thực và throttling thế nào trước khi request chạm tới Lambda?',
oral: 'API Gateway đứng trước Lambda như một lớp cửa, nó nhận request, đối chiếu phương thức và đường dẫn với route đã cấu hình rồi chuyển tiếp cho tích hợp tương ứng. Với trình duyệt, nó xử lý CORS bằng cách trả lời các request kiểm tra tiền điều kiện và gắn đúng header cho phép, nên cấu hình thiếu là trình duyệt chặn ngay dù Lambda vẫn khỏe. Xác thực diễn ra ở lớp gateway bằng kiểm tra token hoặc khóa API, request không hợp lệ bị từ chối sớm mà không tốn một lần chạy Lambda nào. Cuối cùng gateway áp throttling theo giới hạn bạn đặt để chặn bùng nổ lưu lượng, bảo vệ Lambda và các hệ thống phía sau khỏi bị nhấn chìm.',
deep: '<p><strong>Đó là gì:</strong> <code>API Gateway</code> là dịch vụ quản lý API, nhận request từ client, áp các chính sách chung rồi mới gọi tới tích hợp phía sau như Lambda. <code>Route</code> là quy tắc ánh xạ tổ hợp phương thức và đường dẫn tới một tích hợp cụ thể. <code>CORS</code> là cơ chế trình duyệt dùng để cho phép trang web gọi API khác tên miền một cách an toàn.</p><p><strong>Cơ chế hoạt động:</strong> gateway đối chiếu request với bảng route, chạy bước xác thực như kiểm tra token theo chuẩn mở hoặc hàm kiểm tra tùy chỉnh, rồi kiểm tra hạn mức throttling trước khi gọi Lambda. Với CORS, gateway tự trả lời request tiền điều kiện và gắn các header cho phép vào phản hồi, trình duyệt chỉ gửi request thật khi các header này hợp lệ.</p><p><strong>Vì sao cần lớp gateway:</strong> gom xác thực, CORS, giới hạn tốc độ và quan sát vào một chỗ giúp mọi API đều nhất quán và Lambda chỉ lo nghiệp vụ thuần túy. Không có lớp này, mỗi hàm phải tự lặp lại cùng một đoạn mã kiểm tra và một hàm quên kiểm tra là thành lỗ hổng.</p><ul><li><strong>Tình huống cụ thể:</strong> ứng dụng Vue gọi API, gateway xác thực token trước, request hợp lệ mới tới Lambda, request vượt hạn mức nhận mã quá nhiều yêu cầu để client chậm lại.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng gateway cho mọi API công khai cần xác thực và giới hạn tốc độ; không cần gateway cho hàm chỉ chạy nội bộ theo lịch hay theo sự kiện lưu trữ.</li><li><strong>Lỗi phổ biến:</strong> cấu hình CORS thiếu header khiến trình duyệt chặn dù gọi trực tiếp vẫn chạy; đặt throttling quá thấp khiến giờ cao điểm người dùng thật bị từ chối.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu thêm phiên bản API mới, bạn triển khai theo giai đoạn với tỉ lệ chuyển dần để theo dõi lỗi; nếu lưu lượng tăng gấp nhiều lần, bạn nâng hạn mức throttling theo từng route quan trọng thay vì mở toang toàn bộ, và tách route nặng sang hạn mức riêng.</p>',
code: null,
expected: null,
followups: [
{q: 'Request tiền điều kiện CORS là gì và vì sao thiếu nó trình duyệt chặn ngay?', a: 'Trước khi gửi các request có thay đổi dữ liệu qua tên miền khác, trình duyệt gửi một request kiểm tra để hỏi server cho phép những phương thức và header nào. Gateway phải trả lời đúng với các header cho phép khớp tên miền, phương thức và header mà ứng dụng dùng. Nếu thiếu hoặc sai, trình duyệt không gửi request thật và báo lỗi CORS dù server vẫn khỏe. Vì vậy lỗi CORS luôn sửa ở cấu hình gateway và header phản hồi, không phải ở logic Lambda.'},
{q: 'Bạn chọn giữa kiểm tra token có sẵn và hàm kiểm tra tùy chỉnh khi nào?', a: 'Bạn dùng cơ chế kiểm tra token có sẵn khi hệ thống đã phát hành token theo chuẩn mở và bạn chỉ cần xác thực chữ ký cùng phạm vi quyền. Bạn viết hàm kiểm tra tùy chỉnh khi cần logic đặc thù như tra cứu phiên trong cơ sở dữ liệu, kiểm tra danh sách thu hồi hoặc hỗ trợ nhiều loại chứng chỉ cùng lúc. Hàm tùy chỉnh linh hoạt hơn nhưng tốn một lần chạy tính toán cho mỗi request nên bạn giữ nó thật nhẹ và có bộ nhớ đệm.'},
{q: 'Throttling ở gateway khác gì với giới hạn concurrency của Lambda?', a: 'Throttling ở gateway chặn ngay từ cửa với phản hồi quá nhiều yêu cầu để client tự chậm lại, còn giới hạn concurrency của Lambda quyết định có bao nhiêu môi trường chạy song song phía sau. Gateway hết hạn mức thì request bị từ chối nhanh và rẻ, Lambda hết suất thì request có thể bị tiết chế hoặc xếp hàng tùy nguồn gọi. Bạn đặt cả hai lớp phối hợp nhau sao cho gateway là vành đai đầu còn concurrency là vành đai cuối bảo vệ tài nguyên.'}
],
pitfalls: ['Cấu hình CORS thiếu header nên trình duyệt chặn dù gọi trực tiếp vẫn chạy tốt', 'Đặt throttling quá thấp khiến người dùng thật bị từ chối hàng loạt vào giờ cao điểm'],
selfcheck: ['Tôi vẫn chưa giải thích được trình tự route rồi xác thực rồi throttling trước khi gọi Lambda', 'Tôi có thể giải thích bằng ví dụ ứng dụng Vue gọi API qua gateway với kiểm tra token và giới hạn tốc độ', 'Tôi có thể cấu hình route, CORS và throttling cho một API mới trước một hàm Lambda có sẵn'],
refs: ['aws-api-gateway']
}
,
{
id: 'G06',
group: 'G',
topic: 'S3, private bucket, presigned URL và kiểm tra upload',
prio: 'P0',
level: 'L2',
type: 'situation',
q: 'Bạn cần cho người dùng tải ảnh đại diện lên S3 mà không mở bucket ra công khai. Hãy đề xuất thiết kế dùng presigned URL và kiểm tra file tải lên?',
oral: 'Bạn giữ bucket ở chế độ riêng tư hoàn toàn và không bao giờ nhận file qua server trung gian nếu có thể tránh. Thay vào đó backend xác thực người dùng rồi ký một presigned URL có hiệu lực ngắn, cho phép đúng một thao tác tải lên đúng đường dẫn của người đó. Trình duyệt dùng URL này tải file thẳng lên S3 nên server nhẹ tải hơn hẳn. Vì presigned URL chỉ kiểm tra chữ ký chứ không kiểm tra nội dung, bạn phải xác thực phía server bằng sự kiện hoàn tất tải lên kích hoạt hàm kiểm tra loại file, kích thước và quét nội dung, file không đạt thì xóa hoặc cách ly ngay. Cách này vừa an toàn vừa mở rộng tốt.',
deep: '<p><strong>Đó là gì:</strong> <code>S3</code> là kho lưu trữ đối tượng, mỗi file là một <code>object</code> nằm trong <code>bucket</code>. <code>Presigned URL</code> là một đường dẫn tạm thời có chữ ký, cho phép ai cầm nó thực hiện đúng một thao tác trong thời gian ngắn mà không cần tài khoản.</p><p><strong>Cơ chế hoạt động:</strong> backend dùng khóa của mình ký một URL gắn sẵn bucket, đường dẫn file, thao tác cho phép và thời điểm hết hạn. Người dùng tải file thẳng lên S3 qua URL đó, S3 chỉ kiểm tra chữ ký và thời hạn chứ không kiểm tra người dùng là ai.</p><p><strong>Vì sao cần thiết kế này:</strong> tải qua server trung gian vừa chậm vừa tốn băng thông, còn mở bucket công khai ghi thì ai cũng ghi đè được file của ai. Presigned URL giữ bucket riêng tư mà vẫn cho tải trực tiếp, đồng thời dồn kiểm tra quyền về backend nơi bạn kiểm soát được.</p><ul><li><strong>Tình huống cụ thể:</strong> người dùng xin tải ảnh đại diện, backend ký URL chỉ cho ghi đúng đường dẫn của người đó trong năm phút, tải xong hàm kiểm tra xác nhận đúng ảnh nhỏ hơn giới hạn rồi mới đánh dấu hồ sơ đã có ảnh.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng presigned URL cho mọi file do người dùng cung cấp; không dùng cho file hệ thống nội bộ vì backend tự ghi trực tiếp là đủ.</li><li><strong>Lỗi phổ biến:</strong> ký URL cho cả tiền tố chung khiến người này ghi đè file người khác; tin tưởng phần mở rộng file mà không kiểm tra nội dung thật.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu file cần xử lý nặng như tạo nhiều kích thước ảnh, bạn tách luồng tải lên và luồng xử lý qua hàng đợi để người dùng không phải chờ; nếu yêu cầu bảo mật cao hơn, bạn rút ngắn thời hạn URL và bật mã hóa phía server cho bucket.</p>',
code: 'import boto3\n\ns3 = boto3.client("s3")\nBUCKET = "avatars-private"\n\ndef make_upload_url(user_id, ext="jpg"):\n    key = "avatars/%s/profile.%s" % (user_id, ext)\n    return s3.generate_presigned_url(\n        "put_object",\n        Params={"Bucket": BUCKET, "Key": key, "ContentType": "image/jpeg"},\n        ExpiresIn=300,\n    )',
expected: null,
followups: [
{q: 'Vì sao presigned URL không thay thế được bước kiểm tra nội dung file?', a: 'Presigned URL chỉ chứng minh người cầm URL được phép ghi đúng đường dẫn trong thời gian ngắn, còn S3 chấp nhận mọi byte mà client gửi lên. Kẻ xấu hoàn toàn có thể tải lên mã độc với phần mở rộng giả dạng ảnh. Vì vậy bạn luôn chạy một hàm kiểm tra sau khi tải xong để đọc nội dung thật, đối chiếu loại file và kích thước, rồi mới đánh dấu file là hợp lệ cho hệ thống dùng. URL ký là cửa cho vào, kiểm tra nội dung là chốt an toàn cuối cùng.'},
{q: 'Bạn ngăn người dùng ghi đè file của nhau thế nào khi ký URL?', a: 'Bạn nhúng định danh người dùng vào đường dẫn file khi ký, ví dụ mỗi người chỉ được ghi đúng thư mục mang tên mình, và giới hạn thao tác chỉ là ghi một file cụ thể chứ không phải cả tiền tố. Backend kiểm tra quyền sở hữu trước khi ký nên người này không bao giờ nhận được URL trỏ sang đường dẫn của người khác. Khi phục vụ file, bạn cũng ký URL tải xuống theo đúng đường dẫn sở hữu thay vì mở đọc công khai cả bucket.'},
{q: 'Khi tải lên thất bại giữa chừng, bạn thiết kế phía client và server ra sao?', a: 'Phía client khi URL hết hạn hay mạng lỗi thì xin cấp URL mới thay vì thử lại URL cũ, và hiển thị trạng thái rõ ràng để người dùng không bấm tải trùng. Phía server dùng sự kiện hoàn tất tải lên làm mốc duy nhất để đánh dấu thành công, nên các lần tải dở không để lại trạng thái rác trong cơ sở dữ liệu. Bạn đặt quy tắc vòng đời tự xóa các file chưa qua kiểm tra sau một thời gian để bucket không đầy dần vì các lần tải hỏng.'}
],
pitfalls: ['Mở bucket cho ghi công khai hoặc ký URL cho cả tiền tố chung khiến người này ghi đè file người khác', 'Tin phần mở rộng file mà bỏ qua bước kiểm tra nội dung thật sau khi tải lên'],
selfcheck: ['Tôi vẫn chưa giải thích được S3 kiểm tra chữ ký và thời hạn của presigned URL ở bước nào của request', 'Tôi có thể giải thích bằng ví dụ backend ký URL tải ảnh đại diện cho đúng đường dẫn của từng người dùng', 'Tôi có thể triển khai luồng xin URL, tải trực tiếp và kiểm tra file sau tải cho một tính năng ảnh đại diện'],
refs: ['aws-s3', 'aws-s3-presigned']
},
{
id: 'G07',
group: 'G',
topic: 'RDS PostgreSQL: kết nối, sao lưu và mạng',
prio: 'P0',
level: 'L2',
type: 'situation',
q: 'Một web dùng Lambda và RDS PostgreSQL hay bị cạn kết nối khi lưu lượng tăng. Bạn chẩn đoán và khắc phục thế nào, gồm sao lưu và cấu hình mạng?',
oral: 'Lambda mở rộng bằng cách tạo nhiều môi trường chạy song song, mỗi môi trường giữ kết nối riêng tới cơ sở dữ liệu nên tổng kết nối bùng nổ rất nhanh và vượt qua giới hạn của RDS. Bạn chẩn đoán bằng cách đối chiếu số môi trường chạy đồng thời với số kết nối đang mở trên RDS, thấy hai đường này tăng cùng nhau là dấu hiệu đúng bệnh. Cách khắc phục chuẩn là đặt một lớp gộp kết nối ở giữa để hàng trăm hàm chia sẻ một nhóm nhỏ kết nối thật tới RDS. Về mạng, bạn đặt RDS trong mạng riêng không mở ra internet, chỉ cho phép đúng nhóm bảo mật của ứng dụng kết nối vào cổng cơ sở dữ liệu. Về sao lưu, bạn bật sao lưu tự động kèm bản snapshot trước mỗi lần thay đổi lớn để khôi phục được đúng thời điểm khi sự cố.',
deep: '<p><strong>Đó là gì:</strong> <code>RDS</code> là dịch vụ cơ sở dữ liệu quan hệ được quản lý, lo vá lỗi, sao lưu và chuyển đổi dự phòng cho bạn. Cạn kết nối xảy ra khi tổng số kết nối mở vượt qua giới hạn mà máy chủ chịu được, khiến các kết nối mới bị từ chối.</p><p><strong>Cơ chế hoạt động:</strong> mỗi môi trường chạy Lambda giữ kết nối riêng để tái sử dụng cho các lần gọi ấm, nên số kết nối tăng theo số môi trường chạy song song chứ không theo số request. Lớp gộp kết nối đứng giữa nhận hàng trăm kết nối từ các hàm rồi dùng một nhóm nhỏ kết nối thật để nối chuyện với RDS, hàng đợi bên trong sắp xếp lượt dùng chung.</p><p><strong>Vì sao cần cả ba mảng:</strong> gộp kết nối giải quyết nghẽn ở lớp truy cập, mạng riêng giải quyết nguy cơ bị tấn công từ internet, sao lưu giải quyết khả năng mất dữ liệu khi có sự cố. Thiếu một trong ba thì hệ thống vẫn mong manh dù hai mảng còn lại đã tốt.</p><ul><li><strong>Tình huống cụ thể:</strong> giờ cao điểm tạo hai trăm môi trường chạy, mỗi môi trường một kết nối, vượt giới hạn một trăm của RDS nên request mới lỗi hàng loạt dù CPU còn trống.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng lớp gộp kết nối cho mọi workload Lambda tới RDS; không mở cổng cơ sở dữ liệu ra internet trong bất kỳ môi trường nào kể cả dev.</li><li><strong>Lỗi phổ biến:</strong> mở kết nối mới trong handler mà không tái sử dụng ở môi trường ấm; đặt giới hạn kết nối quá thấp cho lớp gộp khiến hàng đợi tắc nghẽn.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu lưu lượng tăng gấp nhiều lần và gộp kết nối vẫn nghẽn, bạn tách đọc ghi sang bản sao chỉ đọc đã dựng sẵn; nếu yêu cầu khôi phục nhanh hơn, bạn rút ngắn thời gian khôi phục mục tiêu bằng bản sao dự phòng đa Zone và diễn tập khôi phục định kỳ.</p>',
code: '_conn = None\n\ndef get_conn():\n    global _conn\n    if _conn is None or _conn.closed:\n        _conn = psycopg2.connect(\n            host=DB_HOST, dbname="appdb", user=DB_USER,\n            password=DB_PASS, connect_timeout=5,\n        )\n    return _conn\n\ndef handler(event, context):\n    conn = get_conn()\n    with conn.cursor() as cur:\n        cur.execute("SELECT id, name FROM users WHERE id = %s", (event["user_id"],))\n        row = cur.fetchone()\n    conn.commit()\n    return {"user": row}',
expected: null,
followups: [
{q: 'Vì sao Lambda làm cạn kết nối RDS nhanh hơn server truyền thống?', a: 'Server truyền thống có số tiến trình cố định nên số kết nối cũng cố định và dễ tính toán. Lambda tự tạo thêm môi trường chạy theo lưu lượng, mỗi môi trường giữ kết nối riêng nên số kết nối tăng bùng nổ theo độ song song. Khi lưu lượng giảm, các môi trường ấm còn giữ kết nối một thời gian trước khi bị thu hồi nên đỉnh kết nối tụt chậm hơn đỉnh request. Vì vậy mọi kiến trúc Lambda tới RDS đều cần lớp gộp kết nối ngay từ đầu chứ không đợi tới khi sắp mới thêm.'},
{q: 'Bạn cấu hình mạng cho RDS thế nào để vừa an toàn vừa cho Lambda truy cập được?', a: 'Bạn đặt RDS trong mạng con riêng không có đường ra internet, gắn nhóm bảo mật chỉ cho phép cổng cơ sở dữ liệu từ đúng nhóm bảo mật của ứng dụng. Lambda muốn nối chuyện với RDS thì chạy trong cùng mạng riêng hoặc đi qua lớp gộp kết nối nằm trong mạng đó. Bạn không bao giờ mở cổng cơ sở dữ liệu cho mọi địa chỉ, và quyền quản trị RDS thì đi qua kênh riêng có xác thực mạnh. Kiểm tra định kỳ các quy tắc đang mở để xóa những gì không còn dùng.'},
{q: 'Bạn thiết kế sao lưu và khôi phục cho RDS ra sao?', a: 'Bạn bật sao lưu tự động hằng ngày với thời gian giữ lại đủ dài cho yêu cầu nghiệp vụ, kết hợp ghi log giao dịch để khôi phục đúng tới từng thời điểm. Trước mỗi lần migrate hay thay đổi lớn, bạn chụp snapshot thủ công để có điểm quay lại ngay. Bạn diễn tập khôi phục sang máy mới định kỳ để chắc bản sao lưu dùng được thật và đo thời gian khôi phục thực tế. Với production quan trọng, bạn bật bản sao dự phòng đa Zone để chuyển đổi nhanh khi Zone chính sập.'}
],
pitfalls: ['Mở kết nối mới trong handler mà không tái sử dụng ở môi trường ấm khiến số kết nối bùng nổ', 'Mở cổng RDS ra internet hoặc cho phép mọi địa chỉ vì tiện kiểm thử rồi quên đóng'],
selfcheck: ['Tôi vẫn chưa giải thích được lớp gộp kết nối xếp hàng và chia sẻ kết nối thật cho hàng trăm hàm thế nào', 'Tôi có thể giải thích bằng ví dụ hai trăm môi trường chạy vượt giới hạn một trăm kết nối của RDS', 'Tôi có thể cấu hình gộp kết nối, nhóm bảo mật và lịch sao lưu cho một web Lambda và RDS mới'],
refs: ['aws-rds', 'aws-vpc']
},
{
id: 'G08',
group: 'G',
topic: 'DynamoDB key, access pattern, Query và Scan',
prio: 'P0',
level: 'L2',
type: 'concept',
q: 'Hãy giải thích partition key và sort key trong DynamoDB, và vì sao Query theo key hiệu quả hơn Scan toàn bảng rất nhiều?',
oral: 'DynamoDB phân tán dữ liệu theo partition key, các item cùng partition key nằm gần nhau và sắp xếp theo sort key nếu có. Thiết kế bảng luôn bắt đầu từ câu hỏi ứng dụng cần truy vấn theo mẫu nào, rồi chọn key sao cho các truy vấn thường gặp đọc đúng phân vùng chứa dữ liệu. Query là đọc có mục tiêu trong một hoặc vài phân vùng nên nhanh và rẻ, chi phí tăng theo lượng dữ liệu trả về. Scan là duyệt toàn bộ bảng bất kể key, càng nhiều dữ liệu càng chậm và càng tốn, lại còn chiếm dung lượng đọc của các truy vấn khác. Vì vậy quy tắc chuẩn là mọi luồng chính đều dùng Query, Scan chỉ dành cho tác vụ quản trị hiếm hoi hoặc xuất dữ liệu một lần.',
deep: '<p><strong>Đó là gì:</strong> <code>partition key</code> quyết định item nằm ở phân vùng vật lý nào, <code>sort key</code> quyết định thứ tự các item trong cùng một phân vùng. Cặp hai key này tạo thành khóa chính của bảng và định danh duy nhất mỗi item.</p><p><strong>Cơ chế hoạt động:</strong> khi <code>Query</code>, bạn chỉ định partition key cụ thể và tùy chọn điều kiện trên sort key, hệ thống đi thẳng tới phân vùng chứa dữ liệu và chỉ đọc đúng phạm vi cần thiết. Khi <code>Scan</code>, hệ thống duyệt qua mọi phân vùng và mọi item rồi mới lọc, nên hệ thống vẫn phải đọc hết toàn bảng dù kết quả trả về rất ít.</p><p><strong>Vì sao cần thiết kế theo access pattern:</strong> DynamoDB không có trình tối ưu truy vấn linh hoạt như cơ sở dữ liệu quan hệ, hiệu năng nằm hết ở cách bạn chọn key ngay từ đầu. Bảng thiết kế đúng thì mọi truy vấn production đều là Query nhanh, bảng thiết kế sai thì sớm muộn cũng phải Scan và trả giá bằng độ trễ cùng chi phí.</p><ul><li><strong>Tình huống cụ thể:</strong> bảng đơn hàng dùng mã khách hàng làm partition key và thời gian đặt làm sort key, trang lịch sử đơn hàng Query đúng một phân vùng thay vì Scan toàn bảng.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng Query cho mọi API phục vụ người dùng; chỉ dùng Scan cho công việc nền hiếm như kiểm toán một lần, và luôn giới hạn song song cùng giờ thấp điểm.</li><li><strong>Lỗi phổ biến:</strong> chọn partition key có ít giá trị distinct khiến một phân vùng phình to thành điểm nóng; dùng Scan có lọc mà tưởng lọc sớm giúp rẻ đi.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu xuất hiện mẫu truy vấn mới không khớp key hiện tại, bạn thêm chỉ mục phụ toàn cục phục vụ đúng mẫu đó thay vì đổi key gốc; nếu một giá trị key quá nóng, bạn thêm hậu tố phân tán để rải tải ra nhiều phân vùng rồi gộp kết quả ở tầng ứng dụng.</p>',
code: 'import boto3\n\nddb = boto3.client("dynamodb")\n\nresp = ddb.query(\n    TableName="orders",\n    KeyConditionExpression="customer_id = :c AND created_at BETWEEN :a AND :b",\n    ExpressionAttributeValues={\n        ":c": {"S": "cust-42"},\n        ":a": {"S": "2026-01-01"},\n        ":b": {"S": "2026-10-01"},\n    },\n    Limit=20,\n)',
expected: null,
followups: [
{q: 'Vì sao bộ lọc của Scan không làm cho Scan rẻ đi?', a: 'Bộ lọc của Scan chỉ loại bỏ kết quả trả về cho bạn, còn hệ thống vẫn phải đọc toàn bộ dữ liệu từ đĩa để xét từng item. Chi phí và dung lượng đọc tiêu thụ tính trên lượng dữ liệu đã đọc chứ không tính trên lượng kết quả sau lọc. Vì vậy Scan kèm lọc một bảng lớn vẫn chậm và tốn như Scan không lọc, chỉ khác là mạng nhẹ hơn chút. Khi cần lọc thường xuyên theo một thuộc tính, bạn thiết kế key hoặc chỉ mục phụ để biến nó thành Query thay vì lọc sau Scan.'},
{q: 'Khi nào bạn thêm chỉ mục phụ toàn cục thay vì đổi key của bảng gốc?', a: 'Bạn thêm chỉ mục phụ khi xuất hiện mẫu truy vấn mới mà key gốc không phục vụ được, ví dụ bảng gốc trả theo khách hàng nhưng giờ cần trả theo trạng thái đơn hàng. Đổi key gốc đồng nghĩa viết lại toàn bộ dữ liệu và sửa mọi truy vấn cũ nên rất rủi ro. Chỉ mục phụ cho phép truy vấn theo key khác mà không đụng tới bảng gốc, với chi phí là dung lượng ghi thêm và độ trễ đồng bộ nhỏ. Bạn chỉ tạo đúng chỉ mục phục vụ mẫu truy vấn thật, tránh tạo dư vì mỗi chỉ mục đều tốn chi phí.'},
{q: 'Điểm nóng partition là gì và bạn xử lý thế nào?', a: 'Điểm nóng xảy ra khi quá nhiều lưu lượng dồn vào một giá trị partition key, ví dụ mọi request cùng ghi vào phân vùng của một khách hàng lớn duy nhất. Phân vùng đó bị giới hạn thông lượng riêng nên khi dung lượng còn trống của phân vùng đó cạn, request bắt đầu bị siết. Bạn xử lý bằng cách thêm hậu tố ngẫu nhiên vào key nóng để rải ghi ra nhiều phân vùng, rồi đọc gộp nhiều phân vùng khi cần. Với key đọc nóng, bạn thêm lớp đệm phía trước để giảm tải trực tiếp cho bảng.'}
],
pitfalls: ['Dùng Scan cho API phục vụ người dùng khiến càng nhiều dữ liệu càng chậm và càng tốn', 'Chọn partition key ít giá trị distinct tạo điểm nóng khiến request bị siết vì cạn dung lượng còn trống'],
selfcheck: ['Tôi vẫn chưa giải thích được DynamoDB băm partition key và phân phối item ra các phân vùng vật lý thế nào', 'Tôi có thể giải thích bằng ví dụ bảng đơn hàng Query theo khách hàng và khoảng thời gian thay vì Scan', 'Tôi có thể chọn partition key và sort key cho một bảng mới từ danh sách mẫu truy vấn của ứng dụng'],
refs: ['aws-dynamodb-model', 'aws-dynamodb-query']
},
{
id: 'G09',
group: 'G',
topic: 'DynamoDB conditional write và optimistic concurrency',
prio: 'P0',
level: 'L3',
type: 'code',
q: 'Hãy viết một thao tác trừ tồn kho trong DynamoDB an toàn khi nhiều Lambda cùng chạy, dùng conditional write để chống ghi đè lẫn nhau?',
oral: 'Khi nhiều hàm cùng đọc một số tồn kho rồi cùng ghi đè, bạn ghi sau xóa mất bản ghi trước mà không ai hay biết. Cách chống là ghi có điều kiện, tức mỗi lần ghi kèm theo điều kiện kiểm tra giá trị hiện tại vẫn như lúc mình đã đọc. DynamoDB thực hiện kiểm tra và ghi trong một bước nguyên tử, nếu điều kiện sai thì từ chối và bạn đọc lại giá trị mới rồi thử lại. Mẫu này gọi là optimistic concurrency vì bạn lạc quan cho rằng xung đột hiếm nên không khóa gì cả, chỉ kiểm tra lúc ghi. Với tồn kho, điều kiện còn gồm số lượng phải đủ lớn để không bao giờ bán âm, lần ghi nào không đủ hàng thì dừng ngay thay vì thử lại.',
deep: '<p><strong>Đó là gì:</strong> <code>conditional write</code> là thao tác ghi kèm điều kiện, hệ thống chỉ thực hiện khi điều kiện đúng trên dữ liệu hiện tại. <code>Optimistic concurrency</code> là chiến lược không khóa tài nguyên khi đọc, mà kiểm tra xung đột duy nhất tại thời điểm ghi bằng số phiên bản hoặc giá trị đã đọc.</p><p><strong>Cơ chế hoạt động:</strong> mỗi item mang một số phiên bản tăng dần sau mỗi lần ghi thành công. Khi cập nhật, bạn gửi kèm điều kiện phiên bản hiện tại phải bằng đúng số bản đã đọc, DynamoDB kiểm tra và ghi nguyên tử trong một bước. Nếu hai hàm cùng đọc phiên bản năm, chỉ một hàm ghi thành công lên phiên bản sáu, hàm còn lại bị từ chối vì điều kiện đã sai và phải đọc lại rồi thử lại.</p><p><strong>Vì sao cần:</strong> môi trường serverless có hàng chục môi trường chạy song song nên đọc rồi ghi không điều kiện gần như chắc chắn mất cập nhật khi lưu lượng tăng. Khóa phân tán thì phức tạp và chậm, còn ghi có điều kiện cho bạn an toàn mà không cần khóa.</p><ul><li><strong>Tình huống cụ thể:</strong> hai đơn hàng cùng trừ một sản phẩm còn năm chiếc, hàm nào ghi trước thắng, hàm sau bị từ chối vì điều kiện tồn kho không còn thỏa rồi đọc lại số mới.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng cho mọi cập nhật cạnh tranh như tồn kho, số dư, đặt chỗ; không cần cho ghi chèn mới hoàn toàn hoặc dữ liệu chỉ một nguồn duy nhất ghi.</li><li><strong>Lỗi phổ biến:</strong> thử lại vô hạn khi xung đột khiến hàm treo; quên kiểm tra tồn kho không âm trong cùng điều kiện.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu xung đột xảy ra thường xuyên thay vì hiếm, bạn chuyển sang gom cập nhật qua hàng đợi để ghi tuần tự thay vì để nhiều hàm đua nhau; nếu thao tác gom nhiều item phải cùng thành công, bạn dùng giao dịch có điều kiện để tất cả cùng đặt hoặc cùng hủy.</p>',
code: 'import boto3\nfrom botocore.exceptions import ClientError\n\nddb = boto3.client("dynamodb")\n\ndef decrement_stock(product_id, qty, version):\n    try:\n        ddb.update_item(\n            TableName="products",\n            Key={"product_id": {"S": product_id}},\n            UpdateExpression="SET stock = stock - :q, version = version + :one",\n            ConditionExpression="version = :v AND stock >= :q",\n            ExpressionAttributeValues={\n                ":q": {"N": str(qty)},\n                ":v": {"N": str(version)},\n                ":one": {"N": "1"},\n            },\n        )\n        return True\n    except ClientError as e:\n        if e.response["Error"]["Code"] == "ConditionalCheckFailedException":\n            return False\n        raise',
expected: null,
followups: [
{q: 'Chuyện gì xảy ra khi hai hàm cùng đọc version 5 và cùng ghi, ai thắng?', a: 'Cả hai hàm cùng gửi điều kiện phiên bản phải bằng năm, nhưng DynamoDB xử lý tuần tự nên chỉ hàm tới trước được ghi và nâng phiên bản lên sáu. Hàm tới sau thấy phiên bản hiện tại đã đổi nên điều kiện sai và bị từ chối với lỗi kiểm tra điều kiện. Hàm thua không được ghi đè mà phải đọc lại phiên bản mới cùng số tồn mới rồi quyết định thử lại. Nhờ vậy không bao giờ có hai bản ghi cùng thắng và không mất cập nhật nào trong im lặng.'},
{q: 'Vì sao phải gộp kiểm tra tồn kho không âm vào cùng điều kiện ghi?', a: 'Nếu bạn kiểm tra tồn kho ở mã ứng dụng rồi ghi riêng, khoảng trống giữa đọc và ghi đủ cho một hàm khác chen vào đúng lúc đó khiến tồn kho thành số âm. Gộp điều kiện tồn phải đủ vào cùng thao tác ghi giúp kiểm tra và trừ diễn ra nguyên tử trong một bước duy nhất. Hàm nào tới khi hàng không đủ thì bị từ chối ngay và trả về hết hàng thay vì bán lỗ. Đây chính là điểm mà kiểm tra trong mã không bao giờ thay thế được điều kiện phía cơ sở dữ liệu.'},
{q: 'Khi xung đột xảy ra liên tục, bạn đổi chiến lược thế nào thay vì thử lại mãi?', a: 'Thử lại chỉ hợp khi xung đột hiếm, còn xung đột liên tục nghĩa là nhiều nguồn đang đua một tài nguyên và bạn nên tuần tự hóa bằng hàng đợi. Bạn đẩy các yêu cầu trừ kho vào hàng đợi rồi cho một nhóm nhỏ worker xử lý lần lượt, mỗi yêu cầu vẫn giữ bước ghi có điều kiện làm chốt an toàn cuối cùng. Cách này biến cuộc đua song song thành hàng cho có thứ tự, giảm hẳn tỷ lệ thử lại. Nếu yêu cầu gom nhiều item liên quan, bạn bọc chúng trong một giao dịch để cùng thành công hoặc cùng hủy.'}
],
pitfalls: ['Đọc rồi ghi không kèm điều kiện khiến bản ghi sau lặng lẽ xóa mất bản ghi trước', 'Thử lại vô hạn khi xung đột mà không giới hạn số lần và không lùi dần giữa các lần thử'],
selfcheck: ['Tôi vẫn chưa giải thích được DynamoDB thực hiện kiểm tra điều kiện và ghi nguyên tử trong một bước thế nào', 'Tôi có thể giải thích bằng ví dụ hai đơn hàng cùng trừ tồn kho và một bên bị từ chối do sai version', 'Tôi có thể viết thao tác trừ tồn kho có điều kiện kèm thử lại giới hạn cho một hàm Lambda thật'],
refs: ['aws-dynamodb-model', 'aws-dynamodb-query']
},
{
id: 'G10',
group: 'G',
topic: 'SQS visibility timeout, giao trùng và DLQ',
prio: 'P0',
level: 'L2',
type: 'concept',
q: 'Hãy giải thích visibility timeout của SQS, vì sao SQS có thể giao một message nhiều lần, và dead-letter queue dùng để làm gì?',
oral: 'Khi một worker nhận message từ hàng đợi, message đó tạm ẩn đi trong khoảng visibility timeout để worker khác không nhận trùng, worker xử lý xong thì xóa message khỏi hàng đợi. Nếu worker sập hoặc xử lý quá lâu mà chưa xóa, hết thời gian ẩn thì message hiện lại để worker khác nhận và xử lý, đây chính là cơ chế đảm bảo không mất việc. Cũng vì cơ chế này mà SQS chỉ đảm bảo giao ít nhất một lần chứ không phải đúng một lần, message hoàn toàn có thể tới tay bạn hai lần khi lần đầu xử lý xong nhưng chưa kịp xóa. Dead-letter queue là một hàng đợi phụ hứng các message thất bại quá số lần cho phép, giúp bạn cách ly message độc khỏi dòng chính để phân tích và xử lý riêng thay vì để nó kẹt mãi trong vòng lặp.',
deep: '<p><strong>Đó là gì:</strong> <code>visibility timeout</code> là khoảng thời gian message bị ẩn sau khi một worker nhận nó. <code>Dead-letter queue</code> là hàng đợi phụ nhận các message thất bại quá số lần cho phép, tách chúng khỏi dòng xử lý chính.</p><p><strong>Cơ chế hoạt động:</strong> worker nhận message, message ẩn đi, worker xử lý xong thì gọi xóa message. Nếu worker sập giữa chừng hoặc xử lý lâu hơn thời gian ẩn mà chưa gia hạn, message hiện lại và worker khác nhận tiếp. Sau số lần nhận thất bại vượt ngưỡng bạn cấu hình, hệ thống tự chuyển message sang hàng đợi chết thay vì cho quay lại hàng đợi chính.</p><p><strong>Vì sao cần thiết kế này:</strong> ẩn tạm thời giúp không mất việc khi worker sập, còn hàng đợi chết giúp một message lỗi không kẹt mãi làm tắc cả dòng chính. Không có hai cơ chế này, bạn hoặc mất việc âm thầm hoặc tắc hàng đợi vì một message độc duy nhất.</p><ul><li><strong>Tình huống cụ thể:</strong> worker xử lý đơn hàng sập giữa chừng, message hiện lại sau ba mươi giây để worker khác làm tiếp; message lỗi định dạng thất bại năm lần thì sang hàng đợi chết cho phân tích.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng hàng đợi chết cho mọi hàng đợi production; không dùng hàng đợi tiêu chuẩn khi nghiệp vụ bắt buộc đúng một lần mà không tự làm được idempotency.</li><li><strong>Lỗi phổ biến:</strong> đặt thời gian ẩn ngắn hơn thời gian xử lý khiến message bị xử lý trùng liên tục; quên cấu hình hàng đợi chết nên message độc quay vòng mãi.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu thời gian xử lý dao động mạnh giữa các message, bạn gia hạn thời gian ẩn theo tiến độ xử lý thay vì đặt một số cố định quá lớn; nếu thứ tự message quan trọng, bạn chuyển sang hàng đợi đảm bảo thứ tự với nhóm message phù hợp và chấp nhận thông lượng thấp hơn.</p>',
code: null,
expected: null,
followups: [
{q: 'Vì sao thời gian ẩn ngắn hơn thời gian xử lý gây ra xử lý trùng liên tục?', a: 'Worker mới nhận được một nửa thì message hết hạn ẩn và hiện lại, worker khác tưởng việc chưa ai làm nên nhận tiếp và xử lý song song cùng một message. Cả hai worker cùng ghi kết quả gây trùng dữ liệu, và mỗi worker xóa message của mình khiến việc theo dõi rất rối. Bạn đặt thời gian ẩn dài hơn thời gian xử lý thực tế cộng biên an toàn, hoặc gia hạn dần trong lúc xử lý các message dài. Quy tắc là message chỉ được hiện lại khi worker thật sự đã sập chứ không phải vì xử lý hơi lâu.'},
{q: 'Bạn cấu hình và vận hành dead-letter queue thế nào cho hiệu quả?', a: 'Bạn đặt ngưỡng số lần nhận tối đa đã vừa phải, dù cho các lỗi thoáng qua tự khỏi sau vài lần thử nhưng không để message độc quay vòng quá lâu. Bạn gắn cảnh báo mỗi khi có message mới rơi vào hàng đợi chết để xử lý sớm thay vì để đọng lại. Định kỳ bạn xem nội dung message chết để phân loại lỗi mã hay lỗi dữ liệu, sửa gốc rồi mới cho chạy lại có kiểm soát. Hàng đợi chết là nơi chẩn đoán chứ không phải thùng rác bỏ quên.'},
{q: 'Khi nào bạn chuyển sang hàng đợi đảm bảo thứ tự thay vì hàng đợi tiêu chuẩn?', a: 'Bạn chuyển khi các sự kiện của cùng một đối tượng bắt buộc phải xử lý đúng thứ tự, ví dụ tạo đơn phải trước hủy đơn. Hàng đợi có thứ tự gom các message cùng nhóm lại để xử lý lần lượt và loại trùng trong cửa sổ ngắn, đổi lại thông lượng thấp hơn và cấu hình phức tạp hơn. Nếu các message độc lập nhau thì hàng đợi tiêu chuẩn với xử lý song song vừa rẻ vừa nhanh hơn nhiều. Bạn chỉ trả giá cho thứ tự khi nghiệp vụ thật sự cần.'}
],
pitfalls: ['Đặt visibility timeout ngắn hơn thời gian xử lý khiến cùng một message bị xử lý trùng liên tục', 'Không cấu hình dead-letter queue nên message lỗi quay vòng mãi và làm tắc dòng chính'],
selfcheck: ['Tôi vẫn chưa giải thích được message chuyển sang hàng đợi chết sau đúng bao nhiêu lần nhận thất bại theo cấu hình', 'Tôi có thể giải thích bằng ví dụ worker sập giữa chừng khiến message hiện lại cho worker khác làm tiếp', 'Tôi có thể cấu hình visibility timeout và dead-letter queue cho một hàng đợi đơn hàng mới'],
refs: ['aws-sqs-visibility', 'aws-sqs-dlq']
}
,
{
id: 'G11',
group: 'G',
topic: 'Lambda retry và idempotency',
prio: 'P1',
level: 'L3',
type: 'predict',
q: 'Một hàm Lambda trừ tiền được gọi bất đồng bộ và cấu hình retry 2 lần, nhưng lần chạy đầu timeout sau khi đã trừ tiền. Kết quả cuối cùng là gì và vì sao retry gây ra trùng lặp?',
oral: 'Kết quả là khách hàng bị trừ tiền hai lần, vì retry không biết lần chạy trước đã làm tới đâu. Khi Lambda timeout, bên gọi chỉ thấy thất bại và gửi lại cùng một event, lần chạy thứ hai đọc lại số dư và trừ tiếp mà không hề biết lần đầu đã trừ rồi. Vấn đề gốc là hàm không có tính idempotency, tức gọi lại cùng một yêu cầu không cho cùng một kết quả. Cách sửa là mỗi yêu cầu mang một mã duy nhất, hàm kiểm tra mã này trong bảng ghi nhận trước khi trừ tiền, thấy mã đã xử lý thì trả lại kết quả cũ thay vì trừ tiếp. Nhờ vậy retry bao nhiêu lần cũng an toàn, lần đầu thực hiện thật còn các lần sau chỉ trả lại kết quả đã có.',
deep: '<p><strong>Đó là gì:</strong> <code>retry</code> là cơ chế tự gọi lại khi lần chạy thất bại hoặc timeout, còn <code>idempotency</code> là tính chất gọi lại cùng một yêu cầu nhiều lần vẫn cho cùng một kết quả như gọi một lần.</p><p><strong>Cơ chế hoạt động:</strong> với gọi bất đồng bộ, Lambda tự retry khi hàm lỗi, còn với nguồn sự kiện như hàng đợi thì message hiện lại và hàm chạy lại cùng payload. Cả hai cơ chế đều mù về trạng thái bên trong lần chạy trước, nên mọi tác dụng phụ như trừ tiền hay gửi mail đều lặp lại nếu mã không phòng thủ.</p><p><strong>Vì sao cần idempotency:</strong> mạng luôn có thể timeout sau khi tác dụng phụ đã xảy ra, nên retry là bình thường chứ không phải ngoại lệ. Không có idempotency, mỗi lần retry là một lần trừ tiền oan mà rất khó đối soát về sau.</p><ul><li><strong>Tình huống cụ thể:</strong> event mang mã giao dịch, hàm ghi có điều kiện mã này vào bảng ledger trước khi trừ tiền, lần retry thấy mã đã có thì trả kết quả cũ.</li><li><strong>Khi nào dùng và khi nào không:</strong> bắt buộc idempotency cho mọi thao tác ghi tiền, tồn kho, gửi thông báo; không cần cho đọc thuần túy vì đọc lại bao nhiêu lần cũng vậy.</li><li><strong>Lỗi phổ biến:</strong> tưởng retry của nền tảng tự loại trùng; kiểm tra trùng trong bộ nhớ của môi trường chạy thay vì trong kho bền vững.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu thao tác gồm nhiều bước qua nhiều dịch vụ, bạn bọc bằng mã giao dịch duy nhất lan truyền qua mọi bước; nếu yêu cầu tới từ client hay bấm trùng nút, bạn để client tự sinh mã idempotency và server tôn trọng nó thay vì chỉ dựa vào retry phía server.</p>',
code: 'import boto3\n\nddb = boto3.client("dynamodb")\n\ndef handler(event, context):\n    tx = event["tx_id"]\n    amount = event["amount"]\n    ddb.put_item(\n        TableName="ledger",\n        Item={"tx_id": {"S": tx}, "amount": {"N": str(amount)}},\n        ConditionExpression="attribute_not_exists(tx_id)",\n    )\n    charge_customer(event["customer_id"], amount)\n    return {"ok": True, "tx_id": tx}',
expected: 'Khách hàng bị trừ tiền hai lần: lần đầu trừ thành công rồi timeout nên bên gọi tưởng thất bại, lần retry trừ tiếp. Nguyên nhân gốc là hàm không idempotent, không ghi nhận mã giao dịch bằng conditional write trước khi trừ tiền.',
followups: [
{q: 'Vì sao kiểm tra trùng trong bộ nhớ của Lambda không đủ?', a: 'Mỗi lần retry có thể rơi vào một môi trường chạy hoàn toàn khác, nên trạng thái trong bộ nhớ của lần chạy trước không tồn tại ở lần chạy sau. Ngay cả cùng môi trường, nó có thể bị thu hồi bất cứ lúc nào khiến dữ liệu trong bộ nhớ mất sạch. Vì vậy mốc kiểm tra trùng phải nằm trong kho bền vững như DynamoDB với ghi có điều kiện, nơi mọi môi trường chạy đều nhìn thấy cùng một sự thật. Bộ nhớ chỉ dùng làm đệm tăng tốc, không bao giờ là nguồn chân lý cho idempotency.'},
{q: 'Khi thao tác gồm nhiều bước, bạn lan truyền idempotency thế nào?', a: 'Bạn sinh một mã giao dịch duy nhất ở điểm vào và truyền nó qua mọi bước tiếp theo, mỗi bước kiểm tra mã trước khi thực hiện tác dụng phụ của mình. Bước nào thấy mã đã xử lý thì bỏ qua và trả kết quả cũ. Với luồng qua hàng đợi, bạn đặt mã vào thuộc tính message để mọi worker đều thấy. Cách này biến cả chuỗi nhiều bước thành một đơn vị idempotent duy nhất thay vì mỗi bước tự lo riêng lẻ.'}
],
pitfalls: ['Tưởng nền tảng tự loại trùng khi retry nên không làm idempotency trong mã', 'Lưu cờ đã xử lý trong bộ nhớ môi trường chạy thay vì trong kho bền vững nên retry sang môi trường khác vẫn trùng'],
selfcheck: ['Tôi vẫn chưa giải thích được retry của gọi bất đồng bộ khác gì với message hiện lại của hàng đợi khi worker sập', 'Tôi có thể giải thích bằng ví dụ hàm trừ tiền bị retry và trừ hai lần vì thiếu ghi nhận mã giao dịch', 'Tôi có thể thêm kiểm tra idempotency bằng conditional write cho một hàm trừ tiền hiện có'],
refs: ['aws-lambda-best', 'aws-sqs-visibility']
},
{
id: 'G12',
group: 'G',
topic: 'VPC, subnet, security group, public và private subnet',
prio: 'P1',
level: 'L2',
type: 'debug',
q: 'Một Lambda trong subnet private không ra được internet để gọi API bên thứ ba, dù security group đã mở outbound 0.0.0.0/0. Lỗi nằm ở đâu và bạn sửa thế nào?',
oral: 'Lỗi nằm ở định tuyến chứ không phải security group, vì security group chỉ là tường lửa còn đường đi do bảng route quyết định. Subnet private không có đường trực tiếp ra internet, mở outbound bao nhiêu cũng không tạo ra đường đi. Cách sửa chuẩn là đặt một NAT gateway ở subnet public rồi thêm route từ subnet private trỏ ra NAT, lưu lượng của Lambda đi qua NAT để ra ngoài với địa chỉ công cộng của NAT. Bạn tuyệt đối không sửa bằng cách chuyển Lambda sang subnet public hay gán địa chỉ công cộng cho tài nguyên trong private. Sau khi sửa, bạn kiểm tra lại bảng route và thử gọi API để xác nhận, đồng thời rà soát security group ở mức tối thiểu cần thiết.',
deep: '<p><strong>Đó là gì:</strong> <code>VPC</code> là mạng riêng ảo của bạn trên đám mây, <code>subnet</code> là từng dải mạng con trong VPC, <code>security group</code> là tường lửa gắn trên từng tài nguyên. Subnet public có đường ra internet qua internet gateway, subnet private thì không.</p><p><strong>Cơ chế hoạt động:</strong> mỗi subnet gắn một bảng route quyết định gói tin đi đâu. Gói tin từ subnet private muốn ra internet phải được route trỏ sang <code>NAT gateway</code> nằm ở subnet public, NAT đứng ra gọi hộ rồi chuyển trả lời về. Security group chỉ cho phép hay chặn trên đường đi đã có, không tự tạo đường đi mới.</p><p><strong>Vì sao cần phân biệt:</strong> nhầm tường lửa với định tuyến khiến bạn mở quyền ngày càng rộng mà lỗi vẫn còn, đồng thời vô tình mở cửa cho kẻ xấu. Hiểu đúng giúp bạn sửa đúng lớp và giữ subnet private thật sự riêng tư.</p><ul><li><strong>Tình huống cụ thể:</strong> Lambda trong private gọi API thanh toán timeout, thêm route tới NAT là thông ngay mà không cần động tới security group.</li><li><strong>Khi nào dùng và khi nào không:</strong> đặt tài nguyên nội bộ như database và Lambda trong private, chỉ đặt cân bằng tải và NAT ở public; không bao giờ đặt database ở public để khỏi phải gọi API.</li><li><strong>Lỗi phổ biến:</strong> mở security group cho mọi địa chỉ để sửa lỗi định tuyến; chuyển tài nguyên sang public cho nhanh rồi quên chuyển lại.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu lưu lượng ra ngoài tăng mạnh và NAT thành nút thắt chi phí, bạn tách các gọi tới dịch vụ cùng nhà cung cấp qua endpoint riêng trong VPC thay vì đi qua NAT; nếu Lambda không cần gọi ra ngoài nữa, bạn gỡ route NAT để thu hẹp bề mặt tấn công.</p>',
code: null,
expected: 'Lambda timeout khi gọi API ngoài vì subnet private không có đường ra internet, security group mở outbound không tạo ra đường đi. Nguyên nhân gốc là thiếu route từ subnet private tới NAT gateway ở subnet public, sửa bằng cách thêm route đó thay vì mở thêm quyền hay chuyển sang public.',
followups: [
{q: 'Vì sao không sửa bằng cách chuyển Lambda sang subnet public?', a: 'Chuyển sang public đồng nghĩa tài nguyên của bạn phơi bày gần internet hơn và đi ngược nguyên tắc đặt logic nội bộ trong vùng riêng tư. Subnet public còn đòi hỏi quản lý địa chỉ công cộng và quy tắc vào ra chặt chẽ hơn, một cấu hình sai là thành lỗ hổng. Đường sửa đúng là giữ Lambda trong private và tạo lối ra có kiểm soát qua NAT, vừa thông vừa an toàn. Public chỉ dành cho những thứ buộc phải nhận traffic trực tiếp từ internet như cân bằng tải.'},
{q: 'Endpoint riêng trong VPC khác gì NAT và khi nào bạn dùng nó?', a: 'Endpoint riêng tạo đường đi thẳng từ VPC tới dịch vụ cùng nhà cung cấp mà không qua internet công cộng, nên nhanh hơn và không tốn phí truyền qua NAT. Bạn dùng endpoint cho các gọi tới lưu trữ, hàng đợi và cơ sở dữ liệu cùng nhà cung cấp khi Lambda đã nằm trong VPC. NAT vẫn cần cho các gọi ra internet công cộng thật sự như API bên thứ ba. Kết hợp cả hai giúp bạn vừa rẻ vừa giảm bề mặt tấn công.'}
],
pitfalls: ['Nhầm security group với định tuyến nên mở quyền ngày càng rộng mà traffic vẫn không thông', 'Chuyển tài nguyên sang subnet public cho nhanh rồi quên chuyển lại khi lên production'],
selfcheck: ['Tôi vẫn chưa giải thích được bảng route của subnet private trỏ sang NAT ở subnet public theo từng bước', 'Tôi có thể giải thích bằng ví dụ Lambda trong private timeout khi gọi API ngoài dù outbound đã mở', 'Tôi có thể kiểm tra bảng route và security group để chẩn đoán một Lambda mất mạng ra ngoài'],
refs: ['aws-vpc']
},
{
id: 'G13',
group: 'G',
topic: 'CloudWatch logs, metrics, alarms và correlation ID',
prio: 'P1',
level: 'L2',
type: 'concept',
q: 'Hãy giải thích bạn dùng CloudWatch logs, metrics và alarms thế nào, và vì sao cần correlation ID để truy vết một request đi qua nhiều service?',
oral: 'Logs cho bạn biết chuyện gì đã xảy ra ở từng dòng mã, metrics cho biết hệ thống khỏe hay yếu qua các con số theo thời gian, còn alarms là người gác tự động báo khi metric vượt ngưỡng. Ba thứ này bổ sung cho nhau chứ không thay thế nhau, có log mà không có alarm thì sự cố xảy ra bạn vẫn không biết. Khi một request đi qua cổng API rồi Lambda rồi hàng đợi rồi database, mỗi tầng ghi log riêng nên không có cách nào ghép chúng lại nếu thiếu định danh chung. Correlation ID là một mã duy nhất sinh ở điểm vào và truyền qua mọi tầng, nhờ đó bạn lọc đúng một mã là thấy toàn bộ hành trình của request từ đầu tới cuối trong vài giây.',
deep: '<p><strong>Đó là gì:</strong> <code>logs</code> là các dòng sự kiện chi tiết từng lần chạy, <code>metrics</code> là các con số tổng hợp theo thời gian như số lỗi hay độ trễ, <code>alarms</code> là quy tắc tự động báo động khi metric vượt ngưỡng. <code>Correlation ID</code> là mã định danh duy nhất của một request, được truyền qua mọi service mà request đi qua.</p><p><strong>Cơ chế hoạt động:</strong> điểm vào sinh mã duy nhất cho mỗi request rồi nhét vào context và header của các gọi tiếp theo, mỗi dòng log ở mọi tầng đều in kèm mã này. Khi sự cố xảy ra, alarm bắn ra từ metric bất thường, bạn lấy mã của request lỗi rồi lọc log toàn hệ thống theo đúng mã đó để thấy request đã đi qua những đâu và sập ở tầng nào.</p><p><strong>Vì sao cần cả ba cộng mã chung:</strong> metric không có log thì biết sập mà không biết vì sao, log không có mã chung thì biết nhiều chuyện rời rạc mà không ghép thành câu chuyện. Kết hợp cả hai giúp thời gian tìm gốc rễ giảm từ hàng giờ xuống vài phút.</p><ul><li><strong>Tình huống cụ thể:</strong> người dùng báo đơn hàng lỗi, bạn xin mã request rồi lọc ra thấy Lambda ghi trừ kho thành công nhưng bước ghi thanh toán báo timeout.</li><li><strong>Khi nào dùng và khi nào không:</strong> luôn sinh mã cho mọi request đi qua nhiều tầng; không cần mã cho hàm đơn lẻ chạy độc lập theo lịch.</li><li><strong>Lỗi phổ biến:</strong> log không in mã nên khi sập phải đoán mò giữa hàng nghìn dòng; đặt alarm cho mọi metric gây nhiễu khiến đội bỏ qua cả cảnh báo thật.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu lưu lượng tăng khiến log phình quá to, bạn hạ mức chi tiết của log thành công và giữ chi tiết cho log lỗi kèm lấy mẫu; nếu có nhiều hệ thống cùng tham gia, bạn thống nhất tên trường chứa mã để công cụ truy vết gộp được toàn bộ hành trình.</p>',
code: 'import json, uuid\n\ndef handler(event, context):\n    corr = event.get("correlation_id") or uuid.uuid4().hex[:12]\n    print(json.dumps({"correlation_id": corr, "step": "start", "order": event.get("order_id")}))\n    try:\n        result = process_order(event)\n        print(json.dumps({"correlation_id": corr, "step": "ok"}))\n        return {"correlation_id": corr, "result": result}\n    except Exception as e:\n        print(json.dumps({"correlation_id": corr, "step": "error", "err": str(e)}))\n        raise',
expected: null,
followups: [
{q: 'Bạn đặt alarm thế nào để vừa báo sớm vừa không gây nhiễu?', a: 'Bạn chỉ đặt alarm cho các tín hiệu ảnh hưởng người dùng như tỷ lệ lỗi, độ trễ cao và hàng đợi tồn đọng, mỗi alarm gắn ngưỡng dựa trên hành vi bình thường đã quan sát chứ không đoán mò. Bạn đặt thời gian chờ đủ dài để các gai thoáng qua tự hết mà không báo, và phân mức báo động khẩn với cảnh báo thường để đội ưu tiên đúng. Định kỳ bạn rà soát các alarm hay kêu oan để chỉnh ngưỡng hoặc xóa, vì một hệ thống báo động mà ai cũng bỏ qua thì coi như không có.'},
{q: 'Khi log quá lớn gây tốn kém, bạn cắt giảm thế nào mà vẫn gỡ được sự cố?', a: 'Bạn giữ log lỗi đầy đủ chi tiết kèm mã truy vết, còn log thành công chỉ giữ dòng tóm tắt một dòng mỗi request. Bạn bật lấy mẫu chi tiết cho một phần nhỏ request thành công để vẫn đo được hành vi bình thường. Bạn đặt thời gian lưu trữ ngắn cho log chi tiết và dài cho log tóm tắt cùng metric tổng hợp. Nhờ vậy chi phí lưu trữ giảm mạnh mà khi sự cố xảy ra bạn vẫn có đủ dữ liệu để truy vết.'}
],
pitfalls: ['Ghi log mà không in correlation ID nên khi sập phải mò giữa hàng nghìn dòng không liên quan', 'Đặt alarm cho quá nhiều metric gây nhiễu khiến đội bỏ qua cả cảnh báo thật sự'],
selfcheck: ['Tôi vẫn chưa giải thích được alarm đánh giá metric theo cửa sổ thời gian và bắn thông báo thế nào', 'Tôi có thể giải thích bằng ví dụ lọc một mã request để thấy hành trình qua gateway, Lambda và hàng đợi', 'Tôi có thể thêm correlation ID vào một API nhiều tầng và đặt một alarm tỷ lệ lỗi cho nó'],
refs: ['aws-cloudwatch']
},
{
id: 'G14',
group: 'G',
topic: 'Secrets Manager và Parameter Store',
prio: 'P1',
level: 'L2',
type: 'predict',
q: 'Đoạn mã Lambda dưới đây đọc mật khẩu database trực tiếp từ biến môi trường ở mỗi lần gọi. Điều gì không ổn về bảo mật và vận hành, và bạn sửa thế nào?',
oral: 'Vấn đề là mật khẩu nằm trần trong biến môi trường, ai xem được cấu hình hàm là thấy, lại còn lộ trong ảnh chụp màn hình và bản sao cấu hình. Mỗi lần đổi mật khẩu bạn phải sửa cấu hình và triển khai lại toàn bộ hàm, gây gián đoạn và dễ quên chỗ. Cách sửa là chuyển bí mật ra dịch vụ quản lý chuyên dụng, hàm chỉ giữ tên tham chiếu và lấy giá trị lúc chạy bằng quyền của execution role. Với mật khẩu database cần xoay vòng, bạn dùng dịch vụ có xoay tự động để mật khẩu đổi định kỳ mà mã không phải sửa gì. Bạn cũng đệm giá trị trong môi trường ấm để không gọi lấy bí mật ở mọi request, vừa nhanh vừa tránh bị giới hạn tốc độ.',
deep: '<p><strong>Đó là gì:</strong> <code>Secrets Manager</code> là dịch vụ giữ bí mật có hỗ trợ xoay vòng tự động và kiểm soát ai được đọc, <code>Parameter Store</code> là kho tham số hợp cho cấu hình thường và bí mật ít nhạy cảm với chi phí thấp hơn.</p><p><strong>Cơ chế hoạt động:</strong> mã gọi tới dịch vụ quản lý bằng quyền của execution role, nhận giá trị bí mật trong bộ nhớ lúc chạy chứ không lưu trong mã hay biến môi trường. Với Secrets Manager, lịch xoay tự động sinh mật khẩu mới, cập nhật database rồi cho phiên bản cũ một thời gian chuyển tiếp để các kết nối cũ không đứt đột ngột.</p><p><strong>Vì sao cần:</strong> bí mật trong mã hay biến môi trường lan ra khắp kho mã, ảnh chụp và bản sao, một lần lộ là phải đổi khắp nơi. Gom về một chỗ giúp xoay vòng một lần là xong và thu hồi quyền đọc chỉ bằng một policy.</p><ul><li><strong>Tình huống cụ thể:</strong> đổi mật khẩu database lúc nửa đêm, các hàm đang chạy vẫn dùng giá trị đệm tới khi hết hạn rồi tự lấy bản mới mà không cần triển khai lại.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng Secrets Manager cho mật khẩu database và khóa cần xoay tự động; dùng Parameter Store cho cấu hình thường và bí mật ít đổi để tiết kiệm.</li><li><strong>Lỗi phổ biến:</strong> nhúng bí mật vào mã nguồn rồi đẩy lên kho chung; gọi lấy bí mật ở mọi request gây chậm và bị giới hạn tốc độ.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu số lần đọc bí mật tăng mạnh, bạn tăng thời gian đệm và dùng phiên bản tham chiếu theo tên thay vì đọc trực tiếp mỗi lần; nếu yêu cầu kiểm toán nghiêm hơn, bạn bật ghi vết ai đã đọc bí mật lúc nào để truy vết khi có sự cố lộ lọt.</p>',
code: 'import os, psycopg2\n\ndef handler(event, context):\n    conn = psycopg2.connect(host=os.environ["DB_HOST"], password=os.environ["DB_PASSWORD"])\n    with conn.cursor() as cur:\n        cur.execute("SELECT 1")\n        return {"ok": cur.fetchone()[0] == 1}',
expected: 'Hàm vẫn chạy đúng nhưng mật khẩu lộ trần trong cấu hình và không xoay vòng được. Nguyên nhân gốc là bí mật bị nhúng vào biến môi trường thay vì lấy lúc chạy từ dịch vụ quản lý bằng execution role, nên đổi mật khẩu phải triển khai lại hàm và mọi bản sao cấu hình đều thành nơi lộ bí mật.',
followups: [
{q: 'Bạn chọn giữa Secrets Manager và Parameter Store khi nào?', a: 'Bạn chọn Secrets Manager khi bí mật cần xoay vòng tự động như mật khẩu database, vì nó lo toàn bộ vòng đời sinh mới và chuyển tiếp mà mã không phải đổi. Bạn chọn Parameter Store cho cấu hình thường và bí mật ít đổi như cờ tính năng hay endpoint nội bộ, vì cách dùng đơn giản và chi phí thấp hơn. Với cả hai, bạn vẫn đệm giá trị trong môi trường ấm và chỉ cho execution role quyền đọc đúng tham số cần thiết. Quy tắc là xoay tự động thì Secrets Manager, còn lại Parameter Store là đủ.'},
{q: 'Bạn đệm bí mật trong Lambda thế nào mà vẫn nhận được bản xoay mới?', a: 'Bạn lưu giá trị bí mật trong biến toàn cục kèm thời điểm lấy, các lần gọi ấm dùng lại mà không gọi dịch vụ nữa. Bạn đặt thời gian sống cho đệm ngắn hơn chu kỳ xoay, hết hạn thì lần gọi tiếp theo lấy bản mới một lần rồi đệm tiếp. Khi xoay mật khẩu database, bạn giữ cửa sổ cả hai phiên bản cùng có hiệu lực để các đệm cũ không đứt đột ngột. Cách này vừa giảm độ trễ và số lần gọi, vừa bảo đảm bản mới lan ra toàn hệ thống trong thời gian có kiểm soát.'}
],
pitfalls: ['Nhúng mật khẩu vào mã nguồn hay biến môi trường rồi đẩy lên kho chung và ảnh chụp cấu hình', 'Gọi lấy bí mật ở mọi request gây chậm, tốn kém và dễ bị giới hạn tốc độ'],
selfcheck: ['Tôi vẫn chưa giải thích được vòng xoay mật khẩu tự động chuyển tiếp giữa bản cũ và bản mới thế nào', 'Tôi có thể giải thích bằng ví dụ hàm đọc mật khẩu trần từ biến môi trường và cách chuyển sang dịch vụ quản lý', 'Tôi có thể chuyển một hàm đang dùng mật khẩu cứng sang lấy bí mật lúc chạy kèm bộ đệm'],
refs: ['aws-secrets']
},
{
id: 'G15',
group: 'G',
topic: 'CloudFront, caching và invalidation',
prio: 'P1',
level: 'L2',
type: 'concept',
q: 'Hãy giải thích CloudFront phân phối nội dung thế nào, khi nào bạn bật cache và khi nào phải chủ động xóa cache?',
oral: 'CloudFront là mạng phân phối nội dung với các điểm hiện diện khắp thế giới đứng gần người dùng, thay vì ai cũng phải về tận máy chủ gốc. Khi có request, điểm gần nhất kiểm tra đã có bản sao chưa, có và còn hạn thì trả ngay nên rất nhanh và giảm tải cho máy chủ gốc. Chưa có hoặc hết hạn thì điểm đó về gốc lấy một lần rồi giữ lại phục vụ các request sau. Bạn bật cache cho nội dung ít đổi như ảnh, file tĩnh và trang công khai để vừa nhanh vừa rẻ. Với nội dung đổi theo từng người dùng hay dữ liệu thời gian thực, bạn tắt cache hoặc cache rất ngắn để không phục vụ nhầm dữ liệu cũ. Khi file tĩnh đổi trước hạn, bạn phải chủ động xóa cache để các điểm hiện diện lấy bản mới thay vì tiếp tục trả bản cũ.',
deep: '<p><strong>Đó là gì:</strong> <code>CloudFront</code> là mạng phân phối nội dung, gồm các điểm hiện diện ở biên gần người dùng và máy chủ gốc giữ bản chính. <code>Caching</code> là việc giữ bản sao ở biên, <code>invalidation</code> là lệnh chủ động xóa bản sao đã cache để buộc lấy bản mới.</p><p><strong>Cơ chế hoạt động:</strong> request tới điểm biên gần nhất, điểm này so sánh khóa cache gồm đường dẫn và một phần header với bản đã giữ. Trúng và còn hạn thì trả ngay không chạm tới gốc, trượt thì về gốc lấy một lần rồi giữ lại theo thời gian sống bạn cấu hình. Lệnh xóa cache lan ra các điểm biên để các request sau buộc phải lấy bản mới từ gốc.</p><p><strong>Vì sao cần:</strong> phục vụ từ biên gần người dùng giảm độ trễ từ hàng trăm mili giây xuống vài chục, đồng thời máy chủ gốc chỉ phục vụ một lần cho hàng nghìn request trùng lặp. Không có lớp này, mỗi người dùng đều đánh thẳng về gốc vừa chậm vừa dễ sập khi đông.</p><ul><li><strong>Tình huống cụ thể:</strong> ảnh sản phẩm đổi mẫu mới, bạn xóa cache đúng đường dẫn ảnh đó để người dùng thấy bản mới ngay mà không phải xóa toàn bộ.</li><li><strong>Khi nào dùng và khi nào không:</strong> bật cache cho nội dung công khai ít đổi; tắt hoặc cache rất ngắn cho trang cá nhân và API thời gian thực.</li><li><strong>Lỗi phổ biến:</strong> cache cả phản hồi mang dữ liệu cá nhân khiến người này thấy dữ liệu người khác; đổi file mà quên xóa cache nên người dùng mãi thấy bản cũ.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu tần suất triển khai tăng và xóa cache thủ công không kịp, bạn đổi sang đặt tên file theo phiên bản để bản mới là đường dẫn mới và không bao giờ cần xóa; nếu nội dung vừa cần nhanh vừa cần tươi, bạn đặt thời gian sống ngắn kèm kiểm tra lại có điều kiện với gốc.</p>',
code: null,
expected: null,
followups: [
{q: 'Vì sao đặt tên file theo phiên bản tốt hơn xóa cache thủ công?', a: 'Mỗi lần triển khai sinh ra tên file mới chứa mã phiên bản nên đường dẫn mới chưa từng được cache, người dùng tự động nhận bản mới mà không cần lệnh xóa nào. Cách này loại bỏ hoàn toàn cửa sổ người dùng thấy bản cũ trong lúc lệnh xóa đang lan, và không tốn chi phí xóa vì lệnh xóa quá nhiều cũng phát sinh phí. Bạn chỉ dùng lệnh xóa cho các trường hợp khẩn như gỡ nội dung sai, còn luồng thường ngày thì tên file theo phiên bản là đủ. Đây là thói quen chuẩn của mọi pipeline frontend hiện đại.'},
{q: 'Bạn tránh phục vụ nhầm dữ liệu cá nhân từ cache thế nào?', a: 'Bạn cấu hình khóa cache tách bạch nội dung công khai và nội dung cá nhân, tuyệt đối không cache phản hồi mang thông tin riêng của từng người dùng. Với API cần đăng nhập, bạn tắt cache hoặc chỉ cache theo mã người dùng trong khóa để mỗi người thấy đúng phần của mình. Bạn kiểm tra kỹ các header mà gốc trả về để chắc phản hồi cá nhân không bị đánh dấu cache công khai. Quy tắc là thà không cache còn hơn cache nhầm dữ liệu của người này cho người khác.'}
],
pitfalls: ['Cache phản hồi mang dữ liệu cá nhân khiến người này thấy dữ liệu của người khác', 'Đổi file tĩnh mà quên xóa cache nên người dùng mãi thấy bản cũ dù gốc đã mới'],
selfcheck: ['Tôi vẫn chưa giải thích được khóa cache gộp đường dẫn và header để quyết định trúng hay trượt thế nào', 'Tôi có thể giải thích bằng ví dụ đổi ảnh sản phẩm và phải xóa cache đúng đường dẫn đó', 'Tôi có thể cấu hình cache cho file tĩnh và tắt cache cho API cá nhân của một web thật'],
refs: ['aws-cloudfront', 'aws-s3']
},
{
id: 'G16',
group: 'G',
topic: 'Lambda và container ECS: chọn theo workload',
prio: 'P1',
level: 'L2',
type: 'concept',
q: 'Hãy so sánh Lambda với container chạy trên ECS và cho biết khi nào bạn chọn mỗi bên cho một workload cụ thể?',
oral: 'Lambda phù hợp cho tác vụ ngắn, chạy theo sự kiện và lưu lượng thất thường, vì bạn không quản lý máy chủ và chỉ trả cho thời gian chạy thật. Container trên ECS phù hợp cho tiến trình chạy liên tục, tác vụ dài hàng giờ và ứng dụng cần kiểm soát môi trường sâu như kết nối bám dính hay bộ nhớ lớn. Điểm quyết định không phải công nghệ nào hiện đại hơn mà là hình dạng workload, thời gian chạy, trạng thái và lưu lượng của bạn ra sao. Nhiều hệ thống thật dùng cả hai, API thất thường chạy Lambda còn worker nền chạy dài nằm trên ECS. Khi workload đổi hình dạng, bạn chuyển phe chứ không cố ép một bên làm việc của bên kia.',
deep: '<p><strong>Đó là gì:</strong> <code>Lambda</code> là hàm chạy theo sự kiện do nền tảng quản lý toàn bộ máy chủ, <code>ECS</code> là dịch vụ điều phối container nơi bạn đóng gói ứng dụng và kiểm soát cách nó chạy. Lambda giới hạn thời gian chạy mỗi lần và không giữ trạng thái giữa các lần gọi, container thì chạy bao lâu tùy bạn và giữ trạng thái trong bộ nhớ suốt vòng đời.</p><p><strong>Cơ chế hoạt động:</strong> Lambda tự tạo thêm môi trường chạy khi request tăng và thu về không khi hết việc, bạn trả theo số lần gọi và thời gian chạy. ECS giữ số container bạn yêu cầu luôn chạy, tự thay thế container hỏng và phân phối tải giữa chúng, bạn trả cho tài nguyên đã đặt bất kể có việc hay không.</p><p><strong>Vì sao cần chọn đúng:</strong> ép tác vụ dài vào Lambda dẫn tới timeout liên tục và retry hỗn loạn, còn chạy API thất thường trên container luôn bật dẫn tới trả tiền cho máy chạy không. Chọn đúng giúp vừa rẻ vừa ít sự cố vận hành.</p><ul><li><strong>Tình huống cụ thể:</strong> API đặt hàng lưu lượng ngày đêm chênh mười lần chạy Lambda, còn worker encode video mỗi job hàng giờ chạy container ECS riêng.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng Lambda cho webhook, xử lý sự kiện, API thất thường; dùng ECS cho daemon, worker dài, ứng dụng cần giữ kết nối và bộ nhớ lớn.</li><li><strong>Lỗi phổ biến:</strong> chọn theo sở thích thay vì theo hình dạng workload; nhồi mọi thứ vào Lambda rồi vá timeout bằng cách tăng giới hạn.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu API từ thất thường thành ổn định cao, bạn chuyển sang container để tận dụng giá tài nguyên đặt trước; nếu worker dài tách được thành nhiều bước ngắn qua hàng đợi, bạn chuyển dần sang Lambda để khỏi nuôi máy chờ việc.</p>',
code: null,
expected: null,
followups: [
{q: 'Dấu hiệu nào cho thấy bạn đang ép sai workload vào Lambda?', a: 'Dấu hiệu rõ nhất là hàm thường xuyên chạy sát timeout và bạn chỉ còn cách tăng giới hạn thay vì xử lý nhanh hơn. Tiếp theo là chi phí tăng vọt vì hàm chạy lâu với bộ nhớ lớn trong khi container luôn bật lại rẻ hơn. Các triệu chứng khác gồm retry hỗn loạn vì tác vụ dài bị cắt giữa chừng và mã đầy logic chia nhỏ tạm bợ. Khi thấy ba dấu hiệu này, bạn tách tác vụ dài sang container thay vì tiếp tục vá Lambda.'},
{q: 'Khi nào bạn chạy cả hai trong cùng một hệ thống?', a: 'Bạn chạy cả hai khi hệ thống có nhiều hình dạng workload khác nhau, ví dụ API thất thường hứng request bằng Lambda rồi đẩy job nặng vào hàng đợi cho container ECS xử lý. Lambda lo phần co giãn nhanh ở cửa, container lo phần chạy bền ở hậu trường, hai bên giao tiếp qua hàng đợi và sự kiện. Cách này mỗi bên làm đúng việc mình giỏi thay vì ép một bên gánh cả hai. Điều kiện là bạn vẽ ranh giới rõ ràng theo thời gian chạy và trạng thái, không để logic nhảy qua lại tùy tiện.'}
],
pitfalls: ['Chọn công nghệ theo sở thích thay vì theo thời gian chạy, trạng thái và hình dạng lưu lượng', 'Nhồi tác vụ dài vào Lambda rồi vá bằng cách tăng timeout thay vì chuyển sang container'],
selfcheck: ['Tôi vẫn chưa giải thích được mô hình trả tiền theo lần gọi của Lambda khác gì trả tiền giữ tài nguyên của container', 'Tôi có thể giải thích bằng ví dụ API thất thường chạy Lambda còn job encode hàng giờ chạy ECS', 'Tôi có thể đề xuất Lambda hay ECS cho một workload mới dựa trên thời gian chạy và lưu lượng của nó'],
refs: ['aws-ecs', 'aws-lambda-best']
},
{
id: 'G17',
group: 'G',
topic: 'IaC và CloudFormation: giá trị, quy trình, rollback',
prio: 'P1',
level: 'L2',
type: 'situation',
q: 'Một đội đang cấu hình AWS bằng tay trên bảng điều khiển và hay gặp sự cố lệch môi trường. Bạn thuyết phục họ dùng IaC với CloudFormation thế nào, gồm quy trình và rollback?',
oral: 'Vấn đề của cấu hình tay là không ai biết môi trường đang có gì, dev chạy được mà production sập vì thiếu một quyền ai đó quên mở. IaC biến hạ tầng thành mã được version như mã ứng dụng, mọi thay đổi đều qua review và ai cũng xem được lịch sử ai đổi gì khi nào. Quy trình chuẩn là viết mẫu khai báo tài nguyên, review như review mã, triển khai thử ở môi trường kiểm thử rồi mới áp lên production theo từng bước có kiểm tra. Khi triển khai lỗi, CloudFormation tự rollback về trạng thái ổn định trước đó thay vì để môi trường kẹt nửa chừng. Nhờ vậy môi trường nào cũng dựng lại giống hệt nhau từ cùng một mã, sự cố lệch môi trường gần như biến mất.',
deep: '<p><strong>Đó là gì:</strong> <code>IaC</code> là quản lý hạ tầng bằng mã thay vì thao tác tay, <code>CloudFormation</code> là dịch vụ IaC khai báo nơi bạn mô tả trạng thái mong muốn và nền tảng tự đưa hạ tầng về đúng trạng thái đó. <code>Rollback</code> là tự quay về trạng thái ổn định trước đó khi triển khai thất bại.</p><p><strong>Cơ chế hoạt động:</strong> bạn viết mẫu mô tả tài nguyên cần có, nền tảng so sánh với thực tế rồi tạo, sửa hoặc xóa theo đúng chênh lệch. Mỗi lần triển khai sinh một bản ghi thay đổi có thể xem trước, áp dụng xong thì trạng thái mới thành mốc để rollback lần sau. Mọi môi trường đều dựng từ cùng một mẫu nên giống hệt nhau trừ các tham số bạn cố tình tách riêng.</p><p><strong>Vì sao cần:</strong> cấu hình tay không review được, không version được và không dựng lại được, người nghỉ việc mang theo cả kiến thức hạ tầng. IaC đưa hạ tầng vào cùng kỷ luật với mã ứng dụng nên sai sót giảm mạnh và onboarding người mới nhanh hơn nhiều.</p><ul><li><strong>Tình huống cụ thể:</strong> thêm một hàng đợi mới bằng cách thêm chục dòng vào mẫu, review, triển khai kiểm thử rồi production, lỗi thì rollback tự động trong vài phút.</li><li><strong>Khi nào dùng và khi nào không:</strong> dùng IaC cho mọi tài nguyên production và kiểm thử; chỉ thao tác tay cho thử nghiệm dùng một lần rồi xóa ngay.</li><li><strong>Lỗi phổ biến:</strong> vừa dùng IaC vừa sửa tay khiến mẫu và thực tế lệch nhau; nhồi mọi môi trường vào một mẫu khổng lồ không tách tham số.</li></ul><p><strong>Khi điều kiện thay đổi:</strong> nếu hệ thống lớn dần, bạn tách mẫu thành nhiều stack nhỏ theo ranh giới dịch vụ để một lỗi không chặn cả hệ thống; nếu cần triển khai không gián đoạn, bạn áp theo từng đợt kèm kiểm tra sức khỏe giữa các đợt thay vì đổi một lần toàn bộ.</p>',
code: 'AWSTemplateFormatVersion: "2010-09-09"\nDescription: Order queue stack\nResources:\n  OrderQueue:\n    Type: AWS::SQS::Queue\n    Properties:\n      VisibilityTimeout: 60\n      RedrivePolicy:\n        deadLetterTargetArn: !GetAtt OrderDLQ.Arn\n        maxReceiveCount: 5\n  OrderDLQ:\n    Type: AWS::SQS::Queue\n    Properties:\n      QueueName: orders-dlq\n',
expected: null,
followups: [
{q: 'Vì sao vừa dùng IaC vừa sửa tay là thói quen nguy hiểm nhất?', a: 'Sửa tay khiến thực tế lệch khỏi mẫu mà không ai ghi lại, lần triển khai IaC tiếp theo hoặc ghi đè mất chỗ sửa tay gây sập, hoặc bị kẹt vì thực tế không còn như mẫu tưởng. Đội rơi vào vòng nghi ngờ lẫn nhau vì không biết đâu mới là sự thật. Quy tắc là mọi thay đổi bền vững đều đi qua mã, thao tác tay chỉ cho thử nghiệm dùng một lần. Nếu buộc phải sửa tay lúc cháy, bạn phải cập nhật ngược vào mẫu ngay sau sự cố.'},
{q: 'Bạn chia stack thế nào khi hệ thống lớn dần?', a: 'Bạn tách theo ranh giới dịch vụ và vòng đời thay đổi, ví dụ mạng riêng một stack ít đổi, hàng đợi và hàm một stack đổi thường xuyên. Stack nhỏ giúp triển khai nhanh, lỗi một chỗ không chặn cả hệ thống và rollback gọn trong phạm vi hẹp. Bạn xuất các giá trị cần chia sẻ giữa các stack qua tham chiếu tường minh thay vì ghi cứng. Khi tách, bạn giữ mỗi stack đủ nhỏ để một người hiểu hết trong một buổi.'}
],
pitfalls: ['Vừa dùng IaC vừa sửa tay khiến mẫu và thực tế lệch nhau rồi lần triển khai sau ghi đè gây sập', 'Nhồi mọi môi trường và mọi dịch vụ vào một mẫu khổng lồ khiến triển khai chậm và rollback rủi ro'],
selfcheck: ['Tôi vẫn chưa giải thích được CloudFormation so sánh mẫu với thực tế và rollback từng bước thế nào', 'Tôi có thể giải thích bằng ví dụ thêm hàng đợi kèm DLQ qua mẫu và rollback tự động khi lỗi', 'Tôi có thể viết một mẫu CloudFormation cho hàng đợi và hàm của một dịch vụ nhỏ'],
refs: ['aws-cfn']
}
);
