var QUESTIONS = QUESTIONS || [];
QUESTIONS.push(
{
id: 'H01',
group: 'H',
topic: 'Image và container',
prio: 'P0',
level: 'L1',
type: 'concept',
attacks: [{"q":"Image và container khác nhau thế nào, và vì sao điều đó quan trọng khi gỡ lỗi?","a":"Image là bản mẫu chỉ đọc gồm các lớp hệ thống tệp cùng metadata; container là một thực thể đang chạy được tạo từ image, có thêm một lớp ghi riêng. Điều này quan trọng khi gỡ lỗi vì mọi thay đổi bạn làm bên trong container đang chạy chỉ nằm ở lớp ghi đó và mất khi container bị xoá — nên nếu bạn sửa file trong container để thử nghiệm rồi khởi động lại, thay đổi biến mất. Hệ quả thực tế là không bao giờ được sửa trực tiếp trong container đang chạy để khắc phục sự cố; mọi thay đổi phải đi vào image và được triển khai lại, nếu không lần sau sự cố sẽ tái diễn và không ai biết vì sao bản sửa đã mất."},{"q":"Vì sao cùng một image chạy tốt trên máy bạn nhưng lỗi trên máy chủ?","a":"Vì image chỉ đóng gói hệ thống tệp và cấu hình của nó, không đóng gói nhân hệ điều hành. Container dùng chung nhân của máy chủ, nên khác biệt về phiên bản nhân, kiến trúc CPU, hoặc các tính năng nhân được bật sẽ tạo ra khác biệt hành vi. Ngoài ra những gì bạn gắn từ ngoài vào — biến môi trường, volume, cấu hình mạng — không nằm trong image, nên thiếu hoặc khác chúng cũng gây lỗi. Cách chẩn đoán là so sánh ba nhóm này giữa hai môi trường, thay vì tìm lỗi trong mã nguồn vì mã nguồn là phần giống nhau."}],
incident: '<p>Tình huống giả định: 23h40 thứ Ba, bạn xóa container <code>web-a</code> trên máy local để chạy lại. Ba đồng nghiệp khác vẫn trỏ vào cùng image và giả định container còn đó. Mười phút sau, đồng nghiệp báo dashboard trống vì container của anh chưa restart được. Log chỉ hiện một dòng: <code>No such container: web-a</code>. Bạn cố xóa image bằng <code>docker rmi</code> thì nhận conflict.</p>',
askFirst: [
  'Vì sao người khác bị ảnh hưởng khi bạn xóa container của mình?',
  'Xóa container khác gì xóa image?'
],
predict: { q: 'Bạn đoán kết quả của docker rmi webapp:1.2 khi còn container tham chiếu image đó?', a: '<p>Docker báo conflict vì layer chỉ đọc của image nằm trong layer store dùng chung. Xóa container chỉ bỏ lớp đọc ghi mỏng và metadata, còn image giữ nguyên trong layer store. <code>docker rmi</code> bị chặn khi còn container tham chiếu, kể cả container đã dừng.</p>' },
anchor: 'Container là lớp đọc ghi trên image bất biến mà không có ràng buộc giữ layer store = xóa container chỉ mất trạng thái, không mất image.',
q: 'Hãy phân biệt Docker image và container, và giải thích vì sao xóa container không làm mất image?',
oral: 'Image là mẫu chỉ đọc gồm các layer xếp chồng, chứa hệ điều hành gọn nhẹ, thư viện và mã nguồn của bạn. Container là một tiến trình đang chạy được tạo ra từ image, cộng thêm một lớp đọc ghi mỏng bên trên. Khi bạn xóa container, bạn chỉ xóa lớp đọc ghi đó và tiến trình đi kèm, còn image gốc vẫn nằm trong bộ nhớ cục bộ. Nhờ vậy bạn có thể tạo lại container mới từ cùng một image bất cứ lúc nào, và nhiều container có thể cùng chạy từ một image mà không ảnh hưởng lẫn nhau.',
deep: '<p>Trước container, mỗi microservice chạy trên một VM: khởi động mất vài phút, patch kernel thủ công, muốn nhân thêm bản sao là chờ hạ tầng. Khi một team chạy hàng chục bản sao cùng host, mô hình đó không theo kịp. Container đóng gói bộ tệp và chạy song song trên kernel cùng host.</p><p>Image là tập layer chỉ đọc tạo khi build; khi chạy, Docker đặt một lớp đọc ghi mỏng trên top kèm namespace và cgroup riêng. Mọi ghi file khi chạy nằm ở lớp mỏng này. Xóa container bằng <code>docker rm</code> chỉ xóa lớp ghi đó và metadata, các layer image nằm trong layer store dùng chung nên vẫn còn trừ khi <code>docker rmi</code> xóa hẳn.</p><p>Thói quen cũ là sửa file trực tiếp trong container rồi kỳ vọng nó tồn tại; chính cơ chế đó khiến recreate xóa mất sửa đổi. Muốn dữ liệu tồn tại qua vòng đời container, phải gắn volume hoặc đẩy ra database và object storage. Ví dụ, build <code>webapp:1.2</code> một lần, chạy <code>web-a</code> và <code>web-b</code> với biến môi trường khác nhau.</p><p>Người phỏng vấn cần nói được: xóa container không mất image vì image nằm trong layer store dùng chung; dữ liệu trong container không hứa tồn tại nên phải gắn volume; cùng một image chạy được nhiều container song song. Lỗi phổ biến là team tưởng mất dữ liệu do image.</p>',
code: 'docker images\ndocker build -t webapp:1.2 .\ndocker run -d --name web-a -p 8080:8000 webapp:1.2\ndocker ps -a\ndocker rm web-a\ndocker images',
expected: 'Lần docker images đầu liệt kê các image đang có sẵn (có thể rỗng); sau docker build -t webapp:1.2 thì lần docker images cuối phải có thêm một dòng với REPOSITORY webapp, TAG 1.2, kèm IMAGE ID 12 ký tự và SIZE. docker run -d in ra container ID đầy đủ 64 ký tự rồi trả quyền ngay vì chạy nền, docker ps -a hiện web-a ở trạng thái Up ... với cột PORTS là 0.0.0.0:8080->8000/tcp. Điểm dễ sai nằm ở docker rm web-a: trên container ĐANG chạy lệnh này lỗi với thông báo You cannot remove a running container, hãy Stop the container before attempting removal or force remove, nên chuỗi lệnh như đề bài chưa xóa được gì; muốn xóa phải docker stop web-a rồi docker rm web-a, hoặc docker rm -f. Phân tích: docker rm chỉ xóa lớp đọc ghi mỏng (writable layer) và metadata của container, còn các layer chỉ đọc của image nằm trong layer store dùng chung giữa mọi container và chỉ bị xóa bởi docker rmi; chính docker rmi cũng từ chối khi còn container tham chiếu image (kể cả container đã dừng), báo lỗi conflict vì image đang bị container tham chiếu. Đó là lý do xóa container không làm mất image, và cũng là lý do dữ liệu ghi trong container biến mất cùng lớp mỏng đó. Lệnh chứng minh: docker images --digests và docker rmi webapp:1.2 (khi container còn tồn tại sẽ báo conflict). Lưu ý: toàn bộ mô tả trên là hành vi theo tài liệu Docker, không phải kết quả chạy trên máy này.',
followups: [
{q: 'Layer trong image hoạt động thế nào khi hai image dùng chung base?', a: 'Các layer được định danh bằng digest và được dùng chung giữa các image. Khi hai image cùng dùng một base, Docker chỉ lưu base một lần và mỗi image chỉ thêm các layer riêng phía trên, giúp tiết kiệm đĩa và tăng tốc kéo image.'},
{q: 'Dữ liệu ghi trong container đi đâu khi xóa container?', a: 'Dữ liệu ghi vào lớp đọc ghi mỏng của container sẽ mất khi xóa container. Muốn giữ lại lâu dài, bạn phải gắn volume hoặc bind mount ra ngoài, hoặc đẩy dữ liệu lên cơ sở dữ liệu và object storage.'},
{q: 'Khi nào bạn dùng tag image và digest?', a: 'Tag giúp con người đọc phiên bản như 1.2 hay latest, còn digest là mã băm bất biến của nội dung image. Khi triển khai production, bạn nên chốt digest để bảo đảm đúng image đã kiểm thử, tránh việc tag bị ghi đè.'}
],
pitfalls: ['Nhầm lẫn xóa container với xóa image, rồi ngạc nhiên vì đĩa vẫn đầy do image còn lại', 'Lưu dữ liệu quan trọng trong container rồi mất khi recreate'],
selfcheck: ['Tôi vẫn chưa giải thích được union filesystem gộp các layer chỉ đọc thành một gốc rễ duy nhất thế nào', 'Tôi có thể giải thích bằng ví dụ một image dùng chung cho hai container chạy song song với biến môi trường khác nhau', 'Tôi có thể liệt kê image đang chiếm đĩa và dọn container đã dừng trên máy dev mà không xóa nhầm image production'],
refs: ['dockerfile-ref']
},
{
id: 'H02',
group: 'H',
topic: 'Dockerfile layer và build cache',
prio: 'P0',
level: 'L2',
type: 'predict',
attacks: [{"q":"Vì sao đổi thứ tự các lệnh trong Dockerfile lại ảnh hưởng lớn tới thời gian build?","a":"Vì mỗi lệnh tạo một lớp, và bộ đệm được dùng lại theo tiền tố: khi một lớp thay đổi, mọi lớp sau nó đều phải dựng lại. Nếu bạn sao chép toàn bộ mã nguồn rồi mới cài phụ thuộc, thì mỗi lần sửa một dòng mã, lớp sao chép đổi và toàn bộ bước cài phụ thuộc chạy lại từ đầu — có thể mất nhiều phút. Đảo lại, sao chép tệp khai báo phụ thuộc trước, cài phụ thuộc, rồi mới sao chép mã nguồn, thì bước cài phụ thuộc chỉ chạy lại khi danh sách phụ thuộc thật sự đổi."},{"q":"Bộ đệm build bị vô hiệu ngoài ý muốn vì những nguyên nhân nào?","a":"Bốn nguyên nhân phổ biến. Một là tệp trong ngữ cảnh build bị thay đổi khi bạn dùng COPY toàn bộ ngữ cảnh (ví dụ <code>COPY . .</code>), như tệp log hoặc thư mục cache không được loại trừ bằng .dockerignore; nếu chỉ COPY từng tệp cụ thể thì tệp không sao chép vào không ảnh hưởng tới cache của layer đó. Hai là lệnh cài đặt phụ thuộc không ghim phiên bản, nên mỗi lần chạy có thể lấy phiên bản mới và tạo ra lớp khác. Ba là dùng ảnh nền theo thẻ động, nên khi ảnh nền được cập nhật thì lớp đầu tiên đổi và mọi thứ sau đó dựng lại. Bốn là thay đổi quyền hoặc dấu thời gian của tệp, vì nội dung có thể giống nhau nhưng metadata khác."}],
incident: '<p>Tình huống giả định: Sáng thứ Tư, pipeline CI build mất 14 phút thay vì 2 phút trước đó. Dev A báo chỉ đổi một dòng trong <code>app.py</code>, không đổi <code>requirements.txt</code>. Đồng nghiệp B xem log: toàn bộ bước <code>pip install</code> chạy lại từ đầu. 40 dev trong team bị kẹt chờ release đến 15h.</p>',
askFirst: [
  'Docker sẽ build lại từ layer nào khi chỉ có app.py đổi?',
  'Vì sao thứ tự COPY và RUN trong Dockerfile quyết định tốc độ build?'
],
predict: { q: 'Bạn đoán điều gì xảy ra khi bỏ requirements.txt vào cùng layer với COPY mã nguồn?', a: '<p>Mọi lần sửa code đều phá cache của layer chứa mã nguồn và kéo theo bước <code>pip install</code> phía sau, vì đầu vào của layer đó đổi. Cách đúng là tách <code>COPY requirements.txt</code> và <code>RUN pip install</code> lên trước, đặt <code>COPY . .</code> xuống sau, để sửa code chỉ build lại hai layer cuối.</p>' },
anchor: 'Build cache so checksum đầu vào từng layer mà không có layer tách bước ít đổi = một dòng code đổi cũng cài lại mọi thư viện.',
q: 'Với Dockerfile dưới đây, khi bạn chỉ sửa mã nguồn mà không đổi requirements, Docker sẽ build lại từ layer nào và vì sao?',
oral: 'Docker build từng chỉ thị thành từng layer và lưu cache theo thứ tự. Layer nào không đổi thì dùng lại cache, layer đầu tiên có thay đổi và mọi layer sau nó phải build lại. Vì vậy thứ tự sao chép file quyết định tốc độ build. Bạn nên sao chép file phụ thuộc và cài đặt trước, sao chép mã nguồn hay đổi sau. Sửa mã nguồn mà không chạm tới requirements thì Docker dùng lại cache tới bước cài đặt, chỉ build lại từ bước sao chép mã nguồn trở đi.',
deep: '<p>Trước container, build nhiều service trên cùng server dùng script và Makefile, cache nằm ngoài hệ quản trị nên khi thư viện đổi không rõ bước nào vô hiệu. Container đưa build vào từng layer chỉ đọc, Docker lưu cache theo thứ tự layer: layer nào đổi, layer đó và mọi layer phía sau phải chạy lại.</p><p>Áp lực đến từ CI. Mỗi lần merge, <code>pip install</code> chạy lại vì <code>requirements.txt</code> và mã nguồn cùng layer. Sửa một dòng <code>app.py</code> cũng kéo theo cài lại mọi thư viện. Cách hiện đại là đổi thứ tự chỉ thị: <code>COPY requirements.txt</code>, <code>RUN pip install</code>, rồi <code>COPY . .</code>. Khi file phụ thuộc không đổi, bước cài đặt trúng cache; khi đổi, chỉ cài lại theo danh sách mới.</p><p>Hôm nay dùng <code>docker build --progress=plain</code> để xem layer nào chạy lại, <code>.dockerignore</code> để log và cache không làm đổi checksum ngữ cảnh, và BuildKit cache mount để giữ thư viện giữa các lần build. Chỗ còn sai là Dockerfile đặt <code>COPY . .</code> trước khi cài phụ thuộc, khiến cache bị vô hiệu mỗi lần dev sửa code.</p><p>Người phỏng vấn cần nói được: build cache so đầu vào theo layer và theo tiền tố; thứ tự COPY quyết định tốc độ; tách file phụ thuộc trước, mã nguồn sau là quy tắc tối ưu. Lỗi phổ biến nhất là không tách layer, làm CI chờ lại toàn bộ bước cài đặt.</p>',
code: 'FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["python", "app.py"]',
expected: 'Docker dùng lại cache từ FROM tới hết RUN cài đặt, và build lại từ COPY . . trở đi. Nguyên nhân là requirements.txt không đổi nên checksum đầu vào của các layer trên giữ nguyên, còn layer COPY . . thấy mã nguồn đổi nên hỏng cache, kéo theo CMD phía sau phải tạo lại.',
followups: [
{q: 'Vì sao thêm .dockerignore lại tăng tỉ lệ trúng cache?', a: 'Vì ngữ cảnh build gửi sang daemon gồm mọi file không bị loại trừ. Nếu không loại trừ thư mục log hay cache, checksum ngữ cảnh đổi liên tục và layer COPY bị coi là đổi dù mã nguồn không đổi. Loại trừ đúng giúp cache ổn định.'},
{q: 'Khi nào bạn dùng --no-cache hoặc build nhiều tầng để xử lý cache?', a: 'Bạn dùng --no-cache khi nghi cache cũ che lỗi như gói bị xóa khỏi kho. Bạn dùng nhiều tầng hoặc cache mount để giữ cache trình quản lý gói giữa các lần build mà không phình image cuối.'},
{q: 'Thứ tự nào tối ưu cho dự án Python và Node?', a: 'Bạn sao chép file khai báo phụ thuộc trước, cài đặt, rồi mới sao chép mã nguồn. Với Node bạn sao chép package lock trước rồi chạy cài đặt, với Python bạn sao chép requirements trước rồi cài, để sửa code không cài lại thư viện.'}
],
pitfalls: ['Sao chép toàn bộ mã nguồn ngay dòng đầu nên build lại luôn chậm', 'Nghĩ cache dựa trên thời gian file, trong khi Docker dựa trên nội dung và lệnh'],
selfcheck: ['Tôi vẫn chưa giải thích được Docker tính checksum cho lệnh COPY nhiều file và phân biệt cache miss do file nào', 'Tôi có thể giải thích bằng ví dụ sửa app.py mà không cài lại requirements nhờ tách layer', 'Tôi có thể sắp xếp lại một Dockerfile thực tế để build lại sau khi sửa code chỉ còn vài giây'],
refs: ['dockerfile-ref', 'docker-multi-stage']
},
{
id: 'H03',
group: 'H',
topic: 'Multi-stage build',
prio: 'P0',
level: 'L2',
type: 'concept',
attacks: [{"q":"Multi-stage build có làm thời gian build lâu hơn không?","a":"Có thể lâu hơn, vì bạn thêm các bước dựng ở giai đoạn đầu, nhưng thời gian đó thường được trả lại ở những lần sau nhờ bộ đệm, và bù lại bằng thời gian tải và khởi động nhanh hơn ở mọi lần chạy. Điều quan trọng hơn là chất lượng của kết quả: image nhỏ hơn nghĩa là ít gói hơn, nên ít lỗ hổng hơn và ít công cụ hơn cho kẻ tấn công. Với hệ thống triển khai thường xuyên, việc tối ưu theo thời gian tải và khởi động thường đáng giá hơn thời gian build, vì build chạy một lần còn tải chạy ở mọi bản sao."},{"q":"Có trường hợp nào multi-stage không giúp ích gì?","a":"Có. Nếu ngôn ngữ hoặc công cụ không tạo ra phần phụ thuộc chỉ dùng lúc build — ví dụ một ứng dụng chỉ gồm các tệp văn bản và một máy chủ đã có sẵn trong ảnh nền — thì giai đoạn dựng thêm không loại bỏ được gì. Nó cũng ít giá trị khi ảnh nền đã rất tối giản và mọi gói cài đặt đều cần thiết lúc chạy. Điểm cần nói rõ là multi-stage là một kỹ thuật để loại bỏ thứ không cần thiết, nên nó chỉ có giá trị khi thực sự tồn tại thứ như vậy — còn thêm nó như một thói quen thì chỉ làm tệp cấu hình dài hơn."}],
incident: '<p>Tình huống giả định: 1h30 đêm Chủ Nhật, cảnh báo Chi phí cloud tăng gấp ba. Dev C kiểm tra: image production <code>api:2.4</code> nặng 1.9 GB vì Dockerfile một tầng kéo theo trình biên dịch C, <code>git</code> và <code>gcc</code>. Mỗi lần scale-out thêm replica phải kéo 1.9 GB, mất 6 phút khởi động lại sau crash. Team Ops chờ 20 phút để khôi phục toàn bộ dịch vụ thanh toán.</p>',
askFirst: [
  'Làm sao giữ image production nhỏ mà vẫn compile được code?',
  'Vì sao stage builder chứa compiler không nên đưa vào image cuối?'
],
predict: { q: 'Bạn đoán stage builder (image python đầy đủ) chiếm phần dung lượng nào của image cuối nếu không dùng multi-stage?', a: '<p>Tất cả: trình biên dịch, git, gcc, cache pip và mã nguồn build đều nằm trong layer chỉ đọc của image xuất ra. Multi-stage chỉ <code>COPY --from=builder</code> sản phẩm thành phẩm sang image runtime slim, nên các layer trung gian không xuất hiện trong image cuối.</p>' },
anchor: 'Image build một tầng mà không có stage tách sản phẩm thành phẩm = compiler và git nằm trong image production, kéo dài thời gian scale-out và phình bề mặt tấn công.',
q: 'Multi-stage build trong Dockerfile là gì và vì sao nó giúp image production nhỏ và an toàn hơn?',
oral: 'Multi-stage build cho phép bạn viết nhiều khối FROM trong một Dockerfile, khối đầu dùng image lớn để biên dịch và cài đặt, khối cuối chỉ sao chép sản phẩm cần chạy. Image cuối không chứa trình biên dịch, mã nguồn hay cache, nên nhỏ hơn nhiều, khởi động nhanh hơn và ít lỗ hổng hơn. Bạn vẫn chỉ cần một file Dockerfile duy nhất, không phải chia nhiều file hay sao chép thủ công giữa các bước.',
deep: '<p>Trước multi-stage, Dockerfile một tầng đưa cả compiler, git, cache trình biên dịch và mã nguồn build vào image production. Scale-out kéo toàn bộ dung lượng đó, và mỗi package thừa là một bề mặt tấn công. Áp lực là chi phí băng thông, thời gian khởi động lại sau crash, và audit bảo mật phình theo image.</p><p>Multi-stage cho phép nhiều <code>FROM</code> trong một Dockerfile. Stage builder dùng image đầy đủ để compile và cài phụ thuộc; stage runtime chỉ nhận sản phẩm thành phẩm qua <code>COPY --from=builder</code>, nên các layer trung gian không xuất hiện trong image đẩy lên registry. Ví dụ: <code>FROM python:3.12 AS builder</code> chạy <code>pip install --prefix=/pkg</code>, rồi <code>FROM python:3.12-slim</code> và <code>COPY --from=builder /pkg /usr/local</code>.</p><p>Chỗ vẫn còn sai: team copy cả <code>src</code>, <code>requirements.txt</code> và cache pip sang stage runtime; hoặc nhét secret vào <code>ARG</code> rồi tưởng image cuối sạch, trong khi lịch sử build vẫn giữ. Multi-stage không tự bảo đảm nhỏ: nó chỉ loại bỏ những gì bạn không <code>COPY --from</code> sang stage cuối.</p><p>Người phỏng vấn cần nói được: chỉ stage cuối mới xuất ra image; image nhỏ giúp khởi động nhanh và giảm bề mặt tấn công. Lỗi phổ biến là copy thừa tệp hoặc tin image cuối tự sạch vì builder tách riêng.</p>',
code: 'FROM python:3.12 AS builder\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --prefix=/pkg --no-cache-dir -r requirements.txt\nFROM python:3.12-slim\nWORKDIR /app\nCOPY --from=builder /pkg /usr/local\nCOPY app.py .\nCMD ["python", "app.py"]',
expected: 'Kết quả build: chỉ stage CUỐI trở thành image xuất ra, nên image cuối gồm base python:3.12-slim cộng các layer do WORKDIR, COPY --from=builder /pkg /usr/local và COPY app.py ., không có layer nào của stage builder (image python:3.12 đầy đủ, pip, wheel, cache pip và requirements.txt đều bị bỏ lại). Phân tích: COPY --from=builder chỉ sao chép nội dung thư mục /pkg; pip install --prefix=/pkg đặt gói vào /pkg/lib/python3.12/site-packages và script vào /pkg/bin, khi đổ vào /usr/local thì thành /usr/local/lib/python3.12/site-packages và /usr/local/bin, đúng vị trí mà interpreter của image chính thức tìm kiếm (image python chính thức cài Python dưới /usr/local), nên import chạy được mà không cài lại. Nhờ vậy image cuối nhỏ hơn nhiều so với image đầy đủ (dung lượng cụ thể tùy runtime, kiểm tra bằng docker images) và ít bề mặt tấn công vì không còn trình biên dịch, không còn pip cache do --no-cache-dir. Các layer trung gian của stage builder vẫn nằm trong build cache cục bộ của daemon và chỉ bị dọn bằng docker builder prune hoặc build với --no-cache, nhưng chúng không được đưa vào image push lên registry. Số layer chính xác phụ thuộc builder (classic so với BuildKit) nên không thể đếm chắc nếu không chạy. CMD ở dạng exec nên python là PID 1 và nhận trực tiếp SIGTERM. Lệnh chứng minh: docker history --no-trunc của image cuối, docker image inspect để so Size với image builder, và docker build --target builder để dừng ở stage builder. Lưu ý: toàn bộ mô tả trên là hành vi theo tài liệu Docker, không phải kết quả chạy trên máy này.',
followups: [
{q: 'Multi-stage khác gì việc viết hai Dockerfile riêng?', a: 'Multi-stage giữ toàn bộ quy trình trong một file và một lần build, Docker tự quản lý layer trung gian. Hai file riêng buộc bạn tự build, gắn tag trung gian và sao chép thủ công, dễ lệch phiên bản và khó dùng cache trên CI.'},
{q: 'Làm sao tránh lộ secret trong giai đoạn build?', a: 'Bạn không nên truyền secret qua ARG vì nó nằm trong lịch sử image. Bạn nên dùng secret mount lúc build hoặc biến môi trường của CI, và bảo đảm giai đoạn cuối không sao chép file chứa secret.'},
{q: 'Khi nào image nhỏ lại quan trọng nhất?', a: 'Khi bạn mở rộng nhanh nhiều bản sao, triển khai lên môi trường băng thông hẹp, hoặc chạy serverless và edge tính tiền theo dung lượng. Image nhỏ giúp khởi động nhanh và giảm thời gian phục hồi sự cố.'}
],
pitfalls: ['Sao chép thừa mã nguồn và công cụ build sang image cuối nên image vẫn phình', 'Nhúng secret vào layer builder rồi nghĩ image cuối an toàn, trong khi lịch sử vẫn giữ'],
selfcheck: ['Tôi vẫn chưa giải thích được Docker có giữ lại layer trung gian trên đĩa build và dọn chúng thế nào', 'Tôi có thể giải thích bằng ví dụ builder cài phụ thuộc rồi chỉ sao chép gói sang image slim', 'Tôi có thể viết lại một Dockerfile một tầng thành hai tầng để giảm dung lượng image thực tế'],
refs: ['docker-multi-stage', 'dockerfile-ref']
},
{
id: 'H04',
group: 'H',
topic: 'Port, biến môi trường, volume, mạng và Compose',
prio: 'P1',
level: 'L2',
type: 'concept',
incident: "<p>Tình huống giả định: Một đội dùng Docker Compose cho môi trường phát triển. Ứng dụng đọc chuỗi kết nối database từ biến môi trường, nhưng biến đó chỉ được đặt trong <code>docker-compose.yml</code> ở máy của một người. Ba thành viên khác chạy lên và nhận lỗi kết nối. Ngoài ra, dữ liệu database biến mất sau mỗi lần chạy <code>down</code> vì không có volume, nên mỗi người phải tạo lại dữ liệu mẫu.</p>",
askFirst: ["Biến môi trường của một service đến từ những nguồn nào?","Dữ liệu trong container mất khi nào?","Làm sao để một service nói chuyện được với service khác trong Compose?"],
predict: {"q":"Hai service trong cùng một file Compose, service A gọi service B qua <code>localhost:5432</code>. Kết nối có thành công không?","a":"<p>Không. Mỗi service chạy trong không gian mạng riêng, nên <code>localhost</code> bên trong A trỏ tới chính A chứ không tới B. Compose tạo một mạng chung và đăng ký tên service như tên máy, nên A phải gọi <code>b:5432</code>. Đây là lỗi phổ biến nhất khi mới dùng Compose, và nó cũng giải thích một hiện tượng liên quan: khi chạy ứng dụng trực tiếp trên máy chủ thay vì trong container, <code>localhost</code> lại đúng — nên cùng một chuỗi kết nối có thể chạy được ở chế độ này và hỏng ở chế độ kia.</p>"},
anchor: "Mỗi container có không gian mạng riêng nên localhost luôn trỏ về chính nó; muốn gọi service khác phải dùng tên service trên mạng chung.",
attacks: [{"q":"Khi nào dùng volume, khi nào dùng bind mount?","a":"Bind mount gắn một đường dẫn trên máy chủ vào container, nên thay đổi ở máy chủ hiện ra ngay trong container — phù hợp cho mã nguồn khi phát triển, vì bạn muốn sửa file và thấy kết quả ngay. Volume do Docker quản lý và nằm trong vùng lưu trữ của nó, phù hợp cho dữ liệu cần tồn tại qua các lần chạy — database, hàng đợi, tệp tải lên. Điểm cần nhớ là dữ liệu trong lớp ghi của container mất khi container bị xoá, nên bất cứ thứ gì bạn muốn giữ đều phải nằm trong volume hoặc bind mount."},{"q":"Làm sao quản lý cấu hình cho nhiều môi trường mà không lặp lại?","a":"Tách cấu hình chung khỏi cấu hình theo môi trường. File Compose chính chứa những gì giống nhau ở mọi nơi, và các file phụ chỉ ghi đè phần khác biệt — cách này giữ cho mỗi file nhỏ và dễ đọc. Với giá trị nhạy cảm, dùng file biến môi trường không được đưa vào kho mã nguồn, và trong môi trường thật thì lấy từ kho secret của hạ tầng. Điều nên tránh là nhân bản toàn bộ file cho mỗi môi trường, vì chúng sẽ trôi khỏi nhau và không ai biết file nào là đúng."}],
q: 'Hãy giải thích port mapping, biến môi trường, volume và network trong Docker Compose qua một ví dụ web và database.',
oral: 'Port mapping nối cổng máy host với cổng trong container để bạn truy cập từ ngoài. Biến môi trường truyền cấu hình như tên database mà không cần sửa code. Volume lưu dữ liệu ra ngoài vòng đời container nên database không mất khi recreate. Network nội bộ cho các service gọi nhau bằng tên service thay vì địa chỉ IP. Compose gom bốn thứ này vào một file duy nhất để chỉ cần một lệnh là dựng cả cụm.',
deep: '<p>Trước Compose, chạy một stack web và database nghĩa là nhớ IP, sửa chuỗi kết nối tay trên từng môi trường và cầu mong dữ liệu database sống qua recreate. Khi microservice chia nhỏ, <code>localhost</code> trong container không còn chỉ về host, nên đội kẹt với chuỗi kết nối đúng trên máy dev nhưng sai trong container.</p><p>Compose gom bốn cơ chế vào một file: mạng project đăng ký tên service như tên máy, service khác gọi bằng tên thay vì IP; port mapping nối cổng host và container theo cặp; biến môi trường truyền cấu hình vào tiến trình; volume đặt dữ liệu ngoài vòng đời container. Cùng một image chạy được ở dev và production chỉ bằng cách đổi file Compose hoặc biến môi trường.</p><p>Chỗ vẫn còn sai: <code>depends_on</code> chỉ bảo đảm thứ tự khởi động, không bảo đảm database sẵn sàng nhận kết nối; nên cần healthcheck hoặc logic thử lại. Volume phải gắn trước khi chạy, không phải chỉ khai báo trong file rồi tưởng Docker tự tạo và giữ lại.</p><p>Người phỏng vấn cần nói được: gọi service khác trong Compose dùng tên, không dùng <code>localhost</code>; port mapping chỉ publish khi khai báo <code>ports</code>; dữ liệu quan trọng phải nằm trong named volume hoặc bind mount; <code>depends_on</code> không thay thế readiness.</p>',
code: 'services:\n  web:\n    build: .\n    ports:\n      - "8080:8000"\n    environment:\n      - DB_HOST=db\n      - DB_NAME=appdb\n    depends_on:\n      - db\n  db:\n    image: postgres:16\n    environment:\n      - POSTGRES_DB=appdb\n      - POSTGRES_PASSWORD=secret123\n    volumes:\n      - pgdata:/var/lib/postgresql/data\nvolumes:\n  pgdata:',
expected: 'Kết quả: docker compose up tạo network bridge tên <tên_thư_mục>_default, tạo named volume <tên_thư_mục>_pgdata, pull postgres:16, build image web rồi khởi động container db trước và web sau theo depends_on; docker compose ps hiện web với PORTS 0.0.0.0:8080->8000/tcp còn db KHÔNG có cột PORTS. Phân tích: web nối tới database qua DNS nội bộ của Docker (127.0.0.11) bằng đúng tên service, nên DB_HOST=db phân giải thành IP container db ở cổng 5432 trong mạng project; db không publish cổng nào nên từ host không kết nối được, đúng nguyên tắc không phơi database ra ngoài. Volume pgdata gắn vào /var/lib/postgresql/data nên dữ liệu nằm ngoài vòng đời container: docker compose down rồi up lại vẫn còn dữ liệu, chỉ docker compose down -v mới xóa volume. Hai cái bẫy phải nói: (1) depends_on chỉ bảo đảm THỨ TỰ khởi động chứ không chờ Postgres sẵn sàng nhận kết nối, nên web có thể chạy trước khi cổng 5432 mở và bị connection refused; muốn đúng phải thêm healthcheck cho db kèm condition: service_healthy hoặc logic retry trong ứng dụng; (2) mật khẩu ghi thẳng trong file compose (POSTGRES_PASSWORD=secret123) sẽ vào git, nên dùng env_file hoặc secret. Lưu ý POSTGRES_DB và POSTGRES_PASSWORD chỉ được dùng khi khởi tạo data directory rỗng, đổi biến này sau khi đã có dữ liệu sẽ không tạo lại database. Lệnh chứng minh: docker compose ps, docker network inspect <project>_default, docker volume ls, docker compose exec web printenv | grep DB_. Lưu ý: toàn bộ mô tả trên là hành vi theo tài liệu Docker Compose, không phải kết quả chạy trên máy này.',
followups: [
{q: 'depends_on có bảo đảm database sẵn sàng nhận kết nối không?', a: 'Không. depends_on chỉ bảo đảm thứ tự khởi động container, không chờ database sẵn sàng. Bạn cần thêm cơ chế chờ như vòng lặp kiểm tra cổng, healthcheck và logic thử lại trong ứng dụng.'},
{q: 'Khi nào dùng named volume thay vì bind mount?', a: 'Bạn dùng named volume cho dữ liệu production vì Docker quản lý, dễ sao lưu và di chuyển. Bạn dùng bind mount khi dev cần phản chiếu mã nguồn trực tiếp để sửa và chạy ngay.'}
],
pitfalls: ['Mở cổng database ra ngoài ở production rồi bị quét và tấn công', 'Lưu dữ liệu database trong container nên mất hết khi cập nhật image'],
selfcheck: ['Tôi vẫn chưa giải thích được Compose đặt tên mạng và volume theo project thế nào khi chạy nhiều project song song', 'Tôi có thể giải thích bằng ví dụ web gọi database qua tên service db trên mạng Compose mặc định', 'Tôi có thể dựng một cụm web và database bằng Compose với volume bền bỉ cho dữ liệu'],
refs: ['docker-compose']
},
{
id: 'H05',
group: 'H',
topic: 'Chạy non-root, secret và healthcheck',
prio: 'P1',
level: 'L2',
type: 'concept',
incident: "<p>Tình huống giả định: Một container chạy ứng dụng bằng người dùng root. Một lỗ hổng trong thư viện xử lý ảnh cho phép thực thi mã, và kẻ tấn công có toàn quyền trong container, bao gồm khả năng ghi vào thư mục hệ thống và đọc các biến môi trường chứa khoá API. Ngoài ra, một service khác bị đánh dấu là đang chạy khoẻ trong khi thực tế tiến trình chính đã chết từ lâu nhưng một tiến trình con vẫn giữ container sống.</p>",
askFirst: ["Vì sao chạy bằng người dùng không phải root lại quan trọng?","Healthcheck kiểm tra cái gì, và khác gì việc container còn chạy?","Khoá API nên đến từ đâu?"],
predict: {"q":"Một container có PID 1 là shell hoặc supervisor vẫn sống, còn tiến trình worker con đã chết hoặc treo. Docker báo trạng thái gì, và khi nào container thật sự dừng?","a":"<p>Docker vẫn báo container đang chạy, vì nó chỉ theo dõi PID 1, không theo dõi cây tiến trình con. Khi PID 1 thoát thì ngược lại: kernel gửi SIGKILL tới mọi tiến trình còn lại trong PID namespace và container dừng. Đây là lý do một healthcheck thật sự cần thiết: nó chủ động gọi vào ứng dụng để kiểm tra khả năng phục vụ, chứ không chỉ hỏi container còn tồn tại hay không. Điều này cũng liên quan tới việc dùng dạng exec cho lệnh khởi động, vì nếu dùng dạng shell thì tiến trình chính là shell và tín hiệu dừng không tới được ứng dụng."},
anchor: "Docker chỉ theo dõi tiến trình số một, nên \"container đang chạy\" không có nghĩa ứng dụng đang phục vụ được — cần healthcheck thật.",
attacks: [{"q":"Healthcheck nên kiểm tra gì?","a":"Nên kiểm tra khả năng phục vụ thật, ở mức đủ nhẹ để gọi thường xuyên. Với một API, một endpoint trả về nhanh và xác nhận rằng tiến trình còn xử lý được request là đủ. Cần cân nhắc có nên kiểm tra cả phụ thuộc: kiểm tra database trong healthcheck giúp phát hiện sớm nhưng cũng có thể làm toàn bộ container bị đánh dấu hỏng chỉ vì một phụ thuộc tạm thời, khiến hệ thống tự tấn công chính mình. Cách phổ biến là tách hai mức: một kiểm tra nhẹ cho vòng đời container, và một kiểm tra sâu hơn cho cảnh báo."},{"q":"Ngoài chạy non-root, còn gì cần làm để giảm thiệt hại khi bị chiếm container?","a":"Bốn việc có giá trị cao. Một là dùng hệ thống tệp chỉ đọc ở nơi có thể, và chỉ mở ghi ở những thư mục thật sự cần. Hai là bỏ hết khả năng của tiến trình mà ứng dụng không dùng, vì mặc định nhiều khả năng vẫn được cấp. Ba là không gắn socket của Docker vào container ứng dụng, vì nó tương đương quyền root trên máy chủ. Bốn là dùng ảnh nền tối giản, vì ít gói hơn nghĩa là ít lỗ hổng hơn và ít công cụ hơn cho kẻ tấn công."}],
q: 'Vì sao bạn nên chạy container dưới user non-root, quản lý secret riêng và thêm healthcheck?',
oral: 'Mặc định tiến trình trong container thường chạy dưới quyền root, nên nếu kẻ tấn công thoát được ra ngoài thì hậu quả rất nặng. Tạo user riêng và chuyển sang USER non-root giúp giảm đặc quyền. Secret như mật khẩu không nên ghi cứng vào image hay biến môi trường dễ lộ, mà nên truyền lúc chạy qua file hoặc dịch vụ quản lý bí mật. Healthcheck giúp dàn dựng như Swarm hay Kubernetes biết container còn phục vụ thật hay chỉ còn tiến trình treo, để rút khỏi cân bằng tải hoặc khởi động lại. Docker standalone không tự restart chỉ vì healthcheck chuyển sang unhealthy.',
deep: '<p>Container mặc định chạy root, nên một lỗ hổng trong thư viện xử lý ảnh thành privilege escalation toàn bộ container, và kẻ tấn công đọc ngay biến môi trường chứa khóa API. Thói quen cũ là chấp nhận root vì đơn giản.</p><p>Đáp án là ba lớp: <code>USER appuser</code> trong Dockerfile hạ đặc quyền; secret gắn lúc chạy dưới dạng file chỉ đọc hoặc từ dịch vụ quản lý bí mật, không ghi cứng vào image; <code>HEALTHCHECK</code> định kỳ xác nhận ứng dụng còn phục vụ thật. Docker chỉ theo dõi PID 1: nếu tiến trình con chết hoặc treo trong khi PID 1 vẫn sống, container vẫn báo running. Ngược lại, khi PID 1 thoát, kernel dừng toàn bộ tiến trình trong namespace.</p><p>Lần kiểm tra đầu chạy sau một <code>interval</code> (không phải ngay khi container chạy), sau đó lặp lại theo <code>interval</code>. Nếu khai báo <code>start-period</code>, các lần fail trong giai đoạn khởi động không tính vào <code>retries</code>. Restart policy <code>always</code> và <code>unless-stopped</code> chỉ phản ứng khi container thoát.</p><p>Người phỏng vấn cần nói được: non-root là hạ bề mặt tấn công; secret không nằm trong image; healthcheck là cơ chế chủ động; standalone Docker không tự restart khi container unhealthy, muốn điều phối theo health phải dùng Swarm hoặc dàn dựng khác.</p>',
code: 'FROM python:3.12-slim\nWORKDIR /app\nCOPY app.py .\nRUN useradd -m appuser && chown -R appuser:appuser /app\nUSER appuser\nEXPOSE 8000\nHEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD python -c "import socket; socket.create_connection((\\"127.0.0.1\\", 8000), timeout=2)"\nCMD ["python", "app.py"]',
expected: 'Kết quả: image có thêm user appuser; tiến trình chính (CMD dạng exec) chạy dưới appuser chứ không phải root, nên docker exec web id trả về uid khác 0 (useradd -m cấp UID tự động, thường 1000 trên base slim, nhưng nên chốt bằng -u để ổn định khi dùng volume); /app thuộc appuser:appuser vì chown chạy trước USER, tức vẫn do root thực hiện. EXPOSE 8000 chỉ là metadata tài liệu chứ không tự mở cổng, phải docker run -p 8080:8000 mới truy cập được từ host; EXPOSE chỉ ảnh hưởng tới docker run -P ánh xạ cổng ngẫu nhiên. Phân tích healthcheck: chỉ thị ở dạng shell form nên Docker chạy nó qua /bin/sh -c, và cặp nháy kép bọc code Python phải được escape trong Dockerfile; thực chất lệnh chạy python -c tạo một kết nối TCP tới 127.0.0.1:8000 với timeout 2 giây, exit 0 là healthy còn exit khác 0 là fail. Theo tài liệu, lần kiểm tra đầu chạy sau một interval (30 giây) kể từ lúc container start, sau đó lặp lại mỗi 30 giây, timeout 3 giây cho một lần chạy, và một lần chạy vượt timeout cũng tính là fail; phải 3 lần fail LIÊN TIẾP (retries=3) mới chuyển sang unhealthy, trạng thái đi từ starting sang healthy hoặc unhealthy. Cái bẫy: Docker KHÔNG tự restart container chỉ vì nó unhealthy, vì restart policy chỉ kích hoạt khi container thoát chứ không theo trạng thái health; muốn restart theo healthcheck phải có Swarm, Kubernetes hoặc một monitor riêng. Về secret, mật khẩu không được nhúng vào image vì mọi layer đều xem được bằng docker history; hãy truyền lúc chạy bằng secret mount hoặc file. Lệnh chứng minh: docker exec web id và docker inspect --format \'{{.State.Health.Status}}\' web. Lưu ý: toàn bộ mô tả trên là hành vi theo tài liệu Docker, không phải kết quả chạy trên máy này.',
followups: [
{q: 'Secret trong biến môi trường có an toàn không?', a: 'Không hoàn toàn. Biến môi trường dễ lộ qua trang quản trị, file dump tiến trình và nhật ký. Với dữ liệu thật sự nhạy cảm, bạn nên dùng file secret gắn lúc chạy hoặc dịch vụ quản lý bí mật có xoay vòng và phân quyền.'},
{q: 'Healthcheck trong Dockerfile khác gì kiểm tra của dàn dựng?', a: 'Healthcheck của Docker chỉ phản ánh trạng thái container trên một máy. Dàn dựng cần thêm kiểm tra mức service để điều phối lưu lượng, khởi động lại và lăn phiên bản. Bạn nên giữ hai lớp này nhất quán nhưng không thay thế nhau.'}
],
pitfalls: ['Chạy root ở production nên một lỗ hổng nhỏ thành chiếm quyền toàn bộ', 'Ghi cứng mật khẩu vào image rồi đẩy lên kho chung'],
selfcheck: ['Tôi vẫn chưa giải thích được sự khác nhau giữa quyền user trong container và quyền trên host khi dùng volume', 'Tôi có thể giải thích bằng ví dụ Dockerfile tạo user riêng và healthcheck cổng dịch vụ', 'Tôi có thể cấu hình lại một image đang chạy root thành non-root mà ứng dụng vẫn ghi được file cần thiết'],
refs: ['docker-security', 'dockerfile-ref']
},
{
id: 'H06',
group: 'H',
topic: 'Tín hiệu và graceful shutdown với PID 1',
prio: 'P0',
level: 'L3',
type: 'debug',
attacks: [{"q":"Vì sao dạng shell cho lệnh khởi động lại làm hỏng việc dừng êm?","a":"Vì khi đó tiến trình có mã một trong container là shell, không phải ứng dụng. Tín hiệu dừng được gửi tới tiến trình một, tức là shell, và shell không chuyển tiếp tín hiệu đó cho tiến trình con. Ứng dụng không bao giờ nhận được yêu cầu dừng, nên nó không có cơ hội hoàn tất yêu cầu đang xử lý, đóng kết nối, hay ghi nốt dữ liệu đang đệm. Sau khoảng thời gian chờ, hệ thống gửi tín hiệu buộc dừng và ứng dụng bị cắt giữa chừng. Dạng exec thay thế shell bằng chính ứng dụng, nên tín hiệu tới đúng nơi cần tới."},{"q":"Nếu ứng dụng cần dọn dẹp lâu hơn thời gian chờ mặc định thì sao?","a":"Phải tăng thời gian chờ trước khi buộc dừng, và đồng thời làm cho việc dọn dẹp nhanh hơn. Hai việc này đi cùng nhau: tăng thời gian chờ mà không xử lý việc dọn dẹp thì chỉ kéo dài thời gian triển khai. Cách làm đúng là khi nhận tín hiệu dừng, ứng dụng lập tức ngừng nhận yêu cầu mới, báo cho bộ cân bằng tải biết để nó ngừng gửi vào, rồi chờ các yêu cầu đang xử lý hoàn tất trong một giới hạn thời gian. Cần đặt giới hạn đó nhỏ hơn thời gian chờ của hệ thống, để ứng dụng tự thoát trước khi bị buộc dừng."}],
incident: '<p>Tình huống giả định: Deploy lúc 9h00 mỗi ngày mất 10 giây. SRE D mở log: <code>Stopping container api-3 ... timeout</code>, rồi Docker gửi <code>SIGKILL</code>. Ứng dụng đã cài handler <code>SIGTERM</code> nhưng log không thấy handler chạy. Một request thanh toán đang xử lý bị giết giữa chừng, khách hàng bị trừ tiền hai lần.</p>',
askFirst: [
  'Vì sao handler SIGTERM đã cài mà tín hiệu vẫn không tới được ứng dụng?',
  'Tiến trình nào là PID 1 trong container này?'
],
predict: { q: 'Bạn đoán ai là PID 1 khi dùng CMD shell form (CMD python app.py) và ai nhận SIGTERM?', a: '<p>Docker chạy <code>/bin/sh -c</code> làm PID 1, ứng dụng Python chỉ là tiến trình con. Shell giữ PID 1 nên SIGTERM dừng ở shell và không tới Python; handler trong Python không bao giờ chạy. Vì hành vi phụ thuộc shell và cách viết, exec form là cách chắc chắn. Sau timeout Docker gửi SIGKILL, request đang xử lý bị mất.</p>' },
anchor: 'Container khởi động bằng shell form mà không có exec form hay init = SIGTERM kẹt ở PID 1 shell và ứng dụng bị SIGKILL giữa chừng.',
q: 'Container dưới đây dừng rất chậm và mất 10 giây mỗi lần deploy, dù ứng dụng đã bắt SIGTERM. Lỗi nằm ở đâu và sửa thế nào?',
oral: 'Vấn đề nằm ở tiến trình PID 1. Container này khởi động bằng shell bọc ngoài; khi shell giữ PID 1, SIGTERM dừng ở shell và không tới Python, nên ứng dụng không có cơ hội hoàn tất việc đang làm. Sau thời gian chờ, Docker gửi SIGKILL để cưỡng bức dừng. Cách sửa là chạy ứng dụng trực tiếp dưới dạng exec form để nó thành PID 1, hoặc thêm tiến trình init nhỏ làm PID 1 để chuyển tiếp tín hiệu và gặt tiến trình con.',
deep: '<p>Mỗi deploy mất 10 giây chờ timeout, log chỉ hiện <code>Stopping container ... timeout</code> rồi <code>SIGKILL</code>. Ứng dụng đã cài handler SIGTERM nhưng handler không bao giờ chạy.</p><p>Container trước có init system ngoài kernel lo chuyển tiếp tín hiệu và gặt zombie; container thì khác, Docker chỉ gửi tín hiệu tới PID 1. Ở dạng shell, Docker chạy <code>/bin/sh -c</code>; khi shell giữ PID 1, SIGTERM dừng ở shell và không tới Python. Kiểm tra <code>/proc/1/cmdline</code> để xem tiến trình nào đang là PID 1 trước khi kết luận.</p><p>Sửa bằng exec form <code>CMD ["python", "app.py"]</code> để Python thành PID 1, hoặc thêm init như tini để chuyển tiếp tín hiệu và gặt zombie. Graceful shutdown là ngừng nhận việc mới, hoàn tất việc đang làm, đóng kết nối rồi mới thoát, và timeout dừng phải dài hơn thời gian dọn dẹp. Chỗ vẫn còn sai: tăng timeout mà không rút endpoint khỏi cân bằng tải trước, request mới vẫn rơi vào container đang dừng.</p><p>Người phỏng vấn cần nói được: Docker chỉ gửi tín hiệu tới PID 1; shell form không bảo đảm ứng dụng nhận SIGTERM; exec form để app thành PID 1 hoặc init giúp chuyển tiếp. Lỗi phổ biến là tăng timeout mà không rút endpoint khỏi cân bằng tải.</p>',
code: 'FROM python:3.12-slim\nWORKDIR /app\nCOPY app.py .\nCMD python app.py',
expected: 'Container dừng chậm vì CMD ở dạng shell không bảo đảm Python là PID 1. Docker chạy /bin/sh -c; nếu shell giữ PID 1, SIGTERM dừng ở shell và không tới Python, Docker chờ hết timeout rồi gửi SIGKILL. Sửa bằng CMD dạng exec ["python", "app.py"] để Python thành PID 1, hoặc thêm init làm PID 1 để chuyển tiếp tín hiệu và gặt zombie.',
followups: [
{q: 'Exec form khác shell form ở điểm nào?', a: 'Exec form chạy trực tiếp binary thành PID 1 và nhận tín hiệu trực tiếp. Shell form chèn thêm lớp shell ở giữa, tín hiệu dừng ở shell và không tới ứng dụng. Vì vậy production nên dùng exec form cho cả ENTRYPOINT và CMD.'},
{q: 'Khi nào bạn cần thêm init như tini?', a: 'Khi ứng dụng sinh nhiều tiến trình con hoặc bạn chưa kiểm soát được PID 1. Init nhẹ sẽ chuyển tiếp tín hiệu, gặt tiến trình con đã kết thúc và tránh zombie, giúp shutdown sạch hơn.'},
{q: 'Nếu sửa PID 1 rồi mà deploy vẫn mất request thì kiểm tra gì tiếp?', a: 'Bạn kiểm tra handler SIGTERM có đóng cổng nhận việc mới, chờ request hiện tại xong và đặt timeout dừng đủ dài không. Bạn cũng kiểm tra dàn dựng có rút endpoint khỏi cân bằng tải trước khi gửi SIGTERM hay không.'}
],
pitfalls: ['Chỉ thêm handler SIGTERM mà không kiểm tra PID 1 nên tín hiệu không bao giờ tới', 'Đặt timeout dừng quá ngắn khiến worker bị giết giữa chừng và mất dữ liệu'],
selfcheck: ['Tôi vẫn chưa giải thích được init thu dọn tiến trình zombie bằng cơ chế chờ tiến trình con thế nào', 'Tôi có thể giải thích bằng ví dụ CMD shell form bị SIGTERM kẹt và CMD exec form dừng êm', 'Tôi có thể kiểm tra PID 1 trong một container thật và sửa Dockerfile để deploy không còn chờ đủ timeout'],
refs: ['signal-man', 'dockerfile-ref']
},
{
id: 'H07',
group: 'H',
topic: 'Pipeline CI/CD và quản lý artifact',
prio: 'P1',
level: 'L2',
type: 'concept',
incident: "<p>Tình huống giả định: Pipeline triển khai build ảnh trong mỗi lần chạy và gắn thẻ <code>latest</code>. Một lần rollback khẩn cấp, đội chạy lại pipeline của phiên bản trước, nhưng pipeline đó build từ nhánh chính hiện tại nên tạo ra một ảnh khác với ảnh đã chạy hôm qua. Việc rollback không đưa hệ thống về trạng thái cũ. Ngoài ra, không ai biết chính xác commit nào đang chạy trên production.</p>",
askFirst: ["Vì sao gắn thẻ <code>latest</code> làm rollback không đáng tin?","Artifact nên được tạo ở bước nào và dùng lại thế nào?","Làm sao biết chính xác phiên bản nào đang chạy?"],
predict: {"q":"Một pipeline build ảnh rồi triển khai ngay trong cùng một lần chạy. Muốn rollback về phiên bản trước, bạn cần gì?","a":"<p>Bạn cần ảnh của phiên bản trước vẫn còn tồn tại và định danh được. Nếu ảnh chỉ có thẻ <code>latest</code>, nó đã bị ghi đè và bản cũ có thể đã bị xoá khỏi registry. Cách làm đúng là mỗi lần build tạo ra một artifact bất biến được định danh bằng mã commit, đẩy lên registry, và bước triển khai chỉ tham chiếu tới định danh đó. Khi đó rollback chỉ là triển khai lại một định danh đã có, không cần build lại gì, nên nó nhanh và cho đúng cùng một ảnh như lần trước.</p>"},
anchor: "Rollback chỉ đáng tin khi artifact là bất biến và được định danh — build lại từ mã nguồn là tạo ra một phiên bản mới chứ không phải quay về bản cũ.",
attacks: [{"q":"Build và deploy nên tách thành hai bước như thế nào?","a":"Bước build tạo artifact một lần cho mỗi commit, đẩy lên registry, và không chạm tới môi trường nào. Bước deploy chỉ lấy một artifact đã tồn tại và đưa nó vào môi trường, không build gì cả. Lợi ích là artifact được kiểm thử ở staging chính là artifact chạy trên production, nên loại bỏ được cả một lớp khác biệt giữa hai môi trường. Nó cũng cho phép triển khai cùng một artifact cho nhiều môi trường và rollback bằng cách chọn một định danh cũ."},{"q":"Secret trong CI nên được xử lý thế nào?","a":"Ưu tiên trao đổi danh tính tạm thời thay vì lưu khoá dài hạn: pipeline nhận một danh tính ngắn hạn từ nhà cung cấp CI và dùng nó để lấy quyền truy cập, nên không có khoá nào tồn tại lâu để bị đánh cắp. Nếu buộc phải dùng khoá dài hạn, phải đánh dấu là secret để hệ thống che trong log, giới hạn quyền tối thiểu, và xoay định kỳ. Điều tuyệt đối tránh là in secret ra log hoặc truyền nó qua tham số dòng lệnh, vì cả hai đều để lại dấu vết đọc được."}],
q: 'Hãy thiết kế một pipeline lint, test, build rồi deploy cho ứng dụng Docker, kèm cách đánh phiên bản artifact.',
oral: 'Pipeline nên chia bốn chặng rõ ràng. Lint và định dạng chạy đầu để chặn lỗi rẻ nhất. Test đơn vị và tích hợp chạy tiếp trên môi trường sạch. Build image chỉ chạy khi test đã qua, gắn tag theo commit và số build để truy vết. Deploy lấy đúng image đã kiểm thử theo tag bất biến, triển khai từng phần và có kiểm tra sức khỏe sau deploy. Mỗi image và bản ghi pipeline đều lưu lại để khi lỗi bạn biết đúng bản nào đang chạy và quay lại được.',
deep: '<p>Trước CI, release là dev kéo tar lên FTP rồi SSH chạy lệnh, không ai biết chính xác build nào đang chạy. Khi microservice tăng và deploy liên tục, việc build lại từ mã nguồn hiện tại khiến tag <code>latest</code> bị ghi đè và rollback thành việc đoán.</p><p>Áp lực là truy vết. Pipeline chia bốn chặng: <code>lint</code>, <code>test</code>, <code>build</code>, <code>deploy</code>. Lint chặn lỗi rẻ nhất; test xác minh hành vi; build đóng gói image và đẩy lên registry; deploy chỉ lấy đúng image đã kiểm thử. Mỗi image được định danh bằng mã commit; trên ECR bật image tag immutability, tag theo commit SHA không bị ghi đè, và deploy trỏ vào digest <code>sha256:...</code> mà registry trả về.</p><p>Chỗ vẫn còn sai: pipeline không có <code>docker login</code>, tag cứng kiểu 1.4.0 nên mất provenance, hoặc chưa có concurrency guard nên hai push chạy song song. Khi rollback, bạn redeploy cùng digest đã biết là tốt, không build lại.</p><p>Người phỏng vấn cần nói được: build một lần rồi deploy cùng artifact; tag theo commit hoặc digest, tránh <code>latest</code> làm điểm neo; rollback phải là redeploy định danh đã biết tốt. Lỗi phổ biến là pipeline thiếu login, tag thiếu provenance, hoặc không có bước deploy tự động.</p>',
code: 'name: service-pipeline\non:\n  push:\n    branches: [main]\njobs:\n  lint-test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: pip install -r requirements.txt\n      - run: ruff check .\n      - run: pytest -q\n  build-push:\n    needs: lint-test\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: docker build -t registry/app:1.4.0 .\n      - run: docker push registry/app:1.4.0',
expected: 'Kết quả: chỉ push lên nhánh main mới kích hoạt pipeline, còn PR, push nhánh khác và push tag đều không chạy, nên PR không được kiểm tra trước khi merge. Hai job chạy trên hai runner ubuntu-latest SẠCH và TÁCH BIỆT, không chia sẻ filesystem; build-push có needs: lint-test nên chỉ chạy khi lint-test thành công, còn nếu ruff check hoặc pytest trả exit code khác 0 thì job lint-test đỏ và build-push bị bỏ qua (skipped), không image nào được đẩy. Artifact của pipeline là image Docker registry/app:1.4.0 trong registry, cộng với log và metadata của run; digest sha256 của image mới là định danh bất biến để truy vết. Các lỗ hổng thực tế cần chỉ ra: (1) không có bước docker login nên docker push lên registry riêng sẽ thất bại với lỗi denied hoặc unauthorized, cần docker/login-action cùng secret; (2) tag cứng 1.4.0 nên mọi lần build ghi đè cùng một tag, không biết commit nào sinh ra nó và không rollback chính xác được, phải gắn thêm sha của commit và số run; (3) thiếu concurrency nên hai push liên tiếp chạy song song và bản cũ có thể push sau đè lên bản mới; (4) không có cache pip nên mỗi run cài lại từ đầu; (5) pipeline dừng ở push, KHÔNG có job deploy, nên chưa có cơ chế rollback tự động nào. Vì vậy rollback trong thiết kế này phải làm tay bằng cách deploy lại tag hoặc digest đã biết là tốt, và ngưỡng kích hoạt rollback là healthcheck sau deploy thất bại hoặc tỉ lệ 5xx vượt ngưỡng cảnh báo. Lệnh chứng minh: docker manifest inspect registry/app:1.4.0 để thấy digest, và xem lịch sử các run gắn với cùng tag để thấy tag đã bị ghi đè. Lưu ý: toàn bộ mô tả trên là hành vi theo tài liệu GitHub Actions, không phải kết quả chạy trên máy này.',
followups: [
{q: 'Vì sao phải build một lần và deploy cùng image đó?', a: 'Vì build lại có thể kéo gói mới hoặc khác cache nên bản chạy khác bản đã test. Build một lần rồi quảng bá cùng tag bất biến giúp staging và production chạy đúng thứ đã kiểm thử.'},
{q: 'Bạn đặt secret và phê duyệt production thế nào?', a: 'Bạn lưu secret trong kho bí mật của CI theo môi trường, không ghi vào file pipeline. Bạn thêm bước phê duyệt tay, giới hạn ai được duyệt deploy production và ghi lại ai đã duyệt bản nào.'}
],
pitfalls: ['Deploy tag latest nên khi lỗi không biết quay về bản nào', 'Bỏ qua test ở nhánh nóng rồi deploy thẳng production'],
selfcheck: ['Tôi vẫn chưa giải thích được cách lưu provenance để chứng minh image production được build từ commit nào', 'Tôi có thể giải thích bằng ví dụ pipeline lint rồi test rồi mới build và đẩy tag theo commit', 'Tôi có thể dựng một pipeline tối thiểu chặn merge khi lint hoặc test đỏ'],
refs: ['gh-actions', 'docker-multi-stage']
},
{
id: 'H08',
group: 'H',
topic: 'Migration và rollback database',
prio: 'P1',
level: 'L3',
type: 'situation',
incident: "<p>Tình huống giả định: Một lần triển khai gồm hai bước: chạy migration đổi tên một cột, rồi triển khai mã mới. Migration chạy xong, nhưng bước triển khai mã thất bại. Trong khoảng 12 phút, phiên bản mã cũ vẫn đang chạy và truy vấn cột cũ, nên mọi request liên quan đều lỗi 500. Việc rollback migration cũng thất bại vì cột cũ đã bị xoá cùng dữ liệu.</p>",
askFirst: ["Vì sao migration và triển khai mã phải tương thích trong cả hai chiều?","Thay đổi phá huỷ nên được chia thành những bước nào?","Làm sao để rollback migration luôn thực hiện được?"],
predict: {"q":"Một migration xoá một cột đang được phiên bản mã cũ sử dụng. Nếu bạn triển khai mã mới thất bại và phải quay lại mã cũ, chuyện gì xảy ra?","a":"<p>Mã cũ lỗi ngay vì cột nó cần không còn tồn tại. Đây là lý do thay đổi phá huỷ phải được tách khỏi thay đổi mã, và tách theo thứ tự khiến cả hai phiên bản cùng chạy được trong giai đoạn chuyển tiếp. Quy trình ba bước thường dùng: trước tiên thêm cột mới và để mã ghi vào cả hai cột, sau khi mọi thứ ổn định thì chuyển sang chỉ đọc cột mới, và chỉ xoá cột cũ ở một lần triển khai riêng sau đó. Như vậy ở mọi thời điểm đều có thể quay lại phiên bản trước mà không mất dữ liệu.</p>"},
anchor: "Migration phá huỷ đi trước mã là tự tay lấy đi đường lùi, nên thay đổi schema phải được chia thành các bước mà cả hai phiên bản mã cùng chạy được.",
attacks: [{"q":"Làm sao chạy một migration lớn trên bảng hàng chục triệu dòng mà không khoá bảng?","a":"Chia thành nhiều bước nhỏ và kiểm soát khoá ở từng bước. Thêm cột cho phép giá trị rỗng thường là thao tác nhẹ. Tạo chỉ mục nên chạy ở chế độ không khoá ghi, chấp nhận thời gian lâu hơn nhưng không chặn ghi. Thêm ràng buộc <code>NOT NULL</code> nên chia làm hai: thêm ràng buộc ở trạng thái không kiểm tra dữ liệu cũ, rồi kiểm tra và xác nhận trong một bước riêng. Với việc làm đầy dữ liệu, chia theo lô nhỏ để mỗi lô là một transaction ngắn, tránh một transaction khổng lồ giữ khoá lâu và làm phình bảng."},{"q":"Migration có nên nằm trong cùng pipeline với triển khai mã không?","a":"Nên nằm trong pipeline nhưng phải là bước riêng, chạy trước, và phải đảm bảo chỉ một tiến trình chạy nó. Nếu nhiều bản sao ứng dụng cùng khởi động và cùng chạy migration, chúng sẽ tranh nhau và có thể áp dụng hai lần. Cần một cơ chế khoá để chỉ một tiến trình được chạy. Và migration phải tương thích ngược — nghĩa là sau khi chạy, cả phiên bản mã cũ đang chạy lẫn phiên bản mới sắp chạy đều phải hoạt động được, vì trong lúc triển khai luôn có một khoảng cả hai cùng tồn tại."}],
q: 'Bạn vừa deploy bản mới kèm migration xóa một cột, giờ cần rollback code gấp. Vì sao rollback code không đồng nghĩa rollback database, và bạn xử lý thế nào?',
oral: 'Rollback code chỉ đổi image ứng dụng về bản cũ, còn migration đã chạy trên database thì vẫn ở đó. Cột đã xóa không tự quay lại, và dữ liệu có thể đã mất nếu không sao lưu. Vì vậy bạn phải coi migration là thay đổi một chiều và luôn có kế hoạch riêng. Cách an toàn là viết migration tương thích ngược, tách bước mở rộng và thu hẹp, sao lưu trước khi chạy, và chuẩn bị sẵn migration đảo ngược đã kiểm thử thay vì mong database tự quay lại.',
deep: '<p>Trước migration tool, DBA chạy SQL dump tay và rollback bằng cách chép lại tệp sao lưu. Khi continuous deployment xuất hiện, migration phải chạy tự động trước code, và việc xóa cột trong cùng một lần deploy khiến rollback code không thể hoạt động.</p><p>Migration là thay đổi có trạng thái trên database, còn rollback code chỉ đổi image ứng dụng; hai lớp tiến hóa độc lập nên không dùng chung một nút quay lại. Áp lực là cửa sổ deploy, trong đó cả bản cũ lẫn bản mới code cùng chạy được. Bạn tách thay đổi phá huỷ thành expand: thêm cột nullable, backfill theo mẻ, ghi cả hai; rồi contract: chuyển mã đọc cột mới, sau đó xóa cột cũ ở lần deploy riêng.</p><p>Chỗ vẫn còn sai: team chạy migration xóa cột cùng lúc với deploy code, hoặc không có migration đảo ngược đã kiểm thử trên sao lưu production. Khi lỗi, rollback mã vẫn chạy được vì cột cũ vẫn còn; nếu đã xóa, chỉ cứu được từ backup.</p><p>Người phỏng vấn cần nói được: rollback code không xóa migration; thay đổi phá huỷ phải chia thành bước mở rộng và thu hẹp để hai phiên bản mã cùng chạy; migration nguy hiểm cần backup đã kiểm thử và migration đảo ngược. Lỗi phổ biến là chạy migration xóa cột cùng deploy code nên không quay lại được.</p>',
code: null,
expected: null,
followups: [
{q: 'Thế nào là migration tương thích ngược?', a: 'Là migration mà cả code cũ và code mới đều chạy được trong lúc chuyển đổi. Bạn chỉ thêm mới dạng cho phép rỗng, không xóa hay đổi nghĩa trường cũ, và dời bước dọn dẹp sang một deploy sau khi mọi bản cũ đã rút.'},
{q: 'Trước một migration nguy hiểm bạn chuẩn bị gì?', a: 'Bạn sao lưu có thể phục hồi đã kiểm thử, chạy thử trên bản sao production, ước lượng thời gian khóa bảng, chuẩn bị migration đảo ngược và kịch bản dừng deploy. Bạn cũng thông báo cửa sổ rủi ro cho bên liên quan.'}
],
pitfalls: ['Xóa cột và deploy code cùng lúc nên rollback code xong hệ thống vẫn lỗi vì thiếu cột', 'Chạy migration production lần đầu mà chưa thử phục hồi sao lưu'],
selfcheck: ['Tôi vẫn chưa giải thích được cách viết backfill theo mẻ cho bảng lớn mà không khóa bảng quá lâu', 'Tôi có thể giải thích bằng ví dụ tách thêm cột và xóa cột thành hai deploy riêng biệt', 'Tôi có thể lập checklist sao lưu và kiểm thử rollback cho một migration xóa trường thực tế'],
refs: ['gh-actions']
},
{
id: 'H09',
group: 'H',
topic: 'Linux tiến trình, cổng, log, biến môi trường và quyền',
prio: 'P2',
level: 'L1',
type: 'code',
incident: "<p>Tình huống giả định: Một service trên máy chủ Linux đột nhiên không nhận kết nối. Kiểm tra cho thấy tiến trình vẫn chạy, nhưng cổng không phản hồi. Một kỹ sư kiểm tra bằng cách khởi động lại service, và sự cố quay lại sau hai giờ. Không ai đọc được log vì ứng dụng ghi vào một tệp trong thư mục của người dùng, và tệp đó không có quyền đọc cho nhóm vận hành.</p>",
askFirst: ["Làm sao kiểm tra một tiến trình có thật sự đang lắng nghe trên cổng không?","Quyền trên tệp log ảnh hưởng gì tới việc xử lý sự cố?","Dấu hiệu nào phân biệt hết file descriptor với cạn cổng?"],
predict: {"q":"Một tiến trình đang chạy nhưng không nhận kết nối trên cổng đã cấu hình. Bạn kiểm tra gì trước?","a":"<p>Kiểm tra xem tiến trình có thật sự đang lắng nghe trên cổng đó hay không, chứ không chỉ kiểm tra nó còn tồn tại. Tiến trình có thể đã khởi động nhưng thất bại ở bước mở cổng — vì cổng đã bị tiến trình khác chiếm, vì thiếu quyền mở cổng dưới 1024, hoặc vì nó đang lắng nghe trên một địa chỉ khác với địa chỉ bạn đang gọi tới. Trường hợp cuối là phổ biến và khó thấy: lắng nghe trên địa chỉ vòng lặp thì chỉ nhận được kết nối từ chính máy đó."},
anchor: "\"Tiến trình còn chạy\" và \"cổng đang phục vụ\" là hai câu hỏi khác nhau, nên chẩn đoán phải kiểm tra trạng thái lắng nghe chứ không chỉ trạng thái tiến trình.",
attacks: [{"q":"Hết file descriptor gây ra triệu chứng gì?","a":"Triệu chứng đặc trưng là service chạy bình thường một thời gian rồi bắt đầu từ chối kết nối mới hoặc không mở được tệp, trong khi tiến trình vẫn sống và CPU thấp. Nguyên nhân thường là rò rỉ: kết nối hoặc tệp không được đóng, nên số lượng tăng dần tới hạn mức của tiến trình. Điều cần phân biệt là hạn mức theo tiến trình khác với hạn mức toàn hệ thống, và cả hai đều có thể bị chạm. Cách chẩn đoán là đếm số file descriptor đang mở của tiến trình và so với hạn mức, rồi xem chúng thuộc loại nào để đoán chỗ rò rỉ."},{"q":"Vì sao quyền trên tệp log lại quan trọng trong xử lý sự cố?","a":"Vì nếu người trực không đọc được log thì mọi chẩn đoán đều thành phỏng đoán, và thời gian khắc phục tăng lên bội phần. Quyền cần được đặt sao cho nhóm vận hành đọc được mà không cần quyền root, và ứng dụng chỉ có quyền ghi chứ không có quyền đọc toàn bộ. Một vấn đề liên quan là xoay vòng log: nếu log không được xoay, đĩa đầy và đó lại là một nguyên nhân sự cố khác. Và log nên được đẩy về một nơi tập trung, vì khi máy chủ hỏng thì log trên chính máy đó cũng mất theo."}],
q: 'Web trong container không trả lời, bạn chỉ có shell Linux trên host. Bạn dùng lệnh nào để tìm tiến trình, cổng, log, biến môi trường và quyền file?',
oral: 'Bạn đi theo thứ tự từ tiến trình tới mạng rồi tới log. Đầu tiên liệt kê tiến trình và mức CPU RAM để biết app còn sống không. Sau đó kiểm tra cổng đang nghe và thử gọi trực tiếp để tách lỗi mạng hay lỗi app. Rồi đọc log hệ thống và log container, kiểm tra biến môi trường và quyền file cấu hình. Mỗi lệnh cho bạn một mảnh ghép, ghép lại là ra nguyên nhân mà không cần đoán mò.',
deep: '<p>Shell trên host không nhìn thấy hết container. Trước khi container, sysadmin bare-metal dùng <code>ps</code>, <code>netstat</code>, journal và file log riêng lẻ; khi service chạy trong namespace, tiến trình còn sống không còn đủ để kết luận service khỏe.</p><p>Chuỗi chẩn đoán hôm nay đi từ tiến trình tới mạng rồi tới cấu hình: <code>ps aux</code> xem app còn sống không và ngốn bao nhiêu; <code>ss -ltnp</code> cho biết ai đang LISTEN trên cổng nào, bind ở địa chỉ nào; <code>docker logs</code> và <code>journalctl</code> đọc lỗi khởi động; <code>printenv</code> kiểm tra biến cấu hình; <code>ls -l</code> kiểm tra quyền đọc file. Nếu <code>ss -ltnp | grep 8000</code> hiện <code>127.0.0.1:8000</code>, app chỉ nghe loopback và ngoài container không gọi được.</p><p>Chỗ vẫn còn sai: team nhìn CPU thấp và tưởng app ổn, trong khi tiến trình sống nhưng bind sai địa chỉ hoặc thiếu <code>DB_HOST</code>. Hoặc UID trong container khác UID trên host khiến file log không đọc được, và người trực kết luận sai quyền vì không nhìn GID.</p><p>Người phỏng vấn cần nói được: tiến trình chạy không bằng service phục vụ; phải kiểm tra LISTEN trên đúng địa chỉ; đọc log và biến môi trường trong container bằng <code>docker exec</code>, không chỉ trên host; quyền file liên quan đến UID/GID khi gắn volume. Lỗi phổ biến là tin CPU thấp đồng nghĩa app khỏe, bỏ qua bind và cấu hình.</p>',
code: 'ps aux --sort=-%cpu | head\nss -ltnp | grep 8000\ndocker ps\ndocker logs --tail 200 web\nprintenv | grep DB_\nls -l /etc/app/config.env',
expected: 'Kết quả từng lệnh: ps aux --sort=-%cpu | head in bảng USER PID %CPU %MEM VSZ RSS TTY STAT START TIME COMMAND, sắp giảm dần theo %CPU và head cắt còn 10 dòng đầu (header cộng 9 tiến trình ngốn CPU nhất), nhưng %CPU của ps là trung bình trên cả vòng đời tiến trình nên nó che các đỉnh ngắn, muốn xem tức thời phải dùng top -o %CPU hoặc pidstat; tiến trình ở trạng thái Z là zombie, không dùng CPU RAM và chỉ được thu dọn bởi tiến trình cha, tìm cha bằng ps -o ppid= -p <pid>. ss -ltnp | grep 8000 in các socket đang LISTEN, TCP, cổng dạng số, kèm tiến trình giữ cổng (cần root hoặc cùng user mới thấy cột Process); nếu dòng hiện 127.0.0.1:8000 thì app chỉ bind loopback nên từ ngoài container hoặc host gọi vào sẽ bị connection refused, đúng lỗi bind sai địa chỉ và phải bind 0.0.0.0; nếu grep không ra dòng nào (exit code 1) thì không có gì nghe cổng 8000, tức app chưa khởi động hoặc nghe cổng khác. docker ps chỉ hiện container ĐANG chạy kèm cột PORTS dạng 0.0.0.0:8080->8000/tcp và STATUS dạng Up 5 minutes (healthy); container vắng mặt thì phải docker ps -a để xem Exited và mã thoát. docker logs --tail 200 web lấy 200 dòng cuối từ stdout/stderr của tiến trình chính, đúng chỗ có stack trace; lưu ý log chỉ tồn tại theo vòng đời container nên docker rm là mất, và log ghi vào file bên trong container sẽ không hiện ở đây. printenv | grep DB_ là lệnh dễ đọc sai nhất: nó in biến môi trường của CHÍNH shell đang gõ lệnh chứ không phải của container, muốn xem biến trong container phải dùng docker exec web printenv | grep DB_ hoặc docker inspect --format \'{{.Config.Env}}\' web, và thiếu DB_HOST là nguyên nhân kinh điển khiến app nối sai database. ls -l /etc/app/config.env in quyền, chủ sở hữu, nhóm, kích thước và thời gian sửa; dạng -rw-r----- với chủ là user khác sẽ khiến app non-root lỗi Permission denied khi mở file, và đây chính là hệ quả của UID/GID lệch nhau khi gắn volume. Lệnh chứng minh kết quả cuối: ss -ltnp \'sport = :8000\' để lọc đúng cổng 8000 (chính xác hơn grep vì grep 8000 cũng khớp 18000 hay 80001) và curl -sv tới cổng 8000 trên localhost để thấy kết nối thành công hay bị từ chối. Lưu ý: toàn bộ mô tả trên là hành vi theo tài liệu Linux, không phải kết quả chạy trên máy này.',
followups: [
{q: 'Bạn phân biệt app chết và app còn sống nhưng không nghe cổng thế nào?', a: 'Bạn đối chiếu tiến trình còn không, cổng có LISTEN không và log nói gì. Tiến trình mất là app đã thoát, còn tiến trình sống mà không có cổng thường là kẹt khởi động, bind sai hoặc chờ phụ thuộc như database.'},
{q: 'Vì sao quyền file hay gây lỗi sau khi gắn volume?', a: 'Vì UID trong container có thể khác UID trên host. File host chỉ cho phép user khác đọc, trong khi app non-root trong container không có quyền. Bạn cần đồng bộ UID, đổi quyền hoặc dùng nhóm chung.'}
],
pitfalls: ['Nhầm bind localhost với bind mọi địa chỉ nên ngoài container không gọi được', 'Đổi quyền 777 cho qua chuyện thay vì sửa đúng user và nhóm'],
selfcheck: ['Tôi vẫn chưa giải thích được cách đọc trạng thái tiến trình zombie và tìm tiến trình cha của nó', 'Tôi có thể giải thích bằng ví dụ dùng ss và log để tách lỗi cổng và lỗi ứng dụng', 'Tôi có thể chẩn đoán một service không trả lời từ shell host mà không cần khởi động lại bừa'],
refs: ['signal-man']
},
{
id: 'H10',
group: 'H',
topic: 'Log, metric, trace và dấu hiệu sự cố',
prio: 'P1',
level: 'L3',
type: 'situation',
incident: "<p>Tình huống giả định: Sau một sự cố kéo dài 90 phút, buổi rút kinh nghiệm cho thấy đội đã mất 25 phút đầu chỉ để xác định sự cố bắt đầu từ khi nào. Dashboard có 60 biểu đồ nhưng không có biểu đồ nào hiển thị tỉ lệ lỗi theo phiên bản triển khai, nên không ai liên hệ được sự cố với lần deploy 20 phút trước đó. Không có cảnh báo nào kêu vì ngưỡng được đặt theo giá trị trung bình, và giá trị trung bình vẫn nằm trong ngưỡng.</p>",
askFirst: ["Metric nào phát hiện sự cố sớm nhất?","Vì sao ngưỡng theo giá trị trung bình lại bỏ sót?","Thông tin nào cần có ngay khi mở dashboard?"],
predict: {"q":"Một sự cố ảnh hưởng tới 3% request nhưng rất nặng với nhóm người dùng đó. Chỉ số trung bình có phát hiện được không?","a":"<p>Không. Nếu 97% request vẫn nhanh và thành công, giá trị trung bình gần như không đổi, nên ngưỡng theo trung bình sẽ không kêu. Đây là lý do phải đặt cảnh báo theo phân vị cao — p95, p99 — và theo tỉ lệ lỗi, chứ không theo trung bình. Với trải nghiệm người dùng, điều đáng quan tâm không phải là người dùng trung bình mà là nhóm người dùng tệ nhất, vì một tỉ lệ nhỏ gặp lỗi vẫn là sự cố thật đối với họ và vẫn là vấn đề danh tiếng với doanh nghiệp.</p>"},
anchor: "Giá trị trung bình che mất nhóm người dùng chịu thiệt, nên cảnh báo phải dựa trên phân vị cao và tỉ lệ lỗi.",
attacks: [{"q":"Ba tín hiệu nào bạn muốn có ngay khi mở dashboard lúc có sự cố?","a":"Thứ nhất, tỉ lệ lỗi và độ trễ theo phân vị cao, tách theo phiên bản đang chạy — vì tách theo phiên bản là cách nhanh nhất để biết có phải do deploy hay không. Thứ hai, độ trễ và tỉ lệ lỗi của từng phụ thuộc bên ngoài, vì phần lớn sự cố nằm ở đó chứ không nằm trong service. Thứ ba, các tài nguyên có giới hạn cứng: độ sâu hàng đợi, tuổi message cũ nhất, số kết nối đang dùng so với hạn mức. Ba nhóm này trả lời được câu hỏi \"hỏng ở đâu\" trong vài phút thay vì vài chục phút."},{"q":"Cảnh báo nên đặt thế nào để không bị bỏ qua?","a":"Mỗi cảnh báo phải gắn với một hành động cụ thể, và nếu không có hành động nào thì nó không nên tồn tại. Cảnh báo nên dựa trên triệu chứng người dùng cảm nhận được — tỉ lệ lỗi, độ trễ — chứ không dựa trên nguyên nhân nội bộ như mức dùng CPU, vì CPU cao mà người dùng vẫn ổn thì không phải sự cố. Cần phân mức rõ ràng: mức đánh thức người trực chỉ dành cho sự cố ảnh hưởng người dùng, còn những thứ khác đi vào kênh thông tin thường. Và phải định kỳ rà lại để xoá những cảnh báo không bao giờ dẫn tới hành động, vì chúng làm mờ những cảnh báo thật."}],
q: 'Sau deploy, tỉ lệ 5xx tăng, p99 latency vọt lên và RAM container tăng đều. Bạn dùng log, metric và trace thế nào để khoanh vùng?',
oral: 'Bạn bắt đầu từ metric để biết cái gì đổi và khi nào, đối chiếu thời điểm deploy với đường 5xx, latency và RAM. Sau đó lọc log lỗi theo request id để tìm stack trace và điểm hỏng chung. Rồi mở trace của request chậm để xem thời gian kẹt ở database, hàng đợi hay service ngoài. RAM tăng đều kèm thu gom rác kém gợi ý rò rỉ, còn latency chỉ tăng ở một endpoint gợi ý câu truy vấn chậm. Khi đã có giả thuyết, bạn kiểm tra thay đổi vừa deploy và thử giảm tải hoặc rollback có kiểm soát.',
deep: '<p>Trước observability stack, sự cố được phát hiện qua điện thoại và ticket; dashboard SNMP theo dõi CPU và RAM trung bình, nên phần nhỏ request hỏng vẫn nằm trong ngưỡng. Khi microservice tăng, giá trị trung bình che mất nhóm user tệ nhất và không ai nối được sự cố với lần deploy.</p><p>Ba nguồn bổ sung nhau: <code>log</code> ghi sự kiện rời rạc, <code>metric</code> là số tổng hợp theo thời gian, <code>trace</code> nối các nhịp xử lý của một request qua nhiều service. Metric cho triệu chứng và thời điểm; log với request id cho bạn lần ra stack trace; trace cho bạn biết latency nằm ở nhịp nào. Bạn so mốc deploy với 5xx và p99, lọc log theo request id, rồi mở trace của request chậm nhất để xem nhịp database hay lời gọi ngoài chiếm bao nhiêu.</p><p>Chỗ vẫn còn sai: kết luận deploy gây lỗi chỉ vì trùng thời gian mà chưa loại trừ lưu lượng tăng hay phụ thuộc ngoài. Hoặc thiếu request id nên log và trace không nối được với nhau; hoặc cảnh báo vẫn đặt theo giá trị trung bình thay vì phân vị cao và tỉ lệ lỗi.</p><p>Người phỏng vấn cần nói được: metric cho triệu chứng và mốc thời gian; log cho nguyên nhân cụ thể theo request; trace cho vị trí bottleneck giữa các service. Lỗi phổ biến là thiếu request id khiến ba nguồn không ghép lại được.</p>',
code: 'docker stats --no-stream\ndocker logs --tail 300 web | grep "ERROR"\nss -s\nfree -m',
expected: 'Kết quả từng lệnh: docker stats --no-stream in MỘT ảnh chụp rồi thoát (không stream liên tục) với các cột CONTAINER ID, NAME, CPU %, MEM USAGE / LIMIT, MEM %, NET I/O, BLOCK I/O, PIDS; điểm phải biết là MEM USAGE tính cả page cache và LIMIT bằng tổng RAM host nếu container không đặt giới hạn bộ nhớ, nên con số RAM tăng đều có thể chỉ là cache tăng chứ chưa chắc rò rỉ. docker logs --tail 300 web | grep ERROR lọc 300 dòng log cuối, nhưng grep mặc định phân biệt hoa thường nên bỏ sót error hay level=error, và chỉ giữ dòng khớp nên stack trace nhiều dòng mất ngữ cảnh; dùng grep -i -A 20 hoặc --since 10m. ss -s in bảng tổng hợp socket (Total, TCP với các trạng thái estab, timewait, orphaned...), nên nó cho biết có bùng nổ kết nối hay timewait, tức dấu hiệu rò rỉ kết nối hoặc cạn pool. free -m in bộ nhớ theo MiB với total, used, free, shared, buff/cache, available; phải nhìn available mới thấy khoảng trống thật vì used không tính cache có thể thu hồi. Lưu ý ss -s và free -m chạy ở namespace của host chứ không phải của container nếu không dùng docker exec, còn giới hạn bộ nhớ của container nằm ở cgroup (memory.max ở cgroup v2, memory.limit_in_bytes ở v1). Cách khoanh vùng: đối chiếu mốc thời gian 5xx và p99 nhảy bậc với thời điểm deploy, nhưng phải loại trừ lưu lượng tăng và phụ thuộc ngoài trước khi kết tội deploy. RAM tăng đơn điệu, không trở về sau khi tải hạ và sau một lần thu gom rác là dấu hiệu rò rỉ, còn tải thật thì RAM lên xuống theo lưu lượng; lưu ý RSS của Python hiếm khi trả bộ nhớ về OS nên phải so RSS sau khi ép gc chứ không chỉ nhìn RSS tăng. Trace của một request chậm phân rã thời gian theo từng nhịp để biết p99 nằm ở database, cache hay lời gọi ngoài. Lệnh chứng minh: docker stats --no-stream cho ảnh chụp tức thời, và docker logs --since 10m web | grep -c 500 để đếm lỗi trong cửa sổ sau deploy. Lưu ý: toàn bộ mô tả trên là hành vi theo tài liệu Docker và Linux, không phải kết quả chạy trên máy này.',
followups: [
{q: 'Bạn phân biệt rò rỉ bộ nhớ với tải tăng thật thế nào?', a: 'Bạn xem RAM có tăng đều khi tải đã hạ và có quay về sau thu gom không. Rò rỉ thường tăng đơn điệu, kèm số đối tượng và thời gian thu gom tăng. Tải thật thì RAM lên xuống theo lưu lượng và trở lại khi hết cao điểm.'},
{q: 'Bạn phân biệt lỗi ứng dụng với cạn kết nối thế nào?', a: 'Bạn xem log có stack trace của code hay toàn lỗi timeout và hàng đợi đầy. Metric số kết nối database, hàng đợi và file mô tả mở giúp xác nhận. Trace kẹt ở nhịp chờ kết nối gợi ý cạn pool chứ không phải logic sai.'}
],
pitfalls: ['Kết luận deploy gây lỗi chỉ vì trùng thời gian mà chưa loại trừ lưu lượng và phụ thuộc ngoài', 'Thiếu request id nên log và trace không khớp nhau được'],
selfcheck: ['Tôi vẫn chưa giải thích được cách chọn ngưỡng cảnh báo p99 và tỉ lệ 5xx tránh báo động giả', 'Tôi có thể giải thích bằng ví dụ dùng trace chỉ ra nhịp database chiếm phần lớn p99', 'Tôi có thể khoanh vùng một đợt 5xx thực tế từ dashboard tới đúng log và trace mẫu'],
refs: ['docker-compose', 'signal-man']
},
{
id: 'H11',
group: 'H',
topic: 'Git merge, rebase, conflict, revert và reset theo tình huống',
prio: 'P2',
level: 'L2',
type: 'situation',
incident: "<p>Tình huống giả định: Một nhánh tính năng bị lệch 60 commit so với nhánh chính. Dev chọn rebase để có lịch sử sạch, và trong quá trình xử lý 14 xung đột, một thay đổi của đồng nghiệp bị ghi đè và mất. Việc mất mát chỉ được phát hiện ba ngày sau trên production. Ngoài ra, cùng nhánh đó đã được đẩy lên máy chủ chung và hai người khác đang làm việc trên nó.</p>",
askFirst: ["Rebase thay đổi điều gì, và điều đó nguy hiểm ở đâu?","Khi nào không được rebase một nhánh đã chia sẻ?","Làm sao hoàn tác một thay đổi đã lên production?"],
predict: {"q":"Bạn rebase một nhánh đã được đẩy lên máy chủ chung và đồng nghiệp đã kéo về. Chuyện gì xảy ra với lịch sử của họ?","a":"<p>Lịch sử phân kỳ: các commit của nhánh đã bị viết lại thành commit mới với định danh khác, nên nhánh trên máy đồng nghiệp và nhánh trên máy chủ không còn chung tổ tiên ở đoạn đó. Khi họ kéo về, Git sẽ cố hợp nhất hai lịch sử và tạo ra xung đột hoặc nhân bản commit, và nếu họ vô tình đẩy lên thì lịch sử cũ quay trở lại. Đây là lý do quy tắc là: rebase chỉ dùng cho nhánh riêng chưa chia sẻ, còn nhánh đã chia sẻ thì dùng merge."},
anchor: "Rebase viết lại lịch sử nên chỉ an toàn trên nhánh riêng — viết lại nhánh đã chia sẻ là làm hỏng lịch sử của người khác.",
attacks: [{"q":"Làm sao hoàn tác một thay đổi đã lên production?","a":"Nếu thay đổi đã được chia sẻ, hoàn tác bằng cách tạo một commit mới đảo ngược nó, vì cách này không viết lại lịch sử nên an toàn cho mọi người. Chỉ dùng cách viết lại lịch sử khi commit chưa từng được đẩy đi. Một điểm thực tế quan trọng: nếu thay đổi đó kèm migration database, hoàn tác mã không hoàn tác được schema, nên cần một migration đảo ngược riêng hoặc một bước khôi phục dữ liệu. Đó là lý do các thay đổi phá huỷ cần được tách khỏi thay đổi mã."},{"q":"Làm sao giảm xung đột khi nhiều người cùng làm việc?","a":"Bốn thói quen có tác động lớn nhất. Một là tích hợp thường xuyên — nhánh sống ngắn, vài ngày chứ không phải vài tuần. Hai là chia nhỏ thay đổi theo chiều dọc, mỗi thay đổi chạm ít tệp. Ba là tránh việc định dạng lại toàn bộ tệp trong cùng một thay đổi với thay đổi logic, vì nó làm mọi dòng thành xung đột. Bốn là thống nhất quy ước đặt tên và cấu trúc thư mục, vì xung đột nặng nhất thường đến từ việc di chuyển và đổi tên tệp."}],
q: 'Khi nào bạn chọn merge, rebase, revert hay reset, và lệnh nào có nguy cơ mất dữ liệu cần cảnh báo?',
oral: 'Bạn chọn theo đã đẩy code hay chưa và mục tiêu là giữ lịch sử hay sửa sai an toàn. Merge giữ đầy đủ lịch sử phân nhánh, phù hợp nhánh tính năng đã chia sẻ. Rebase làm lịch sử thẳng và sạch nhưng chỉ dùng cho nhánh riêng chưa đẩy, vì viết lại lịch sử đã chia sẻ gây rắc rối cho cả nhóm. Revert tạo commit mới đảo ngược commit cũ nên an toàn cho nhánh chung. Reset di chuyển con trỏ nhánh và có thể xóa commit và thay đổi, nguy hiểm nhất khi dùng cờ cứng trên nhánh đã đẩy.',
deep: '<p>Trước Git, team dùng SVN hoặc CVS với nhánh trung tâm; hợp nhất là một bước, và việc viết lại lịch sử gần như không tồn tại. Khi Git ra đời, rebase cho phép gọt bỏ nhánh rẽ thành dòng thẳng, nhưng cũng mở ra nguy cơ ghi đè thay đổi của người khác.</p><p>Hôm nay bạn chọn theo bốn lệnh: <code>merge</code> tạo commit hợp nhất giữ nguyên lịch sử rẽ nhánh; <code>rebase</code> sao chép từng commit lên nền mới nên lịch sử thẳng nhưng đổi mã commit; <code>revert</code> thêm commit đảo ngược thay vì xóa; <code>reset</code> di chuyển con trỏ nhánh, dạng cứng xóa cả thay đổi trong cây làm việc.</p><p>Quy tắc: nhánh riêng thì rebase lên main mới; nhánh đã chia sẻ chỉ dùng merge; main deploy lỗi thì revert; reset cứng chỉ dùng trên nhánh cá nhân sau khi đã có bản sao. Chỗ vẫn còn sai: rebase rồi ép đẩy nhánh chung làm đồng nghiệp mất commit, hoặc dùng reset cứng trên nhánh đã đẩy thay vì revert an toàn. Khi lỡ tay, reflog là cách tìm lại mã commit trong thời gian nó còn giữ.</p><p>Người phỏng vấn cần nói được: merge giữ lịch sử phân nhánh; rebase chỉ an toàn trên nhánh riêng; revert an toàn trên nhánh chia sẻ; reset cứng nguy hiểm nhất khi dùng trên nhánh đã đẩy. Lỗi phổ biến là rebase rồi ép đẩy nhánh chung hoặc dùng reset cứng thay vì revert.</p>',
code: null,
expected: null,
followups: [
{q: 'Giải conflict thế nào cho an toàn?', a: 'Bạn mở từng file conflict, hiểu cả hai phía thay vì chọn bừa một bên, giữ lại test liên quan, chạy lại lint và test rồi mới commit tiếp. Với rebase, bạn giải quyết từng commit một và dùng tiếp tục sau mỗi bước.'},
{q: 'Vì sao reset cứng nguy hiểm và cứu thế nào khi lỡ tay?', a: 'Vì reset cứng xóa commit khỏi nhánh và xóa thay đổi chưa commit. Bạn chỉ dùng khi chắc chắn có bản sao. Khi lỡ tay, bạn cần tìm lại mã commit qua nhật ký reflog nếu còn, nên quy tắc là sao lưu nhánh trước khi reset.'}
],
pitfalls: ['Rebase rồi ép đẩy nhánh chung làm đồng nghiệp mất commit', 'Dùng reset cứng trên nhánh đã đẩy thay vì revert an toàn'],
selfcheck: ['Tôi vẫn chưa giải thích được reflog giữ commit bị reset trong bao lâu và khi nào hết cứu được', 'Tôi có thể giải thích bằng ví dụ chọn revert cho main đã deploy lỗi và reset cho nhánh riêng', 'Tôi có thể xử lý một conflict merge thực tế mà không làm mất test của đồng nghiệp'],
refs: ['gh-actions']
},
{
id: 'H12',
group: 'H',
topic: 'Xử lý sự cố và cải tiến từ phản hồi người dùng',
prio: 'P2',
level: 'L3',
type: 'situation',
incident: "<p>Tình huống giả định: Người dùng báo qua kênh hỗ trợ rằng nút xuất báo cáo \"đôi khi không hoạt động\". Phiếu được chuyển cho đội kỹ thuật, nhưng không có mã lỗi, không có thời điểm, không có trình duyệt, và không ai tái hiện được. Phiếu nằm đó hai tuần. Khi có người thử lại với tài khoản của chính người báo, lỗi tái hiện ngay: báo cáo vượt quá thời gian chờ khi có hơn 50.000 dòng.</p>",
askFirst: ["Thông tin nào còn thiếu để biến báo cáo này thành việc làm được?","Vì sao lỗi không tái hiện được ở môi trường của đội?","Sau khi sửa, làm sao biết sửa đúng và không lặp lại?"],
predict: {"q":"Một báo cáo lỗi chỉ nói \"nút không hoạt động\". Bước đầu tiên bạn làm là gì?","a":"<p>Biến nó thành một câu hỏi kiểm tra được: lỗi xảy ra với tài khoản nào, vào thời điểm nào, trên dữ liệu nào, và trình duyệt nào. Cách nhanh nhất thường là hỏi lại người báo một vài câu cụ thể, hoặc dùng chính tài khoản và dữ liệu của họ để tái hiện. Việc này quan trọng vì phần lớn thời gian của một sự cố nằm ở chỗ hiểu sai vấn đề, không nằm ở chỗ sửa. Và nếu hệ thống có định danh request trả về cho người dùng, bước này có thể rút ngắn từ ngày xuống còn phút.</p>"},
anchor: "Một báo cáo lỗi không tái hiện được không phải là vấn đề khó, mà là vấn đề chưa được mô tả đủ để trở thành câu hỏi kiểm tra được.",
attacks: [{"q":"Làm sao rút ngắn vòng lặp từ lúc người dùng báo tới lúc bạn hiểu vấn đề?","a":"Bốn việc, theo thứ tự chi phí tăng dần. Một là hiển thị một mã tham chiếu cho mỗi lỗi và yêu cầu người dùng gửi kèm — mã này tra ra được log tương ứng. Hai là ghi lại các hành động gần nhất của phiên để tái dựng đường đi. Ba là có một cách để tái hiện với dữ liệu của chính người dùng trong môi trường an toàn, vì nhiều lỗi phụ thuộc vào hình dạng dữ liệu chứ không phụ thuộc vào code. Bốn là một kênh cho phép người dùng gửi ảnh chụp hoặc bản ghi màn hình, vì với lỗi giao diện thì một ảnh nói nhiều hơn một đoạn mô tả."},{"q":"Sau khi sửa xong, làm sao đóng vòng lặp cho đúng?","a":"Ba bước. Một là xác nhận với chính người đã báo rằng vấn đề đã hết, trên đúng dữ liệu và tài khoản của họ — vì đó là người duy nhất biết chắc. Hai là thêm một kiểm tra tự động để lỗi đó không quay lại: một test, một ràng buộc, hoặc một cảnh báo. Ba là trả lời câu hỏi vì sao lỗi này không bị phát hiện sớm hơn, và sửa luôn khoảng trống đó nếu chi phí hợp lý. Điều nên tránh là đóng phiếu ngay sau khi deploy mà không xác nhận, vì nếu vấn đề vẫn còn thì người dùng sẽ mất niềm tin vào cả kênh báo cáo."}],
q: 'Khi hệ thống gặp sự cố production và sau đó nhận nhiều phản hồi người dùng, bạn xử trí sự cố và biến phản hồi thành cải tiến thế nào?',
oral: 'Khi sự cố xảy ra, bạn ưu tiên giảm thiệt hại trước rồi mới tìm nguyên nhân gốc. Bạn khoanh vùng ảnh hưởng, thông báo trạng thái rõ ràng, dùng cờ tính năng hoặc rollback có kiểm soát để trả lại dịch vụ. Song song đó bạn thu thập log, metric và trace theo mốc thời gian. Sau khi hệ thống ổn, bạn viết báo cáo sự cố gồm timeline, nguyên nhân gốc và hành động khắc phục. Với phản hồi người dùng, bạn gom nhóm theo vấn đề, chấm điểm theo mức độ và tần suất, làm bản sửa nhỏ nhất rồi đo lại.',
deep: '<p>Trước SRE và postmortem không đổ lỗi, sự cố được xử lý qua điện thoại với người trực; phản hồi người dùng nằm trong email và không ai đo lại sau khi sửa. Khi downtime ảnh hưởng doanh thu, áp lực là giảm thiệt hại trước, rồi mới tìm nguyên nhân.</p><p>Hôm nay, incident handling gồm phát hiện, giảm thiệt hại, khắc phục và học sau sự cố. Bạn khoanh vùng ảnh hưởng, thông báo trạng thái rõ ràng, dùng cờ tính năng hoặc rollback có kiểm soát để trả lại dịch vụ, song song thu thập log, metric và trace theo mốc thời gian. Với phản hồi người dùng, bạn gom nhóm theo vấn đề, chấm điểm theo tần suất và mức đau, làm bản sửa nhỏ nhất rồi đo lại.</p><p>Chỗ vẫn còn sai: mải tìm nguyên nhân gốc trong lúc downtime thay vì giảm thiệt hại trước; hoặc chạy theo phản hồi to nhất mà bỏ qua phản hồi lặp lại nhiều nhất. Khi sự cố lặp lại sau khi đã sửa triệu chứng, bạn nâng thành vấn đề kiến trúc.</p><p>Người phỏng vấn cần nói được: ưu tiên giảm thiệt hại trước, ghi timeline, báo cáo sự cố không đổ lỗi; phản hồi người dùng phải gom nhóm, chấm điểm theo tần suất và mức ảnh hưởng, làm bản sửa đo được. Lỗi phổ biến là mải tìm nguyên nhân gốc trong lúc downtime hoặc bỏ qua phản hồi lặp lại.</p>',
code: null,
expected: null,
followups: [
{q: 'Báo cáo sự cố tốt gồm những gì?', a: 'Báo cáo gồm tóm tắt ảnh hưởng, timeline theo mốc thời gian, nguyên nhân gốc, hành động khắc phục ngay và hành động ngăn lặp lại có người chịu trách nhiệm và hạn xong. Báo cáo không đổ lỗi mà tập trung vào lỗ hổng quy trình.'},
{q: 'Bạn ưu tiên phản hồi người dùng thế nào khi nguồn lực có hạn?', a: 'Bạn gom phản hồi thành chủ đề, chấm theo tần suất, mức đau và số người ảnh hưởng, trừ đi chi phí làm. Bạn làm bản nhỏ nhất có thể đo được trước, rồi mở rộng khi số liệu cải thiện.'}
],
pitfalls: ['Mải tìm nguyên nhân gốc trong lúc downtime thay vì giảm thiệt hại trước', 'Làm theo phản hồi to nhất thay vì phản hồi lặp lại nhiều nhất'],
selfcheck: ['Tôi vẫn chưa giải thích được cách đặt mức độ sự cố và tiêu chí huy động theo từng mức', 'Tôi có thể giải thích bằng ví dụ dùng cờ tính năng để giảm thiệt hại rồi viết báo cáo sự cố', 'Tôi có thể biến một chùm phản hồi trùng lặp thành một cải tiến có số liệu đo sau triển khai'],
refs: ['gh-actions', 'docker-compose']
},
{
id: 'H13',
group: 'H',
topic: 'Deploy AWS từ CI: OIDC, ECR, tag bất biến, rollback',
prio: 'P0',
level: 'L2',
type: 'situation',
incident: "<p>Tình huống giả định: 14h30, pipeline deploy lên production fail vì vai trò triển khai không có <code>ecr:PutImage</code>. Bạn bật lại và thấy vai trò đó còn đang dùng một access key dài hạn được dán vào một comment trong repo cách đây hai năm — key đó hiện nằm trong nhật ký của một nhánh tính năng bị xóa. Nếu key bị đánh cắp hôm qua, kẻ tấn công dùng được quyền của vai trò đó tới ECR, và key không có ngày hết hạn để tự vô hiệu.</p>",
askFirst: [
  'OIDC thay access key dài hạn như thế nào và điều kiện nào gắn kèm?',
  'Vì sao tag latest lại phá rollback?',
  'Khi nào không nên dùng OIDC?'
],
predict: { q: 'CI đẩy image lên ECR báo lỗi trust policy dù secret đúng. Bạn đoán nguyên nhân ở đâu?', a: '<p>Điều kiện trust policy không khớp claim trong JWT: nhánh đẩy không nằm trong danh sách cho phép, tên repo sai, hoặc OIDC provider ARN trỏ nhầm tài khoản. Thiếu <code>ecr:PutImage</code> trên vai trò triển khai gây lỗi khác ở bước push chứ không phải ở bước lấy session tạm.</p>' },
anchor: 'OIDC khóa mỗi phiên CI vào repo và nhánh bằng JWT ngắn hạn = không còn khóa dài hạn để lộ; tag bất biến theo commit SHA = rollback luôn biết ảnh nào là bản tốt.',
attacks: [
  {q: 'Vì sao không dùng lại access key dài hạn dù nó đơn giản?', a: 'Vì access key dài hạn không có ngày hết hạn; một khi bị đánh cắp, kẻ tấn công dùng được tới khi bạn vô hiệu hóa key đó. Xoay key không bắt buộc ngừng dịch vụ: tạo key mới, cập nhật ứng dụng, vô hiệu hóa key cũ, theo dõi, rồi mới xóa; hai key có thể hoạt động song song trong lúc chuyển. Vấn đề thật là khó gắn mỗi lần dùng với người và commit nào. OIDC đảo ngược điều đó: GitHub Actions phát hành JWT, AWS cấp tạm thời có thời hạn khoảng một giờ, trust policy có thể gắn điều kiện theo repository, branch và sự kiện.'},
  {q: 'Làm sao rollback khi deploy thất bại?', a: 'Vì bạn gắn tag theo commit SHA trên repo ECR đã bật image tag immutability, và deployment production trỏ vào digest sha256 mà ECR trả về, nên rollback chỉ là redeploy cùng digest đã biết là tốt. Tag latest luôn bị ghi đè, nên dùng latest đồng nghĩa với mất điểm neo để quay về.'},
  {q: 'Khi triển khai nhiều môi trường hay nhiều tài khoản AWS, OIDC phức tạp thế nào?', a: 'Bạn tách vai trò theo môi trường và tài khoản, mỗi vai trò có trust policy chỉ cho phép nhánh cần thiết, mỗi môi trường có ECR repo riêng. Khi cần cross-account, vai trò CI ở tài khoản nguồn gọi sts:AssumeRole vào vai trò triển khai ở tài khoản đích; trust policy của vai trò đích phải liệt kê ARN của vai trò CI, và vai trò CI phải có quyền sts:AssumeRole tới ARN đó. Nguyên tắc vẫn là ít đặc quyền nhất và điều kiện nhánh chặt.'}
],
q: 'Khi bạn triển khai AWS từ CI bằng GitHub Actions, làm sao dùng OIDC thay access key dài hạn, đẩy image lên ECR, tag bất biến theo commit SHA, và rollback an toàn?',
oral: 'Deploy AWS từ CI không nên dùng access key dài hạn, vì key bị lộ thì có hiệu lực tới khi bạn vô hiệu hóa nó. Cách đúng là OIDC: GitHub Actions phát hành một JWT, AWS kiểm tra JWT qua OIDC provider rồi cấp temporary credentials có thời hạn mặc định khoảng một giờ, với trust policy giới hạn theo repository và branch. Quy trình: job build khai báo id-token: write, gọi configure-aws-credentials với role-to-assume và aws-region, đăng nhập ECR bằng session tạm, build image gắn tag theo commit SHA rồi push. Muốn tag thật sự bất biến, phải bật image tag immutability trên repo ECR, vì mặc định tag vẫn ghi đè được. Sau khi push, ghi lại digest sha256 mà ECR trả về; production trỏ vào digest đó, không dùng latest, nên rollback là trỏ lại digest cũ. Khi deploy thất bại, kiểm tra điều kiện trust policy (repo, branch) có khớp không, vai trò triển khai có đủ ecr:GetAuthorizationToken và ecr:PutImage chưa, và OIDC provider ARN có đúng không. Không dùng OIDC khi runner tự host không ra được tới GitHub để lấy token, hoặc hệ thống cũ bắt buộc khóa tĩnh. Khi xoay access key cũ, không cần ngừng dịch vụ: tạo key mới, cập nhật ứng dụng, vô hiệu hóa key cũ rồi mới xóa.',
deep: '<p>Trước OIDC, CI giữ access key dài hạn trong biến môi trường; key lộ thì vẫn có hiệu lực tới khi ai đó vô hiệu hóa nó. Khi pipeline chạy trên runner của bên thứ ba và nhiều team cùng truy cập AWS, thói quen đó không còn an toàn.</p><p>Hôm nay, GitHub Actions phát hành JWT, IAM OIDC provider kiểm tra chữ ký, và trust policy của vai trò cho phép <code>sts:AssumeRoleWithWebIdentity</code> kèm điều kiện repo và branch. AWS cấp temporary credentials có thời hạn; pipeline dùng nó để đăng nhập ECR và push image. Tag theo commit SHA chỉ bất biến khi repo ECR bật image tag immutability; mặc định tag vẫn ghi đè được. Sau khi push, pipeline ghi lại digest <code>sha256:...</code> mà ECR trả về, production chỉ trỏ vào digest đó.</p><p>Chỗ vẫn còn sai: team tin tag <code>latest</code> cho phép rollback, trong khi latest luôn bị ghi đè nên không còn điểm neo để quay về. Hoặc cấu hình OIDC quá rộng cho mọi nhánh, khiến nhánh độc hại cũng có quyền đẩy image lên ECR. Khi cross-account, vai trò CI ở tài khoản nguồn AssumeRole vào vai trò đích; trust policy của vai trò đích phải liệt kê vai trò CI.</p><p>Người phỏng vấn cần nói được: OIDC thay access key dài hạn bằng session tạm thời; ECR bật image tag immutability; production trỏ digest.</p>',
code: 'name: deploy\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    permissions:\n      id-token: write\n      contents: read\n    steps:\n      - uses: actions/checkout@v4\n      - uses: aws-actions/configure-aws-credentials@v4\n        with:\n          role-to-assume: arn:aws:iam::ACCOUNT:role/gh-actions-ecr\n          role-session-name: github-actions\n          aws-region: REGION\n      - name: Login to Amazon ECR\n        run: aws ecr get-login-password --region REGION | docker login --username AWS --password-stdin ACCOUNT.dkr.ecr.REGION.amazonaws.com\n      - name: Build and push\n        run: |\n          docker build -t ACCOUNT.dkr.ecr.REGION.amazonaws.com/app:${{ github.sha }} .\n          docker push ACCOUNT.dkr.ecr.REGION.amazonaws.com/app:${{ github.sha }}\n      - name: Record digest\n        run: aws ecr describe-images --repository-name app --image-ids imageTag=${{ github.sha }} --query "imageDetails[0].imageDigest" --output text',
expected: null,
followups: [
  {q: 'Khi pipeline fail vì trust policy không khớp, bạn đọc lỗi ở đâu?', a: 'Bạn đọc nhật ký CloudTrail của vai trò triển khai: call AssumeRoleWithWebIdentity bị từ chối, trong sự kiện có ghi điều kiện branch hay repo không khớp. Bạn không đoán; bạn tra call đó vì cùng một pipeline có thể fail ở các bước khác nhau.'},
  {q: 'Image đã đẩy lên ECR rồi, sao rollback vẫn không chạy được?', a: 'Thường vì bước rollback không có quyền giả vờ là vai trò triển khai, hoặc vì nó trỏ vào một tag mutable thay vì digest. Bạn cần cho bước rollback AssumeRole vào cùng vai trò với thời hạn đủ dài, và luôn trỏ bằng digest.'},
  {q: 'Làm sao biết image production là bản nào đã build từ commit nào?', a: 'Bạn ghi lại commit SHA và digest sha256 mà ECR trả về sau khi push; digest định danh đúng nội dung image nên không đổi. Deploy production lưu digest nào đang chạy. Không cần tag latest, và mỗi rollback luôn biết chính xác ảnh nào đã chạy.'}
],
pitfalls: [
  'Tin tag latest có thể rollback, trong khi latest luôn bị ghi đè nên không còn điểm neo để quay về',
  'Cấu hình OIDC quá rộng cho mọi nhánh nên một nhánh độc hại cũng có quyền đẩy image lên ECR',
  'Cho vai trò triển khai toàn bộ phép ecr:* thay vì chỉ các phép thật sự cần thiết'
],
selfcheck: [
  'Tôi vẫn chưa giải thích được JWT OIDC của GitHub chứa những claim nào và AWS kiểm tra chúng ra sao trong trust policy',
  'Tôi có thể giải thích bằng ví dụ một workflow build image tag theo commit SHA rồi đẩy lên ECR bằng session tạm',
  'Tôi có thể chuyển một pipeline đang dùng access key dài hạn sang OIDC + vai trò triển khai theo nhánh'
],
refs: ['gh-actions', 'docker-security']
},
);

