var QUESTIONS = QUESTIONS || [];
QUESTIONS.push(
  {
    id: 'I01',
    group: 'I',
    topic: 'Big-O và array, hash map, set, stack, queue',
    prio: 'P0',
    level: 'L2',
    type: 'concept',
    q: 'Khi nào bạn chọn array, hash map, set, stack hay queue cho một bài toán cụ thể, và Big-O của các thao tác chính trên từng cấu trúc là gì?',
    oral: 'Big-O mô tả cách chi phí tăng theo kích thước đầu vào nên bạn dùng nó để so sánh phương án trước khi tối ưu vi mô. Array cho truy cập theo chỉ số O(1), thêm cuối mảng O(1) trung bình, nhưng chèn hoặc xóa ở giữa tốn O(n) vì phải dời phần tử. Hash map và set có thêm, xóa, tìm kiếm trung bình O(1) nhờ hàm băm, nhưng trường hợp xấu có thể lùi về O(n) khi đụng độ nhiều. Stack là LIFO còn queue là FIFO: stack thêm và lấy ở cùng một đầu, queue thêm ở đuôi và lấy ở đầu, với deque các thao tác này đều đạt O(1). Bạn chọn theo hành vi truy cập: cần thứ tự và chỉ số thì dùng array, cần tra cứu theo khóa thì dùng hash map, cần kiểm tra tồn tại thì dùng set, cần hoàn tác thì dùng stack, cần hàng đợi công việc thì dùng queue.',
    deep: '<p><strong>Big-O</strong> mô tả tốc độ tăng của thời gian và bộ nhớ theo kích thước đầu vào <code>n</code>. Bạn dùng nó để loại sớm phương án không thể mở rộng, trước khi bàn đến tối ưu nhỏ.</p><ul><li><strong>Array:</strong> đọc ghi theo chỉ số <code>O(1)</code>, thêm cuối mảng <code>O(1)</code> trung bình, chèn hoặc xóa giữa mảng <code>O(n)</code> vì phải dời các phần tử còn lại, tìm kiếm tuyến tính <code>O(n)</code> nếu chưa sắp xếp.</li><li><strong>Hash map:</strong> thêm, xóa, tìm theo khóa trung bình <code>O(1)</code> nhờ hàm băm, trường hợp xấu <code>O(n)</code> khi nhiều khóa đụng độ vào cùng một xô băm.</li><li><strong>Set:</strong> tương tự hash map nhưng chỉ lưu khóa, phù hợp cho kiểm tra tồn tại và khử trùng lặp, trung bình <code>O(1)</code>.</li><li><strong>Stack:</strong> cấu trúc LIFO với <code>push</code> và <code>pop</code> ở một đầu, <code>O(1)</code>, dùng cho hoàn tác, duyệt sâu và phân tích cú pháp.</li><li><strong>Queue:</strong> cấu trúc FIFO với thêm ở đuôi và lấy ở đầu, <code>O(1)</code> khi dùng <code>deque</code>, dùng cho hàng đợi tác vụ và duyệt rộng.</li></ul><p>Bạn cần cấu trúc này vì mỗi bài toán có mẫu truy cập khác nhau. Dùng sai cấu trúc biến bài toán <code>O(1)</code> thành <code>O(n)</code> ở quy mô lớn. Khi dữ liệu nhỏ thì sự khác biệt không đáng kể, nhưng khi danh sách lên hàng trăm nghìn phần tử thì vòng lặp lồng nhau và tìm kiếm tuyến tính lặp lại sẽ làm API chậm rõ rệt.</p><p>Khi không nên dùng: không dùng array để kiểm tra tồn tại lặp lại trong vòng lặp lớn, không dùng hash map khi bạn cần giữ thứ tự sắp xếp phức tạp hoặc duyệt theo khoảng giá trị, không dùng queue mảng với <code>pop(0)</code> trong Python vì thao tác đó tốn <code>O(n)</code>.</p>',
    code: 'from collections import deque\nindex = {"an": 101, "binh": 102}\nprint("an" in index)\nseen = set(["an", "binh", "an"])\nprint(len(seen))\nstack = ["a", "b"]\nstack.append("c")\nstack.pop()\nqueue = deque(["job1", "job2"])\nqueue.append("job3")\nqueue.popleft()\nprint(list(queue))',
    expected: null,
    followups: [
      { q: 'Vì sao thêm cuối array là O(1) trung bình chứ không phải O(1) mọi lúc?', a: 'Vì mảng động thường cấp phát dư dung lượng nên lần thêm thông thường chỉ ghi vào ô trống với O(1). Thỉnh thoảng mảng đầy và phải cấp phát mảng lớn hơn rồi chép toàn bộ phần tử sang, lần đó tốn O(n). Chia đều chi phí chép cho nhiều lần thêm thì chi phí trung bình mỗi lần vẫn là O(1), gọi là O(1) khấu hao.' },
      { q: 'Khi nào hash map lùi về O(n) và bạn xử lý ra sao trong bài toán thực tế?', a: 'Khi nhiều khóa đụng độ vào cùng một xô băm hoặc hàm băm kém thì các thao tác phải duyệt chuỗi dài trong xô đó nên lùi về O(n). Trong thực tế bạn chọn khóa có hàm băm tốt, tránh khóa do người dùng điều khiển trực tiếp mà không giới hạn, và tách dữ liệu thành nhiều phân đoạn nhỏ. Nếu cần thứ tự thì kết hợp thêm cấu trúc có thứ tự thay vì ép hash map làm mọi việc.' },
      { q: 'Vì sao không dùng mảng với pop ở đầu làm queue, và deque khắc phục điều gì?', a: 'Vì mảng lưu liên tục nên mỗi lần lấy phần tử đầu phải dời toàn bộ phần tử còn lại sang trái một vị trí, tốn O(n). Nếu hàng đợi xử lý hàng nghìn tác vụ thì chi phí đó cộng dồn rất lớn. Deque lưu theo khối rời rạc nên thêm ở đuôi và lấy ở đầu đều O(1), đúng với hành vi FIFO của queue.' }
    ],
    pitfalls: ['Nhầm lẫn giữa chi phí trung bình và chi phí tệ nhất của hash map, cho rằng O(1) đúng trong mọi trường hợp', 'Dùng array để tìm kiếm tồn tại trong vòng lặp lớn thay vì set, biến bài toán O(n) thành O(n bình phương', 'Dùng mảng làm queue với thao tác lấy đầu mảng mà không biết nó tốn O(n) mỗi lần'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là khi nào đụng độ băm kéo hash map về O(n) trong hệ thống thật', 'Tôi giải thích được bằng ví dụ vì sao tra cứu theo khóa dùng hash map còn kiểm tra tồn tại dùng set với thao tác O(1) trung bình', 'Trong tình huống API chậm do tìm kiếm tuyến tính lặp lại, tôi đổi sang set hoặc hash map và đo lại thời gian phản hồi'],
    refs: ['py-datamodel', 'py-expressions']
  },
  {
    id: 'I02',
    group: 'I',
    topic: 'Khử trùng lặp và đếm tần suất bằng hash map và set',
    prio: 'P0',
    level: 'L2',
    type: 'predict',
    q: 'Đoạn mã Python sau in ra gì, và vì sao danh sách unique vẫn giữ đúng thứ tự xuất hiện đầu tiên?',
    oral: 'Bạn khử trùng lặp mà vẫn giữ thứ tự bằng cách tận dụng dict giữ thứ tự chèn, còn đếm tần suất bằng hash map với giá trị mặc định. Cách làm này chạy O(n) vì mỗi phần tử chỉ xử lý một lần. Bạn không nên dùng vòng lặp lồng nhau để đếm vì nó thành O(n bình phương). Lỗi phổ biến là dùng set để khử trùng rồi mong thứ tự giữ nguyên, hoặc quên giá trị khởi tạo khi đếm nên gặp lỗi khóa thiếu. Trong API thật, mẫu này dùng để chuẩn hóa danh sách email, đếm lượt bình chọn hoặc phát hiện mã giảm giá bị lặp.',
    deep: '<p><strong>Khử trùng lặp</strong> là loại bỏ phần tử lặp nhưng thường phải giữ thứ tự xuất hiện đầu tiên. <strong>Đếm tần suất</strong> là đếm mỗi giá trị xuất hiện bao nhiêu lần. Cả hai đều là ứng dụng trực tiếp của hash map và set.</p><ul><li><strong>Cách hoạt động:</strong> <code>dict.fromkeys</code> tạo dict từ dãy đầu vào nên khóa trùng sẽ ghi đè mà giữ vị trí chèn đầu tiên, chuyển lại thành list là xong. Đếm tần suất duyệt một lần và dùng <code>get</code> với giá trị mặc định để tăng bộ đếm.</li><li><strong>Vì sao cần:</strong> vòng lặp lồng nhau để kiểm tra trùng tốn <code>O(n)</code> bình phương, còn dùng set và dict chỉ tốn <code>O(n)</code> trung bình nên mở rộng tốt với danh sách lớn.</li><li><strong>Khi dùng và khi không:</strong> dùng mẫu này khi cần giữ thứ tự hoặc đếm chính xác bằng một lần duyệt. Không dùng set trần khi thứ tự quan trọng, vì set không đảm bảo thứ tự bạn mong muốn.</li></ul><p>Lỗi hay gặp là quên khởi tạo bộ đếm nên phải viết nhánh kiểm tra khóa thủ công, hoặc dùng <code>count</code> trong vòng lặp khiến mỗi lần đếm lại duyệt cả danh sách. Khi điều kiện thay đổi, ví dụ phần tử là dict không băm được, bạn phải chuyển sang khóa băm được như tuple hoặc chuẩn hóa chuỗi trước khi đếm.</p>',
    code: 'nums = [3, 1, 2, 3, 2, 1, 4]\nunique = list(dict.fromkeys(nums))\nfreq = {}\nfor n in nums:\n    freq[n] = freq.get(n, 0) + 1\nprint(unique)\nprint(freq)',
    expected: 'In ra hai dòng. Dòng một là [3, 1, 2, 4] vì dict.fromkeys giữ thứ tự xuất hiện đầu tiên và bỏ lần lặp sau. Dòng hai là {3: 2, 1: 2, 2: 2, 4: 1} vì mỗi phần tử được đếm đúng số lần xuất hiện sau một lần duyệt. Từ Python 3.7 dict giữ thứ tự chèn nên kết quả này ổn định.',
    followups: [
      { q: 'Vì sao dict.fromkeys giữ được thứ tự còn set thì không nên dùng khi cần thứ tự?', a: 'Vì từ Python 3.7 dict được đảm bảo giữ thứ tự chèn nên khóa xuất hiện đầu tiên giữ nguyên vị trí, khóa lặp sau chỉ ghi đè giá trị mà không tạo vị trí mới. Set không cam kết thứ tự lặp lại theo ý bạn nên dùng nó rồi chuyển thành list có thể cho thứ tự khác. Khi yêu cầu giữ thứ tự thì dict là lựa chọn đúng.' },
      { q: 'Độ phức tạp của cách đếm một lần duyệt là gì, và cách nào khiến nó thành O(n bình phương)?', a: 'Cách một lần duyệt là O(n) trung bình vì mỗi phần tử chỉ băm và cập nhật một lần. Nếu trong vòng lặp bạn gọi count trên cả danh sách cho từng phần tử khác nhau thì mỗi lần gọi lại duyệt hết danh sách nên thành O(n bình phương). Với danh sách lớn thì sự chênh lệch này quyết định API còn đáp ứng được hay không.' },
      { q: 'Nếu phần tử là dict hoặc list không băm được thì bạn xử lý ra sao?', a: 'Vì dict và list không băm được nên không thể làm khóa trực tiếp. Bạn cần rút ra một trường băm được làm khóa, ví dụ mã người dùng hoặc email đã chuẩn hóa, hoặc chuyển list thành tuple nếu thứ tự có ý nghĩa. Khi không có khóa tự nhiên thì phải chuẩn hóa dữ liệu trước rồi mới khử trùng và đếm.' }
    ],
    pitfalls: ['Tưởng set giữ thứ tự chèn nên khử trùng bằng set rồi ngạc nhiên khi thứ tự đổi', 'Dùng count trong vòng lặp khiến thuật toán phình thành O(n bình phương mà không hay', 'Quên giá trị mặc định khi đếm nên code rẽ nhánh phức tạp hoặc gặp lỗi khóa thiếu'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là cách chọn khóa băm được khi phần tử là dict lồng nhau phức tạp', 'Tôi giải thích được bằng ví dụ vì sao dict.fromkeys cho [3, 1, 2, 4] và vòng đếm cho tần suất đúng', 'Trong tình huống danh sách email trùng lặp, tôi viết hàm khử trùng giữ thứ tự và đếm tần suất bằng một lần duyệt'],
    refs: ['py-expressions', 'py-datamodel']
  },
  {
    id: 'I03',
    group: 'I',
    topic: 'Nhóm dữ liệu theo khóa bằng hash map',
    prio: 'P1',
    level: 'L2',
    type: 'code',
    q: 'Hãy viết hàm nhóm danh sách user theo phòng ban bằng hash map, và giải thích vì sao dùng setdefault hoặc defaultdict thay vì kiểm tra khóa thủ công?',
    oral: 'Bạn nhóm theo khóa bằng cách duyệt danh sách một lần và đẩy từng phần tử vào xô tương ứng trong hash map. Mỗi khóa là một phòng ban, mỗi giá trị là danh sách thành viên. Dùng setdefault hoặc defaultdict giúp bạn khỏi viết nhánh kiểm tra khóa tồn tại, code ngắn hơn và ít lỗi hơn. Cách này chạy O(n) trung bình và là mẫu rất phổ biến trong API báo cáo, trang quản trị và xử lý đơn hàng theo trạng thái. Lỗi hay gặp là quên khởi tạo danh sách cho khóa mới, hoặc dùng chung một danh sách cho nhiều khóa.',
    deep: '<p><strong>Nhóm theo khóa</strong> là biến danh sách phẳng thành hash map mà mỗi khóa ánh xạ tới danh sách các bản ghi cùng nhóm. Bạn gặp mẫu này khi làm báo cáo theo phòng ban, đơn hàng theo trạng thái hoặc bài viết theo chuyên mục.</p><ul><li><strong>Cách hoạt động:</strong> duyệt từng bản ghi một lần, lấy khóa nhóm từ bản ghi, thêm bản ghi vào danh sách của khóa đó trong hash map. Tra cứu và tạo xô đều trung bình <code>O(1)</code> nên toàn bộ là <code>O(n)</code>.</li><li><strong>Vì sao cần:</strong> API thường trả danh sách phẳng từ cơ sở dữ liệu, nhưng giao diện cần dữ liệu đã nhóm để hiển thị. Nhóm ở tầng ứng dụng giúp bạn không phải gọi nhiều truy vấn lặp lại cho từng nhóm.</li><li><strong>Khi dùng và khi không:</strong> dùng khi số nhóm vừa phải và toàn bộ dữ liệu đã nằm trong bộ nhớ. Không nên nhóm toàn bộ bảng khổng lồ trong bộ nhớ khi cơ sở dữ liệu có thể gom nhóm trực tiếp hiệu quả hơn.</li></ul><p>Lỗi phổ biến là kiểm tra khóa thủ công rồi quên khởi tạo, hoặc vô tình gán cùng một tham chiếu danh sách cho nhiều khóa. <code>setdefault</code> và <code>defaultdict</code> loại bỏ cả hai lỗi này. Khi điều kiện thay đổi, ví dụ khóa bị thiếu hoặc viết hoa không nhất quán, bạn cần chuẩn hóa khóa trước khi nhóm để tránh sinh ra hai nhóm thực chất là một.</p>',
    code: 'users = [\n    {"name": "An", "dept": "web"},\n    {"name": "Binh", "dept": "api"},\n    {"name": "Chi", "dept": "web"},\n]\ngroups = {}\nfor u in users:\n    groups.setdefault(u["dept"], []).append(u["name"])\nprint(groups)',
    expected: null,
    followups: [
      { q: 'setdefault giúp tránh lỗi gì so với kiểm tra khóa thủ công?', a: 'Nó gộp kiểm tra và khởi tạo thành một thao tác nguyên tử ở mức logic nên bạn không thể quên nhánh khởi tạo danh sách cho khóa mới. Code ngắn hơn và không lặp lại tên khóa hai lần. Với defaultdict thì việc khởi tạo còn tự động hoàn toàn, bạn chỉ cần gọi append mà không cần quan tâm khóa đã tồn tại hay chưa.' },
      { q: 'Khi nào bạn đẩy việc nhóm xuống cơ sở dữ liệu thay vì nhóm trong Python?', a: 'Khi dữ liệu quá lớn không vừa bộ nhớ hoặc bạn chỉ cần số lượng theo nhóm chứ không cần chi tiết từng bản ghi. Cơ sở dữ liệu có chỉ mục và phép gom nhóm tối ưu nên tránh tải hàng triệu dòng về ứng dụng. Ngược lại khi dữ liệu đã có sẵn trong bộ nhớ và số lượng vừa phải thì nhóm trong Python đơn giản và linh hoạt hơn.' },
      { q: 'Nếu trường dept bị thiếu hoặc viết hoa không nhất quán thì kết quả nhóm sai ra sao?', a: 'Truy cập trực tiếp khóa thiếu sẽ gây lỗi, còn giá trị Web và web sẽ tách thành hai nhóm khác nhau dù thực chất là một. Bạn cần dùng get với giá trị mặc định như Nhóm khác và chuẩn hóa chuỗi bằng strip và lower trước khi nhóm. Quy tắc này nên viết thành hàm chuẩn hóa dùng chung để mọi nơi nhóm giống nhau.' }
    ],
    pitfalls: ['Quên khởi tạo danh sách cho khóa mới nên gặp lỗi khi thêm phần tử đầu tiên của nhóm', 'Không chuẩn hóa khóa nhóm khiến Web và web tách thành hai nhóm khác nhau', 'Tải toàn bộ bảng lớn về bộ nhớ để nhóm trong khi truy vấn gom nhóm trực tiếp hiệu quả hơn'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là giới hạn bộ nhớ khi nhóm hàng triệu bản ghi trong một tiến trình', 'Tôi giải thích được bằng ví dụ nhóm user theo phòng ban với setdefault và độ phức tạp O(n)', 'Trong tình huống trang báo cáo cần gom đơn theo trạng thái, tôi viết hàm nhóm dùng chung kèm chuẩn hóa khóa'],
    refs: ['py-expressions', 'ts-handbook']
  },
  {
    id: 'I04',
    group: 'I',
    topic: 'Logic phân trang với slice và kiểm tra biên',
    prio: 'P1',
    level: 'L2',
    type: 'debug',
    q: 'Hàm phân trang JavaScript sau sai ở đâu, vì sao gọi với trang 1 lại trả về kết quả sai, và cách sửa đúng là gì?',
    oral: 'Hàm này sai ở công thức tính vị trí bắt đầu vì trang mà người dùng thấy thường bắt đầu từ 1 còn chỉ số mảng bắt đầu từ 0. Công thức đúng phải trừ một trước khi nhân với kích thước trang. Ngoài lỗi lệch một, hàm còn thiếu kiểm tra biên cho trang vượt quá, kích thước trang không hợp lệ và trang không phải số nguyên. Bản sửa đúng chuẩn hóa đầu vào, kẹp trang trong khoảng hợp lệ và trả về mảng rỗng hoặc trang cuối thay vì để lỗi lan ra giao diện. Đây là lỗi rất hay gặp trong API danh sách và bạn nên có kiểm thử cho trang đầu, trang cuối và trang vượt quá.',
    deep: '<p><strong>Phân trang</strong> là cắt danh sách thành từng trang cố định để API nhẹ và giao diện dễ duyệt. Lỗi trong câu này là <strong>lệch một đơn vị</strong> giữa số trang bắt đầu từ 1 và chỉ số mảng bắt đầu từ 0.</p><ul><li><strong>Cách hoạt động:</strong> với trang <code>page</code> và kích thước <code>pageSize</code>, vị trí bắt đầu đúng là <code>(page - 1) * pageSize</code> và vị trí kết thúc là <code>start + pageSize</code>. Hàm sai dùng <code>page * pageSize</code> nên bỏ qua đúng một trang đầu.</li><li><strong>Vì sao cần:</strong> phân trang sai khiến người dùng bỏ sót dữ liệu mà không hay biết, trang 1 hiện nội dung của trang 2 và bản ghi đầu tiên không bao giờ hiển thị.</li><li><strong>Khi dùng và khi không:</strong> dùng cắt mảng khi toàn bộ dữ liệu đã ở bộ nhớ và số lượng vừa phải. Không dùng cách này cho bảng lớn mà nên phân trang ở truy vấn với giới hạn và phần bù, kèm tổng số lượng riêng.</li></ul><p>Lỗi thường đi kèm là không kiểm tra biên: trang bằng 0, trang âm, kích thước trang bằng 0, trang vượt quá tổng số trang hoặc đầu vào không phải số. Bản sửa chuẩn hóa đầu vào thành số nguyên, kẹp trong khoảng hợp lệ và trả về kết quả rỗng có ý nghĩa. Khi điều kiện thay đổi, ví dụ dữ liệu thêm mới liên tục, phân trang theo số trang có thể trùng hoặc sót nên bạn chuyển sang phân trang theo con trỏ với mốc duy nhất.</p>',
    code: 'function paginate(items, page, pageSize) {\n  const start = page * pageSize;\n  const end = start + pageSize;\n  return items.slice(start, end);\n}\nconst items = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\nconsole.log(paginate(items, 1, 3));',
    expected: 'In ra [4, 5, 6] thay vì [1, 2, 3] như mong đợi. Nguyên nhân gốc là công thức start dùng page nhân trực tiếp mà quên trang 1 tương ứng chỉ số 0, nên mọi trang đều lệch về sau một trang. Sửa đúng là const start = (page - 1) * pageSize, kèm kiểm tra page và pageSize là số nguyên dương và kẹp page trong tổng số trang.',
    followups: [
      { q: 'Ngoài công thức sai, hàm này còn thiếu những kiểm tra biên nào?', a: 'Hàm thiếu kiểm tra page nhỏ hơn 1, pageSize nhỏ hơn 1, đầu vào không phải số nguyên và page vượt quá tổng số trang. Bản sửa nên ép kiểu và kiểm tra số nguyên dương, tính tổng số trang từ độ dài mảng, rồi kẹp page vào khoảng hợp lệ hoặc trả về mảng rỗng có ý nghĩa. Mỗi nhánh này cần một kiểm thử riêng để không tái phát.' },
      { q: 'Khi dữ liệu thay đổi liên tục thì phân trang theo số trang gặp vấn đề gì?', a: 'Khi có bản ghi mới chèn vào đầu danh sách giữa hai lần gọi thì cùng một số trang sẽ trỏ sang nội dung khác, gây trùng hoặc sót bản ghi. Giải pháp là phân trang theo con trỏ với mốc ổn định như mã tăng dần hoặc thời điểm tạo kèm mã. Mỗi phản hồi trả về con trỏ trang sau để lần gọi tiếp theo tiếp tục chính xác.' }
    ],
    pitfalls: ['Nhầm giữa số trang bắt đầu từ 1 và chỉ số mảng bắt đầu từ 0 nên mọi trang lệch một đơn vị', 'Quên kiểm tra trang vượt quá, kích thước trang bằng 0 hoặc đầu vào không phải số', 'Phân trang trong bộ nhớ cho bảng khổng lồ thay vì phân trang ở truy vấn dữ liệu'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là cách chọn mốc con trỏ ổn định khi sắp xếp theo nhiều cột', 'Tôi giải thích được bằng ví dụ vì sao paginate với trang 1 trả về [4, 5, 6] và công thức (page - 1) * pageSize sửa được lỗi', 'Trong tình huống API danh sách bỏ sót bản ghi đầu, tôi sửa công thức start và bổ sung kiểm thử trang đầu, trang cuối, trang vượt quá'],
    refs: ['ts-handbook', 'mdn-execution-model']
  },
  {
    id: 'I05',
    group: 'I',
    topic: 'Xử lý chuỗi: chuẩn hóa, tách và ghép',
    prio: 'P1',
    level: 'L1',
    type: 'predict',
    q: 'Đoạn mã Python sau in ra gì, và mỗi bước strip, lower, replace, split biến đổi chuỗi ra sao?',
    oral: 'Chuỗi trong Python là bất biến nên mỗi phương thức trả về chuỗi mới chứ không sửa tại chỗ. Strip cắt khoảng trắng hai đầu, lower hạ toàn bộ về chữ thường, replace xóa dấu phẩy và split tách theo khoảng trắng thành danh sách từ. Kết quả cuối là danh sách hai từ viết thường. Mẫu này dùng hằng ngày để chuẩn hóa dữ liệu người dùng nhập như tên, email và từ khóa tìm kiếm. Lỗi phổ biến là quên gán lại kết quả, hoặc tách chuỗi khi chưa xóa dấu câu nên từ dính ký tự lạ.',
    deep: '<p><strong>Xử lý chuỗi</strong> là chuẩn hóa và trích xuất thông tin từ văn bản trước khi lưu hoặc tìm kiếm. Chuỗi trong Python là <strong>bất biến</strong> nên mỗi phương thức trả về chuỗi mới, chuỗi gốc không đổi.</p><ul><li><strong>Cách hoạt động:</strong> <code>strip</code> cắt khoảng trắng hai đầu, <code>lower</code> hạ chữ hoa thành chữ thường, <code>replace</code> thay thế đúng chuỗi con được chỉ định, <code>split</code> không tham số tách theo cụm khoảng trắng bất kỳ và bỏ phần tử rỗng.</li><li><strong>Vì sao cần:</strong> dữ liệu nhập từ biểu mẫu thường thừa khoảng trắng, lẫn chữ hoa và dấu câu. Chuẩn hóa trước giúp tìm kiếm và so sánh chính xác, tránh lưu hai bản ghi thực chất là một.</li><li><strong>Khi dùng và khi không:</strong> dùng chuỗi phương thức cho pipeline chuẩn hóa ngắn gọn. Không dùng <code>lower</code> đơn giản cho so sánh không phân biệt hoa thường đa ngôn ngữ mà nên dùng <code>casefold</code> khi yêu cầu khắt khe hơn.</li></ul><p>Lỗi hay gặp là gọi phương thức mà quên gán lại kết quả vì tưởng chuỗi sửa tại chỗ, hoặc tách trước khi xóa dấu câu nên từ còn dính ký tự lạ. Khi điều kiện thay đổi, ví dụ cần giữ dấu phẩy trong địa chỉ hoặc tách theo dấu chấm phẩy của file nhập, bạn phải đổi thứ tự bước và chọn dấu tách phù hợp thay vì dùng mặc định.</p>',
    code: 's = "  Hello, World!  "\nprint(s.strip().lower().replace(",", "").split())',
    expected: 'In ra [hello, world!] dạng danh sách hai chuỗi. Chuỗi gốc mất khoảng trắng hai đầu sau strip, thành chữ thường sau lower, mất dấu phẩy sau replace rồi tách thành hai từ. Dấu chấm than còn lại vì replace chỉ xóa dấu phẩy được chỉ định.',
    followups: [
      { q: 'Vì sao phải gán lại kết quả khi xử lý chuỗi trong Python?', a: 'Vì chuỗi là bất biến nên mỗi phương thức tạo ra chuỗi mới thay vì sửa chuỗi gốc. Nếu bạn gọi s.strip() mà không gán lại thì kết quả bị bỏ đi và s vẫn giữ nguyên. Chuỗi các phương thức trong câu này hoạt động được vì mỗi bước trả về chuỗi mới làm đầu vào cho bước tiếp theo.' },
      { q: 'split không tham số khác gì split theo một dấu cách đơn?', a: 'Split không tham số tách theo cụm khoảng trắng bất kỳ gồm cách, tab và xuống dòng, đồng thời bỏ qua khoảng trắng thừa và phần tử rỗng. Split theo một dấu cách đơn thì tách đúng tại từng ký tự đó nên khoảng trắng liên tiếp sẽ sinh chuỗi rỗng. Với dữ liệu nhập tay không đều thì bản không tham số cho kết quả sạch hơn.' },
      { q: 'Khi nào lower chưa đủ và bạn cần casefold?', a: 'Khi so sánh không phân biệt hoa thường với ký tự ngoài bảng chữ cái tiếng Anh, ví dụ một số chữ Đức và Hy Lạp có quy tắc gập chữ đặc biệt. Casefold xử lý mạnh hơn lower cho mục đích so sánh. Với tên và email tiếng Việt thông thường thì lower đã đủ, nhưng với yêu cầu đa ngôn ngữ khắt khe bạn nên dùng casefold.' }
    ],
    pitfalls: ['Gọi phương thức xử lý chuỗi mà quên gán lại vì tưởng chuỗi sửa tại chỗ', 'Tách chuỗi trước khi xóa dấu câu nên từ kết quả còn dính ký tự lạ', 'Dùng lower cho mọi so sánh đa ngôn ngữ trong khi casefold phù hợp hơn'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là khác biệt đầy đủ giữa lower và casefold với ký tự ngoài tiếng Anh', 'Tôi giải thích được bằng ví dụ từng bước cho ra [hello, world!] và lý do dấu chấm than còn lại', 'Trong tình huống biểu mẫu nhập tên thừa khoảng trắng và lẫn chữ hoa, tôi viết pipeline chuẩn hóa trước khi lưu'],
    refs: ['py-expressions', 'py-datamodel']
  },
  {
    id: 'I06',
    group: 'I',
    topic: 'OOP, SOLID, DRY, KISS và rủi ro over-engineering',
    prio: 'P1',
    level: 'L3',
    type: 'concept',
    q: 'Hãy lấy một ví dụ thực tế minh họa một nguyên tắc SOLID cùng DRY hoặc KISS, và cho biết khi nào việc áp dụng quá mức trở thành over-engineering?',
    oral: 'Bạn dùng OOP để gom dữ liệu và hành vi liên quan thành đối tượng, SOLID để giữ thiết kế dễ thay đổi, DRY để tránh lặp logic và KISS để giữ giải pháp đơn giản nhất có thể. Ví dụ thực tế là tách tính tiền đơn hàng khỏi gửi email để mỗi lớp chỉ có một lý do thay đổi, rồi dùng chung một hàm tính phí thay vì chép công thức khắp nơi. Over-engineering xảy ra khi bạn tách quá sớm thành nhiều lớp trừu tượng cho yêu cầu chỉ có một trường hợp dùng, khiến sửa một dòng phải chạm năm file. Dấu hiệu là tên lớp chung chung, tầng trung gian không chứa logic và dự đoán tương lai không bao giờ tới.',
    deep: '<p><strong>OOP</strong> gom trạng thái và hành vi liên quan thành đối tượng. <strong>SOLID</strong> là năm nguyên tắc giữ thiết kế dễ mở rộng, trong đó nguyên tắc đơn trách nhiệm yêu cầu mỗi lớp chỉ có một lý do thay đổi. <strong>DRY</strong> yêu cầu mỗi kiến thức chỉ có một nơi duy nhất, còn <strong>KISS</strong> yêu cầu chọn giải pháp đơn giản nhất còn đáp ứng được yêu cầu.</p><ul><li><strong>Cách hoạt động:</strong> lớp tính tiền chỉ biết tính tiền, cổng gửi email chỉ biết gửi thư, service điều phối gọi hai thành phần qua ranh giới rõ ràng. Công thức tính phí nằm trong một hàm dùng chung nên sửa một nơi là đúng mọi nơi.</li><li><strong>Vì sao cần:</strong> khi tính tiền và gửi thư nằm chung một hàm thì sửa nội dung email cũng có nguy cơ làm hỏng tính tiền, và kiểm thử phải dựng cả hai hệ thống cùng lúc. Tách ra giúp kiểm thử từng phần độc lập và thay nhà cung cấp email mà không chạm logic tiền.</li><li><strong>Khi dùng và khi không:</strong> dùng khi logic đã lặp lần thứ hai hoặc khi thay đổi ở một trục gây rủi ro cho trục khác. Không tách khi yêu cầu mới ở dạng nháp và có thể bị xóa sau một tuần.</li></ul><p>Rủi ro <strong>over-engineering</strong> là trừu tượng hóa cho tương lai không tới: một giao diện chỉ có một lớp triển khai, một tầng trung gian chỉ chuyển tiếp gọi hàm, một hệ thống plugin cho ba giá trị cố định. Chi phí là mỗi thay đổi nhỏ phải sửa nhiều file và người mới mất nhiều ngày chỉ để theo luồng gọi hàm. Điều kiện thay đổi đáp án: với nguyên mẫu cần ra mắt trong một tuần thì một module rõ ràng kèm kiểm thử là đủ, còn với hệ thống nhiều đội ngũ cùng sửa trong nhiều năm thì ranh giới nghiêm ngặt và kiểm thử hợp đồng mới xứng đáng.</p>',
    code: 'class OrderPricer:\n    def total(self, items):\n        return sum(i["price"] * i["qty"] for i in items)\nclass EmailSender:\n    def send(self, email, text):\n        print("send to " + email)\nclass Checkout:\n    def __init__(self, pricer, mailer):\n        self.pricer = pricer\n        self.mailer = mailer\n    def run(self, items, email):\n        total = self.pricer.total(items)\n        self.mailer.send(email, str(total))\n        return total',
    expected: null,
    followups: [
      { q: 'Dấu hiệu nào cho thấy bạn đã tách lớp quá mức?', a: 'Dấu hiệu là sửa một hành vi nhỏ phải mở nhiều file, tên lớp chung chung như Manager hay Helper mà không nói rõ trách nhiệm, và tầng trung gian chỉ chuyển tiếp gọi hàm không thêm kiểm tra hay biến đổi nào. Một dấu hiệu nữa là giao diện chỉ có đúng một lớp triển khai suốt nhiều tháng. Khi thấy vậy bạn nên gộp lại thành một module rõ ràng cho đến khi có trường hợp dùng thứ hai thật sự.' },
      { q: 'Phân biệt DRY đúng với việc gộp nhầm hai logic chỉ tình cờ giống nhau?', a: 'DRY đúng là gộp khi hai đoạn code thay đổi cùng lý do và cùng nhịp, ví dụ công thức tính phí dùng ở nhiều nơi. Gộp nhầm là khi hai đoạn chỉ tình cờ giống nhau hiện tại nhưng thay đổi vì lý do khác nhau, ví dụ chiết khấu nhân viên và chiết khấu sự kiện. Gộp nhầm khiến sửa một chính sách làm hỏng chính sách còn lại, nên bạn giữ tách cho đến khi quy tắc thật sự hội tụ.' }
    ],
    pitfalls: ['Tạo giao diện và tầng trừu tượng cho yêu cầu chỉ có một trường hợp dùng, khiến code khó theo dõi', 'Gộp hai logic chỉ tình cờ giống nhau thành một hàm dùng chung rồi sửa một nơi làm hỏng nơi còn lại', 'Nhầm KISS với code cẩu thả, bỏ kiểm thử và đặt tên mập mờ rồi gọi đó là đơn giản'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là khi nào một giao diện trừu tượng mới thật sự xứng đáng với chi phí của nó', 'Tôi giải thích được bằng ví dụ tách OrderPricer khỏi EmailSender theo đơn trách nhiệm và gộp công thức tính phí theo DRY', 'Trong tình huống service vừa tính tiền vừa gửi thư khó kiểm thử, tôi tách hai trách nhiệm và giữ thiết kế đủ đơn giản cho quy mô hiện tại'],
    refs: ['py-datamodel', 'ts-handbook']
  },
  {
    id: 'I07',
    group: 'I',
    topic: 'Separation of concerns và dependency injection',
    prio: 'P2',
    level: 'L3',
    type: 'situation',
    q: 'Giả sử một service vừa gọi trực tiếp cơ sở dữ liệu vừa gửi email trong cùng một hàm, bạn tách lớp và áp dụng dependency injection ra sao để dễ kiểm thử?',
    oral: 'Separation of concerns nghĩa là mỗi thành phần chỉ lo một việc, còn dependency injection nghĩa là thành phần không tự tạo thứ nó cần mà nhận từ bên ngoài qua tham số khởi tạo. Bạn tách service thành kho lưu trữ lo dữ liệu và cổng gửi thư lo email, rồi truyền hai thành phần này vào service qua constructor. Nhờ đó kiểm thử có thể truyền bản giả nhẹ thay cho cơ sở dữ liệu và dịch vụ thư thật, giúp kiểm thử nhanh và ổn định. Khi điều kiện thay đổi như chuyển nhà cung cấp email hoặc dùng nhiều cơ sở dữ liệu, bạn chỉ thay thành phần được tiêm mà không sửa logic điều phối. Lỗi phổ biến là vẫn tạo cứng kết nối bên trong class hoặc truyền cả container chứa mọi thứ khiến ranh giới mờ trở lại.',
    deep: '<p><strong>Separation of concerns</strong> là tách mỗi trục thay đổi thành một thành phần riêng: truy cập dữ liệu, gửi thông báo và điều phối nghiệp vụ. <strong>Dependency injection</strong> là kỹ thuật truyền các thành phần phụ thuộc từ bên ngoài vào, thường qua <code>constructor</code>, thay vì để lớp tự tạo cứng chúng.</p><ul><li><strong>Cách hoạt động:</strong> service chỉ giữ luồng nghiệp vụ như tạo người dùng rồi gửi thư chào mừng, còn <code>userRepo</code> lo câu lệnh dữ liệu và <code>mailer</code> lo giao thức gửi thư. Thành phần khởi tạo ở ngoài quyết định dùng bản thật hay bản giả rồi tiêm vào qua tham số.</li><li><strong>Vì sao cần:</strong> khi tạo cứng kết nối trong hàm thì mỗi kiểm thử phải dựng cơ sở dữ liệu và gửi thư thật nên chậm và thiếu ổn định. Sau khi tiêm phụ thuộc thì kiểm thử truyền bản giả trong bộ nhớ, còn môi trường chạy thật tiêm bản kết nối thật.</li><li><strong>Khi dùng và khi không:</strong> dùng cho ranh giới có tác dụng phụ như dữ liệu, mạng và thời gian. Không tiêm mọi hằng số và hàm thuần túy vì chúng đã dễ kiểm thử và việc tiêm quá mức làm chữ ký hàm phình to.</li></ul><p>Thất bại thường gặp là tiêm cả container vạn năng để lớp tự lấy thứ cần, khiến phụ thuộc bị giấu và kiểm thử vẫn khó. Cách đúng là khai báo tường minh từng phụ thuộc ở <code>constructor</code>. Điều kiện thay đổi đáp án: với script một lần chạy thì gọi trực tiếp là đủ, còn với API lâu dài nhiều người sửa thì tiêm phụ thuộc kèm ranh giới rõ ràng mới giữ được tốc độ kiểm thử và khả năng thay nhà cung cấp.</p>',
    code: 'class UserService {\n  constructor(userRepo, mailer) {\n    this.userRepo = userRepo;\n    this.mailer = mailer;\n  }\n  async register(email) {\n    const user = await this.userRepo.create(email);\n    await this.mailer.send(email, "welcome");\n    return user;\n  }\n}\nconst fakeRepo = { create: async (e) => ({ id: 1, email: e }) };\nconst fakeMailer = { send: async () => true };\nconst svc = new UserService(fakeRepo, fakeMailer);',
    expected: null,
    followups: [
      { q: 'Vì sao tiêm qua constructor tốt hơn để lớp tự tạo kết nối bên trong?', a: 'Vì lớp tự tạo kết nối thì logic nghiệp vụ bị dính cứng với chi tiết hạ tầng nên kiểm thử bắt buộc dùng hạ tầng thật. Tiêm qua constructor đảo ngược quyền quyết định ra ngoài, cho phép mỗi môi trường chọn bản triển khai phù hợp. Kiểm thử dùng bản giả nhẹ còn môi trường thật dùng bản kết nối thật mà không sửa một dòng logic nào.' },
      { q: 'Khi nào dependency injection trở thành lạm dụng?', a: 'Khi bạn tiêm cả hằng số, hàm thuần túy và mọi chi tiết nhỏ khiến constructor dài mà không tăng khả năng kiểm thử. Một dạng lạm dụng khác là tiêm cả container vạn năng để lớp tự lấy thứ cần, khiến phụ thuộc bị giấu và khó đọc. Quy tắc là chỉ tiêm ranh giới có tác dụng phụ và khai báo tường minh từng phụ thuộc.' },
      { q: 'Điều kiện nào khiến bạn chọn cách đơn giản thay vì tiêm đầy đủ?', a: 'Với script một lần, nguyên mẫu dùng một tuần hoặc công cụ nội bộ ít người dùng thì gọi trực tiếp giúp ra kết quả nhanh và ít chi phí. Khi code sống lâu, nhiều người sửa và kiểm thử chạy hằng ngày thì chi phí tạo cứng vượt xa chi phí tiêm. Bạn nâng dần mức tách lớp theo tuổi thọ và số người sửa code chứ không áp một mẫu cho mọi tình huống.' }
    ],
    pitfalls: ['Tự tạo kết nối dữ liệu và dịch vụ thư bên trong class nên kiểm thử bắt buộc dùng hạ tầng thật', 'Tiêm cả container vạn năng khiến phụ thuộc bị giấu và ranh giới giữa các lớp mờ trở lại', 'Tiêm mọi hằng số và hàm thuần túy khiến constructor phình to mà không tăng khả năng kiểm thử'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là cách quản lý vòng đời của đối tượng được tiêm trong ứng dụng lớn', 'Tôi giải thích được bằng ví dụ UserService nhận userRepo và mailer qua constructor kèm bản giả khi kiểm thử', 'Trong tình huống service khó kiểm thử vì gọi cứng dữ liệu và email, tôi tách hai cổng và tiêm bản giả cho kiểm thử'],
    refs: ['ts-handbook', 'py-datamodel']
  },
  {
    id: 'I08',
    group: 'I',
    topic: 'Chọn cấu trúc dữ liệu cho tác vụ API cụ thể',
    prio: 'P2',
    level: 'L1',
    type: 'concept',
    q: 'API cần kiểm tra username đã tồn tại, đếm lượt xem theo bài viết và lấy 20 thông báo mới nhất, bạn chọn cấu trúc dữ liệu nào cho từng nhu cầu và vì sao?',
    oral: 'Bạn chọn cấu trúc theo thao tác chính của từng nhu cầu. Kiểm tra username tồn tại là kiểm tra thành viên nên dùng set với O(1) trung bình thay vì duyệt mảng. Đếm lượt xem theo bài viết là ánh xạ từ mã bài viết sang số lượng nên dùng hash map với cập nhật O(1). Lấy 20 thông báo mới nhất là lấy đoạn cuối của dãy có thứ tự nên dùng mảng giữ theo thời gian rồi cắt đoạn cuối, hoặc deque khi cần thêm đầu và lấy đầu liên tục. Sai lầm phổ biến là dùng một mảng cho mọi việc rồi duyệt tuyến tính khắp nơi, khiến API chậm dần khi dữ liệu lớn. Với dữ liệu cần mở rộng nhiều máy thì bạn chuyển các cấu trúc này sang dịch vụ lưu trữ phù hợp thay vì giữ trong bộ nhớ một tiến trình.',
    deep: '<p>Chọn cấu trúc dữ liệu là ghép <strong>thao tác chính</strong> của bài toán với cấu trúc có thao tác đó rẻ nhất. Ba nhu cầu trong câu này thuộc ba mẫu khác nhau nên đáp án cũng khác nhau.</p><ul><li><strong>Kiểm tra username tồn tại:</strong> dùng <code>set</code> chứa tên đã chuẩn hóa, kiểm tra thành viên trung bình <code>O(1)</code>. Không dùng mảng rồi duyệt tuyến tính vì mỗi lần đăng ký tốn <code>O(n)</code>.</li><li><strong>Đếm lượt xem theo bài viết:</strong> dùng <code>hash map</code> từ mã bài viết sang bộ đếm, mỗi lượt xem chỉ cập nhật một khóa với <code>O(1)</code> trung bình. Không tạo mảng riêng cho từng bài viết vì lãng phí và khó tổng hợp.</li><li><strong>20 thông báo mới nhất:</strong> dùng mảng giữ theo thứ tự thời gian rồi cắt đoạn cuối, hoặc <code>deque</code> khi cần thêm và lấy ở hai đầu liên tục với <code>O(1)</code>.</li></ul><p>Bạn cần sự phân biệt này vì dùng một cấu trúc cho mọi việc khiến code vừa chậm vừa khó đọc. Lỗi phổ biến là quên chuẩn hóa username trước khi cho vào set nên An và an thành hai người khác nhau, hoặc quên giới hạn số thông báo nên mảng phình vô hạn. Khi điều kiện thay đổi như nhiều máy cùng phục vụ thì bạn chuyển set và hash map trong bộ nhớ thành dịch vụ lưu trữ dùng chung có tính bền và hết hạn phù hợp.</p>',
    code: null,
    expected: null,
    followups: [
      { q: 'Vì sao kiểm tra tồn tại bằng set tốt hơn duyệt mảng?', a: 'Vì set dùng hàm băm để nhảy thẳng tới vị trí cần kiểm tra nên chi phí trung bình là O(1) không phụ thuộc số lượng tên đã lưu. Duyệt mảng phải so sánh từng phần tử nên chi phí O(n) và tăng dần theo số người dùng. Với hệ thống có hàng trăm nghìn tài khoản thì chênh lệch này quyết định thời gian đăng ký.' },
      { q: 'Khi nào cấu trúc trong bộ nhớ không còn đủ và bạn chuyển sang lưu trữ dùng chung?', a: 'Khi API chạy nhiều máy, khi dữ liệu phải còn sau khi khởi động lại, hoặc khi nhiều tiến trình cùng cập nhật một bộ đếm. Lúc đó bạn chuyển sang dịch vụ lưu trữ dùng chung với tính bền, hết hạn và thao tác nguyên tử phù hợp. Cấu trúc trong bộ nhớ chỉ còn là bộ nhớ đệm chứ không phải nguồn sự thật duy nhất.' }
    ],
    pitfalls: ['Dùng mảng và duyệt tuyến tính cho kiểm tra tồn tại khiến chi phí tăng tuyến tính theo dữ liệu', 'Quên chuẩn hóa username nên tên trùng thực chất bị tính thành hai người khác nhau', 'Giữ danh sách thông báo phình vô hạn trong bộ nhớ mà không giới hạn số lượng'],
    selfcheck: ['Điều tôi vẫn chưa giải thích trôi chảy là cách chọn dịch vụ lưu trữ dùng chung khi API chạy nhiều máy', 'Tôi giải thích được bằng ví dụ set cho username, hash map cho lượt xem và cắt đoạn cuối cho 20 thông báo mới nhất', 'Trong tình huống API đăng ký chậm do duyệt mảng tên, tôi đổi sang set kèm chuẩn hóa tên trước khi kiểm tra'],
    refs: ['py-datamodel', 'mdn-execution-model']
  }
);
