var QUESTIONS = QUESTIONS || [];
QUESTIONS.push(
{
id: 'J01',
group: 'J',
topic: 'Khung giới thiệu bản thân 60-90 giây',
prio: 'P0',
level: 'L1',
type: 'situation',
q: 'Bạn hãy giới thiệu bản thân trong 60 đến 90 giây sao cho phù hợp với vị trí Fullstack Engineer?',
oral: 'Tôi làm backend Python và frontend JavaScript, tổng cộng khoảng năm năm. Phần API chủ yếu là Django và DRF, khi cần async và hiệu năng tôi chuyển sang FastAPI. Phần frontend tôi dùng React kèm TypeScript nên quen với state, hook và cách gọi API. Hạ tầng thì tôi đóng gói bằng Docker, tự viết pipeline build image, chạy migration và deploy, sau đó theo dõi log, metric và chi phí theo từng dịch vụ. Tôi cũng dựng một hệ thống RAG hybrid để tra cứu tài liệu nội bộ, kết hợp BM25 và vector trên pgvector, có reranking và bộ đánh giá. Tôi còn yếu ở trải nghiệm trực tiếp với AWS và với Vue, nên tôi đã dựng hạ tầng tương đương bằng Docker Compose để luyện trước. Tôi muốn vào đội để gia cố phần backend Python và hạ tầng, đồng thời lấp dần khoảng trống đó.',
deep: '<p><strong>Cấu trúc khung 90 giây:</strong></p><ol><li>0-15 giây: tên, số năm làm, stack chính, một câu định vị ngắn gọn về vai trò.</li><li>15-45 giây: hai bằng chứng cụ thể có hệ thống thật, nêu vấn đề đã giải quyết chứ không chỉ liệt kê công nghệ.</li><li>45-70 giây: hạ tầng và vận hành, Docker, pipeline, log, metric, chi phí.</li><li>70-90 giây: nói thẳng khoảng trống của bạn, rồi nối khoảng trống đó với việc team đang cần.</li></ol><p><strong>Vì sao khung này hiệu quả:</strong> sau 90 giây người phỏng vấn cần có đủ ba câu trả lời trong đầu: bạn từng làm gì, bạn giải quyết vấn đề gì, bạn có hợp với công việc không. Câu bốn, nói về khoảng trống một cách chủ động, giữ bạn ở thế chủ động thay vì bị hỏi thăm và lộ ra điểm yếu giữa buổi nói chuyện.</p><p><strong>Khi nào dùng và khi nào không dùng:</strong> ở vòng screening 20 phút bạn chỉ dùng 30 giây, ở vòng technical dài bạn dùng trọn 90 giây rồi để họ đào sâu từng ý. Nếu JD ghi rõ stack, bạn dồn thời gian vào phần trùng khớp nhất và cắt phần không liên quan. Nếu công ty chỉ cần người làm nhanh một module, bạn đổi trọng tâm từ kiến trúc sang tốc độ và độ ổn định.</p>',
code: null,
expected: null,
followups: [
{q: 'Nếu buộc phải giới thiệu trong 30 giây thay vì 90 giây, bạn cắt phần nào?', a: 'Tôi cắt theo thứ tự: bỏ chi tiết dự án thứ hai, bỏ chi tiết hạ tầng, giữ lại một bằng chứng cụ thể nhất và câu nối với vị trí. Với 30 giây thì người nghe chỉ nhớ được một con số và một câu, nên tôi chọn bằng chứng có số liệu rõ như số lượng người dùng, số request mỗi ngày hoặc số lần deploy mỗi tuần, và kết bằng một câu về điều tôi muốn làm cùng team.'},
{q: 'Bạn tự nêu khoảng trống AWS và Vue ngay trong phần mở đầu có làm giảm cơ hội không?', a: 'Tôi nghĩ đây là rủi ro thấp hơn việc để họ phát hiện giữa buổi nói chuyện. Nếu tôi giấu và bị hỏi sâu ở phần kỹ thuật, tôi mất điểm về tính trung thực. Nếu tôi nói ngay, tôi kiểm soát được khung câu chuyện và kèm theo bằng chứng chuẩn bị, chẳng hạn hạ tầng tương đương dựng bằng Docker Compose và bài tập triển khai Lambda cùng API Gateway. Điều tôi tránh là nói khiêm tốn chung chung kiểu em còn học.'},
{q: 'Câu nào trong phần giới thiệu tạo ấn tượng nhất với bạn?', a: 'Câu nói về vận hành và chi phí. Hầu hết ứng viên dừng ở việc viết code, còn tôi hay kể việc sau khi code lên chạy thì theo dõi thế nào, phát hiện lỗi qua metric nào, và chi phí tăng lên do đâu. Câu đó cho thấy tôi hiểu sản phẩm là một hệ thống đang chạy chứ không phải một nhánh code còn chưa ai dùng.'}
],
pitfalls: ['Kể lại CV theo thứ tự thời gian, không dẫn dắt người nghe vào điểm khớp với JD', 'Dùng toàn tính từ quá mức, mỗi ý một mô tả dài khiến 90 giây chỉ đủ nói hai ý', 'Giấu khoảng trống AWS và Vue, để bị hỏi thăm giữa chừng rồi trả lời lúng túng'],
selfcheck: ['Tôi vẫn chưa chốt được câu mở đầu 10 giây sao cho khác biệt thay vì nghe chung chung như mọi ứng viên khác', 'Tôi có thể kể lại trong 90 giây bằng ba bằng chứng cụ thể gắn với Django, FastAPI và pipeline Docker mà không đọc giấy', 'Tôi có thể cắt còn 30 giây mà vẫn giữ được một con số và một câu nối với vị trí đang tuyển'],
refs: ['mdn-http-overview', 'aws-lambda-best']
},
{
id: 'J02',
group: 'J',
topic: 'Feature end-to-end từ UI đến monitoring',
prio: 'P0',
level: 'L2',
type: 'situation',
q: 'Hãy kể một feature bạn từng làm đầy đủ từ UI, API, database, deploy cho tới monitoring?',
oral: 'Tôi từng làm chức năng lọc và xuất báo cáo doanh thu theo khoảng thời gian. Ở tầng UI tôi dựng form chọn khoảng ngày và bảng kết quả, xử lý trạng thái tải, lỗi và trường hợp rỗng riêng biệt, không để component gọi thẳng API. Ở tầng API tôi viết endpoint có phân trang, giới hạn khoảng thời gian tối đa và ghi log có request id để đối chiếu với log của tầng dưới. Ở tầng dữ liệu tôi thêm chỉ mục phù hợp với truy vấn lọc theo thời gian và trạng thái đơn, rồi đo bằng EXPLAIN trước khi lên production. Phần deploy đi qua pipeline: build image, chạy migration, canary nhỏ rồi mới tăng tải. Sau khi lên chạy tôi theo dõi độ trễ p95, tỉ lệ lỗi 5xx, số request và chi phí truy vấn theo ngày.',
deep: '<p><strong>Đây là gì:</strong> đây là câu hỏi kiểm tra bạn có thực sự sở hữu một feature từ đầu đến cuối hay chỉ làm một đoạn. Người phỏng vấn muốn nghe chuỗi liên kết giữa một quyết định ở UI với hậu quả ở database và chi phí vận hành.</p><p><strong>Cơ chế và lý do cần nó:</strong> một feature sống được vòng đời đi qua năm trạng thái: mô tả yêu cầu, hợp đồng dữ liệu, triển khai, quan sát và phản hồi. Nếu bạn kể thiếu một mắt xích, họ sẽ hỏi đúng mắt xích đó. Ví dụ nếu bạn chỉ nói có chỉ mục, câu hỏi tiếp sẽ là lấy cột nào, thứ tự cột ra sao và bạn đã đo EXPLAIN chưa.</p><p><strong>Khi nào dùng và khi nào không dùng:</strong> dùng mô tả theo đường đi của dữ liệu khi bạn cần chứng minh hiểu hệ thống, và dùng theo miền nghiệp vụ khi bạn không nhớ chi tiết kỹ thuật. Không nên kể một feature quá lớn trong 3 phút, và không nên chọn feature mà bạn chỉ tham gia một phần nhỏ. Nếu JD thiên về hạ tầng AWS, hãy chọn feature có đụng tới hàng đợi, lưu trữ hoặc triển khai tự động.</p><p><strong>Ví dụ cụ thể:</strong> nếu quyền truy cập khác nhau giữa khách hàng và nhân viên, hãy nói rõ bạn kiểm tra quyền ở tầng API chứ không phải ẩn nút ở UI, vì ẩn nút không phải bảo mật. Nếu xuất file lớn, hãy nói bạn đẩy job sang hàng đợi và trả về mã tác vụ, vì xử lý đồng bộ sẽ hết thời gian chờ của gateway.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn chọn chỉ mục cho truy vấn lọc theo khoảng thời gian và trạng thái như thế nào?', a: 'Tôi xuất phát từ câu SQL thật rồi xem EXPLAIN, không đoán. Với truy vấn lọc theo khoảng thời gian và một điều kiện trạng thái, tôi thường đặt cột thời gian trước vì nó có selectivity cao hơn, rồi cột trạng thái đứng sau. Nếu tỉ lệ trạng thái phân bố không đều, tôi cân nhắc partial index cho nhóm trạng thái phổ biến và loại bỏ những giá trị không ai lọc. Sau khi tạo index tôi đo lại cùng một câu truy vấn để so sánh số dòng đọc và thời gian thực tế.'},
{q: 'Monitoring sau khi deploy bạn cần những chỉ số nào và cảnh báo ở mức nào?', a: 'Tôi theo dõi tỉ lệ lỗi 5xx, độ trễ p95 và p99, throughput, và tỉ lệ lỗi 4xx để phân biệt lỗi máy chủ với lỗi phía người dùng. Tôi thêm metric nghiệp vụ như số tác vụ thất bại trong hàng đợi vì lỗi ở đó không hiện ra trên HTTP. Ngưỡng cảnh báo tôi đặt theo hành vi bình thường đã đo, ví dụ lỗi 5xx vượt 2 phần trăm trong 5 phút, và mọi cảnh báo phải có link tới dashboard và runbook để người trực xử lý được ngay.'},
{q: 'Nếu sau khi lên chạy truy vấn chậm hơn dự kiến, bạn xử lý theo thứ tự nào?', a: 'Tôi kiểm tra trước xem đây là lỗi code hay lỗi hạ tầng: xem log có lỗi không, đối chiếu độ trễ của database với độ trễ tổng, rồi kiểm tra traffic có đột biến không. Nếu tỉ lệ cache hit giảm thì tôi xem lại kích thước trang và TTL. Nếu lỗi nằm ở truy vấn, tôi mở EXPLAIN ANALYZE trên dữ liệu gần giống thực tế để xem estimate có lệch với thực tế không, thường là do index chưa được vacuum hoặc thiếu chỉ mục đúng cột. Nếu vẫn chưa rõ, tôi thêm log có thời lượng theo từng câu truy vấn thay vì đoán.'}
],
pitfalls: ['Kể chỉ phần backend, bỏ mặt UI và monitoring nên nghe như chưa từng làm việc end-to-end', 'Nhảy thẳng vào tên công nghệ mà không nói vấn đề gốc đã giải quyết', 'Nói quá chi tiết một tính năng nhỏ khiến 3 phút trôi qua mà không có kết luận'],
selfcheck: ['Tôi vẫn chưa chỉ ra được chỉ số nào trong bốn chỉ số cốt lõi thực sự phát hiện lỗi sớm nhất với hệ thống của tôi', 'Tôi có thể kể lại feature báo cáo doanh thu theo đúng chuỗi UI, API, chỉ mục, pipeline và canary trong 3 phút', 'Tôi có thể nhận ra ngay khi metric độ trễ tăng mà cảnh báo cũng tăng theo, và biết mở dashboard nào trước tiên'],
refs: ['mdn-http-overview', 'fastapi-tutorial', 'dockerfile-ref']
},
{
id: 'J03',
group: 'J',
topic: 'Bảo vệ quyết định thiết kế bằng ownership và tradeoff',
prio: 'P0',
level: 'L3',
type: 'situation',
q: 'Khi bạn bảo vệ một quyết định thiết kế trước team, bạn trình bày ownership và tradeoff như thế nào?',
oral: 'Tôi dùng bốn bước. Một, nói rõ tôi là người chịu trách nhiệm cho phần nào và tôi sẽ chịu hậu quả gì nếu sai. Hai, đưa ra lựa chọn của tôi kèm tiêu chí chọn, ví dụ độ trễ, chi phí, độ phức tạp vận hành. Ba, nói rõ tôi đã cân nhắc phương án nào khác và vì sao tôi loại. Bốn, mời phản biện và đề xuất cách kiểm chứng quyết định trong thời gian ngắn. Ví dụ một lần tôi chọn giữ truy vấn ở tầng database thay vì đưa sang tầng ứng dụng, vì dữ liệu chỉ vài triệu dòng và phần filter có điều kiện theo múi giờ. Tôi nói rõ nếu tải tăng gấp mười thì sẽ đo lại, và nếu độ trễ vượt ngưỡng thì sẽ chuyển sang chuyển tầng ứng dụng với bộ nhớ đệm. Như vậy tôi không bảo vệ lựa chọn của mình, tôi bảo vệ một tiêu chí đã nêu rõ.',
deep: '<p><strong>Đây là gì:</strong> đây là câu hỏi về kỹ năng kỹ thuật được bọc trong kỹ năng con người. Người phỏng vấn muốn biết bạn có đứng sau quyết định của mình hay chỉ trôi theo số đông, và bạn có chịu trách nhiệm khi nó sai không.</p><p><strong>Cơ chế của một lập luận tốt:</strong> quyết định thiết kế chỉ được chấp nhận khi có tiêu chí đo được. Nếu bạn nói giải pháp A nhanh hơn mà không có phép đo, mọi phản biện đều hợp lý. Bạn nên chuẩn bị sẵn phép đo: kết quả EXPLAIN, log độ trễ, ước tính chi phí lưu trữ, hoặc số giây thêm trong pipeline.</p><p><strong>Khi nào nên bảo vệ và khi nào nên nhường:</strong> hãy bảo vệ khi bạn có dữ liệu, khoảng trống nhỏ và đã nghĩ tới hậu quả. Hãy nhường khi đối phương có thông tin mà bạn thiếu, ví dụ áp lực deadline từ khách hàng hoặc ràng buộc vận hành mà bạn không nắm. Nhường một ý nhỏ để giữ quan hệ làm việc tốt hơn là giữ một ý đúng nhưng cũng đúng.</p><p><strong>Thay đổi câu trả lời khi điều kiện đổi:</strong> nếu team nhỏ dưới năm người, bạn nên giảm số lựa chọn được trình bày và tăng phần phương án thực thi. Nếu hệ thống đã có hàng chục service và chuẩn bảo mật nghiêm, một lựa chọn tối ưu tốc độ có thể không đáng đổi thêm rủi ro vận hành. Nếu bạn chỉ mới vào team và chưa nắm bối cảnh, bạn nêu quan điểm rồi xin thêm dữ liệu, chứ không tranh luận.</p><p><strong>Lỗi thường gặp:</strong> biến cuộc tranh luận thành so sánh người, tranh cãi bằng bằng chứng suông, hoặc lặp lại lập luận cũ khi đã có dữ liệu mới.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn nói gì khi quyết định của mình cuối cùng vẫn sai và đã gây sự cố?', a: 'Tôi nói thẳng tôi đã sai ở chỗ nào và bổ sung dữ liệu nào đã lệch so với giả định ban đầu. Tôi không bào vệ bằng cách nói quyết định hợp lý với thông tin lúc đó, vì thông tin mới đã thay đổi bối cảnh. Sau đó tôi mô tả điều gì đã bị ảnh hưởng, thời gian khắc phục mất bao lâu và tôi thêm bước kiểm tra nào để lỗi loại đó không tái diễn. Kết thúc bằng việc nếu có quy trình review tốt hơn thì đã bắt được sai sót sớm hơn.'},
{q: 'Làm sao phân biệt bảo vệ quyết định với bám chặt vào cách làm cũ?', a: 'Tôi tự kiểm tra ba điều: lập luận của tôi có dựa trên dữ liệu đo được không, rủi ro tôi nêu ra có được đo sau khi triển khai không, và nếu phương án khác rẻ hơn thì tôi chấp nhận đổi vì lý do nào. Nếu tôi giữ một lựa chọn chỉ vì tôi đã viết nó, đó là bám chặt. Ngược lại, nếu tôi nêu được điều kiện khiến tôi đổi ý, thì tôi đang bảo vệ một tiêu chí chứ không bảo vệ ego.'},
{q: 'Bạn trình bày khác đi gì nếu quyết định ảnh hưởng trực tiếp tới khách hàng và dữ liệu thật?', a: 'Tôi tách bạch hai lớp: lớp kỹ thuật và lớp rủi ro vận hành. Với lớp kỹ thuật tôi trình bày tiêu chí và phép đo. Với lớp rủi ro tôi nói rõ dữ liệu nào bị tác động, có cần migration và rollback được không, và giai đoạn nào chỉ chạy cho một nhóm nhỏ trước. Khi có dữ liệu thật, tôi luôn kèm kế hoạch canary và câu hỏi ai là người duyệt trước khi mở rộng, thay vì chỉ tranh luận về hiệu năng.'}
],
pitfalls: ['Bảo vệ quyết định bằng cảm tính, không kèm phép đo nào đo được', 'Liệt kê nhiều phương án cùng lúc nên nghe như chưa từng phải chọn thứ gì', 'Nhường bước quá sớm vì sợ gây khó chịu, rồi lặng lẽ làm ngược lại điều mình đề xuất'],
selfcheck: ['Tôi vẫn chưa biết cách trình bày rõ tiêu chí ưu tiên khi phải cân đo giữa độ trễ, chi phí và độ phức tạp vận hành', 'Tôi có thể kể lại một lần tôi đã đổi ý sau khi số liệu từ team đối tác cho thấy giả định của tôi sai', 'Tôi có thể khoanh vùng điều kiện khiến mình sẽ đổi quyết định, thay vì giữ mình một cách mơ hồ'],
refs: ['django-queries', 'fastapi-tutorial']
},
{
id: 'J04',
group: 'J',
topic: 'Điều tra bug production',
prio: 'P0',
level: 'L3',
type: 'situation',
q: 'Kể một lỗi production bạn đã xử lý và mô tả cách bạn điều tra từ đầu đến cuối?',
oral: 'Có một lần dịch vụ xuất báo cáo chậm dần sau mỗi đợt ca đêm. Tôi bắt đầu bằng cách xem dashboard: độ trễ p95 tăng dần chứ không tăng đột ngột, tỉ lệ lỗi vẫn bằng không, nhưng số hàng trong bảng tạm tính toán tăng đều. Tôi hạ mức ưu tiên dịch vụ xuất nhưng không tắt, rồi đọc log theo request id để xem thời gian nằm ở đâu. Kết quả cho thấy phần lấy dữ liệu vẫn nhanh nhưng bước tổng hợp chậm dần. Tôi kiểm tra mã, thấy có một câu truy vấn lấy toàn bộ lịch sử thay đổi trạng thái rồi lọc ở tầng ứng dụng, dữ liệu tăng dần theo thời gian. Tôi sửa bằng cách đẩy điều kiện lọc xuống truy vấn, thêm chỉ mục đúng cột, rồi triển khai. Sau đó tôi viết lại thao tác dọn bảng tạm theo lịch và thêm cảnh báo khi số bản ghi vượt ngưỡng. Bài học là cứu vãi phải đi kèm nguyên nhân gốc và một cơ chế ngăn tái diễn.',
deep: '<p><strong>Đây là gì:</strong> đây là câu hỏi đo năng lực vận hành. Người phỏng vấn theo dõi bạn ưu tiên tín hiệu nào trước, bạn giảm thiểu tổn thất ra sao, và bạn có sửa tận gốc hay chỉ vá triệu chứng.</p><p><strong>Cơ chế điều tra:</strong> sự cố được giảm thiểu trước và hiểu sau. Giảm thiểu có thể là hạ tải, tắt tính năng lỗi, tăng tài nguyên tạm thời, hoặc tăng hàng đợi để hệ thống không sập. Hiểu thì dựa trên ba nguồn: metric để biết phạm vi, log có request id để lần theo chuỗi gọi, và dữ liệu để xác nhận giả thuyết. Ba loại tín hiệu này phải khớp nhau mới đủ tin cậy.</p><p><strong>Khi nào dùng và khi nào không dùng:</strong> dùng mô tả theo timeline khi cần chứng minh khả năng hành xử dưới áp lực, và dùng theo nguyên nhân gốc khi người nghe muốn hiểu kỹ thuật. Không kể quá nhiều chi tiết cấu hình, và không kể một lỗi mà bạn chỉ là người nghe. Nếu lỗi do bên thứ ba, bạn nói rõ bạn làm gì để cô lập và giảm thiểu, không cần chỉ tên công ty.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> nếu lỗi xảy ra đúng một giờ mỗi ngày, nghi phạm lịch chạy hoặc bảo trì; nếu chỉ xảy ra với một nhóm người dùng, nghi phạn dữ liệu đầu vào đặc biệt; nếu độ trễ tăng theo thời gian, nghi phạm tích tụ dữ liệu. Nếu bạn đã có cảnh báo từ trước, câu chuyện bắt đầu bằng việc xác nhận cảnh báo đúng, điều này cho thấy giám sát đang hoạt động chứ không chỉ trưa trưng.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn làm gì để biết lỗi nằm ở tầng nào trước khi đọc mã nguồn?', a: 'Tôi dựng đường đi của một request thật qua từng tầng rồi so sánh thời gian từng đoạn. Nếu tổng thời gian tăng nhưng thời gian từng tầng riêng lẻ không đổi, khả năng cao là tích tụ ở hàng đợi hoặc thời gian chờ kết nối. Nếu thời gian của một tầng tăng theo tỷ lệ với lưu lượng, tôi nghĩ tới tài nguyên bị nghẽn. Tôi cũng đối chiếu số liệu của một phiên bản khác hoặc một region khác để xác nhận lỗi không nằm ở hạ tầng dùng chung.'},
{q: 'Vì sao câu chuyện kết bằng bài học và cơ chế ngăn tái diễn lại tạo ấn tượng?', a: 'Vì một sự cố đã xử lý không chứng minh năng lực, mà sự cố đã được chặn lại lần sau mới chứng minh. Người phỏng vấn muốn biết bạn có học từ dữ liệu hay chỉ sửa cho xong. Cơ chế ngăn tái diễn có thể là test hồi quy, cảnh báo có ngưỡng, quy trình review bắt buộc, hay tài liệu vận hành. Khi tôi kể được cả ba phần, người nghe hiểu rằng tôi xử lý sự cố như một quy trình, không phải như một sự kiện lẻ.'},
{q: 'Nếu bạn không tìm ra nguyên nhân trong 30 phút đầu, bạn làm gì?', a: 'Tôi dừng việc đoán nguyên nhân và chuyển sang giảm thiểu, đồng thời ghi lại những giả thuyết đã loại trừ kèm bằng chứng. Tôi nâng mức cảnh báo, bật log chi tiết hơn ở tầng nghi phạm và chuẩn bị phương án rollback vì nhiều lần giải pháp tạm thời lại gây sự cố thứ hai. Tôi cũng báo cho người quản lý để có người ra quyết định về việc công bố hay giới hạn phạm vi, vì ở mức ảnh hưởng lớn thì tốc độ thông tin quan trọng hơn việc tìm ra tên nguyên nhân.'}
],
pitfalls: ['Kể lại lỗi mà không nói mình đã làm gì giảm thiểu, nghe như chỉ biết sửa mã', 'Nhảy thẳng vào giả thuyết nguyên nhân mà không có metric hay log đi kèm', 'Khoe lỗi do người khác gây ra, mất điểm vì người nghe muốn nghe phần xử lý của bạn'],
selfcheck: ['Tôi vẫn chưa biết cách phân biệt chính xác độ trễ do hàng đợi với độ trễ do kết nối mạng chỉ bằng số liệu thô', 'Tôi có thể kể lại lỗi bảng tạm toán không dọn bằng timeline và chỉ ra bằng chứng nào dẫn tới giả thuyết đó', 'Tôi có thể chuẩn bị sẵn thao tác giảm thiểu và lệnh rollback trước khi bắt đầu điều tra một sự cố mới'],
refs: ['mdn-http-overview', 'django-queries']
},
{
id: 'J05',
group: 'J',
topic: 'Chiến lược kiểm thử unit, integration và e2e',
prio: 'P0',
level: 'L2',
type: 'concept',
q: 'Chiến lược kiểm thử của bạn thế nào, khi nào viết unit, khi nào viết integration và khi nào viết e2e?',
oral: 'Tôi chia theo tốc độ và chi phí. Unit test nhanh nhất, chạy mỗi lần lưu code, nên tôi dồn logic nghiệp vụ vào đó, đặc biệt là các thuật toán tính tiền, thuế và phân quyền, vì đây là chỗ sai một chút là hậu quả lớn. Integration test dùng cho các mối ghép mà unit test không chạm tới: truy vấn Django, transaction, gọi service ngoài, và tương tác với hàng đợi. Ở đây tôi dùng database thật trong container thay vì mock, vì phần lỗi hay nằm ở câu SQL và ràng buộc. E2E chỉ giữ cho vài luồng quan trọng như đăng nhập, thanh toán và tạo đơn, chạy trên môi trường giống thật. Tôi không viết E2E cho từng trường hợp biên vì bộ test sẽ chậm, đội sẽ bỏ dùng, và test hỏng nhiều sẽ làm mất niềm tin vào cả bộ kiểm thử.',
deep: '<p><strong>Đây là gì:</strong> kiểm thử là tầng bảo vệ rẻ nhất khi lỗi được phát hiện sớm. Ba loại test khác nhau về tốc độ, độ sâu thực tế và chi phí bảo trì, và nhiệm vụ là chọn đúng tầng cho từng loại rủi ro chứ không phải viết thật nhiều test.</p><p><strong>Cơ chế:</strong> unit test gọi trực tiếp hàm hoặc lớp với đầu vào đã biết và khẳng định đầu ra, nhanh vì không chạm hạ tầng. Integration test dựng môi trường thật tối thiểu, ví dụ database trong container, để kiểm tra SQL, ràng buộc, transaction và hành vi khi tối ưu hoặc cache bật. E2E chạy luồng thật qua nhiều dịch vụ nên chậm và dễ gãy vì lý do ngoài mã nguồn.</p><p><strong>Vì sao cần chiến lược:</strong> tổng thời gian chạy quyết định tần suất chạy. Nếu bộ test chậm, người ta bỏ chạy local, rồi lỗi chỉ lộ ra ở production. Nguyên tắc thực tế là phần lớn test nhanh, một phần nhỏ test sâu, và mọi test đều phải ổn định, không phụ thuộc thứ tự chạy.</p><p><strong>Khi nào không dùng:</strong> đừng mock cơ sở dữ liệu rồi khẳng định câu SQL, vì khi đó bạn chỉ chứng minh chuỗi ký tự bạn viết khớp với chuỗi bạn mong đợi. Cũng đừng để E2E chạy trên dữ liệu thật của khách hàng. Với logic phụ thuộc thời gian hoặc ngẫu nhiên, hãy tiêm đồng hồ và hàm sinh giả để kết quả tất định.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> nếu nhóm phát triển nhanh và hạ tầng CI giới hạn, bạn đẩy tỉ lệ E2E xuống và tăng mock tại biên. Nếu hệ thống xử lý tiền, bạn tăng cả coverage ở tầng nghiệp vụ và thêm test hồi quy cho mọi lỗi từng xảy ra, bất kể lỗi đó thuộc loại nào.</p>',
code: null,
expected: null,
followups: [
{q: 'Khi nào mock là lựa chọn đúng và khi nào mock che mất lỗi thật?', a: 'Mock hợp lý khi phụ thuộc là dịch vụ ngoài mà bạn không kiểm soát, hoặc khi bạn cần kiểm thử các nhánh lỗi như timeout và trả về dữ liệu bẩn. Mock nguy hiểm khi thứ bị thay thế chính là phần bạn cần kiểm tra, ví dụ repository hay truy vấn SQL. Quy tắc thực tế: càng gần trái tim hệ thống càng phải test với thật, càng xa biên càng dễ mock. Nếu bạn mock một hành vi mà chưa từng quan sát ở hệ thống thật, bạn có thể đang kiểm thử một hành vi không tồn tại.'},
{q: 'Bạn làm gì khi bộ test chạy chậm và bắt đầu bị bỏ qua?', a: 'Tôi đo trước: test nào chiếm phần lớn thời gian, thường là E2E và test chạm nhiều dịch vụ ngoài. Tôi tách bộ test thành các tầng để chạy song song trên CI, di chuyển phần chậm sang pipeline đêm, và cắt bớt case trùng lặp trong E2E. Song song tôi cấm thêm test E2E mới nếu chưa bù lại bằng test nhanh ở tầng dưới. Sau đó tôi đo lại thời gian và tỉ lệ test bị bỏ qua, vì cải tiến chỉ có giá trị nếu thói quen chạy test thay đổi theo.'},
{q: 'Bạn có dùng coverage làm tiêu chí không?', a: 'Tôi coi coverage là tín hiệu dò tìm chỗ chưa được kiểm thử, không phải mục tiêu cần đạt. Đặt ngưỡng cao chỉ khiến mọi người viết test vô nghĩa cho các dòng không quan trọng. Tôi dùng coverage để tìm các nhánh lỗi chưa có test, nhất là trong code xử lý tiền hoặc phân quyền, và dùng danh sách test bị xóa trong review để phát hiện độ phủ đang giảm dần theo thời gian.'}
],
pitfalls: ['Viết E2E cho mọi trường hợp biên khiến bộ test chậm và bị bỏ qua', 'Mock cơ sở dữ liệu rồi khẳng định câu SQL, nên lỗi cú pháp hay chỉ mục không bao giờ bị phát hiện', 'Tin rằng test nhiều hơn luôn tốt hơn, quên rằng bộ test giòn có chi phí bảo trì và làm mất niềm tin'],
selfcheck: ['Tôi vẫn chưa biết cách đo và loại bỏ test chậm nhất trong bộ của mình mà không làm hỏng độ phủ', 'Tôi có thể chỉ ra vì sao test chuyển khoản phải chạy ở tầng nghiệp vụ trong khi test gửi email thì chấp nhận mock', 'Tôi có thể khi thấy pipeline đỏ vì test gãy cụ thể, biết nó thuộc tầng nào và xử lý theo đúng thứ tự ưu tiên'],
refs: ['fastapi-tutorial', 'django-queries']
},
{
id: 'J06',
group: 'J',
topic: 'Trả lời trung thực khi chưa rành AWS và Vue',
prio: 'P0',
level: 'L3',
type: 'situation',
q: 'Bạn chưa dùng AWS và VueJS sâu như yêu cầu công việc, bạn sẽ trả lời câu hỏi này như thế nào?',
oral: 'Tôi tách rõ phần nào là kinh nghiệm thật và phần nào là kiến thức kèm thực hành tương đương. Kinh nghiệm thật của tôi là Python, Django, FastAPI, Docker và pipeline triển khai tự động. Với AWS tôi chưa có tài khoản production nên tôi không tạo bất kỳ sự cố nào trong production, tôi đã dựng chuỗi tương đương bằng Docker Compose gồm API, worker, PostgreSQL và Redis, rồi học cách ánh xạ từng khái niệm: hàng đợi khác message broker, gọi theo sự kiện khác webhook, Với Vue tôi chưa dùng trong dự án thật, tôi viết lại các bài toán quen bằng React và Vue: khi state dùng chung, khi nên tính lại giá trị, và cách tách phần dùng lại thành composable. Kỹ năng chuyển đổi giữa các framework đó tôi đã làm nhiều với React và Angular. Tôi không định giấu khoảng trống, và tôi sẵn sàng làm bài tập mà đội giao trong tuần đầu để chứng minh bằng kết quả chứ không bằng lời hứa.',
deep: '<p><strong>Nguyên tắc:</strong> trả lời câu hỏi về khoảng trống theo công thức bốn nhát: thừa nhận rõ, chỉ ra nền tảng liên quan đã có, mô tả cách đã chuẩn bị, và cam kết một việc kiểm chứng được. Bốn nhát này biến một câu trả lời phòng thủ thành một câu trả lời có kế hoạch.</p><p><strong>Cấu trúc câu trả lời:</strong></p><ol><li>Nói thẳng giới hạn: tôi chưa triển khai thật trên AWS, tôi không muốn tạo ấn tượng sai.</li><li>Nêu nền tảng chuyển đổi được: quy trình triển khai, container, hàng đợi, cấu hình theo môi trường, quan sát hệ thống.</li><li>Nói đã làm gì: dựng hệ thống tương đương, đọc tài liệu chính thức, viết bài tập có kiểm chứng.</li><li>Cam kết một việc cụ thể trong tháng đầu để chuyển kiến thức thành kinh nghiệm.</li></ol><p><strong>Ánh xạ khái niệm là phần quan trọng nhất:</strong> nhiều khái niệm AWS chỉ là tên gọi mới của thứ bạn đã dùng. Hàng đợi khác với broker là khác cách xử lý khi người nhận chết giữa chừng và khác ngữ nghĩa xác nhận. Container khác với Lambda là khác ranh giới trách nhiệm về việc vá lỗi hệ điều hành và đặt giới hạn tài nguyên. Nếu bạn nói được các ánh xạ này, câu trả lời của bạn có trọng lượng dù thiếu từ khóa thương hiệu.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> nếu JD yêu cầu chứng chỉ hoặc số năm cụ thể với AWS, bạn nói rõ điều đó là điều kiện bắt buộc và hỏi lại xem team có sẵn sàng đào tạo không. Nếu team đang trong giai đoạn chuyển sang serverless và không có người hướng dẫn, rủi ro cao hơn nhiều so với một team có người biết AWS sẽ review code của bạn. Nếu vị trí có thể chấp nhận người mạnh backend nhưng yếu frontend, hãy nói rõ bạn nhận phần backend trước và cam kết lịch cụ thể cho phần frontend.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn định lấp khoảng trống AWS bằng cách nào nếu được nhận?', a: 'Tôi dùng cơ chế học theo việc thật: ngày đầu đọc tài liệu chính thức và dựng một dịch vụ nhỏ chạy thật, ví dụ API Gateway nối Lambda đọc và ghi S3, rồi thêm CloudWatch log và cảnh báo chi phí. Sau đó tôi dùng chính dịch vụ đó để phục vụ một phần việc của team. Tôi ghi lại những chỗ khác với Docker mà tôi thật sự bị mắc, vì đó đúng là danh sách học có giá trị thay vì đọc hết mọi dịch vụ của AWS.'},
{q: 'Vì sao bạn tin bản thân chuyển đổi nhanh giữa các framework frontend?', a: 'Vì khung lớn gần như không đổi: component có props và state, dữ liệu đi qua một luồng một chiều, và luôn có câu hỏi ở đâu nên nguồn sự thật. Phần khác nhau nằm ở hệ sinh thái và cách quản lý vòng đời, mà đó là thứ tôi học bằng cách đọc và dựng một bài toán nhỏ, không phải thứ mất nhiều tháng. Trong các dự án trước tôi cũng từng chuyển giữa nhiều framework, nên kinh nghiệm đó là thật chứ không phải suông.'},
{q: 'Bạn có sẵn sàng làm bài test tay không, và bạn sẽ đề xuất bài gì?', a: 'Tôi sẵn sàng, và tôi sẽ tự đề xuất để chứng minh chủ động. Với backend tôi đề xuất viết một endpoint FastAPI kèm test, đóng gói bằng Dockerfile nhiều tầng, rồi triển khai lên một môi trường thật và theo dõi log. Với Vue tôi đề xuất dựng một màn hình danh sách có phân trang, tìm kiếm và xử lý trạng thái tải, kèm kiểm thử bằng Vitest. Bài như vậy nhỏ, kiểm chứng được và đúng vào việc team cần trong hai tuần đầu.'}
],
pitfalls: ['Nói dài dòng thừa về việc chưa biết, biến thành biện minh thay vì chuyển sang phần có thể đóng góp', 'Vờ thành thạo, dùng tên dịch vụ AWS một cách máy móc khi chưa hiểu giới hạn vận hành của nó', 'Chỉ nói sẽ tự học mà không đưa ra một việc cụ thể có thể kiểm chứng trong tháng đầu'],
selfcheck: ['Tôi vẫn chưa biết rõ giới hạn vận hành thực tế của Lambda về thời gian chạy, bộ nhớ và số request đồng thời', 'Tôi có thể giải thích ba khái niệm AWS bằng hệ thống tương đương tôi đã dựng bằng Docker Compose', 'Tôi có thể nêu tên một bài tập cụ thể kéo dài một buổi và tự chấm điểm bằng log thật'],
refs: ['aws-lambda-best', 'dockerfile-ref']
},
{
id: 'J07',
group: 'J',
topic: 'Giới thiệu dự án RAG hybrid',
prio: 'P1',
level: 'L3',
type: 'concept',
q: 'Bạn hãy trình bày dự án tra cứu tài liệu dùng RAG hybrid mà bạn đã tự xây, hoạt động ra sao?',
oral: 'Đó là hệ thống tra cứu tài liệu nội bộ cho một nhóm nhỏ. Tôi chia làm hai lớp: trước hết lấy ứng viên bằng BM25 trên nội dung đã tách đoạn, sau đó lấy ứng viên vector bằng mô hình nhúng lưu trong pgvector, rồi hợp nhất hai danh sách bằng công thức có trọng số. Ở bước cuối tôi đưa ứng viên qua mô hình xếp hạng lại để sắp xúng và loại bỏ đoạn không đủ liên quan, rồi mới đưa vào mô hình sinh. Luồng xử lý được mô tả bằng LangGraph để có trạng thái rõ ràng, có thể thử lại từng bước khi cần. Vận hành dùng Redis Streams để job cập nhật chỉ mục không chặn request, và có một bộ đánh giá gồm câu hỏi mẫu có đáp án để đo tỉ lệ đúng và mức độ trùng khớp.',
deep: '<p><strong>Đây là gì:</strong> RAG là kiểu truy xuất ngữ cảnh trước khi sinh câu trả lời. Bản hybrid dùng đồng thời tìm kiếm từ khoá và tìm kiếm theo vector, vì mỗi cách có điểm mạnh khác nhau và khi kết hợp sẽ bớt sót.</p><p><strong>Cơ chế từng lớp:</strong></p><ul><li>BM25 dựa trên tần suất từ và độ hiếm, mạnh với từ khoá chính xác, mã số, tên riêng, và yếu với câu hỏi diễn đạt khác.</li><li>Tìm kiếm vector dựa trên khoảng cách cosin giữa vector của câu hỏi và vector của đoạn văn, mạnh với nghĩa gần nhau, yếu với định danh chính xác.</li><li>Quy trình hợp nhất dùng công thức pha trộn điểm, thường kèm một lượt truy hồi bổ sung nếu tổng số ứng viên quá ít.</li><li>Xếp hạng lại với mô hình chấm điểm cặp câu hỏi và đoạn văn, giúp loại đoạn hợp về hình thức nhưng thiếu nội dung trả lời.</li><li>Đồ thị LangGraph giữ trạng thái của mỗi bước, cho phép thử lại một nhánh khi trung gian thất bại mà không phải chạy lại từ đầu.</li></ul><p><strong>Vì sao cần đánh giá:</strong> hệ thống truy xuất không thể kiểm chứng bằng cảm giác. Bộ câu hỏi mẫu kèm đáp án tham chiếu cho phép so sánh hai cấu hình tìm kiếm, đo số tài liệu được lấy đúng trong k mết đầu, và phát hiện hồi quy sau khi đổi mô hình nhúng.</p><p><strong>Khi nào không dùng:</strong> không dùng khi câu hỏi cần số liệu thay đổi theo thời gian, lúc đó phải gọi công cụ truy vấn dữ liệu sống. Cũng không nên bật hybrid nếu tập tài liệu nhỏ và đồng đều, vì chi phí vận hành hai đường truy hồi không thu được lợi ích.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> nếu câu hỏi trong hệ thống không chứa mã số hay tên riêng, chỉ cần một đường truy hồi là đủ và hệ thống đơn giản hơn nhiều. Nếu tài liệu cập nhật liên tục, phần đồng bộ chỉ mục trở thành nút thắt và cần kiểm soát tần suất cập nhật cùng phiên bản tài liệu.</p>',
code: null,
expected: null,
followups: [
{q: 'Vì sao cần kết hợp BM25 với tìm kiếm vector mà không chỉ dùng một trong hai?', a: 'Vì đặc điểm thất bại của chúng gần như bổ sung cho nhau. BMIM hiểu rõ từ khoá chính xác, mã số, tên hợp đồng, các thứ mà tìm kiếm theo nghĩa hay trượt vì từ đó hiếm hoặc không xuất hiện trong câu hỏi. Ngược lại, tìm kiếm theo vector bắt được các đoạn dùng từ hoàn toàn khác nhưng nói cùng một ý. Khi hệ thống có cả hai loại câu hỏi, dùng riêng một cách sẽ bỏ sót một nhóm, và đánh giá bằng bộ câu hỏi thật sẽ chỉ ra nhóm nào đang thiếu. Câu trả lời không nên là hybrid luôn tốt hơn, mà là hybrid tốt hơn ở tập câu hỏi có cả hai dạng.'},
{q: 'Đo chất lượng hệ thống RAG của bạn bằng cách nào?', a: 'Tôi có một tập câu hỏi mẫu kèm đoạn tài liệu đúng, và tôi đo nhiều tầng thay vì chỉ nhìn câu trả lời cuối. Tầng một là chất lượng truy hồi: tài liệu cần thiết có nằm trong danh sách ứng viên không, và xếp hạng của nó có đúng không. Tầng hai là chất lượng câu trả lời: có đúng ý không, có bịa thêm thông tin không có trong ngữ cảnh không. Ngoài ra tôi đo độ trễ toàn tuyến và số lượng token ngữ cảnh, vì một hệ thống trả lời đúng nhưng quá chậm và tốn kém vẫn không dùng được. Sau mỗi lần đổi mô hình hoặc tham số tôi chạy lại bộ đánh giá để phát hiện hồi quy.'}
],
pitfalls: ['Kể dự án theo danh sách công nghệ mà không nói bài toán người dùng và cách đo kết quả', 'Nói tìm kiếm hybrid luôn tốt hơn, quên rằng hiệu quả phụ thuộc đặc điểm câu hỏi thật', 'Nhảy từ ý tưởng thẳng tới triển khai, bỏ qua việc đánh giá chất lượng truy hồi'],
selfcheck: ['Tôi vẫn chưa nói được chính xác tại sao xếp hạng lại lại giảm được câu trả lời bịa nội dung ngoài ngữ cảnh', 'Tôi có thể giải thích lỗi truy hồi bằng một ví dụ câu hỏi chứa mã hợp đồng mà chỉ dùng vector thì trượt', 'Tôi có thể chạy lại bộ đánh giá trên cùng tập câu hỏi để so sánh hai cấu hình truy hồi trước khi đổi chính'],
refs: ['django-queries', 'aws-lambda-best']
},
{
id: 'J08',
group: 'J',
topic: 'Tradeoff giữa hai lựa chọn công nghệ',
prio: 'P1',
level: 'L2',
type: 'situation',
q: 'Hãy so sánh một lựa chọn bạn từng cân nhắc, ví dụ REST với GraphQL hoặc monolith với microservice, và nói rõ bạn chọn gì?',
oral: 'Tôi từng cân nhắc tách một monolith Django thành nhiều service để chạy độc lập, nhưng cuối cùng không làm. Lý do là các module thường gọi nhau trong cùng một luồng người dùng, tách ra lúc đó sẽ tạo nhiều lời gọi mạng cho mọi thao tác, đồng thời mất giao dịch xuyên suốt và làm việc gỡ lỗi khó hơn. Thay vào đó tôi giữ một tiến trình ứng dụng, tách phần nền tảng sẵn sàng nâng cấp: dùng chung một cơ sở dữ liệu có chủ quyền theo bảng, đưa việc nặng sang worker, và đặt mọi giao tiếp bên ngoài qua hàng đợi. Với REST so với GraphQL, tôi chọn REST vì phần lớn API của chúng tôi là vài chức năng CRUD, và GraphQL tốn thêm chi phí cho caching, giới hạn độ sâu truy vấn và giám sát, trong khi không mang lại lợi ích rõ.',
deep: '<p><strong>Đây là gì:</strong> câu hỏi này hỏi khả năng ra quyết định chứ không hỏi kiến thức thuộc lòng. Người phỏng vấn muốn biết bạn có tiêu chí chọn, có dữ liệu, và có chịu trách nhiệm khi chọn sai không.</p><p><strong>REST so với GraphQL:</strong></p><ul><li>REST định nghĩa sẵn các endpoint nên hợp đồng rõ, dễ cache theo URL, dễ kiểm thử, và mỗi client chỉ lấy đúng phần mình cần.</li><li>GraphQL cho phép client tự định nghĩa trường cần lấy, nên giảm số lần gọi thừa trên màn hình có nhiều widget.</li><li>Đổi lại, GraphQL đẩy tải lên server khi truy vấn phức tạp, dễ bị truy vấn tốn tài nguyên nếu không giới hạn, và cache phức tạp hơn vì truy vấn khác nhau cùng một tài nguyên.</li><li>Yêu cầu bảo mật cũng khác: kiểm tra phân quyền phải làm ở tầng resolver chứ không chỉ ở tầng endpoint.</li></ul><p><strong>Monolith so với microservice:</strong> monolith triển khai và gỡ lỗi đơn giản, giao dịch xuyên module dễ dàng, và chi phí vận hành thấp khi đội còn nhỏ. Microservice cho độc lập triển khai, cô lập lỗi và mở rộng theo từng phần, nhưng đòi hỏi hạ tầng quan sát, định tuyến, xử lý phân tán và lịch trình phối hợp. Ranh giới thực tế không nằm ở số service mà ở việc mỗi service có thể thay đổi và phát hành độc lập hay không.</p><p><strong>Khi nào đổi lựa chọn:</strong> REST là lựa chọn mặc định hợp lý cho đa số API. GraphQL đáng cân nhắc khi nhiều client khác nhau cần dữ liệu khác nhau trên cùng một nguồn và nhóm sản phẩm có thể chịu chi phí vận hành. Tách service chỉ nên làm khi một phần có chu kỳ phát hành hoặc yêu cầu mở rộng khác hẳn phần còn lại, chứ không phải vì số dòng code đã lớn.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn nói monolith nhưng vẫn chuẩn bị để tách, vậy ranh giới tách mà bạn chọn dựa vào đâu?', a: 'Tôi chọn ranh giới theo mức độ thay đổi độc lập và theo dữ liệu, không theo số module. Một phần được tách khi nó có chủ quyền dữ liệu rõ ràng, có chu kỳ phát hành riêng, và có nhu cầu mở rộng hoặc cô lập lỗi khác phần còn lại. Trước khi tách, tôi tách mã và dữ liệu ngay trong monolith: đặt ranh giới module, mỗi module tự truy cập bảng của mình, và mọi giao tiếp giữa module đi qua hàng đợi. Khi ranh giới đó đã chạy ổn định một thời gian, việc tách tiến trình mới là thay đổi kỹ thuật chứ không phải tái thiết kế. Nếu không làm bước trung gian đó, lần tách đầu tiên gần như luôn thất bại.'},
{q: 'Khi nào bạn sẽ khuyên đội chọn GraphQL thay vì REST?', a: 'Tôi khuyên khi có nhiều loại client khác nhau trên cùng một nguồn dữ liệu: web, mobile, và báo cáo, mỗi bên cần tập trường khác nhau và backend phải lặp lại nhiều endpoint chuyên biệt. Khi đó GraphQL loại bỏ phần dư thừa đó. Tôi không khuyên khi API chỉ phục vụ một client duy nhất, hoặc khi đội thiếu người giám sát chất lượng truy vấn, vì lúc đó chi phí cho giới hạn độ sâu, chống truy vấn quá nặng và kiểm soát cache sẽ lớn hơn lợi ích thu được.'}
],
pitfalls: ['Chọn công nghệ vì đang thịnh hành, không nêu được tiêu chí nào dẫn tới lựa chọn', 'Tranh luận bằng lý thuyết về khả năng mở rộng mà không có dữ liệu tải thật của hệ thống', 'Đổi hướng kiến trúc giữa chừng dự án mà không nói rõ chi phí chuyển đổi và kế hoạch giai đoạn'],
selfcheck: ['Tôi vẫn chưa nói được rõ điều kiện nào khiến monolith trở thành nút thắt thật sự trong dự án của tôi', 'Tôi có thể giải thích vì sao REST hợp với đa số API CRUD bằng ví dụ endpoint báo cáo đã tốn nhiều vòng gọi thừa', 'Tôi có thể đo được chi phí vận hành thêm của một lựa chọn trước khi áp dụng cho cả team'],
refs: ['mdn-http-overview', 'owasp-api-security']
},
{
id: 'J09',
group: 'J',
topic: 'Câu hỏi nên hỏi nhà tuyển dụng',
prio: 'P1',
level: 'L1',
type: 'situation',
q: 'Bạn sẽ hỏi những gì về khách hàng, sản phẩm, stack, onboarding và quy trình review khi phỏng vấn?',
oral: 'Tôi chia câu hỏi thành bốn nhóm và chọn hai câu cho mỗi nhóm, vì hỏi nhiều quá sẽ giống một bảng câu hỏi. Nhóm khách hàng và sản phẩm: đội đang phục vụ ai, nếu có ai đó dùng hệ thống hằng ngày thì đó là người thế nào, và feature nào trong ba tháng tới tạo ra tác động lớn nhất. Nhóm stack và phiên bản: hệ thống chạy trên hạ tầng nào, dịch vụ nào đã dùng, bao lâu được nâng cấp một lần, và có kế hoạch chuyển sang serverless không. Nhóm làm việc: vị trí này mang phần tích hợp với frontend hay chủ yếu backend, khi nào tôi được giao phần đầu tiên. Nhóm quy trình: một feature đi qua những bước gì từ khi bắt đầu đến khi lên chạy và ai là người duyệt.',
deep: '<p><strong>Đây là gì:</strong> câu hỏi của bạn là kênh để sửa thông tin bạn đang hiểu sai về công việc. Một công việc được mô tả đúng ở quảng cáo vẫn có thể rất khác ở thực tế, và bạn chỉ biết điều đó khi hỏi. Người phỏng vấn có xu hướng đánh giá cao người hỏi câu liên quan tới việc làm, và giảm điểm với câu chung chung.</p><p><strong>Nhóm câu hỏi nên dùng:</strong></p><ul><li><strong>Khách hàng và sản phẩm:</strong> hệ thống phục vụ ai, bao nhiêu người dùng thật, và feature nào sắp tới. Câu này cho bạn biết mức độ ưu tiên giữa chất lượng trải nghiệm và tốc độ phát triển.</li><li><strong>Stack và phiên bản:</strong> dịch vụ nào đang dùng, hệ thống tự chứa hay trên cloud, lịch nâng cấp thư viện, và có kế hoạch di cờ hạ tầng nào trong năm tới không. Đây là câu hỏi quan trọng nhất với hai khoảng trống AWS và Vue của bạn.</li><li><strong>Quy trình và trách nhiệm:</strong> một feature đi qua những bước gì, ai duyệt, sau khi lên chại ai là người trực sự cảm nhận hậu quả vận hành.</li><li><strong>Con người:</strong> người trong team giữ những phần nào, người nào hỗ trợ khi kẹt, và đào tạo nội bộ diễn ra thế nào.</li><li><strong>Kỳ vọng 90 ngày:</strong> sau khi nhận việc, thành tích nào được coi là bạn đã vào gu.</li></ul><p><strong>Phong cách đặt câu hỏi:</strong> hãy gắn câu hỏi vào một điều bạn vừa nghe trong cuộc phỏng vấn, ví dụ sau khi nghe mô tả về kiến trúc. Câu hỏi có ngữ cảnh cho thấy bạn đang lắng nghe, và cho phép bạn biết team có lường trước hay không.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> ở vòng cuối, khi bạn đã hiểu sản phẩm rồi, bạn chuyển sang hỏi về điểm khó nhất mà team đang gặp và cách họ đo thành công của người mới. Ở vòng học sinh thì hãy hỏi cụ thể về stack, vì đó là nơi bạn cần thông tin nhất để quyết định.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn sẽ hỏi gì nếu biết chắc mình thiếu kinh nghiệm AWS của đội?', a: 'Tôi sẽ hỏi trong team có ai đã làm với dịch vụ mà tôi sẽ phụ trách không, khi nào có việc liên quan thật để tôi tham gia, và có quy ước review thế nào cho dịch vụ đó. Tôi cũng hỏi quy trình hạ tầng được mô tả bằng gì, là hạ tầng bằng mã hay thao tác tay, vì điều đó quyết định tốc độ tôi học. Tôi không hỏi có đào tạo không, vì câu đó nghe như chờ được cấp phát, còn các câu trên cho tôi biết mình sẽ học theo cách nào ngay trong công việc thật. Câu hỏi tôi muốn nghe câu trả lời là quy trình review và triển khai chạy thế nào.'},
{q: 'Bạn có nên hỏi về lương và phúc lợi không, và hỏi vào lúc nào?', a: 'Tôi nghĩ nên hỏi, vì đây là thông tin hai bên cần biết, và hỏi sớm giúp cả hai bên tiết kiệm thời gian. Tôi đặt câu hỏi ở cuối buổi trao đổi, sau khi đã thống nhất về phần công việc, vì hỏi sớm dễ tạo cảm giác mục đích. Cách tôi hỏi là mở với khung mong muốn của mình rồi hỏi về cách đội xây dựng mức lương, ví dụ theo cấp bậc, kinh nghiệm và phạm vi trách nhiệm. Tôi cũng không né chủ đề bảo hiểm và ngày nghỉ, vì đó cũng là một phần của mức độ hợp tác dài hạn. Nếu phỏng vấn bên nhà tuyển dụng không phải người quyết định, tôi hỏi về bước tiếp theo và thời gian phản hồi.'}
],
pitfalls: ['Hỏi cả chục câu khiến buổi phỏng vấn biến thành một bản điền thông tin', 'Hỏi những gì đã đăng trong mô tả công việc, lãng phí lượt hỏi quý giá', 'Hỏi chỉ về quyền lợi mà không hỏi gì về công việc và cách team vận hành'],
selfcheck: ['Tôi vẫn chưa biết nên hỏi gì để tìm ra điểm bất khả thi tiềm ẩn trong cách họ triển khai hiện tại', 'Tôi có thể chọn từ mỗi nhóm một câu có ngữ cảnh sau phần họ đã trình bày', 'Tôi có thể nói rõ kỳ vọng 90 ngày của mình mà không hứa hẹn những gì chưa đo được'],
refs: ['owasp-api-security', 'mdn-http-overview']
},
{
id: 'J10',
group: 'J',
topic: 'Trình bày kết quả code review',
prio: 'P2',
level: 'L2',
type: 'concept',
q: 'Bạn trình bày kết quả code review như thế nào, khi cả nhận lẫn khi góp ý cho người khác?',
oral: 'Khi tôi nhận góp ý, tôi tách làm hai nhóm. Nhóm thứ nhất là điểm tôi đồng ý và sẽ sửa, tôi nói rõ sẽ sửa trong thay đổi này hay thay đổi sau kèm lý do. Nhóm thứ hai là điểm tôi chưa đồng ý, tôi không im lặng cũng không tranh luận; tôi hỏi lại mình đang bỏ sót điều gì và đề xuất cách kiểm chứng bằng dữ liệu hoặc bằng một thử nghiệm nhỏ. Khi tôi góp ý cho người khác, tôi luôn gắn mỗi ý với lý do và hậu quả cụ thể: lỗi này gây truy vấn quét toàn bảng, lỗi này để lộ dữ liệu qua log. Tôi tránh góp ý về hình thức không ảnh hưởng chức năng và luôn góp ý trên code, không đánh giá con người. Sau khi thảo luận xong, tôi tóm tắt lại thống nhất để tránh hiểu lầm.',
deep: '<p><strong>Đây là gì:</strong> code review là nơi kiến thức được lan truyền nhanh nhất trong một đội, và cũng là nơi phát sinh nhiều xung đột nếu thiếu kỹ năng giao tiếp. Chất lượng của một review phụ thuộc vào việc góp ý có giải được vấn đề hay chỉ làm người khác thấy bị phê bình.</p><p><strong>Cấu trúc một góp ý tốt:</strong></p><ol><li>Nêu loại và mức độ: lỗi chặn, lỗi, hay gợi ý.</li><li>Chỉ ra dòng hoặc đoạn liên quan.</li><li>Giải thích hậu quả cụ thể với hệ thống thật: dữ liệu lộ, truy vấn chậm, khó mở rộng sau này.</li><li>Đề xuất hướng sửa, không bắt buộc viết hộ cả đoạn nếu tác giả nhanh hơn.</li></ol><p><strong>Khi bạn là người nhận:</strong> phản ứng tệ nhất không phải là phản biện mà là im lặng rồi không sửa, vì đội sẽ dần ngừng góp ý. Hãy phản hồi từng điểm, kể cả điểm bạn không đồng ý. Khi bạn không đồng ý, bạn nói điều kiện khiến mình đồng ý, ví dụ nếu dữ liệu lớn hơn mức này thì ràng buộc cần đổi. Câu này biến bất đồng thành một phép kiểm chứng.</p><p><strong>Khi nào không nên làm:</strong> đừng gộp nhiều vấn đề khác nhau vào một nhận xét dài, vì tác giả không biết phần nào quan trọng nhất. Đừng gửi hàng chục nhận xét nhỏ vụn vặt trong một lần, và đừng né những lỗi lớn vì ngại. Một nhận xét dài đúng trọng tâm tốt hơn nhiều nhận xét ngắn sai thứ tự ưu tiên.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> với thay đổi nhỏ, review nhanh bằng comment trên dòng là đủ. Với thay đổi lớn, bạn review ở mức thiết kế trước khi đọc code, vì lỗi kiến trúc sửa sau rất tốn kém. Khi làm việc với người mới, bạn kèm luôn một gợi ý cụ thể thay vì chỉ nêu vấn đề, vì đó là cách duy nhất để họ tiến bộ.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn phản ứng thế nào khi không đồng ý với góp ý trong review?', a: 'Tôi phản hồi trực tiếp trên dòng đó, nêu lý do và đề xuất cách kiểm chứng thay vì phản bác bằng uy tín. Ví dụ nếu tác giả nói nên thêm chỉ mục cho một cột gần như không ai lọc, tôi sẽ hỏi tần suất lọc thực tế và đề xuất kiểm tra bằng truy vấn thống kê trước khi thêm. Nếu sau đó dữ liệu cho thấy tôi sai, tôi đồng ý ngay và cảm ơn tác giả đã bắt lỗi. Điều tôi tránh tuyệt đối là im lặng rồi không sửa, vì người khác sẽ không bao giờ góp ý nữa. Khi bất đồng về kiến trúc, tôi chuyển sang trao đổi nói nhanh ngoài code để tránh kéo dài vòng comment.'},
{q: 'Bạn có làm gì để việc review không bị biến thành cuộc tranh luận cá nhân không?', a: 'Tôi quy ước trước với đội về ngôn từ và thứ tự ưu tiên: vấn đề chặn được nêu trước, mỗi nhận xét đi kèm hậu quả cụ thể, và không có nhận xét nào về cách viết quen thuộc nếu không ảnh hưởng bảo trì. Tôi cũng tách vai trò: người viết giải thích ý định trước khi đọc chi tiết, vì nhiều khi góp ý đi ngược với ý định đã được thống nhất. Khi thấy một luồng review kéo dài quá ba vòng, tôi đề nghị chuyển sang trao đổi trực tiếp và ghi kết luận trở lại vào nhận xét, để người khác đọc lại được. Nếu có lịch sử xung đột lặp lại với một người, tôi báo lại để trưởng nhóm can thiệp sớm.'}
],
pitfalls: ['Góp ý mơ hồ kiểu làm lại đi mà không nêu hậu quả cụ thể', 'Phản biện để thắng thay vì kiểm chứng, biến review thành tranh luận ý kiến', 'Nhận góp ý nhưng im lặng không sửa, khiến cả đội ngừng góp ý'],
selfcheck: ['Tôi vẫn chưa biết cách diễn đạt một nhận xét về bảo mật mà không nghe như cáo buộc cả nhóm', 'Tôi có thể viết lại một góp ý kiểu chỉ ra lỗi thành góp ý nêu rõ loại, dòng, hậu quả và hướng sửa', 'Tôi có thể tóm tắt thống nhất sau một vòng review dài để không ai hiểu lầm kết luận'],
refs: ['mdn-http-overview', 'fastapi-tutorial']
},
{
id: 'J11',
group: 'J',
topic: 'Xử lý khi không biết câu trả lời',
prio: 'P2',
level: 'L2',
type: 'situation',
q: 'Trong phỏng vấn, khi bạn không biết câu trả lời bạn xử lý ra sao?',
oral: 'Tôi không đoán bừa. Tôi nói thẳng phần nào tôi chưa biết, sau đó tách ra hai việc: phần tôi biết chắc dù được dùng để giải quyết vấn đề, và phần tôi cần học thêm. Với phần biết, tôi đi từ nguyên nhân gốc và những rủi ro tôi nhận ra. Với phần chưa biết, tôi nói sẽ kiểm chứng bằng tài liệu hoặc bằng một thử nghiệm nhỏ, và nói rõ tôi sẽ mất bao lâu. Nếu câu hỏi nằm ngoài vai trò của tôi, tôi nói rõ phạm vi công việc của mình và chuyển sang phần liên quan đến phần tôi đã làm. Tôi xem một câu trả lời sai thành rủi ro lớn hơn một câu trả lời chưa đầy đủ, vì người phỏng vấn sẽ hỏi tiếp đúng chỗ sai đó.',
deep: '<p><strong>Đây là gì:</strong> câu hỏi hỏi cơ chế bạn xử lý bất định trước mặt người đánh giá. Một câu trả lời dối trá chắc chắn sẽ bị phát hiện ở tầng hỏi tiếp, còn một câu trả lời trung thực cho bạn cơ hội trình diễn cách bạn suy luận.</p><p><strong>Khuôn mẫu bốn bước:</strong></p><ol><li>Nhận diện giới hạn bằng một câu, không kéo dài giải thích.</li><li>Nêu phần bạn biết chắc liên quan, có gắn với kinh nghiệm thật.</li><li>Suy luận từ nguyên lý đã biết để đưa ra hướng giải quyết, nói rõ đó là suy luận chứ không phải kinh nghiệm.</li><li>Cam kết cách kiểm chứng và thời gian cần.</li></ol><p><strong>Tại sao không đoán:</strong> một câu trả lời bịa có thể đúng ở tầng đầu và hỏng ở tầng hỏi tiếp, và lúc đó bạn mất uy tín cho cả buổi phỏng vấn, không chỉ mất điểm của câu hỏi đó. Ngược lại, nói không biết nhưng đưa ra hướng giải quyết và lý do lại cho thấy bạn biết cách học trong bối cảnh không rõ.</p><p><strong>Khi nào nên hỏi lại:</strong> nếu câu hỏi mơ hồ về phạm vi hệ thống mà bạn không nắm, hãy hỏi lại một câu để làm rõ rồi trả lời. Nếu câu hỏi nằm ngoài vai trò của bạn, hãy nói thẳng rồi chỉ ra phần bạn thực sự phụ trách, vì trả lời sâu vào thứ mình không làm còn tệ hơn là nói không.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> trong phỏng vấn không chính thức, bạn có thể thoải mái nói rõ điều mình cần tra cứu vì không ghi chép. Với cuộc phỏng vấn có bài kiểm tra, bạn nói bạn sẽ tìm hiểu và trình bày lại, nhưng đừng kéo dài thời gian của cả nhóm vì đó là ảnh hưởng tới người khác. Nếu câu hỏi là về kiến thức nền tảng của ngành, đề xuất của tôi là học sâu hơn trước khi nói không biết, vì đây là phần không nên để trống.</p>',
code: null,
expected: null,
followups: [
{q: 'Nếu câu hỏi nằm ngoài phạm vi công việc của bạn, bạn xử lý thế nào?', a: 'Tôi nói rõ phần đó nằm ngoài phần tôi đã làm, rồi chuyển sang phần có liên quan. Ví dụ với câu hỏi về cấu hình mạng nội bộ mà tôi không phụ trách, tôi sẽ nói phần đó do đội hạ tầng đảm nhiệm và tôi chỉ làm việc phía trên nó, rồi trả lời phần liên quan tới cách dịch vụ được gọi, cách xử lý lỗi kết nối và cách chẩn đoán bằng log. Nếu tôi có chút kiến thức nền, tôi nói rõ đó là kiến thức đọc chứ không phải trải nghiệm vận hành. Như vậy tôi vẫn cho thấy mình có nền để học nhanh mà không tạo ấn tượng giả.'},
{q: 'Bạn sẽ làm gì sau câu trả lời nói không biết đó, ngoài việc học?', a: 'Tôi ghi lại câu hỏi đó vào danh sách kiến thức cần lấp, kèm nguồn tài liệu và thời gian dự kiến. Sau đó tôi kiểm chứng bằng một việc nhỏ có kết quả quan sát được, ví dụ dựng một ví dụ nhỏ trên môi trường cục bộ hoặc đọc mã nguồn thay vì đọc tài liệu. Khi đã hiểu, tôi viết lại câu trả lời thành một đoạn ngắn có ví dụ, vì lúc đó tôi sẽ nhớ lâu hơn và dùng lại được. Nếu là lỗi tôi mắc trong phỏng vấn thật, tôi đưa nó vào danh sách câu hỏi để ôn lại trước vòng sau.'}
],
pitfalls: ['Đoán bừa một câu trả lời nghe có vẻ hợp lý rồi bị hỏi tiếp tới mức lộ', 'Nói không biết rồi dừng luôn, mất cả phần mình thực sự biết', 'Xin phép hỏi lại để tránh trả lời, lạm dụng cách này với câu hỏi rõ ràng'],
selfcheck: ['Tôi vẫn chưa biết đâu là ranh giới giữa nói không biết và nói chưa chắc trong lúc phỏng vấn', 'Tôi có thể luyện câu trả lời cho một tình huống quen thuộc bằng cấu trúc bốn bước trong vòng ba mươi giây', 'Tôi có thể ghi lại câu hỏi sau buổi phỏng vấn và kiểm chứng bằng một ví dụ chạy được'],
refs: ['mdn-http-overview', 'owasp-api-security']
},
{
id: 'J12',
group: 'J',
topic: 'Kế hoạch hai tuần đầu học AWS và Vue',
prio: 'P2',
level: 'L1',
type: 'situation',
q: 'Nếu được nhận, kế hoạch học AWS và Vue trong hai tuần đầu của bạn là gì?',
oral: 'Tôi chia hai tuần thành bốn khối, mỗi khối gắn với một việc thật trong dự án. Ngày đầu tôi dựng môi trường chạy được toàn bộ hệ thống ở local, đọc cấu hình hạ tầng hiện có và hiểu một feature thật đi hết từ giao diện tới cơ sở dữ liệu. Tuần đầu tôi làm một luồng nhỏ trên AWS: API Gateway gọi Lambda đọc và ghi một bucket S3, có log và cảnh báo, và tôi đăng ký thẻ miễn phí giới hạn ngân sách để không phát sinh chi phí bất ngờ. Song song tôi học Vue bằng cách dựng lại màn hình đang có của dự án bằng component và composable, kèm test. Tuần hai tôi đưa luồng đó lên môi trường thật của công ty qua pipeline hiện có và nhờ một pull request nhỏ. Cuối hai tuần tôi có hai bằng chứng: một luồng chạy trên hạ tầng thật và một màn hình Vue được review.',
deep: '<p><strong>Đây là gì:</strong> câu hỏi này đo khả năng lập kế hoạch học gắn với việc thật. Kế hoạch tốt có đầu ra kiểm chứng được, tức là cuối giai đoạn phải có thứ gì đó chạy hoặc được review, không phải danh sách khóa học đã xem.</p><p><strong>Cách lập kế hoạch hai tuần:</strong></p><ul><li><strong>Ngày 1 và 2:</strong> chạy được hệ thống ở local, đọc cấu hình hạ tầng, hiểu một feature thật đi hết luồng, và cài bản Vue CLI hoặc công cụ dự án đang dùng. </li><li><strong>Tuần 1, khối hạ tầng:</strong> dựng một luồng nhỏ gồm API Gateway, Lambda và S3, có log, cảnh báo và giới hạn ngân sách. Tự triển khai qua pipeline của công ty để chạm đúng đường đi thật.</li><li><strong>Tuần 1, khối frontend:</strong> dựng lại một màn hình đơn giản đang có bằng Vue, tách phần dùng lại thành composable, và viết test cho phần logic. Mục tiêu là hiểu cách dự án này tổ chức code, không phải làm demo.</li><li><strong>Tuần 2:</strong> mở pull request nhỏ, nhận review, và sửa theo review. Đây là bước hay bị bỏ qua, nhưng lại giúp học nhanh nhất vì review ép bạn hiểu quy ước của đội.</li></ul><p><strong>Rủi ro cần tính trước:</strong> tài khoản thử nghiệm và quyền truy cập môi trường có thể mất thời gian chờ cấp, nên ngày đầu phải hỏi ngay. Chi phí phát sinh ngoài ý muốn là rủi ro lớn nhất của tháng đầu, nên phải đặt cảnh báo ngân sách ngay khi có tài khoản. Cuối cùng, đừng hứa học hết trong hai tuần; hãy nói rõ phần nào vừa đủ dùng và phần nào học tiếp khi có việc thật.</p><p><strong>Thay đổi khi điều kiện đổi:</strong> nếu đội đang trong giai đoạn di cờ hạ tầng, hãy thay bài tập tự do bằng việc học theo tài liệu thiết kế nội bộ và tham gia một phần đã được lên kế hoạch. Nếu việc giao hàng gấp, kế hoạch phải nhường chỗ cho nhiệm vụ đó, và bạn giữ lại phần học bằng bài tập nhỏ vào cuối ngày thay vì bỏ hẳn.</p>',
code: null,
expected: null,
followups: [
{q: 'Bạn ưu tiên học AWS hay Vue trước nếu chỉ chọn một trong hai?', a: 'Tôi ưu tiên phần mang lại giá trị cho đội ngay. Nếu đội đang cần giao diện nhanh thì tôi học Vue trước vì khoảng trống đó chặn tiến độ của nhiều người. Nếu hệ thống đang chuyển sang serverless mà không có ai chịu trách nhiệm hạ tầng, tôi học AWS trước dù cảm thấy chưa thoải mái. Tôi quyết định bằng cách hỏi ở tuần đầu xem đội đang bị chặn bởi cái gì, thay vì tự chọn theo cảm giác thoải mái của bản thân. Trong hai tuần tôi vẫn cố giữ lấy một chút cho phần còn lại để không bỏ rơi hoàn toàn. Kinh nghiệm của tôi cho thấy cả hai phần đều dùng chung nền tảng là hiểu luồng dữ liệu và cách quan sát hệ thống.'},
{q: 'Bạn sẽ báo cáo tiến độ học với team bằng cách nào?', a: 'Tôi dùng đầu ra cụ thể thay cho lời hứa. Cuối mỗi tuần tôi gửi ngắn: tôi đã dựng được luồng nào, nó chạy ở đâu, tôi gặp vướng gì và cần ai hỗ trợ. Tôi kèm link pull request để người review đọc trực tiếp thay vì đọc lời tóm tắt. Nếu có phần nào chưa hiểu, tôi nói rõ tôi đang ở đâu trong tài liệu chứ không ghi chung chung là đang học dần. Cách này giúp người hướng dẫn tiết kiệm thời gian hỏi tình hình và giúp tôi nhận được hướng dẫn đúng chỗ đang vướng.'}
],
pitfalls: ['Hứa học hết một danh sách dài khóa học trong hai tuần, không có đầu ra kiểm chứng', 'Bỏ qua bước mở pull request vì ngại, bỏ lỡ cơ hội học nhanh nhất từ review của đội', 'Không tính thời gian chờ cấp tài khoản và quyền truy cập, rồi trượt tiến độ ngay tuần đầu'],
selfcheck: ['Tôi vẫn chưa xác định được luồng nhỏ nào vừa đủ chứng minh năng lực mà không tốn quá một tuần', 'Tôi có thể dựng một luồng API Gateway cùng Lambda đọc ghi S3 trong một buổi và tự kiểm tra bằng log', 'Tôi có thể báo cáo cuối tuần bằng link pull request cụ thể thay vì bằng danh sách đã học'],
refs: ['aws-lambda-best', 'dockerfile-ref']
}
);
